const histologiaEmbriologiaReproducaoAbaetetubaTeoria = [
  {
    "titulo": "🧬 Página 1 — Histologia e organização do corpo",
    "conteudo": "<div class=\"apostila-container ciencias-abaetetuba-teoria\">\n<p>organização biológica segue a sequência célula, tecido, órgão, sistema e organismo. A Histologia estuda como células especializadas se associam e formam tecidos com funções específicas.</p>\n<p>Os quatro tecidos fundamentais são epitelial, conjuntivo, muscular e nervoso. A diferenciação celular explica por que células com o mesmo material genético podem apresentar formas e funções distintas.</p>\n<figure class=\"farol-figura-ciencias\"><img src=\"imagens/ciencias/abaetetuba/eixo2/organizacao_tecidos.png\" alt=\"Níveis de organização biológica e os quatro tecidos fundamentais.\" loading=\"lazy\" decoding=\"async\"><figcaption>Níveis de organização biológica e os quatro tecidos fundamentais.</figcaption></figure>\n<div class=\"farol-quadro farol-dica\"><strong>🎯 Revisão IVIN</strong>Relacione estrutura, localização e função antes de escolher a alternativa.</div>\n</div>"
  },
  {
    "titulo": "🧱 Página 2 — Tecido epitelial",
    "conteudo": "<div class=\"apostila-container ciencias-abaetetuba-teoria\">\n<p>O tecido epitelial possui células justapostas, pouca matriz extracelular e apoio sobre a membrana basal. Como é geralmente avascular, recebe nutrientes por difusão a partir do tecido conjuntivo subjacente.</p>\n<p>Pode atuar em proteção, absorção, secreção, filtração e percepção. Classifica-se pelo número de camadas e pelo formato celular; também forma glândulas exócrinas, endócrinas e mistas.</p>\n<figure class=\"farol-figura-ciencias\"><img src=\"imagens/ciencias/abaetetuba/eixo2/tecido_epitelial.png\" alt=\"Classificação, especializações e funções do tecido epitelial.\" loading=\"lazy\" decoding=\"async\"><figcaption>Classificação, especializações e funções do tecido epitelial.</figcaption></figure>\n<div class=\"farol-quadro farol-dica\"><strong>🎯 Revisão IVIN</strong>Relacione estrutura, localização e função antes de escolher a alternativa.</div>\n</div>"
  },
  {
    "titulo": "🧵 Página 3 — Tecido conjuntivo propriamente dito",
    "conteudo": "<div class=\"apostila-container ciencias-abaetetuba-teoria\">\n<p>O tecido conjuntivo apresenta células mais afastadas e abundante matriz extracelular, composta por substância fundamental e fibras colágenas, elásticas e reticulares.</p>\n<p>Fibroblastos produzem matriz; macrófagos fagocitam; mastócitos participam da inflamação; plasmócitos produzem anticorpos. O tecido pode ser frouxo, denso não modelado ou denso modelado.</p>\n<figure class=\"farol-figura-ciencias\"><img src=\"imagens/ciencias/abaetetuba/eixo2/tecido_conjuntivo.png\" alt=\"Células, fibras e tipos de tecido conjuntivo propriamente dito.\" loading=\"lazy\" decoding=\"async\"><figcaption>Células, fibras e tipos de tecido conjuntivo propriamente dito.</figcaption></figure>\n<div class=\"farol-quadro farol-dica\"><strong>🎯 Revisão IVIN</strong>Relacione estrutura, localização e função antes de escolher a alternativa.</div>\n</div>"
  },
  {
    "titulo": "🦴 Página 4 — Tecidos conjuntivos especializados",
    "conteudo": "<div class=\"apostila-container ciencias-abaetetuba-teoria\">\n<p>O tecido adiposo armazena energia e participa do isolamento térmico; a cartilagem oferece sustentação flexível; o tecido ósseo possui matriz mineralizada; e o sangue apresenta matriz líquida.</p>\n<p>Osteoblastos formam matriz óssea, osteócitos a mantêm e osteoclastos realizam reabsorção. Hemácias transportam gases, leucócitos atuam na defesa e plaquetas participam da coagulação.</p>\n<figure class=\"farol-figura-ciencias\"><img src=\"imagens/ciencias/abaetetuba/eixo2/tecidos_conjuntivos_especializados.png\" alt=\"Comparação entre tecido adiposo, cartilaginoso, ósseo e sanguíneo.\" loading=\"lazy\" decoding=\"async\"><figcaption>Comparação entre tecido adiposo, cartilaginoso, ósseo e sanguíneo.</figcaption></figure>\n<div class=\"farol-quadro farol-dica\"><strong>🎯 Revisão IVIN</strong>Relacione estrutura, localização e função antes de escolher a alternativa.</div>\n</div>"
  },
  {
    "titulo": "💪 Página 5 — Tecido muscular",
    "conteudo": "<div class=\"apostila-container ciencias-abaetetuba-teoria\">\n<p>O tecido muscular é especializado em contração e utiliza principalmente actina, miosina, cálcio e ATP. O sarcômero é a unidade contrátil do músculo estriado.</p>\n<p>O músculo esquelético é estriado e predominantemente voluntário; o cardíaco é estriado, ramificado e involuntário; o liso é fusiforme, não estriado e involuntário.</p>\n<figure class=\"farol-figura-ciencias\"><img src=\"imagens/ciencias/abaetetuba/eixo2/tecido_muscular.png\" alt=\"Tipos musculares, organização e mecanismo de contração.\" loading=\"lazy\" decoding=\"async\"><figcaption>Tipos musculares, organização e mecanismo de contração.</figcaption></figure>\n<div class=\"farol-quadro farol-dica\"><strong>🎯 Revisão IVIN</strong>Relacione estrutura, localização e função antes de escolher a alternativa.</div>\n</div>"
  },
  {
    "titulo": "🧠 Página 6 — Tecido nervoso",
    "conteudo": "<div class=\"apostila-container ciencias-abaetetuba-teoria\">\n<p>O tecido nervoso recebe, processa e transmite informações. Neurônios possuem dendritos, corpo celular, axônio e terminações; células da glia oferecem suporte, defesa, nutrição e mielinização.</p>\n<p>A mielina acelera a condução saltatória. Sinapses químicas utilizam neurotransmissores, e arcos reflexos integram receptores, neurônios sensitivos, centros integradores, neurônios motores e efetores.</p>\n<figure class=\"farol-figura-ciencias\"><img src=\"imagens/ciencias/abaetetuba/eixo2/tecido_nervoso.png\" alt=\"Neurônio, glia, mielina, sinapse e condução nervosa.\" loading=\"lazy\" decoding=\"async\"><figcaption>Neurônio, glia, mielina, sinapse e condução nervosa.</figcaption></figure>\n<div class=\"farol-quadro farol-dica\"><strong>🎯 Revisão IVIN</strong>Relacione estrutura, localização e função antes de escolher a alternativa.</div>\n</div>"
  },
  {
    "titulo": "⚥ Página 7 — Reprodução humana e gametogênese",
    "conteudo": "<div class=\"apostila-container ciencias-abaetetuba-teoria\">\n<p>A espermatogênese ocorre nos túbulos seminíferos e produz espermatozoides. Células de Sertoli sustentam as células germinativas e células de Leydig produzem testosterona.</p>\n<p>A ovogênese começa na vida embrionária e apresenta divisões citoplasmáticas desiguais. FSH, LH, estrogênio e progesterona coordenam os ciclos ovariano e uterino.</p>\n<figure class=\"farol-figura-ciencias\"><img src=\"imagens/ciencias/abaetetuba/eixo2/reproducao_gametogenese.png\" alt=\"Sistemas reprodutores, gametogênese e controle hormonal.\" loading=\"lazy\" decoding=\"async\"><figcaption>Sistemas reprodutores, gametogênese e controle hormonal.</figcaption></figure>\n<div class=\"farol-quadro farol-dica\"><strong>🎯 Revisão IVIN</strong>Relacione estrutura, localização e função antes de escolher a alternativa.</div>\n</div>"
  },
  {
    "titulo": "🧫 Página 8 — Fecundação e desenvolvimento inicial",
    "conteudo": "<div class=\"apostila-container ciencias-abaetetuba-teoria\">\n<p>A fecundação ocorre geralmente na ampola da tuba uterina. Capacitação, reação acrossômica, fusão das membranas e reação cortical antecedem a formação do zigoto.</p>\n<p>As clivagens formam blastômeros, mórula e blastocisto. O trofoblasto participa da implantação e da placenta; o embrioblasto origina o embrião propriamente dito.</p>\n<figure class=\"farol-figura-ciencias\"><img src=\"imagens/ciencias/abaetetuba/eixo2/fecundacao_desenvolvimento_inicial.png\" alt=\"Da fecundação à formação e implantação do blastocisto.\" loading=\"lazy\" decoding=\"async\"><figcaption>Da fecundação à formação e implantação do blastocisto.</figcaption></figure>\n<div class=\"farol-quadro farol-dica\"><strong>🎯 Revisão IVIN</strong>Relacione estrutura, localização e função antes de escolher a alternativa.</div>\n</div>"
  },
  {
    "titulo": "🌱 Página 9 — Gastrulação, folhetos e organogênese",
    "conteudo": "<div class=\"apostila-container ciencias-abaetetuba-teoria\">\n<p>Na gastrulação formam-se ectoderma, mesoderma e endoderma. O ectoderma origina sistema nervoso e epiderme; o mesoderma forma músculos, ossos, sangue, rins e gônadas; o endoderma origina revestimentos internos e glândulas associadas.</p>\n<p>A notocorda induz a placa neural. Durante a neurulação, a placa dobra-se e forma o tubo neural; a organogênese estabelece os principais órgãos e sistemas.</p>\n<figure class=\"farol-figura-ciencias\"><img src=\"imagens/ciencias/abaetetuba/eixo2/gastrulacao_organogenese.png\" alt=\"Gastrulação, neurulação e derivados dos folhetos embrionários.\" loading=\"lazy\" decoding=\"async\"><figcaption>Gastrulação, neurulação e derivados dos folhetos embrionários.</figcaption></figure>\n<div class=\"farol-quadro farol-dica\"><strong>🎯 Revisão IVIN</strong>Relacione estrutura, localização e função antes de escolher a alternativa.</div>\n</div>"
  },
  {
    "titulo": "🤰 Página 10 — Anexos embrionários e gestação",
    "conteudo": "<div class=\"apostila-container ciencias-abaetetuba-teoria\">\n<p>Âmnio, córion, saco vitelínico, alantoide, placenta e cordão umbilical são estruturas temporárias essenciais à proteção, às trocas e ao desenvolvimento.</p>\n<p>A placenta realiza trocas e produz hormônios. O cordão típico possui duas artérias e uma veia. A gestação divide-se em trimestres, e o parto envolve dilatação, expulsão e dequitação.</p>\n<figure class=\"farol-figura-ciencias\"><img src=\"imagens/ciencias/abaetetuba/eixo2/anexos_gestacao.png\" alt=\"Anexos embrionários, placenta, circulação umbilical e gestação.\" loading=\"lazy\" decoding=\"async\"><figcaption>Anexos embrionários, placenta, circulação umbilical e gestação.</figcaption></figure>\n<div class=\"farol-quadro farol-dica\"><strong>🎯 Revisão IVIN</strong>Relacione estrutura, localização e função antes de escolher a alternativa.</div>\n</div>"
  }
];

if (typeof window !== "undefined") { window.histologiaEmbriologiaReproducaoAbaetetubaTeoria = histologiaEmbriologiaReproducaoAbaetetubaTeoria; }
