// FAROL DO SABER — Tópico 33 de História
// A Crise Econômica Mundial e o avanço dos Regimes Totalitários pela Europa
// Banco autoral com 50 questões difíceis, independentes e contextualizadas.

const dadosCriseTotalitarismos = [
    {id:"CRT01",s:"Pós-guerra",t:"Depois de 1919, reparações alemãs, dívidas aliadas e empréstimos norte-americanos formavam um circuito financeiro.",p:"A fragilidade desse circuito estava na:",a:["autonomia europeia em relação aos bancos dos Estados Unidos.","ausência de compromissos financeiros depois de Versalhes.","dependência da continuidade do crédito norte-americano.","proibição alemã de realizar pagamentos aos antigos Aliados.","substituição do dólar pelo marco como moeda internacional."],c:2,e:"O circuito dependia dos empréstimos dos EUA; os distratores negam dívidas, dependência e pagamentos efetivamente previstos.",d:"Siga o fluxo: EUA → Alemanha → Aliados → EUA."},
    {id:"CRT02",s:"Entreguerras",t:"A Europa viveu hiperinflação, estabilização parcial e depois depressão.",p:"Essa sequência mostra que o entreguerras:",a:["formou um período econômico uniforme desde 1919.","manteve prosperidade contínua em todos os países.","eliminou tensões depois da criação da Liga das Nações.","foi definido por uma crise única e sem fases distintas.","reuniu recuperações temporárias e novas rupturas."],c:4,e:"O período alternou crises e recuperação; os distratores apagam fases, diferenças nacionais e instabilidade.",d:"Não confunda hiperinflação de 1923 com depressão iniciada em 1929."},
    {id:"CRT03",s:"Hiperinflação",t:"Em 1923, preços alemães aumentavam rapidamente e poupanças perdiam valor.",p:"Esse fenômeno relacionou-se principalmente à:",a:["desorganização monetária, dívidas e ocupação do Ruhr.","quebra da bolsa de Nova York ocorrida seis anos antes.","política nazista de rearmamento já dirigida por Hitler.","coletivização agrícola imposta pelo governo de Weimar.","recuperação industrial financiada pelo Plano Marshall."],c:0,e:"A hiperinflação alemã ligou-se ao pós-guerra e ao Ruhr; os distratores misturam 1929, nazismo, URSS e pós-1945.",d:"Datas eliminam várias alternativas: 1923 não é 1929 nem pós-guerra de 1945."},
    {id:"CRT04",s:"Prosperidade americana",t:"Produção em massa, publicidade e compras parceladas ampliaram o consumo nos Estados Unidos.",p:"Uma limitação desse crescimento era:",a:["a inexistência de produção industrial padronizada.","o desaparecimento completo do crédito ao consumidor.","a distribuição igual dos ganhos de produtividade.","o endividamento e a desigual capacidade de consumo.","a proibição de investimentos privados no mercado acionário."],c:3,e:"Crédito e concentração de renda limitavam demanda sustentável; os distratores negam características centrais da economia dos anos 1920.",d:"Produzir muito não garante consumidores com renda para comprar."},
    {id:"CRT05",s:"Fordismo",t:"Linhas de montagem elevaram a quantidade de bens fabricados por trabalhador.",p:"No contexto da crise, esse avanço podia gerar:",a:["redução automática da oferta para acompanhar salários menores.","produção superior à demanda efetivamente capaz de pagar.","fim da padronização por retorno ao artesanato doméstico.","distribuição imediata dos lucros entre todos os consumidores.","desaparecimento dos estoques antes da quebra da bolsa."],c:1,e:"Produtividade sem demanda equivalente produz estoques e cortes; os distratores atribuem ajustes automáticos ou resultados contrários.",d:"Superprodução é relação entre oferta e demanda solvente."},
    {id:"CRT06",s:"Agricultura",t:"Agricultores norte-americanos ampliaram produção durante a Primeira Guerra e enfrentaram queda de preços depois.",p:"A situação rural demonstra que:",a:["a crise agrícola começou apenas após a posse de Roosevelt.","todos os setores partilharam igualmente a prosperidade urbana.","fragilidades importantes antecederam a quebra de 1929.","o campo abandonou máquinas e crédito durante os anos 1920.","as exportações agrícolas cresceram sem interrupção até 1939."],c:2,e:"O campo já acumulava estoques e dívidas; os distratores adiam a crise ou idealizam prosperidade e exportações.",d:"A Grande Depressão agravou uma crise rural que já existia."},
    {id:"CRT07",s:"Especulação",t:"Investidores compravam ações com dinheiro emprestado, esperando revendê-las por preço maior.",p:"Essa prática aumentava o risco porque:",a:["impedia qualquer valorização das empresas na bolsa.","retirava os bancos de todas as operações financeiras.","garantia pagamento das dívidas mesmo com queda dos preços.","reduzia a relação entre crédito e mercado acionário.","ampliava perdas e inadimplência quando as cotações caíam."],c:4,e:"A alavancagem ampliava ganhos e perdas; os distratores negam crédito, risco ou funcionamento do mercado.",d:"Compra financiada multiplica o efeito da queda sobre investidor e banco."},
    {id:"CRT08",s:"Quebra de 1929",t:"Em outubro de 1929, grandes ordens de venda derrubaram as cotações em Nova York.",p:"A relação entre quebra e depressão deve ser entendida assim:",a:["a queda acionária ativou fragilidades bancárias, produtivas e de consumo.","a depressão terminou quando a bolsa fechou sua primeira semana de perdas.","o evento financeiro não teve qualquer efeito sobre crédito e confiança.","a quebra foi causada pela redução do desemprego industrial.","o mercado se recuperou imediatamente sem falências bancárias."],c:0,e:"O colapso acionário transmitiu-se a bancos e economia real; os distratores isolam, invertem ou encerram prematuramente o processo.",d:"A quebra é evento; a depressão é processo cumulativo."},
    {id:"CRT09",s:"Bancos",t:"Muitos bancos haviam financiado especulação e não possuíam recursos para atender a retiradas em massa.",p:"As falências bancárias aprofundaram a crise ao:",a:["aumentar crédito disponível para empresas em dificuldade.","garantir depósitos e ampliar a confiança dos consumidores.","estimular imediatamente novos investimentos industriais.","destruir poupanças e contrair empréstimos e pagamentos.","separar o mercado financeiro da economia produtiva."],c:3,e:"Falências reduziram poupança, crédito e confiança; os distratores descrevem expansão ou separação inexistentes.",d:"O banco conecta patrimônio familiar, consumo e investimento empresarial."},
    {id:"CRT10",s:"Ciclo depressivo",t:"Empresas demitiam, famílias consumiam menos e novas fábricas reduziam produção.",p:"O exemplo representa:",a:["recuperação automática gerada pela queda dos salários.","ciclo cumulativo entre desemprego, demanda e produção.","fim do vínculo entre renda do trabalho e mercado consumidor.","expansão econômica sustentada por estoques crescentes.","efeito do aumento das exportações norte-americanas."],c:1,e:"Desemprego reduz demanda e provoca novos cortes; os distratores chamam retração de recuperação ou rompem relações econômicas.",d:"Na depressão, cada queda pode alimentar a próxima."},
    {id:"CRT11",s:"Hoover",t:"O governo Hoover promoveu algumas obras e empréstimos, mas preservou confiança no ajuste privado.",p:"Sua resposta é considerada limitada porque:",a:["a escala da depressão superou medidas graduais e voluntárias.","o governo nacionalizou toda a indústria antes de 1930.","a administração criou a previdência e o seguro de depósitos.","Hoover proibiu qualquer iniciativa de infraestrutura pública.","a economia já estava recuperada quando as políticas começaram."],c:0,e:"As medidas existiram, mas foram insuficientes; os distratores exageram intervenção, negam obras ou antecipam recuperação.",d:"Evite a caricatura de inação absoluta: o problema principal foi alcance insuficiente."},
    {id:"CRT12",s:"Mundialização",t:"Depois de 1929, bancos norte-americanos reduziram empréstimos e empresas diminuíram importações.",p:"A crise espalhou-se principalmente por:",a:["conflitos militares diretos iniciados pelos Estados Unidos.","isolamento completo das economias europeias do crédito externo.","redes internacionais de capital, bancos e comércio.","substituição imediata do capitalismo pelo socialismo europeu.","crescimento das exportações de matérias-primas latino-americanas."],c:2,e:"Interdependência transmitiu a retração; os distratores inventam guerra, isolamento, mudança sistêmica e expansão exportadora.",d:"Procure os canais de transmissão, não uma causa nacional isolada."},
    {id:"CRT13",s:"Alemanha",t:"Empréstimos dos Estados Unidos sustentavam parte da estabilização alemã.",p:"A retirada desses capitais depois de 1929:",a:["fortaleceu bancos e reduziu o desemprego alemão.","eliminou a influência de Versalhes sobre a política.","garantiu maioria parlamentar aos partidos democráticos.","agravou falências, desemprego e instabilidade política.","restaurou a monarquia alemã antes das eleições de 1930."],c:3,e:"A retirada de crédito aprofundou a crise alemã; os distratores atribuem estabilidade, maioria ou restauração inexistentes.",d:"A dependência financeira tornou a Alemanha muito exposta ao choque externo."},
    {id:"CRT14",s:"Padrão-ouro",t:"Moedas ligadas ao ouro limitavam desvalorização e expansão monetária.",p:"Durante a depressão, essa rigidez:",a:["permitiu gastos ilimitados sem efeitos cambiais.","dificultou políticas expansivas em vários países.","impediu qualquer transmissão internacional da crise.","garantiu pleno emprego a quem manteve a conversibilidade.","eliminou a necessidade de reservas nos bancos centrais."],c:1,e:"O padrão-ouro restringia moeda e crédito; os distratores atribuem liberdade, isolamento ou pleno emprego.",d:"Regra monetária rígida reduz instrumentos de reação à recessão."},
    {id:"CRT15",s:"Protecionismo",t:"Países elevaram tarifas para defender produtores nacionais durante a queda.",p:"Quando adotado de forma generalizada, o protecionismo:",a:["restabeleceu rapidamente o comércio internacional anterior a 1929.","garantiu igualdade entre economias industriais e agrárias.","reduziu importações e provocou retaliações que agravaram o comércio.","eliminou a necessidade de políticas internas de emprego.","aumentou de modo uniforme a renda dos países exportadores."],c:2,e:"Tarifas e retaliações comprimiram o comércio; os distratores atribuem recuperação uniforme e efeitos incompatíveis.",d:"Uma proteção nacional pode piorar a contração quando todos reagem igual."},
    {id:"CRT16",s:"América Latina",t:"A queda de preços e compras externas atingiu economias exportadoras de produtos primários.",p:"Em vários países latino-americanos, a crise favoreceu:",a:["abandono definitivo da indústria urbana e retorno ao campo.","redução da intervenção estatal em câmbio e infraestrutura.","expansão das importações de manufaturas norte-americanas.","novas políticas industriais e substituição de importações.","fim da dependência de mercados externos em poucos meses."],c:3,e:"A falta de importações estimulou produção interna e Estado; os distratores negam industrialização ou prometem independência instantânea.",d:"Crise externa pode incentivar indústria voltada ao mercado interno."},
    {id:"CRT17",s:"Efeitos políticos",t:"A depressão atingiu democracias e ditaduras, mas produziu resultados diferentes.",p:"Essa diversidade comprova que a crise:",a:["determinou o fascismo em qualquer país com desemprego elevado.","abriu possibilidades condicionadas por instituições e coalizões.","preservou todos os governos parlamentares existentes em 1929.","foi politicamente irrelevante fora dos Estados Unidos.","eliminou disputas ideológicas ao unificar a população."],c:1,e:"A crise alterou oportunidades sem impor desfecho único; os distratores defendem automatismo, irrelevância ou consenso.",d:"Condição econômica não substitui decisões e instituições."},
    {id:"CRT18",s:"Keynes",t:"Keynes analisou situações em que investimento e consumo privados permaneciam insuficientes.",p:"A resposta econômica associada a essa análise é:",a:["reduzir toda despesa pública até o retorno espontâneo da confiança.","fixar salários e preços em ouro para impedir qualquer mudança.","estimular demanda por gastos e investimentos públicos.","abolir mercados e propriedade privada por decreto estatal.","proibir bancos centrais de alterar juros durante recessões."],c:2,e:"A política keynesiana estimula demanda; os distratores descrevem austeridade rígida, socialização total ou imobilidade monetária.",d:"Em recessão, o Estado pode gastar quando o setor privado recua."},
    {id:"CRT19",s:"New Deal",t:"Roosevelt reuniu programas de socorro, recuperação e reforma a partir de 1933.",p:"O New Deal caracterizou-se pela:",a:["retirada federal das políticas bancárias e trabalhistas.","eliminação do capitalismo por propriedade coletiva nacional.","continuidade integral das práticas adotadas antes da crise.","ampliação da intervenção estatal para reformar o capitalismo.","substituição das eleições por planejamento econômico autoritário."],c:3,e:"O programa regulou e reformou o capitalismo; os distratores confundem intervenção com socialismo ou ditadura.",d:"New Deal altera o papel do Estado sem abolir mercado e propriedade."},
    {id:"CRT20",s:"Regulação bancária",t:"Reformas criaram garantia a depósitos e maior fiscalização financeira.",p:"O objetivo imediato dessas medidas era:",a:["estimular retiradas em massa para selecionar bancos fortes.","restaurar confiança e reduzir o risco de novas corridas bancárias.","transferir todas as contas privadas para empresas industriais.","encerrar a função de crédito desempenhada pelos bancos.","proibir famílias de manter poupança em instituições financeiras."],c:1,e:"Garantia e fiscalização estabilizam confiança; os distratores incentivam corridas ou eliminam funções bancárias.",d:"Se o depósito parece seguro, diminui o incentivo para retirá-lo às pressas."},
    {id:"CRT21",s:"Obras públicas",t:"Programas federais contrataram trabalhadores para estradas, parques e edifícios.",p:"A lógica econômica dessas iniciativas era:",a:["gerar renda, emprego e demanda enquanto ampliavam infraestrutura.","reduzir circulação monetária para provocar queda adicional dos preços.","substituir permanentemente todas as empresas por órgãos federais.","impedir trabalhadores empregados de consumir produtos privados.","concentrar recursos públicos na especulação do mercado acionário."],c:0,e:"Obras combinavam emprego e estímulo à demanda; os distratores descrevem retração, estatização total ou especulação.",d:"O salário da obra pública retorna à economia como consumo."},
    {id:"CRT22",s:"Limites do New Deal",t:"A economia melhorou nos anos 1930, mas o desemprego permaneceu relevante até a mobilização de guerra.",p:"Esse dado permite concluir que o New Deal:",a:["fracassou porque nenhuma reforma bancária produziu resultado.","encerrou integralmente a depressão no primeiro ano de governo.","aliviou e reformou sem resolver sozinho todos os efeitos da crise.","foi abolido pela Suprema Corte antes de qualquer execução.","dependia da coletivização agrícola realizada pelos estados."],c:2,e:"O programa produziu reformas e recuperação parcial; os distratores oscilam entre fracasso total e solução instantânea.",d:"Avalie objetivos distintos: socorro, reforma e recuperação."},
    {id:"CRT23",s:"Totalitarismo",t:"Alguns regimes buscaram enquadrar política, educação, cultura e organizações sociais.",p:"O conceito de totalitarismo destaca a:",a:["preservação da competição partidária e da imprensa independente.","separação completa entre Estado, partido e liderança.","desmobilização da sociedade e autonomia plena das associações.","pretensão de controle amplo por ideologia, partido e propaganda.","ausência de repressão quando havia apoio popular ao governo."],c:3,e:"Totalitarismo envolve ambição abrangente de controle; os distratores descrevem pluralismo, autonomia ou ausência de repressão.",d:"A palavra-chave é pretensão totalizante, não controle perfeito de cada pessoa."},
    {id:"CRT24",s:"Autoritarismo",t:"Uma ditadura pode limitar eleições e perseguir opositores sem mobilizar toda a sociedade.",p:"Essa observação diferencia autoritarismo de totalitarismo pela:",a:["existência obrigatória de propriedade coletiva no autoritarismo.","menor pretensão de mobilização e transformação integral.","presença de sufrágio universal competitivo nas ditaduras.","proibição total de instituições religiosas em qualquer autoritarismo.","ausência de elites tradicionais nos governos conservadores."],c:1,e:"Autoritarismos podem preferir desmobilização e preservar setores autônomos; os distratores inventam regras universais.",d:"Nem toda ditadura procura criar um novo homem e controlar toda a vida social."},
    {id:"CRT25",s:"Comparação",t:"Fascismo, nazismo e stalinismo utilizaram partido, propaganda e repressão.",p:"Uma comparação historicamente correta deve:",a:["reconhecer mecanismos comuns e preservar diferenças ideológicas.","definir todos como movimentos racistas de propriedade privada.","ignorar métodos de controle porque seus objetivos eram distintos.","tratar qualquer governo interventor como regime totalitário.","concluir que estruturas econômicas eram idênticas nos três casos."],c:0,e:"Comparar exige semelhanças e diferenças; os distratores igualam ideologia, economia ou ampliam indevidamente o conceito.",d:"Compare método, ideologia, propriedade e inimigo político em colunas separadas."},
    {id:"CRT26",s:"Fascismo italiano",t:"Depois da guerra, inflação, greves e ocupações de fábricas alarmaram proprietários italianos.",p:"Esse contexto favoreceu o fascismo porque:",a:["eliminou o medo de revolução entre as elites econômicas.","isolou os esquadrões fascistas de qualquer apoio conservador.","aproximou grupos anticomunistas de um movimento de ordem.","garantiu maioria socialista estável em toda a península.","levou a monarquia a entregar o governo aos sindicatos."],c:2,e:"Medo social aproximou elites e fascistas; os distratores invertem alianças e decisões da monarquia.",d:"O fascismo cresceu também como reação organizada ao movimento operário."},
    {id:"CRT27",s:"Esquadrismo",t:"Camisas-negras atacavam sindicatos, jornais e administrações socialistas.",p:"A violência fascista foi politicamente eficaz porque:",a:["enfrentou repressão uniforme de todas as autoridades italianas.","não recebeu recursos de proprietários ou setores conservadores.","pretendia fortalecer organizações autônomas de trabalhadores.","eliminou a necessidade de alianças com instituições tradicionais.","contou com tolerância e apoio de partes das elites e do Estado."],c:4,e:"Esquadrões agiram com cumplicidades importantes; os distratores negam apoio ou atribuem objetivo sindical.",d:"Violência de movimento dependeu também da omissão e cooperação institucional."},
    {id:"CRT28",s:"Marcha sobre Roma",t:"Em outubro de 1922, fascistas pressionaram o governo e a monarquia.",p:"Mussolini tornou-se primeiro-ministro quando:",a:["o rei decidiu nomeá-lo após recusar medidas contra os fascistas.","os camisas-negras derrotaram todo o exército em batalha na capital.","uma eleição presidencial direta lhe concedeu maioria absoluta.","o papa dissolveu o parlamento e transferiu a Coroa ao partido.","a Itália foi ocupada por forças alemãs aliadas ao movimento."],c:0,e:"A nomeação foi decisão do rei sob pressão; os distratores inventam batalha, eleição, ato papal e ocupação alemã.",d:"Marcha combinou ameaça de força e porta institucional."},
    {id:"CRT29",s:"Ditadura fascista",t:"Mussolini chefiou inicialmente uma coalizão antes de eliminar a oposição.",p:"A transformação em ditadura ocorreu por:",a:["devolução voluntária do cargo depois do caso Matteotti.","restauração do pluralismo pelas leis fascistíssimas.","pressão, mudanças legais, censura e repressão progressiva.","nacionalização completa das propriedades industriais.","rompimento imediato com monarquia e Igreja em 1922."],c:3,e:"A ditadura foi construída gradualmente; os distratores invertem leis, propriedade e alianças preservadas.",d:"Chegar ao governo e destruir a democracia são etapas relacionadas, mas distintas."},
    {id:"CRT30",s:"Corporativismo",t:"O regime reuniu representantes patronais e trabalhistas em órgãos supervisionados pelo Estado.",p:"Na prática, o corporativismo fascista:",a:["entregou fábricas ao controle direto dos sindicatos livres.","subordinou os conflitos trabalhistas à estrutura estatal.","aboliu propriedade privada e lucro empresarial na Itália.","restabeleceu corporações medievais independentes do governo.","garantiu negociação equilibrada sem repressão aos trabalhadores."],c:1,e:"O Estado enquadrava capital e trabalho e eliminava autonomia sindical; os distratores confundem corporativismo com socialismo ou liberdade negocial.",d:"Corporação fascista não é sindicato livre nem propriedade operária."},
    {id:"CRT31",s:"Pactos de Latrão",t:"Em 1929, o governo italiano e a Igreja Católica estabeleceram acordos.",p:"Os Pactos de Latrão:",a:["reconheceram o Vaticano e fortaleceram a legitimidade do regime.","transformaram a Itália em Estado dirigido diretamente pelo papa.","proibiram ensino religioso e dissolveram organizações católicas.","encerraram a monarquia e criaram uma república fascista.","romperam relações entre Mussolini e as instituições religiosas."],c:0,e:"Os pactos resolveram a Questão Romana e favoreceram legitimidade; os distratores inventam teocracia, proibição e ruptura.",d:"Fascismo italiano negociou com instituições tradicionais importantes."},
    {id:"CRT32",s:"Weimar",t:"A Constituição de Weimar garantia sufrágio amplo e direitos sociais, mas enfrentava oposição radical.",p:"A república alemã deve ser entendida como:",a:["ditadura militar criada diretamente pelo Partido Nazista.","monarquia constitucional estável desde o fim do século XIX.","democracia inovadora submetida a crises e inimigos internos.","governo soviético implantado depois da Revolução Espartaquista.","regime sem eleições nacionais antes da nomeação de Hitler."],c:2,e:"Weimar foi democracia real e vulnerável; os distratores a transformam em ditadura, monarquia ou governo soviético.",d:"Fragilidade democrática não significa inexistência de democracia."},
    {id:"CRT33",s:"Nazismo em 1923",t:"Hitler participou de uma tentativa de golpe em Munique e foi preso.",p:"Depois do fracasso, o movimento nazista passou a:",a:["abandonar propaganda, eleições e organização partidária.","aceitar permanentemente as instituições democráticas de Weimar.","apoiar partidos comunistas contra a direita conservadora.","combinar disputa legal, mobilização e violência paramilitar.","defender a manutenção integral do Tratado de Versalhes."],c:3,e:"Os nazistas adotaram estratégia eleitoral sem abandonar antidemocracia e violência; os distratores inventam conversão democrática ou apoio comunista.",d:"Mudança de método não significa mudança do objetivo autoritário."},
    {id:"CRT34",s:"Crise e nazismo",t:"O desemprego alemão cresceu e coalizões parlamentares tornaram-se instáveis após 1929.",p:"Os nazistas aproveitaram a crise prometendo:",a:["manutenção de Versalhes e redução do nacionalismo.","trabalho, ordem, unidade nacional e anticomunismo.","coletivização rural conforme o modelo soviético.","fortalecimento dos sindicatos social-democratas livres.","retorno da Alemanha ao sistema monárquico dos Habsburgo."],c:1,e:"O programa combinava respostas sociais e nacionalismo; os distratores contrariam revisionismo, anticomunismo e posição trabalhista nazista.",d:"A propaganda adaptava mensagens a públicos diferentes sem abandonar seus núcleos."},
    {id:"CRT35",s:"Nomeação de Hitler",t:"Em janeiro de 1933, conservadores acreditavam que poderiam controlar Hitler dentro de um gabinete.",p:"A chegada de Hitler ao governo ocorreu por:",a:["nomeação presidencial apoiada por acordos com elites conservadoras.","eleição direta para presidente com maioria absoluta dos votos.","ocupação militar de Berlim por tropas estrangeiras fascistas.","vitória do Partido Nazista com cem por cento do parlamento.","abdicação de Mussolini em favor de uma liderança alemã."],c:0,e:"Hindenburg nomeou Hitler chanceler em arranjo conservador; os distratores inventam eleição direta, ocupação e unanimidade.",d:"Hitler foi nomeado chanceler; não eleito presidente."},
    {id:"CRT36",s:"Reichstag",t:"Depois do incêndio do Reichstag, o governo suspendeu direitos civis e ampliou prisões políticas.",p:"O decreto permitiu ao nazismo:",a:["restaurar liberdades públicas antes das novas eleições.","transferir o poder executivo ao parlamento alemão.","usar uma emergência para enfraquecer opositores e garantias.","encerrar a atuação policial contra comunistas e socialistas.","reconhecer autonomia regional diante do governo central."],c:2,e:"A emergência justificou suspensão de direitos; os distratores descrevem liberdades, descentralização ou fim da repressão.",d:"Regimes autoritários frequentemente transformam exceção em instrumento permanente."},
    {id:"CRT37",s:"Plenos Poderes",t:"A lei de março de 1933 autorizou o gabinete a editar normas sem aprovação parlamentar.",p:"Seu efeito institucional foi:",a:["fortalecer a fiscalização do Reichstag sobre Hitler.","garantir alternância partidária durante quatro anos.","restaurar a constituição democrática depois da emergência.","esvaziar o parlamento e concentrar capacidade legislativa.","transferir o governo aos estados federados alemães."],c:3,e:"A lei desmontou o controle parlamentar; os distratores atribuem fiscalização, pluralismo ou descentralização.",d:"Plenos Poderes convertem maioria circunstancial em ditadura legalizada."},
    {id:"CRT38",s:"Gleichschaltung",t:"Partidos, sindicatos, associações e governos regionais foram submetidos ao novo regime.",p:"Esse processo de coordenação buscava:",a:["ampliar autonomia de organizações civis independentes.","alinhar instituições sociais e políticas ao Estado nazista.","restaurar federalismo e diversidade partidária alemã.","separar o Partido Nazista da administração pública.","garantir negociação livre entre capital e trabalho."],c:1,e:"Coordenação significava enquadramento institucional; os distratores descrevem autonomia, pluralismo e liberdade eliminados.",d:"Gleichschaltung = sincronização forçada das instituições."},
    {id:"CRT39",s:"Ideologia nazista",t:"O nazismo classificava seres humanos por uma suposta hierarquia biológica.",p:"O racismo nazista deve ser interpretado como:",a:["componente central que orientou cidadania, exclusão e expansão.","recurso eleitoral abandonado assim que Hitler assumiu o governo.","posição pessoal sem efeitos sobre leis e instituições públicas.","doutrina criada apenas depois do início da Segunda Guerra.","ideia incompatível com o nacionalismo defendido pelo partido."],c:0,e:"A ideologia racial estruturou o regime desde cedo; os distratores a reduzem, adiam ou separam do nacionalismo.",d:"No nazismo, raça não é detalhe retórico: organiza o projeto político."},
    {id:"CRT40",s:"Leis de Nuremberg",t:"As normas de 1935 retiraram cidadania dos judeus e regularam relações civis.",p:"Historicamente, essas leis representam:",a:["retorno à igualdade jurídica prevista pela Constituição de Weimar.","transformação da discriminação racial em política jurídica estatal.","proteção de minorias contra ações de organizações partidárias.","abandono do antissemitismo pela liderança nazista.","separação entre ideologia do partido e administração pública."],c:1,e:"As leis institucionalizaram exclusão; os distratores alegam igualdade, proteção ou abandono do racismo.",d:"Uma lei pode converter preconceito ideológico em estrutura estatal."},
    {id:"CRT41",s:"Propaganda",t:"Rádio, cinema, escola e cerimônias difundiam imagens de unidade e liderança.",p:"A propaganda totalitária pretendia:",a:["mobilizar emoções, identidades e comportamentos em favor do regime.","preservar diversidade de opiniões na comunicação pública.","eliminar o culto aos líderes em benefício das instituições.","separar educação, cultura e objetivos políticos nacionais.","estimular análise crítica das mensagens oficiais."],c:0,e:"Propaganda mobilizava e enquadrava; os distratores atribuem pluralismo, separação e crítica que o regime restringia.",d:"Analise meio, público, símbolo e comportamento esperado."},
    {id:"CRT42",s:"Recepção social",t:"Nem todas as pessoas recebiam mensagens oficiais do mesmo modo.",p:"Essa observação indica que a propaganda:",a:["não possuía qualquer capacidade de influenciar a sociedade.","era rejeitada por todos os trabalhadores e empresários.","tinha efeitos mediados por interesse, contexto, medo e experiência.","controlava automaticamente cada pensamento individual.","funcionava sem censura, repetição ou organizações sociais."],c:2,e:"A recepção varia sem tornar propaganda irrelevante; os distratores opõem controle perfeito e ausência total de efeito.",d:"Influência não é hipnose: público interpreta mensagens em situações concretas."},
    {id:"CRT43",s:"Economia nazista",t:"Obras públicas e rearmamento reduziram desemprego, enquanto direitos trabalhistas eram restringidos.",p:"A recuperação alemã esteve ligada à:",a:["prioridade pacifista e redução permanente dos gastos militares.","autonomia sindical para determinar salários e jornadas.","eliminação da intervenção estatal na produção industrial.","preparação militar, controle do trabalho e investimento público.","coletivização das empresas conforme o modelo soviético."],c:3,e:"Rearmamento e comando estatal impulsionaram emprego; os distratores descrevem pacifismo, sindicalismo livre, laissez-faire e coletivização.",d:"A recuperação nazista não pode ser separada da preparação para a guerra."},
    {id:"CRT44",s:"Stalinismo",t:"A URSS combinou planejamento econômico, partido único, propaganda e repressão.",p:"Em comparação aos fascismos, o stalinismo diferenciava-se pela:",a:["defesa da hierarquia racial como fundamento declarado do Estado.","propriedade estatal e objetivo oficial de construir o socialismo.","preservação de eleições competitivas e liberdade sindical.","aliança política com monarquias e igrejas tradicionais.","ausência de culto à liderança e polícia política."],c:1,e:"A estrutura de propriedade e a ideologia socialista distinguiam a URSS; os distratores atribuem racismo nazista, pluralismo ou ausência de mecanismos repressivos.",d:"Semelhança de método não elimina diferença de projeto econômico e social."},
    {id:"CRT45",s:"Planos Quinquenais",t:"Metas estatais priorizaram indústria pesada e infraestrutura na União Soviética.",p:"Os planos representaram:",a:["planejamento central para industrialização acelerada.","retorno à NEP com predomínio de empresários privados.","abandono das metas produtivas em favor do livre mercado.","descentralização econômica entre empresas autônomas.","redução do papel estatal na definição de investimentos."],c:0,e:"Os Planos Quinquenais centralizaram metas e recursos; os distratores descrevem NEP e mercado descentralizado.",d:"Plano Quinquenal é oposto à coordenação econômica pelo mercado."},
    {id:"CRT46",s:"Coletivização",t:"O governo soviético reuniu terras em fazendas coletivas e estatais.",p:"A coletivização foi marcada por:",a:["adesão unânime dos camponeses e aumento imediato da oferta.","manutenção da propriedade rural privada criada pela NEP.","coerção, resistência e grandes dificuldades de abastecimento.","entrega da agricultura a companhias estrangeiras privadas.","fim da intervenção partidária sobre as comunidades rurais."],c:2,e:"A política encontrou resistência e produziu grave desorganização; os distratores supõem consenso, privatização ou retirada estatal.",d:"Coletivização não é reforma voluntária de pequenos proprietários."},
    {id:"CRT47",s:"Fascismo e nazismo",t:"Os dois regimes eram ultranacionalistas, anticomunistas e antiliberais.",p:"Uma diferença importante foi:",a:["a defesa nazista de eleições livres durante todo o regime.","a recusa fascista italiana de qualquer acordo com a Igreja.","a inexistência de partido dominante na Alemanha nazista.","a centralidade mais radical do racismo biológico no nazismo.","a adoção italiana de propriedade estatal socialista integral."],c:3,e:"O racismo biológico foi estruturante no nazismo; os distratores negam ditadura, Latrão, partido e propriedade privada.",d:"Nazismo é fascista, mas possui radicalização racial própria."},
    {id:"CRT48",s:"Salazarismo",t:"Portugal viveu uma ditadura conservadora, católica e corporativista.",p:"Em relação ao totalitarismo nazista, o salazarismo:",a:["mobilizou massas com intensidade e racismo idênticos.","preferiu ordem conservadora e menor mobilização social.","preservou competição partidária e imprensa plenamente livres.","implantou economia socialista de planejamento quinquenal.","aboliu instituições religiosas para criar culto estatal."],c:1,e:"O regime português foi autoritário e mais desmobilizador; os distratores o igualam ao nazismo ou inventam pluralismo e socialismo.",d:"Autoritarismo conservador e totalitarismo mobilizador não são categorias iguais."},
    {id:"CRT49",s:"Frentes Populares",t:"Na década de 1930, partidos de esquerda buscaram alianças amplas contra o fascismo.",p:"As Frentes Populares pretendiam:",a:["unir forças democráticas e operárias para conter a extrema direita.","substituir eleições por ditaduras militares conservadoras.","apoiar a expansão fascista como barreira ao liberalismo.","restaurar monarquias absolutas na França e na Espanha.","encerrar reformas sociais para atrair grupos nazistas."],c:0,e:"As frentes reuniam esquerdas e republicanos contra o fascismo; os distratores invertem objetivo e programa.",d:"A ameaça fascista levou antigos rivais da esquerda a buscar coalizões."},
    {id:"CRT50",s:"Síntese",t:"A depressão atingiu Estados Unidos, Reino Unido, Alemanha e países nórdicos, mas seus regimes seguiram caminhos distintos.",p:"A conclusão histórica mais adequada é:",a:["desemprego elevado produz necessariamente um regime fascista.","crise econômica interage com instituições, alianças e decisões políticas.","democracias permaneceram estáveis sem criar novas políticas sociais.","totalitarismos cresceram sem relação com nacionalismo e anticomunismo.","a economia não influenciou os conflitos políticos do entreguerras."],c:1,e:"A crise condicionou, mas não determinou; os distratores defendem automatismo, imobilidade democrática ou irrelevância econômica.",d:"Explique possibilidades abertas pela crise e escolhas que definiram cada resultado."}
];

const redistribuicaoGabaritoCRT = {
    CRT03: 4, CRT08: 4,
    CRT05: 4, CRT10: 4, CRT14: 4,
    CRT01: 4, CRT04: 4
};

const ajustesExtensaoDistratoresCRT = {
    CRT08: [1, " depois"],
    CRT13: [2, " alemães"],
    CRT15: [0, " mundial"],
    CRT17: [0, " por décadas"],
    CRT20: [4, " privadas"],
    CRT22: [1, " federal"],
    CRT23: [0, " duradoura"],
    CRT31: [2, " nacionais"],
    CRT35: [1, " válidos"],
    CRT36: [3, " alemães"],
    CRT37: [2, " nacional"],
    CRT38: [0, " alemãs"],
    CRT40: [0, " de 1919"],
    CRT41: [2, " públicas"],
    CRT42: [0, " alemã urbana"],
    CRT43: [0, " alemães"],
    CRT44: [0, " soviético"],
    CRT46: [0, " agrícola"],
    CRT49: [1, " europeias duradouras"],
    CRT50: [3, " europeus"]
};

const criseEconomicaMundialAvancoRegimesTotalitariosEuropa = dadosCriseTotalitarismos.map((q) => {
    const corretaFinal = Object.prototype.hasOwnProperty.call(redistribuicaoGabaritoCRT, q.id)
        ? redistribuicaoGabaritoCRT[q.id]
        : q.c;
    const alternativas = [...q.a];
    if (corretaFinal !== q.c) {
        [alternativas[q.c], alternativas[corretaFinal]] = [alternativas[corretaFinal], alternativas[q.c]];
    }
    if (ajustesExtensaoDistratoresCRT[q.id]) {
        const [indice, complemento] = ajustesExtensaoDistratoresCRT[q.id];
        alternativas[indice] = alternativas[indice].replace(/\.$/, `${complemento}.`);
    }
    return {
        id: q.id,
        subtopico: q.s,
        texto: q.t,
        pergunta: q.p,
        alternativas,
        correta: corretaFinal,
        feedbackAcerto: `✅ ${q.e}`,
        feedbackErro: `❌ ${q.e}`,
        dicaBanca: `💡 ${q.d}`,
        dificuldade: "difícil"
    };
});
