// FAROL DO SABER — Tópico 36 de História
// Lutas e resistências nas independências e descolonizações da África e Ásia.

const dadosDescolonizacoesAfricaAsia = [
    {id:"DAA01",s:"Conceitos",t:"A soberania jurídica de uma colônia podia ser reconhecida enquanto antigas relações econômicas permaneciam.",p:"A distinção historicamente adequada é:",a:["independência é marco político; descolonização envolve transformação mais ampla.","descolonização significa apenas substituir a bandeira do território.","independência elimina necessariamente toda influência estrangeira.","colonialismo termina antes de qualquer mobilização nacionalista.","soberania formal impede relações econômicas assimétricas."],c:0,e:"A independência é marco decisivo de um processo mais amplo; os distratores reduzem a descolonização ou prometem ruptura econômica automática.",d:"Diferencie o ato jurídico do processo histórico."},
    {id:"DAA02",s:"Protagonismo",t:"Greves, revoltas, boicotes e preservação cultural ocorreram antes do grande ciclo posterior a 1945.",p:"Esse dado permite afirmar que:",a:["a resistência começou apenas com a criação das Nações Unidas.","as sociedades colonizadas reagiram desde as primeiras fases da ocupação.","o anticolonialismo foi totalmente importado das metrópoles.","os movimentos anteriores não influenciaram os nacionalismos.","a dominação europeia foi aceita até o final da guerra."],c:1,e:"Resistências acompanharam a dominação desde o início; as demais alternativas apagam experiências locais e sua continuidade histórica.",d:"1945 acelerou lutas que possuíam raízes anteriores."},
    {id:"DAA03",s:"Imperialismo",t:"Administrações coloniais reorganizaram terras, trabalho, impostos e rotas de comércio.",p:"Uma consequência frequente foi:",a:["formação de economias autônomas e pouco ligadas ao exterior.","eliminação das hierarquias raciais nas colônias.","orientação produtiva para exportação e interesses metropolitanos.","preservação de todas as fronteiras políticas anteriores.","industrialização equilibrada de todos os territórios dominados."],c:2,e:"Economias coloniais foram orientadas à exportação e à metrópole; os distratores descrevem autonomia, igualdade ou preservação inexistentes.",d:"Observe para quem a economia colonial era organizada."},
    {id:"DAA04",s:"Atores locais",t:"Chefias, comerciantes e funcionários locais podiam colaborar, negociar ou aderir à oposição.",p:"Essa variação demonstra que:",a:["o colonialismo eliminou todas as escolhas políticas locais.","a oposição dependia apenas de ordens estrangeiras.","as elites coloniais formavam grupo invariável e homogêneo.","as relações coloniais incluíam alianças e mudanças de posição.","todo intermediário tornou-se nacionalista desde o início."],c:3,e:"As relações coloniais eram negociadas e posições podiam mudar; as demais opções eliminam agência e diversidade.",d:"Evite dividir a sociedade em dois blocos imutáveis."},
    {id:"DAA05",s:"Trabalhadores",t:"Portos, ferrovias e minas reuniam trabalhadores em setores estratégicos das economias coloniais.",p:"As greves nesses espaços podiam:",a:["impedir o surgimento de qualquer partido nacionalista.","fortalecer a administração metropolitana sem outros efeitos.","substituir automaticamente todas as formas de mobilização.","separar reivindicações sociais de qualquer questão política.","combinar demandas trabalhistas e pressão anticolonial."],c:4,e:"Greves podiam ligar condições de trabalho à soberania; os distratores isolam artificialmente as dimensões social e política.",d:"Questões econômicas podem adquirir sentido nacional."},

    {id:"DAA06",s:"Segunda Guerra",t:"França, Reino Unido e Países Baixos saíram economicamente enfraquecidos da Segunda Guerra Mundial.",p:"Para os impérios, isso significou:",a:["maior dificuldade para financiar e legitimar a dominação colonial.","capacidade ilimitada de restaurar antigas administrações.","desaparecimento imediato de todos os territórios ultramarinos.","fim completo dos interesses estratégicos nas colônias.","apoio europeu unânime à independência imediata."],c:0,e:"A guerra elevou custos e reduziu legitimidade, sem produzir retirada automática; os distratores confundem enfraquecimento com fim instantâneo.",d:"Crise imperial abre oportunidade, mas não resolve o processo."},
    {id:"DAA07",s:"Ocupação japonesa",t:"O Japão expulsou temporariamente potências europeias de partes do Sudeste Asiático.",p:"O principal efeito político dessa experiência foi:",a:["demonstrar que toda ocupação japonesa era libertadora.","abalar o mito da invencibilidade colonial europeia.","eliminar os movimentos nacionalistas já existentes.","garantir reconhecimento imediato da Indonésia e do Vietnã.","impedir o retorno europeu depois de 1945."],c:1,e:"As vitórias japonesas abalaram o prestígio europeu, embora o Japão também fosse potência imperial; os distratores romantizam ou exageram o efeito.",d:"Enfraquecer um império não transforma outro em libertador."},
    {id:"DAA08",s:"Veteranos",t:"Africanos e asiáticos participaram do esforço aliado durante a guerra.",p:"No pós-guerra, muitos veteranos:",a:["defenderam a restauração integral dos privilégios coloniais.","abandonaram qualquer reivindicação de cidadania.","questionaram a contradição entre liberdade e domínio colonial.","assumiram automaticamente governos independentes.","rejeitaram todas as organizações nacionalistas locais."],c:2,e:"A experiência militar ampliou questionamentos sobre cidadania e liberdade; as demais opções apagam ou automatizam sua ação.",d:"Compare o discurso da guerra com a realidade colonial."},
    {id:"DAA09",s:"ONU",t:"A Carta da ONU valorizou igualdade entre povos e autodeterminação.",p:"Seu impacto deve ser avaliado como:",a:["abolição jurídica imediata de todos os impérios em 1945.","transferência automática das colônias à administração da ONU.","proibição de movimentos nacionalistas não reconhecidos.","nova linguagem de legitimidade usada pelos anticoloniais.","garantia de independência sem mobilização nos territórios."],c:3,e:"A Carta forneceu linguagem e espaço diplomático, mas não dissolveu os impérios automaticamente.",d:"Norma internacional fortalece reivindicações; não substitui a luta."},
    {id:"DAA10",s:"Guerra Fria",t:"Estados Unidos e URSS criticavam o colonialismo, mas calculavam interesses estratégicos.",p:"A melhor interpretação é:",a:["as superpotências sempre apoiaram o mesmo movimento.","a bipolaridade eliminou decisões dos atores colonizados.","todo conflito local foi criado após 1945 pelas superpotências.","os movimentos anticoloniais recusaram qualquer auxílio externo.","apoio anticolonial podia coexistir com alianças contraditórias."],c:4,e:"As superpotências combinavam discurso e interesse; os distratores impõem coerência absoluta ou retiram agência local.",d:"Na Guerra Fria, princípios e estratégia podiam entrar em tensão."},

    {id:"DAA11",s:"Nacionalismos",t:"Territórios coloniais reuniam grupos linguísticos, religiosos e regionais variados.",p:"Os nacionalismos anticoloniais:",a:["construíram coalizões e identidades políticas abrangentes.","reproduziram sem mudanças todas as fronteiras pré-coloniais.","eliminaram divergências sociais antes da independência.","foram formados apenas por funcionários europeus.","dispensaram participação de trabalhadores e camponeses."],c:0,e:"Os nacionalismos construíram coalizões amplas e disputadas; os distratores tratam identidade como dada ou elitista.",d:"Nação também é projeto político em construção."},
    {id:"DAA12",s:"Pan-africanismo",t:"Ativistas africanos e da diáspora reuniram-se em congressos contra racismo e colonialismo.",p:"O pan-africanismo defendia:",a:["subordinação permanente dos novos Estados às metrópoles.","solidariedade, emancipação e formas de unidade africana.","criação de um império europeu comum na África.","separação completa entre continente e diáspora.","extinção das identidades nacionais africanas."],c:1,e:"O pan-africanismo articulava solidariedade e unidade em projetos diversos; os distratores invertem seu conteúdo.",d:"Unidade africana não exigia apagar toda identidade nacional."},
    {id:"DAA13",s:"Nkrumah",t:"Após a independência de Gana, Kwame Nkrumah apoiou movimentos de outros territórios.",p:"Sua posição expressava:",a:["isolamento diplomático do novo Estado ganês.","prioridade exclusiva à manutenção do império britânico.","ideia de que a liberdade de Gana dependia da libertação africana.","recusa de qualquer cooperação continental.","projeto de anexar militarmente toda a África Ocidental."],c:2,e:"Nkrumah relacionava soberania ganesa à emancipação continental; os distratores confundem solidariedade com isolamento ou anexação.",d:"Gana tornou-se base política do pan-africanismo."},
    {id:"DAA14",s:"Identidades",t:"Religiões e tradições locais foram mobilizadas por diferentes movimentos.",p:"Historicamente, isso mostra que:",a:["a modernidade política suprimiu toda referência cultural.","a religião determinou um único nacionalismo na África e Ásia.","as tradições permaneceram fora das disputas políticas.","referências culturais foram reinterpretadas em projetos modernos.","nacionalismo e cultura eram sempre incompatíveis."],c:3,e:"Movimentos reinterpretaram tradições em projetos modernos; as outras opções opõem artificialmente cultura e política.",d:"Tradição também pode ser reinventada politicamente."},
    {id:"DAA15",s:"Coalizões",t:"A unidade anticolonial frequentemente reunia setores com interesses sociais diferentes.",p:"Depois da independência, era possível que:",a:["todas as divergências desaparecessem pela soberania jurídica.","os antigos aliados mantivessem sempre o mesmo programa.","as classes sociais deixassem de influenciar a política.","as fronteiras resolvessem todo conflito regional.","disputas internas reaparecessem na construção do novo Estado."],c:4,e:"A independência podia reabrir disputas antes subordinadas à luta comum; os distratores prometem unidade permanente.",d:"Unidade contra o colonizador não garante consenso posterior."},

    {id:"DAA16",s:"Formas de luta",t:"Movimentos combinaram petições, greves, boicotes, eleições e resistência armada.",p:"Essa diversidade decorreu:",a:["das condições políticas e das mudanças em cada conjuntura.","de um plano único determinado pela Conferência de Bandung.","da proibição de negociações em todos os impérios.","da ausência de repressão contra mobilizações pacíficas.","do controle completo das lutas pelas superpotências."],c:0,e:"Estratégias variavam conforme abertura, repressão e organização; as demais alternativas impõem uniformidade externa.",d:"O repertório de luta muda no tempo."},
    {id:"DAA17",s:"Desobediência civil",t:"Campanhas recusavam leis, impostos ou produtos considerados instrumentos de dominação.",p:"A desobediência civil buscava:",a:["substituir o nacionalismo por lealdade à metrópole.","retirar cooperação social de uma ordem julgada injusta.","impedir participação popular em mobilizações públicas.","garantir confronto militar em todas as campanhas.","preservar monopólios econômicos coloniais."],c:1,e:"A desobediência retira cooperação para desafiar uma ordem; os distratores invertem seu objetivo ou a tornam necessariamente militar.",d:"Poder político também depende de obediência cotidiana."},
    {id:"DAA18",s:"Negociação",t:"Certas independências foram formalizadas por acordos entre metrópoles e lideranças locais.",p:"Isso não significa ausência de resistência porque:",a:["acordos eram proibidos pelos movimentos nacionalistas.","a metrópole sempre aceitava todas as demandas iniciais.","pressão popular podia alterar a força das partes negociadoras.","negociação ocorria antes de qualquer mobilização social.","os tratados anulavam as lutas que os antecederam."],c:2,e:"Mobilização cria poder de negociação; os distratores isolam artificialmente acordo e resistência.",d:"A mesa de negociação também reflete forças construídas fora dela."},
    {id:"DAA19",s:"Mulheres",t:"Mulheres atuaram em redes de abastecimento, comunicação, protesto e liderança.",p:"Uma leitura historiográfica adequada deve:",a:["restringir sua atuação ao ambiente doméstico.","tratá-las como grupo politicamente homogêneo.","presumir que obtiveram igualdade plena após a vitória.","integrar sua participação às diferentes formas de resistência.","atribuir todas as decisões militares às mulheres."],c:3,e:"A participação feminina deve integrar a narrativa sem homogeneização; os distratores a apagam ou exageram.",d:"Procure atores que narrativas oficiais tornaram menos visíveis."},
    {id:"DAA20",s:"Comparação imperial",t:"Britânicos e franceses negociaram em alguns territórios e reprimiram movimentos em outros.",p:"A conclusão correta é:",a:["cada império adotou política única em todas as colônias.","o Reino Unido realizou apenas transições pacíficas.","a França recusou negociação em todo território africano.","a resistência armada foi inexistente no império britânico.","a resposta metropolitana variou conforme território e conjuntura."],c:4,e:"Políticas coloniais variaram em cada caso; os distratores reproduzem estereótipos de império sempre pacífico ou sempre repressivo.",d:"Compare casos, não rótulos fixos."},

    {id:"DAA21",s:"Índia",t:"O Congresso Nacional Indiano ampliou sua base durante a primeira metade do século XX.",p:"Sua importância consistiu em:",a:["articular diferentes setores em torno da independência.","defender a permanência ilimitada do governo britânico.","representar apenas interesses militares estrangeiros.","impedir a participação de Gandhi nas campanhas.","substituir a Liga Muçulmana em todas as regiões."],c:0,e:"O Congresso foi centro amplo do nacionalismo; os distratores o apresentam como colonial ou capaz de eliminar toda rivalidade.",d:"Congresso era coalizão nacional, não partido sem divergências."},
    {id:"DAA22",s:"Gandhi",t:"A Marcha do Sal de 1930 contestou o monopólio britânico sobre um produto cotidiano.",p:"A ação exemplifica:",a:["aliança militar do Congresso com a metrópole.","desobediência civil que ligava cotidiano e soberania.","abandono da mobilização de massas na Índia.","campanha pela divisão territorial imediata.","aceitação dos impostos coloniais como legítimos."],c:1,e:"A Marcha do Sal transformou uma regra cotidiana em contestação de soberania; os distratores invertem sua finalidade.",d:"Um símbolo simples pode revelar a estrutura colonial."},
    {id:"DAA23",s:"Satyagraha",t:"Gandhi associava resistência política, verdade e não violência.",p:"O princípio de satyagraha propunha:",a:["passividade completa diante de toda injustiça.","controle colonial exercido por lideranças indianas.","pressão moral e política pela recusa ativa de cooperação.","separação obrigatória entre política e ética.","uso de violência como primeira etapa da campanha."],c:2,e:"Satyagraha é resistência ativa não violenta, não passividade; os distratores invertem ou esvaziam o conceito.",d:"Não violência pode ser ação organizada e confrontadora."},
    {id:"DAA24",s:"Partição",t:"Em 1947, o antigo domínio britânico foi dividido entre Índia e Paquistão.",p:"A partição revela que:",a:["independência garantiu unidade territorial consensual.","diferenças religiosas não influenciaram o acordo.","o Paquistão foi criado décadas depois da Índia.","soberania e conflito territorial podiam ocorrer juntos.","a Liga Muçulmana rejeitava qualquer Estado separado."],c:3,e:"Independência e partição foram simultâneas e contestadas; os distratores negam o papel da Liga e das tensões.",d:"1947 possui duas palavras-chave: independência e partição."},
    {id:"DAA25",s:"Bangladesh",t:"O Paquistão nasceu com partes ocidental e oriental separadas geograficamente.",p:"A independência de Bangladesh em 1971 demonstra:",a:["estabilidade definitiva de todas as fronteiras de 1947.","subordinação voluntária da parte oriental à Índia.","desaparecimento das identidades linguísticas regionais.","retorno do domínio britânico ao subcontinente.","permanência de tensões nacionais depois da descolonização."],c:4,e:"Bangladesh evidencia conflitos pós-coloniais internos ao Estado criado em 1947; os distratores apresentam estabilidade ou recolonização.",d:"O fim do império não encerra a construção das nações."},

    {id:"DAA26",s:"Indonésia",t:"Sukarno e Hatta proclamaram independência após a rendição japonesa, mas os neerlandeses tentaram retornar.",p:"A soberania indonésia foi consolidada por:",a:["resistência interna combinada com pressão diplomática internacional.","reconhecimento neerlandês automático em agosto de 1945.","anexação do arquipélago à Índia independente.","decisão unilateral da Conferência de Bandung.","ocupação permanente do território pelos Estados Unidos."],c:0,e:"A luta interna e a diplomacia levaram ao reconhecimento de 1949; os distratores tornam o processo instantâneo ou externo.",d:"Proclamação em 1945; reconhecimento em 1949."},
    {id:"DAA27",s:"Indochina",t:"Ho Chi Minh proclamou a República Democrática do Vietnã em 1945.",p:"A guerra posterior iniciou-se porque:",a:["a China tentou restaurar diretamente o império francês.","a França procurou restabelecer seu controle colonial.","o Vietnã já era membro da OTAN naquele momento.","os nacionalistas rejeitavam qualquer independência.","a ONU determinou nova colonização europeia."],c:1,e:"A França tentou retornar à Indochina, gerando guerra; as demais opções atribuem o conflito a atores ou objetivos inadequados.",d:"Pós-1945 também foi momento de tentativas de recolonização."},
    {id:"DAA28",s:"Dien Bien Phu",t:"Em 1954, forças francesas foram derrotadas em Dien Bien Phu.",p:"A consequência principal foi:",a:["restauração do domínio colonial por prazo indeterminado.","ingresso imediato do Vietnã reunificado na OTAN.","acordos de Genebra e encerramento do domínio francês.","reconhecimento da soberania francesa sobre a Indonésia.","fim de toda disputa política no Sudeste Asiático."],c:2,e:"A derrota levou aos Acordos de Genebra e à retirada francesa; os distratores restauram o colonialismo ou prometem paz completa.",d:"Dien Bien Phu encerra a fase francesa, não toda a crise vietnamita."},
    {id:"DAA29",s:"Vietnã",t:"A divisão de 1954 foi apresentada como temporária, mas consolidou governos rivais.",p:"A trajetória vietnamita combinou:",a:["apenas disputa religiosa sem dimensão colonial.","domínio britânico e nacionalismo monárquico.","neutralidade permanente entre todos os atores.","anticolonialismo, revolução social e Guerra Fria.","ausência de participação política vietnamita."],c:3,e:"O conflito combinou nacionalismo, transformação social e bipolaridade; os distratores reduzem ou apagam sua complexidade.",d:"A Guerra Fria se sobrepôs a raízes anticoloniais."},
    {id:"DAA30",s:"Sudeste Asiático",t:"Indonésia e Vietnã proclamaram independência em 1945, mas enfrentaram tentativas europeias de retorno.",p:"A comparação demonstra que:",a:["proclamação e reconhecimento internacional eram sempre simultâneos.","o Japão garantiu soberania duradoura aos dois países.","as metrópoles aceitaram imediatamente o fim dos impérios.","os dois territórios seguiram processos políticos idênticos.","a retirada colonial exigiu novas lutas depois da guerra."],c:4,e:"As proclamações foram seguidas por conflitos e negociação; os distratores confundem anúncio com soberania consolidada.",d:"1945 abriu uma etapa, não encerrou todas as lutas."},

    {id:"DAA31",s:"Bandung",t:"Vinte e nove países africanos e asiáticos reuniram-se na Indonésia em 1955.",p:"A conferência defendeu:",a:["soberania, cooperação e oposição ao colonialismo e racismo.","criação de comando militar afro-asiático obrigatório.","retorno das administrações coloniais europeias.","subordinação dos participantes à União Soviética.","fim de todas as relações com países ocidentais."],c:0,e:"Bandung articulou soberania e anticolonialismo sem formar aliança militar; os distratores transformam autonomia em isolamento ou submissão.",d:"Bandung foi espaço político e diplomático, não pacto militar."},
    {id:"DAA32",s:"Afro-asiatismo",t:"Países com sistemas políticos diferentes formularam princípios comuns em Bandung.",p:"Isso foi possível porque:",a:["todos adotavam a mesma ideologia econômica.","compartilhavam interesses em soberania e anticolonialismo.","haviam ingressado no Pacto de Varsóvia.","renunciaram às suas políticas externas nacionais.","pretendiam criar um único Estado continental."],c:1,e:"Interesses anticoloniais comuns permitiram cooperação apesar das diferenças; os distratores inventam uniformidade ideológica ou estatal.",d:"Cooperação não exige identidade total."},
    {id:"DAA33",s:"Não Alinhamento",t:"O Movimento dos Não Alinhados foi formalizado em Belgrado, em 1961.",p:"Não alinhamento significava:",a:["neutralidade idêntica em toda crise internacional.","isolamento econômico diante das superpotências.","busca de autonomia sem adesão permanente a um bloco.","proibição de receber qualquer ajuda estrangeira.","criação de terceira aliança militar centralizada."],c:2,e:"Não alinhamento buscava autonomia estratégica; os distratores confundem autonomia com equidistância, isolamento ou bloco militar.",d:"Não alinhado pode tomar posição e negociar com ambos os lados."},
    {id:"DAA34",s:"Terceiro Mundo",t:"A expressão surgiu no contexto de povos que buscavam voz própria na ordem bipolar.",p:"Em seu sentido político inicial, indicava:",a:["lista de países sem participação diplomática.","zona administrada conjuntamente pelas superpotências.","região definida apenas pela renda per capita.","posição autônoma diante dos blocos da Guerra Fria.","grupo restrito aos territórios ainda colonizados."],c:3,e:"O sentido inicial destacava posição política e autonomia; os distratores reduzem o conceito a pobreza ou tutela externa.",d:"O termo nasceu político antes de ser usado economicamente."},
    {id:"DAA35",s:"Agência internacional",t:"Países recém-independentes ampliaram sua presença na Assembleia Geral da ONU.",p:"Esse crescimento permitiu:",a:["abolir o veto dos membros permanentes do Conselho.","substituir imediatamente todas as potências europeias.","encerrar conflitos coloniais por maioria simples.","eliminar divergências entre países africanos e asiáticos.","fortalecer agendas de descolonização, soberania e desenvolvimento."],c:4,e:"O peso numérico fortaleceu agendas comuns, sem apagar o veto ou as divergências entre novos Estados.",d:"Mais votos ampliam influência, mas não controlam toda a ONU."},

    {id:"DAA36",s:"Egito",t:"Os Oficiais Livres derrubaram a monarquia egípcia em 1952.",p:"Sob Nasser, o Egito tornou-se referência por:",a:["associar nacionalismo árabe, soberania e anticolonialismo.","reintegrar-se formalmente ao Império Britânico.","abandonar o controle sobre o Canal de Suez.","aderir ao Pacto de Varsóvia como membro europeu.","restaurar o domínio francês no Norte da África."],c:0,e:"Nasser articulou soberania e nacionalismo árabe; os distratores invertem a nacionalização e a posição anticolonial.",d:"Egito nasserista simboliza autonomia no mundo árabe."},
    {id:"DAA37",s:"Suez",t:"Em 1956, Nasser nacionalizou o Canal de Suez, e França, Reino Unido e Israel atacaram o Egito.",p:"A crise terminou com:",a:["anexação permanente do Egito pelo Reino Unido.","retirada dos atacantes após pressão internacional.","entrega definitiva do canal a uma empresa francesa.","queda imediata de Nasser e restauração monárquica.","entrada egípcia na Organização do Tratado do Atlântico."],c:1,e:"Pressões levaram à retirada e fortaleceram Nasser; os distratores apresentam vitória colonial ou mudanças inexistentes.",d:"Suez marcou o declínio do poder colonial franco-britânico."},
    {id:"DAA38",s:"Argélia",t:"A Argélia possuía população europeia numerosa e era tratada como parte da França.",p:"Essa característica contribuiu para:",a:["independência imediata por simples decreto francês.","ausência de mobilização entre argelinos.","resistência francesa prolongada à separação política.","incorporação da Argélia ao Egito de Nasser.","fim da atuação da Frente de Libertação Nacional."],c:2,e:"Os vínculos coloniais e a população de origem europeia aumentaram a resistência francesa; os distratores negam a luta ou confundem territórios.",d:"A França não tratava a Argélia como colônia comum."},
    {id:"DAA39",s:"FLN",t:"A Frente de Libertação Nacional iniciou insurreição em 1954 e ampliou sua atuação diplomática.",p:"A estratégia da FLN combinou:",a:["apoio à permanência do governo colonial.","recusa de qualquer representação internacional.","defesa de autonomia sem ruptura com a França.","resistência interna e busca de legitimidade externa.","aliança para restaurar a monarquia francesa."],c:3,e:"A FLN combinou luta interna e diplomacia; os distratores a colocam a favor da ordem colonial.",d:"Movimentos de libertação também disputavam opinião internacional."},
    {id:"DAA40",s:"Magreb",t:"Marrocos e Tunísia tornaram-se independentes em 1956; a Argélia, em 1962.",p:"A diferença cronológica mostra que:",a:["todo o Norte da África seguiu uma única negociação.","a Argélia não esteve sob domínio francês.","Marrocos e Tunísia alcançaram soberania depois da Argélia.","o nacionalismo era inexistente fora do Egito.","a descolonização regional apresentou mecanismos distintos."],c:4,e:"Os ritmos e mecanismos diferiram entre países; os distratores impõem uniformidade ou erram datas e domínios.",d:"Mesma região não significa mesmo processo."},

    {id:"DAA41",s:"Gana",t:"A antiga Costa do Ouro tornou-se Gana em 1957.",p:"Sua importância simbólica deve-se a:",a:["abrir o ciclo de independências na África Subsaariana britânica.","ser a primeira colônia de toda a África desde a Antiguidade.","ter conquistado soberania por anexação ao Egito.","encerrar todas as administrações coloniais do continente.","fundar imediatamente a União Africana atual."],c:0,e:"Gana foi referência pioneira do ciclo subsaariano; os distratores exageram seu alcance ou confundem instituições.",d:"Gana e Nkrumah são marcos do pan-africanismo."},
    {id:"DAA42",s:"Ano da África",t:"Dezessete países africanos conquistaram independência em 1960.",p:"A expressão Ano da África:",a:["indica que todo o continente ficou independente naquele ano.","destaca a concentração de independências, não a conclusão do processo.","designa apenas a independência do Congo Belga.","marca a fundação do Movimento dos Não Alinhados.","refere-se ao fim das colônias portuguesas."],c:1,e:"1960 concentrou independências, mas colônias permaneceram; os distratores universalizam o processo ou confundem marcos.",d:"Ano da África não é fim de toda colonização africana."},
    {id:"DAA43",s:"Congo",t:"A independência congolesa foi seguida por secessões, interferência externa e crise entre lideranças.",p:"O caso evidencia:",a:["transição cuidadosamente preparada por décadas de autonomia.","ausência de interesses estrangeiros em recursos minerais.","soberania formal combinada com fragilidade institucional e disputa externa.","estabilidade automática produzida pela retirada belga.","isolamento completo do conflito em relação à Guerra Fria."],c:2,e:"O Congo reuniu soberania recente, instituições frágeis e interferência; os distratores apresentam preparação ou estabilidade inexistentes.",d:"Independência não é sinônimo de Estado consolidado."},
    {id:"DAA44",s:"Quênia",t:"Conflitos sobre terra e trabalho alimentaram a revolta Mau Mau nos anos 1950.",p:"A independência queniana demonstra:",a:["ausência de resistência no império britânico.","separação completa entre questão agrária e nacionalismo.","retirada britânica antes de qualquer mobilização.","ligação entre desigualdade fundiária, repressão e luta política.","incorporação do Quênia à federação de Gana."],c:3,e:"Terra, trabalho e nacionalismo estavam conectados; os distratores apagam a resistência ou confundem países.",d:"No Quênia, a questão da terra foi central."},
    {id:"DAA45",s:"Comparação africana",t:"Gana, Quênia e Congo alcançaram independência por trajetórias diferentes.",p:"Uma comparação adequada reconhece:",a:["o mesmo partido e a mesma liderança nos três casos.","ausência de participação popular no conjunto.","controle soviético direto sobre cada processo.","idêntica preparação institucional pelas metrópoles.","variação entre mobilização política, conflito agrário e crise estatal."],c:4,e:"Os casos representam trajetórias distintas; as demais opções homogeneízam atores, metrópoles e resultados.",d:"Use comparação para revelar diferenças, não para apagá-las."},

    {id:"DAA46",s:"Portugal",t:"O Estado Novo chamava suas colônias africanas de províncias ultramarinas.",p:"Essa linguagem procurava:",a:["negar o caráter colonial e dificultar reivindicações de independência.","reconhecer imediatamente a soberania de Angola e Moçambique.","preparar eleições livres em todos os territórios.","transferir a administração das colônias à OUA.","admitir que Portugal abandonaria a África em 1961."],c:0,e:"A designação buscava negar juridicamente o colonialismo; os distratores a tratam como reconhecimento da descolonização.",d:"Mudar o nome não elimina a relação colonial."},
    {id:"DAA47",s:"Movimentos",t:"PAIGC, FRELIMO e MPLA atuaram em diferentes colônias portuguesas.",p:"A associação correta é:",a:["PAIGC—Angola; FRELIMO—Guiné-Bissau; MPLA—Moçambique.","PAIGC—Guiné-Bissau; FRELIMO—Moçambique; MPLA—Angola.","PAIGC—Quênia; FRELIMO—Argélia; MPLA—Congo.","PAIGC—Índia; FRELIMO—Vietnã; MPLA—Indonésia.","PAIGC—Gana; FRELIMO—Egito; MPLA—Tunísia."],c:1,e:"PAIGC atuou na Guiné-Bissau, FRELIMO em Moçambique e MPLA em Angola; os demais pares trocam países e continentes.",d:"Fixe a tríade Guiné–PAIGC, Moçambique–FRELIMO, Angola–MPLA."},
    {id:"DAA48",s:"Revolução dos Cravos",t:"Em 25 de abril de 1974, o Movimento das Forças Armadas derrubou a ditadura portuguesa.",p:"Sua relação com a descolonização foi:",a:["criar as lutas africanas que antes não existiam.","restaurar o controle português sobre todo o ultramar.","abrir negociações que aceleraram independências já reivindicadas.","incorporar as colônias à Comunidade Econômica Europeia.","impedir o reconhecimento da Guiné-Bissau."],c:2,e:"A revolução abriu negociações, mas as lutas africanas eram anteriores; os distratores apagam esse protagonismo ou invertem o resultado.",d:"1974 acelera um processo já construído nas colônias."},
    {id:"DAA49",s:"OUA",t:"A Organização da Unidade Africana foi criada em 1963.",p:"Entre seus objetivos estava:",a:["redesenhar por força todas as fronteiras coloniais.","substituir cada governo por administração continental.","integrar militarmente a África ao Pacto de Varsóvia.","defender soberania e apoiar territórios ainda colonizados.","restaurar relações imperiais com as antigas metrópoles."],c:3,e:"A OUA defendia soberania, cooperação e libertação restante; os distratores atribuem-lhe governo supranacional ou alinhamento militar.",d:"OUA apoiava descolonização sem criar um Estado africano único."},
    {id:"DAA50",s:"Síntese",t:"A descolonização transformou o sistema internacional, mas preservou fronteiras e dependências econômicas.",p:"A melhor síntese é:",a:["as metrópoles concederam soberania sem pressão local.","a independência eliminou todas as desigualdades herdadas.","a Guerra Fria criou integralmente os nacionalismos.","os novos Estados permaneceram sem capacidade de escolha.","a crise imperial e o protagonismo local produziram rupturas incompletas."],c:4,e:"Crise dos impérios e ação local explicam a soberania, enquanto heranças coloniais limitaram seus efeitos; os distratores usam causas ou resultados absolutos.",d:"Combine ruptura política, agência e permanências estruturais."}
];

const lutasResistenciasIndependenciasDescolonizacoesAfricaAsia = dadosDescolonizacoesAfricaAsia.map((q) => {
    const alternativas = [...q.a];
    const acrescentarContexto = (indice, complemento) => {
        alternativas[indice] = alternativas[indice].replace(/\.$/, `${complemento}.`);
    };
    const tamanhosIniciais = alternativas.map((item) => item.length);
    const maiorDistrator = tamanhosIniciais.reduce((melhor, tamanho, indice) => {
        if (indice === q.c) return melhor;
        return tamanho > tamanhosIniciais[melhor] || melhor === q.c ? indice : melhor;
    }, q.c === 0 ? 1 : 0);
    if (tamanhosIniciais[q.c] >= tamanhosIniciais[maiorDistrator]) {
        acrescentarContexto(maiorDistrator, " no contexto analisado");
    }
    let maiorExtensao = Math.max(...alternativas.map((item) => item.length));
    alternativas.forEach((item, indice) => {
        if (maiorExtensao - item.length > 25) {
            acrescentarContexto(indice, " no período");
        }
    });
    maiorExtensao = Math.max(...alternativas.map((item) => item.length));
    alternativas.forEach((item, indice) => {
        if (maiorExtensao - item.length > 25) {
            acrescentarContexto(indice, " histórico");
        }
    });
    return {
        id: q.id,
        subtopico: q.s,
        texto: q.t,
        pergunta: q.p,
        alternativas,
        correta: q.c,
        feedbackAcerto: `✅ ${q.e}`,
        feedbackErro: `❌ ${q.e}`,
        dicaBanca: `💡 ${q.d}`,
        dificuldade: "difícil"
    };
});
