// FAROL DO SABER — Tópico 27 de História
// Teoria completa em 12 páginas.

const civilizacoesAntiguidadeClassicaGreciaRomaTeoria = [
    {
        "titulo": "1. Antiguidade Clássica: conceito, fontes e periodização",
        "conteudo": "<p>A expressão Antiguidade Clássica costuma designar principalmente experiências históricas gregas e romanas. Ela foi consolidada por tradições intelectuais posteriores que escolheram certos textos, instituições e formas artísticas como referências de “clássico”.</p><p>Essa categoria ajuda a organizar o estudo, mas não deve sugerir que Grécia e Roma foram sociedades homogêneas, superiores ou isoladas. Ambas mantiveram contatos intensos com egípcios, fenícios, persas, povos itálicos, cartagineses, celtas e muitas outras populações.</p><p>A cronologia é extensa. O mundo grego inclui períodos micênico, arcaico, clássico e helenístico; a história romana atravessa monarquia, República, Principado e Antiguidade Tardia.</p><p>As fontes são variadas: poemas, discursos, tragédias, leis, inscrições, moedas, cerâmicas, esculturas, ruínas urbanas, túmulos, objetos cotidianos e documentos administrativos.</p><p>Autores antigos escreviam a partir de posições sociais e objetivos próprios. Tucídides, Cícero, Tácito e outros não representavam automaticamente toda a população de seu tempo.</p><p>A arqueologia permite observar grupos pouco presentes na literatura, como trabalhadores, mulheres, soldados comuns, pessoas escravizadas e habitantes de províncias.</p><p>Mitos também são fontes históricas quando analisados como narrativas de identidade, religião e poder. Eles não devem ser aceitos literalmente nem descartados como invenções sem valor.</p><p>Em concursos, a melhor resposta costuma evitar eurocentrismo e anacronismo, combinando crítica das fontes, diversidade interna e conexões mediterrânicas.</p><div class=\"box-teoria exemplo\"><strong>🧭 Exemplo de prova:</strong><p>Uma inscrição honorífica revela quem recebeu prestígio e quais virtudes a comunidade desejava valorizar.</p></div><div class=\"box-teoria erro\"><strong>⚠️ Erro clássico:</strong><p>Tomar “clássico” como sinônimo de perfeito, universal ou sem conflitos.</p></div><div class=\"box-teoria dica\"><strong>🎯 Dica de banca:</strong><p>Observe sempre quem produziu a fonte e quais grupos ficaram ausentes.</p></div><div class=\"box-teoria checkpoint\"><strong>✅ Checkpoint:</strong><p>Por que uma obra literária de elite precisa ser cruzada com evidências arqueológicas?</p></div><div class=\"box-teoria resumo\"><strong>📝 Resumo:</strong><p>Antiguidade Clássica é uma categoria historiográfica útil, desde que não apague diversidade, contatos e desigualdades.</p></div>"
    },
    {
        "titulo": "2. Geografia do mundo grego e formação das pólis",
        "conteudo": "<p>O mundo grego antigo abrangia a península Balcânica, ilhas do Egeu, costa da Ásia Menor, sul da Itália, mar Negro e outras áreas colonizadas. Não correspondia a um Estado nacional unificado.</p><p>Montanhas, vales, ilhas e litorais favoreceram comunidades relativamente autônomas e circulação marítima. O ambiente criou possibilidades, mas não determinou sozinho instituições políticas.</p><p>A pólis reunia núcleo urbano, campos, santuários, portos e território. Sua principal característica era formar uma comunidade política com leis, cultos e instituições próprias.</p><p>A cidadania variava entre as pólis e era geralmente restrita. Participação política dependia de sexo, nascimento, liberdade, riqueza e pertencimento cívico.</p><p>No período arcaico, aristocracias controlavam terras e magistraturas. Dívidas, concentração fundiária e novas demandas militares produziram conflitos.</p><p>Tiranos assumiram poder em algumas cidades com apoio de grupos insatisfeitos. Na Grécia antiga, tirania indicava governo pessoal fora da ordem aristocrática tradicional, não exatamente o sentido contemporâneo do termo.</p><p>A colonização ampliou redes comerciais e culturais. As novas pólis mantinham vínculos religiosos e familiares com suas metrópoles, mas frequentemente possuíam autonomia política.</p><p>Para a prova, diferencie unidade cultural e fragmentação política: língua, mitos e festivais comuns coexistiam com rivalidades entre cidades.</p><div class=\"box-teoria exemplo\"><strong>🧭 Exemplo de prova:</strong><p>Uma pólis podia possuir porto, campos agrícolas e santuários fora de suas muralhas.</p></div><div class=\"box-teoria erro\"><strong>⚠️ Erro clássico:</strong><p>Traduzir pólis apenas como “cidade” e esquecer território, cidadania e comunidade política.</p></div><div class=\"box-teoria dica\"><strong>🎯 Dica de banca:</strong><p>Não transforme geografia em causa automática da fragmentação política.</p></div><div class=\"box-teoria checkpoint\"><strong>✅ Checkpoint:</strong><p>Quais elementos faziam da pólis mais que um centro urbano?</p></div><div class=\"box-teoria resumo\"><strong>📝 Resumo:</strong><p>A pólis era comunidade política territorial, e o mundo grego combinava conexões culturais com autonomia das cidades.</p></div>"
    },
    {
        "titulo": "3. Atenas: reformas e construção da democracia",
        "conteudo": "<p>Atenas passou por reformas durante conflitos entre aristocratas, pequenos proprietários, comerciantes e endividados. A democracia resultou de um processo, não de uma invenção individual repentina.</p><p>Drácon é associado à primeira codificação escrita de leis atenienses. A dureza atribuída a suas penas originou o uso moderno do adjetivo “draconiano”.</p><p>Sólon limitou a escravização por dívidas de cidadãos, reorganizou participação por riqueza e criou espaços de recurso jurídico. Suas medidas não aboliram desigualdades nem criaram democracia plena.</p><p>Após um período de tirania, Clístenes reorganizou cidadãos por demos e tribos territoriais. Essa mudança reduziu parte do peso das antigas redes aristocráticas.</p><p>O Conselho dos Quinhentos preparava assuntos para a assembleia, enquanto magistraturas podiam ser preenchidas por eleição ou sorteio.</p><p>A Eclésia deliberava diretamente sobre guerra, finanças e decisões políticas. Pagamentos por funções públicas, ampliados no século V a.C., facilitaram a participação de cidadãos menos ricos.</p><p>O ostracismo permitia afastar por dez anos um cidadão visto como ameaça política, sem funcionar como julgamento criminal comum.</p><p>Em provas, organize a sequência: Drácon–leis escritas; Sólon–dívidas e classes censitárias; Clístenes–demos e tribos; Péricles–ampliação da participação no século V.</p><div class=\"box-teoria exemplo\"><strong>🧭 Exemplo de prova:</strong><p>Uma questão pode pedir para distinguir reformas de Sólon e Clístenes pela cronologia e pelo conteúdo.</p></div><div class=\"box-teoria erro\"><strong>⚠️ Erro clássico:</strong><p>Atribuir voto universal ou cidadania de mulheres e metecos às reformas atenienses.</p></div><div class=\"box-teoria dica\"><strong>🎯 Dica de banca:</strong><p>Democracia ateniense foi processo gradual, condicionado por conflitos sociais.</p></div><div class=\"box-teoria checkpoint\"><strong>✅ Checkpoint:</strong><p>Como a organização territorial de Clístenes afetou as redes aristocráticas?</p></div><div class=\"box-teoria resumo\"><strong>📝 Resumo:</strong><p>A democracia ateniense foi construída por reformas sucessivas e participação direta de um corpo cívico restrito.</p></div>"
    },
    {
        "titulo": "4. Limites da democracia ateniense e sociedade",
        "conteudo": "<p>A cidadania ateniense clássica estava concentrada em homens livres, adultos e filhos de cidadãos. Mulheres, metecos e pessoas escravizadas eram excluídos da participação formal.</p><p>Os metecos eram estrangeiros residentes. Atuavam em comércio, artesanato e serviços, pagavam tributos específicos e podiam servir militarmente, mas não possuíam cidadania comum.</p><p>Mulheres cidadãs tinham papel central na família, herança e cultos, porém não participavam da assembleia ou das magistraturas políticas.</p><p>O trabalho escravizado existia em casas, oficinas, minas e atividades agrícolas. A democracia de cidadãos coexistia com uma estrutura social desigual.</p><p>As decisões da assembleia podiam ser influenciadas por oradores, guerras, redes de prestígio e desigualdade econômica. Participação direta não eliminava disputas de poder.</p><p>Atenas também construiu um império marítimo e utilizou tributos dos aliados. Democracia interna e dominação externa coexistiram.</p><p>O conceito moderno de democracia envolve representação, sufrágio amplo, direitos individuais e constituições que não correspondem exatamente às instituições antigas.</p><p>Em concurso, uma resposta equilibrada reconhece inovação participativa e exclusões sociais, sem idealizar ou negar a experiência ateniense.</p><div class=\"box-teoria exemplo\"><strong>🧭 Exemplo de prova:</strong><p>A mesma Atenas que deliberava em assembleia reprimia cidades que tentavam abandonar a Liga de Delos.</p></div><div class=\"box-teoria erro\"><strong>⚠️ Erro clássico:</strong><p>Usar a palavra democracia para afirmar igualdade política de toda a população.</p></div><div class=\"box-teoria dica\"><strong>🎯 Dica de banca:</strong><p>Procure alternativas que apresentem participação e exclusão simultaneamente.</p></div><div class=\"box-teoria checkpoint\"><strong>✅ Checkpoint:</strong><p>Por que a presença da Eclésia não permite falar em sufrágio universal?</p></div><div class=\"box-teoria resumo\"><strong>📝 Resumo:</strong><p>A democracia ateniense era direta entre cidadãos, mas excluía grande parte da população e convivia com imperialismo.</p></div>"
    },
    {
        "titulo": "5. Esparta e a diversidade das pólis",
        "conteudo": "<p>Esparta mostra que não existia um único modelo de pólis. Sua organização resultou da conquista da Messênia e da sujeição de populações chamadas hilotas.</p><p>Os esparciatas eram cidadãos-guerreiros que dependiam do trabalho de grupos subordinados. Seu número diminuiu ao longo do tempo, criando dificuldades políticas e militares.</p><p>A diarquia reunia dois reis, especialmente associados a funções militares e religiosas. A Gerúsia era conselho de anciãos, e os éforos exerciam fiscalização e administração.</p><p>A Ápela reunia cidadãos, mas sua participação não equivalia à assembleia ateniense. O sistema espartano possuía forte caráter oligárquico.</p><p>A educação dos jovens esparciatas, frequentemente chamada agogê, enfatizava disciplina coletiva e preparação militar, embora práticas tenham mudado ao longo do tempo.</p><p>Mulheres espartanas possuíam maior visibilidade patrimonial e treinamento físico do que em muitas pólis, mas não exerciam cidadania política formal.</p><p>Os periecos eram comunidades livres sem cidadania espartiata, ligadas a comércio, artesanato e serviço militar. Os hilotas estavam sujeitos ao trabalho compulsório.</p><p>Comparar Atenas e Esparta exige observar instituições, grupos sociais e base econômica, evitando a fórmula simplista “democracia contra militarismo”.</p><div class=\"box-teoria exemplo\"><strong>🧭 Exemplo de prova:</strong><p>A vigilância sobre os hilotas ajuda a explicar a centralidade militar da sociedade espartana.</p></div><div class=\"box-teoria erro\"><strong>⚠️ Erro clássico:</strong><p>Afirmar que todos os habitantes de Esparta eram soldados-cidadãos iguais.</p></div><div class=\"box-teoria dica\"><strong>🎯 Dica de banca:</strong><p>Memorize as diferenças entre esparciatas, periecos e hilotas.</p></div><div class=\"box-teoria checkpoint\"><strong>✅ Checkpoint:</strong><p>Como a sujeição dos hilotas sustentava e ameaçava o sistema espartano?</p></div><div class=\"box-teoria resumo\"><strong>📝 Resumo:</strong><p>Esparta combinou instituições oligárquicas, cidadania militar restrita e domínio sobre populações subordinadas.</p></div>"
    },
    {
        "titulo": "6. Guerras, hegemonias e crise das pólis",
        "conteudo": "<p>As Guerras Greco-Persas envolveram expedições aquemênidas e alianças entre algumas pólis. Batalhas como Maratona, Termópilas, Salamina e Plateia tornaram-se referências de memória política.</p><p>A cooperação contra os persas não criou um Estado grego unificado. Rivalidades entre Atenas, Esparta e outras cidades continuaram.</p><p>A Liga de Delos nasceu como aliança defensiva, mas Atenas controlou tributos, frota e decisões, transformando-a em instrumento de hegemonia.</p><p>A Guerra do Peloponeso opôs principalmente as alianças de Atenas e Esparta. Peste, revoltas, campanhas fracassadas e intervenção persa contribuíram para a derrota ateniense.</p><p>A vitória espartana não gerou estabilidade. Tebas, Atenas e Esparta disputaram novas hegemonias ao longo do século IV a.C.</p><p>Filipe II da Macedônia reformou o exército e utilizou diplomacia e guerra para impor supremacia após Queroneia.</p><p>Alexandre conquistou o Império Persa e formou domínio extenso, mas sua morte produziu reinos rivais governados por sucessores.</p><p>Em prova, ligue guerras e instituições: vitória contra a Pérsia fortaleceu Atenas; imperialismo ateniense aumentou tensões; conflitos internos favoreceram a Macedônia.</p><div class=\"box-teoria exemplo\"><strong>🧭 Exemplo de prova:</strong><p>A Liga de Delos passou de aliança defensiva a instrumento de domínio ateniense.</p></div><div class=\"box-teoria erro\"><strong>⚠️ Erro clássico:</strong><p>Confundir Guerras Médicas, Guerra do Peloponeso e conquista macedônica.</p></div><div class=\"box-teoria dica\"><strong>🎯 Dica de banca:</strong><p>Use linha do tempo e identifique adversários, alianças e consequências.</p></div><div class=\"box-teoria checkpoint\"><strong>✅ Checkpoint:</strong><p>Por que a vitória grega contra a Pérsia não produziu unidade política?</p></div><div class=\"box-teoria resumo\"><strong>📝 Resumo:</strong><p>Guerras e hegemonias transformaram as pólis e abriram caminho para a supremacia macedônica.</p></div>"
    },
    {
        "titulo": "7. Helenismo, religião, cultura e pensamento grego",
        "conteudo": "<p>O helenismo designa o período de reinos formados após Alexandre e a ampla circulação de língua, instituições e práticas gregas em contato com tradições locais.</p><p>Alexandria tornou-se centro de governo, comércio e conhecimento. Bibliotecas, museus e escolas reuniam estudiosos de diferentes regiões.</p><p>A religião grega era plural e ritual. Cultos cívicos, domésticos, oráculos, mistérios e festivais vinculavam pessoas a cidades e comunidades.</p><p>O teatro surgiu em festivais religiosos e discutia conflitos de poder, justiça, família, guerra e identidade cívica.</p><p>Filosofias não formavam bloco único. Sócrates, Platão, Aristóteles, estoicos, epicuristas e céticos propuseram respostas diferentes sobre conhecimento e vida coletiva.</p><p>Heródoto e Tucídides desenvolveram formas de investigação do passado, mas escreveram com métodos, temas e escolhas narrativas próprias.</p><p>Arte e arquitetura gregas eram coloridas e ligadas a usos religiosos e políticos. A imagem de mármore branco é em parte resultado da perda da policromia.</p><p>Em concursos, evite afirmar que a cultura grega substituiu totalmente culturas locais ou que filosofia eliminou mito e religião.</p><div class=\"box-teoria exemplo\"><strong>🧭 Exemplo de prova:</strong><p>O helenismo pode ser observado em moedas, cidades, cultos e textos que combinam elementos de diferentes regiões.</p></div><div class=\"box-teoria erro\"><strong>⚠️ Erro clássico:</strong><p>Tratar helenização como cópia passiva e uniforme da cultura grega.</p></div><div class=\"box-teoria dica\"><strong>🎯 Dica de banca:</strong><p>Cultura circula por apropriações, negociações e relações de poder.</p></div><div class=\"box-teoria checkpoint\"><strong>✅ Checkpoint:</strong><p>Como o mundo helenístico combinou integração e diversidade?</p></div><div class=\"box-teoria resumo\"><strong>📝 Resumo:</strong><p>O helenismo ampliou redes culturais e políticas, sem apagar tradições locais ou conflitos.</p></div>"
    },
    {
        "titulo": "8. Origens de Roma, monarquia e República",
        "conteudo": "<p>Roma surgiu no Lácio por integração de comunidades e contatos com latinos, sabinos, etruscos e gregos. A tradição de Rômulo e Remo expressa memória cívica, não relato arqueológico literal.</p><p>O período monárquico é conhecido por tradições posteriores. Reis exerciam funções religiosas, militares e judiciais em interação com Senado e assembleias.</p><p>A expulsão do último rei é apresentada pela tradição como início da República, em torno de 509 a.C. A mudança fortaleceu famílias aristocráticas.</p><p>Os cônsules eram magistrados anuais com comando militar. Pretor, questor, edil e censor desempenhavam outras funções no cursus honorum.</p><p>O Senado reunia antigos magistrados e possuía grande autoridade sobre política externa, finanças e administração.</p><p>Os comícios elegiam magistrados e aprovavam medidas, mas sua organização por riqueza e unidades de voto produzia desigualdades.</p><p>O Conflito das Ordens permitiu conquistas plebeias, como tribunos, Doze Tábuas e acesso gradual a magistraturas.</p><p>Em prova, República Romana não deve ser confundida com democracia igualitária: instituições eletivas coexistiam com poder oligárquico.</p><div class=\"box-teoria exemplo\"><strong>🧭 Exemplo de prova:</strong><p>A Lei das Doze Tábuas ampliou publicidade jurídica, mas não criou igualdade social moderna.</p></div><div class=\"box-teoria erro\"><strong>⚠️ Erro clássico:</strong><p>Traduzir República como governo de todo o povo em condições iguais.</p></div><div class=\"box-teoria dica\"><strong>🎯 Dica de banca:</strong><p>Compare magistraturas anuais, Senado e assembleias sem apagar hierarquias.</p></div><div class=\"box-teoria checkpoint\"><strong>✅ Checkpoint:</strong><p>Quais elementos aristocráticos e populares coexistiam na República?</p></div><div class=\"box-teoria resumo\"><strong>📝 Resumo:</strong><p>A República distribuiu funções entre magistrados, Senado e assembleias, mantendo forte desigualdade.</p></div>"
    },
    {
        "titulo": "9. Expansão romana e crise da República",
        "conteudo": "<p>Roma expandiu-se pela Itália mediante guerras, tratados, colônias e estatutos diferenciados. Essa flexibilidade integrou aliados de forma hierárquica.</p><p>As Guerras Púnicas contra Cartago deram a Roma domínio no Mediterrâneo ocidental. A vitória ampliou províncias, tributos, riquezas e cativos.</p><p>A expansão favoreceu grandes proprietários e aumentou o uso de trabalho escravizado em várias atividades. Pequenos camponeses enfrentaram dificuldades, embora os efeitos variassem regionalmente.</p><p>Tibério e Caio Graco tentaram responder a problemas de terra, abastecimento e cidadania. A violência contra os tribunos marcou a radicalização política.</p><p>Mário, Sula, Pompeu, Crasso e César combinaram comandos militares, alianças e competição por poder. Soldados podiam vincular expectativas de recompensa aos generais.</p><p>Guerras civis e proscrições enfraqueceram normas republicanas. Comandos extraordinários tornaram-se mais frequentes.</p><p>Júlio César foi nomeado ditador perpétuo e assassinado em 44 a.C. Ele não foi o primeiro imperador no sentido institucional consolidado por Augusto.</p><p>Para concurso, relacione expansão externa e crise interna: conquistas transformaram economia, exército, elites e participação política.</p><div class=\"box-teoria exemplo\"><strong>🧭 Exemplo de prova:</strong><p>A entrada de cativos e riquezas ampliou desigualdades e disputas agrárias.</p></div><div class=\"box-teoria erro\"><strong>⚠️ Erro clássico:</strong><p>Explicar o fim da República por ambição de um único indivíduo.</p></div><div class=\"box-teoria dica\"><strong>🎯 Dica de banca:</strong><p>Procure relações entre guerra, exército, terra, cidadania e competição aristocrática.</p></div><div class=\"box-teoria checkpoint\"><strong>✅ Checkpoint:</strong><p>Como a expansão mediterrânica alterou as bases sociais da República?</p></div><div class=\"box-teoria resumo\"><strong>📝 Resumo:</strong><p>A crise republicana resultou de transformações sociais e militares acumuladas durante a expansão.</p></div>"
    },
    {
        "titulo": "10. Augusto, Principado e integração imperial",
        "conteudo": "<p>Após novas guerras civis, Otávio venceu Marco Antônio e Cleópatra. Em 27 a.C., recebeu o título de Augusto e reorganizou o poder.</p><p>O Principado preservou nomes e cargos republicanos, mas concentrou no príncipe comando militar, autoridade religiosa e controle de províncias estratégicas.</p><p>Augusto utilizou propaganda, monumentos, literatura e restauração de cultos para apresentar seu governo como retorno da ordem.</p><p>A Pax Romana designa estabilidade relativa, não ausência de guerras. Exércitos continuaram nas fronteiras e revoltas foram reprimidas.</p><p>Províncias eram administradas por autoridades imperiais ou senatoriais, com participação de elites locais e cobrança de tributos.</p><p>Estradas, portos, moedas e cidades facilitaram circulação de tropas, impostos e mercadorias, mas a integração econômica permaneceu desigual.</p><p>A romanização é melhor entendida como apropriação e negociação. Latim, direito e urbanismo misturaram-se a línguas, cultos e tradições locais.</p><p>Em concurso, diferencie propaganda de restauração republicana e realidade de concentração de poder no princeps.</p><div class=\"box-teoria exemplo\"><strong>🧭 Exemplo de prova:</strong><p>O Senado permaneceu ativo, mas sua autonomia foi condicionada pela supremacia imperial.</p></div><div class=\"box-teoria erro\"><strong>⚠️ Erro clássico:</strong><p>Descrever Augusto como rei absoluto medieval ou como simples magistrado republicano.</p></div><div class=\"box-teoria dica\"><strong>🎯 Dica de banca:</strong><p>Principado combina continuidade formal e mudança efetiva na distribuição do poder.</p></div><div class=\"box-teoria checkpoint\"><strong>✅ Checkpoint:</strong><p>Por que Augusto evitou apresentar-se oficialmente como rei?</p></div><div class=\"box-teoria resumo\"><strong>📝 Resumo:</strong><p>O Principado manteve formas republicanas enquanto consolidava a autoridade do imperador.</p></div>"
    },
    {
        "titulo": "11. Sociedade, trabalho, religião e direito no Império",
        "conteudo": "<p>A sociedade romana era hierárquica. Cidadania, liberdade, gênero, riqueza, origem e patronato afetavam direitos e oportunidades.</p><p>Pessoas escravizadas atuavam em casas, campos, minas, oficinas e administração. Manumissões existiam, mas não eliminavam a violência e a exploração do sistema.</p><p>Libertos podiam trabalhar, enriquecer e formar famílias, embora carregassem limitações jurídicas e vínculos com antigos proprietários.</p><p>Mulheres não ocupavam magistraturas, mas podiam gerir patrimônio, negócios, redes familiares e cultos, especialmente entre grupos de maior riqueza.</p><p>A religião imperial reuniu cultos tradicionais, domésticos, orientais e veneração ao imperador. Sincretismo e repressão coexistiam.</p><p>Cristãos enfrentaram perseguições em momentos específicos. No século IV, Constantino favoreceu a religião e Teodósio ampliou sua posição dominante.</p><p>O direito romano resultou de leis, costumes, juristas e decisões acumuladas. Ele mudou ao longo do tempo e foi reinterpretado em sociedades posteriores.</p><p>A Constitutio Antoniniana de 212 ampliou cidadania à maioria dos homens livres do Império, sem criar igualdade social ampla.</p><div class=\"box-teoria exemplo\"><strong>🧭 Exemplo de prova:</strong><p>Uma mulher rica podia administrar propriedades sem ter direito a ocupar o consulado.</p></div><div class=\"box-teoria erro\"><strong>⚠️ Erro clássico:</strong><p>Afirmar que cidadania, liberdade ou gênero tinham o mesmo efeito para toda a população.</p></div><div class=\"box-teoria dica\"><strong>🎯 Dica de banca:</strong><p>Cruze status jurídico, riqueza e gênero ao analisar a sociedade romana.</p></div><div class=\"box-teoria checkpoint\"><strong>✅ Checkpoint:</strong><p>Por que a manumissão não permite classificar a escravidão romana como relação branda?</p></div><div class=\"box-teoria resumo\"><strong>📝 Resumo:</strong><p>O Império articulou cidadania ampla e hierarquias profundas, com trabalho escravizado e diversidade religiosa.</p></div>"
    },
    {
        "titulo": "12. Crises, Antiguidade Tardia e estratégia de prova",
        "conteudo": "<p>A crise do século III combinou sucessões rápidas, guerras civis, pressão nas fronteiras, epidemias e dificuldades monetárias e fiscais.</p><p>Diocleciano reformou administração, exército e tributação. A Tetrarquia dividiu responsabilidades entre dois augustos e dois césares.</p><p>Constantino reuniu o poder, fundou Constantinopla e favoreceu o cristianismo. O centro político do Império deslocou-se progressivamente para o Oriente.</p><p>Migrações, acordos e guerras envolveram povos chamados genericamente de germânicos. Eles não formavam bloco único nem destruíram sozinhos o Império.</p><p>Em 476, a deposição de Rômulo Augústulo tornou-se marco do fim do Ocidente, mas instituições, leis, cidades e identidades romanas continuaram em vários reinos.</p><p>O Império Romano do Oriente persistiu por séculos, com capital em Constantinopla. Por isso, 476 não representa fim de toda a história romana.</p><p>O conceito de Antiguidade Tardia destaca transformações religiosas, políticas e culturais, evitando a narrativa de decadência uniforme e súbita.</p><p>Para revisar, organize quatro eixos: cronologia, instituições, grupos sociais e conceitos. Desconfie de alternativas absolutas e comparações anacrônicas.</p><div class=\"box-teoria exemplo\"><strong>🧭 Exemplo de prova:</strong><p>Uma questão pode opor “queda súbita” a “transformação gradual com rupturas e continuidades”.</p></div><div class=\"box-teoria erro\"><strong>⚠️ Erro clássico:</strong><p>Usar 476 como desaparecimento imediato de Roma em todo o Mediterrâneo.</p></div><div class=\"box-teoria dica\"><strong>🎯 Dica de banca:</strong><p>Diferencie Império do Ocidente, Império do Oriente e reinos pós-romanos.</p></div><div class=\"box-teoria checkpoint\"><strong>✅ Checkpoint:</strong><p>Quais continuidades permaneceram depois da deposição do último imperador do Ocidente?</p></div><div class=\"box-teoria resumo\"><strong>📝 Resumo:</strong><p>A Antiguidade Tardia foi período de crises e reorganizações, não simples desaparecimento instantâneo do mundo romano.</p></div>"
    }
];
