// FAROL DO SABER — Tópico 33 de História
// A Crise Econômica Mundial e o avanço dos Regimes Totalitários pela Europa
// Teoria premium em 12 páginas.

const criseEconomicaMundialAvancoRegimesTotalitariosEuropaTeoria = [
    {
        "titulo": "1. O mundo do pós-guerra e a instabilidade dos anos 1920",
        "conteudo": "<p>O período entre as duas guerras mundiais foi marcado por reconstrução, transformações culturais, disputas sociais e fragilidade política. A paz de 1919 encerrou os combates, mas não produziu estabilidade duradoura.</p><p>A Europa saiu da Primeira Guerra com dívidas, inflação, infraestrutura danificada e perdas demográficas. Estados Unidos e Japão ampliaram sua posição econômica, enquanto antigas potências europeias tentavam recuperar mercados.</p><p>As reparações impostas à Alemanha e as dívidas dos Aliados criaram um circuito financeiro dependente de empréstimos norte-americanos. O sistema funcionava enquanto o crédito permanecia disponível.</p><p>Novos Estados da Europa central enfrentavam minorias nacionais, fronteiras contestadas e instituições recentes. Democracias parlamentares coexistiam com movimentos revolucionários e grupos autoritários.</p><p>O medo da expansão comunista depois de 1917 levou setores conservadores a apoiar alternativas que prometiam ordem. Isso não significa que todo anticomunista aderiu ao fascismo.</p><p>A inflação alemã de 1923 destruiu poupanças e abalou a confiança, embora tenha sido estabilizada antes da crise de 1929. Confundir hiperinflação com Grande Depressão apaga momentos econômicos diferentes.</p><p>Em provas, o entreguerras deve ser visto como sequência de recuperação parcial e novas crises, não como intervalo homogêneo entre duas guerras.</p><div class=\"box-teoria exemplo\"><strong>🧭 Exemplo de prova:</strong><p>Empréstimos dos Estados Unidos ajudavam a Alemanha a pagar reparações, que financiavam o pagamento de dívidas dos Aliados.</p></div><div class=\"box-teoria erro\"><strong>⚠️ Erro clássico:</strong><p>Tratar a crise de 1929 como continuação direta e sem diferenças da hiperinflação alemã de 1923.</p></div><div class=\"box-teoria dica\"><strong>🎯 Dica de banca:</strong><p>Pós-guerra = dívidas, reparações, dependência de crédito e fragilidade democrática.</p></div><div class=\"box-teoria resumo\"><strong>📝 Resumo:</strong><p>A ordem de 1919 reorganizou fronteiras, mas preservou tensões econômicas, nacionais e políticas.</p></div>"
    },
    {
        "titulo": "2. Os Estados Unidos e os limites da prosperidade",
        "conteudo": "<p>Nos anos 1920, os Estados Unidos viveram expansão da indústria, do crédito e do consumo. Automóveis, eletrodomésticos, publicidade e produção em massa transformaram hábitos urbanos.</p><p>O fordismo articulava padronização, linha de montagem e grandes mercados. A produtividade aumentou, mas salários, lucros e capacidade de consumo não cresceram de modo igualmente distribuído.</p><p>Compras a prazo ampliaram a demanda e o endividamento das famílias. O crédito permitia consumir no presente com renda futura, tornando muitos orçamentos sensíveis a desemprego e queda de salários.</p><p>A agricultura enfrentava dificuldades desde o fim da Primeira Guerra. Produtores haviam ampliado a oferta durante o conflito e depois sofreram com queda de preços, dívidas e estoques.</p><p>A concentração de renda restringia a capacidade de absorver toda a produção. Superprodução não significa excesso absoluto de bens, mas produção superior à demanda capaz de pagar.</p><p>A bolsa atraiu investidores que compravam ações com recursos emprestados. A expectativa de valorização alimentava preços cada vez mais afastados dos resultados de algumas empresas.</p><p>A prosperidade era real, porém desigual e apoiada em fragilidades. A crise não pode ser explicada por consumo excessivo ou especulação isoladamente.</p><div class=\"box-teoria exemplo\"><strong>🧭 Exemplo de prova:</strong><p>Uma fábrica podia produzir mais automóveis do que consumidores endividados conseguiam comprar.</p></div><div class=\"box-teoria erro\"><strong>⚠️ Erro clássico:</strong><p>Afirmar que toda a sociedade norte-americana participou igualmente da prosperidade.</p></div><div class=\"box-teoria dica\"><strong>🎯 Dica de banca:</strong><p>Associe produtividade, concentração de renda, crédito, crise agrícola e especulação.</p></div><div class=\"box-teoria resumo\"><strong>📝 Resumo:</strong><p>A expansão norte-americana combinou inovação e consumo com desequilíbrios de renda, crédito e produção.</p></div>"
    },
    {
        "titulo": "3. A quebra de 1929 e a Grande Depressão",
        "conteudo": "<p>Em outubro de 1929, fortes vendas derrubaram o preço das ações em Nova York. A Quinta-Feira Negra tornou-se símbolo de uma crise que possuía causas anteriores e efeitos posteriores.</p><p>A queda da bolsa reduziu patrimônios e confiança, mas não explica sozinha a depressão. Falências bancárias, contração do crédito, queda do consumo e redução do investimento reforçaram-se mutuamente.</p><p>Bancos haviam emprestado para especulação e enfrentaram retiradas de depósitos. Como não existia proteção federal ampla aos depositantes, falências podiam eliminar economias familiares.</p><p>Empresas reduziram produção e demitiram trabalhadores. O desemprego diminuía ainda mais a demanda, criando um ciclo de queda econômica.</p><p>O governo de Herbert Hoover adotou algumas medidas e obras, porém manteve confiança considerável no ajuste do mercado e respostas voluntárias. A escala da crise superou suas políticas.</p><p>A Grande Depressão foi prolongada e variou por país e setor. A economia norte-americana começou a se recuperar nos anos 1930, mas a mobilização da Segunda Guerra eliminou o desemprego em grande escala.</p><p>Em concursos, diferencie quebra da bolsa, evento financeiro de 1929, e Grande Depressão, processo econômico e social mais amplo.</p><div class=\"box-teoria exemplo\"><strong>🧭 Exemplo de prova:</strong><p>A falência de um banco podia reduzir crédito empresarial e destruir a poupança de consumidores ao mesmo tempo.</p></div><div class=\"box-teoria erro\"><strong>⚠️ Erro clássico:</strong><p>Explicar a crise como punição moral a investidores ou como um único dia de queda.</p></div><div class=\"box-teoria dica\"><strong>🎯 Dica de banca:</strong><p>Bolsa cai → crédito contrai → produção e emprego caem → consumo diminui.</p></div><div class=\"box-teoria resumo\"><strong>📝 Resumo:</strong><p>A crise financeira converteu fragilidades econômicas em uma depressão profunda e cumulativa.</p></div>"
    },
    {
        "titulo": "4. Mundialização da crise e efeitos sociais",
        "conteudo": "<p>A crise tornou-se mundial porque os Estados Unidos eram credores, investidores e consumidores centrais. A retirada de capitais e a queda das importações transmitiram a depressão.</p><p>A Alemanha dependia de empréstimos norte-americanos para estabilizar sua economia e cumprir pagamentos. A interrupção do crédito agravou falências e desemprego.</p><p>O padrão-ouro limitava respostas monetárias ao vincular moedas a reservas metálicas. Países que abandonaram mais cedo essa rigidez puderam adotar políticas expansivas com maior liberdade.</p><p>Governos elevaram tarifas para proteger produtores nacionais. O protecionismo adotado por vários países reduziu o comércio e aprofundou dificuldades internacionais.</p><p>Economias exportadoras de produtos primários sofreram com queda de preços e demanda. Na América Latina, a crise estimulou novas políticas industriais e maior intervenção estatal.</p><p>Desemprego, perda de moradias, insegurança e pobreza atingiram milhões de pessoas. Redes familiares, associações, sindicatos e governos ofereceram respostas desiguais.</p><p>A crise deslegitimou partidos tradicionais em alguns lugares, mas não produziu automaticamente ditaduras. Instituições, alianças sociais e decisões políticas explicam resultados nacionais diferentes.</p><div class=\"box-teoria exemplo\"><strong>🧭 Exemplo de prova:</strong><p>A retirada de empréstimos norte-americanos podia causar crise bancária em outro país antes mesmo de grande queda de suas exportações.</p></div><div class=\"box-teoria erro\"><strong>⚠️ Erro clássico:</strong><p>Afirmar que a depressão levou todos os países europeus ao fascismo.</p></div><div class=\"box-teoria dica\"><strong>🎯 Dica de banca:</strong><p>Transmissão internacional: capitais, bancos, comércio, padrão-ouro e protecionismo.</p></div><div class=\"box-teoria resumo\"><strong>📝 Resumo:</strong><p>Interdependência econômica transformou a crise norte-americana em depressão mundial.</p></div>"
    },
    {
        "titulo": "5. Democracias, keynesianismo e New Deal",
        "conteudo": "<p>A depressão abriu debate sobre os limites do liberalismo econômico. John Maynard Keynes defendeu que a demanda agregada poderia ser estimulada por gastos públicos em períodos de retração.</p><p>Eleito em 1932, Franklin Roosevelt lançou o New Deal. O programa reuniu socorro emergencial, recuperação econômica e reformas regulatórias, sem apresentar um plano imutável desde o início.</p><p>Obras públicas criaram empregos e infraestrutura. Programas apoiaram agricultores, trabalhadores e comunidades, embora benefícios tenham sido distribuídos de forma desigual.</p><p>Reformas bancárias criaram garantias aos depósitos e maior fiscalização. Regras para o mercado financeiro buscavam restaurar confiança e reduzir práticas de risco.</p><p>Direitos sindicais e previdência ampliaram a responsabilidade federal. O New Deal reformou o capitalismo norte-americano em vez de abolir propriedade privada e mercado.</p><p>Críticos conservadores consideravam a intervenção excessiva; setores progressistas julgavam as medidas insuficientes. A Suprema Corte anulou partes do programa, mostrando conflitos institucionais.</p><p>Democracias europeias também adotaram combinações de proteção social, desvalorização monetária e intervenção. A crise gerou respostas variadas, não apenas totalitarismo.</p><div class=\"box-teoria exemplo\"><strong>🧭 Exemplo de prova:</strong><p>Contratar trabalhadores para uma obra pública podia elevar renda e demanda por produtos privados.</p></div><div class=\"box-teoria erro\"><strong>⚠️ Erro clássico:</strong><p>Confundir New Deal com socialização integral da economia norte-americana.</p></div><div class=\"box-teoria dica\"><strong>🎯 Dica de banca:</strong><p>New Deal = alívio, recuperação, reforma e maior intervenção do Estado.</p></div><div class=\"box-teoria resumo\"><strong>📝 Resumo:</strong><p>As democracias responderam à depressão por regulação, políticas sociais e estímulo econômico.</p></div>"
    },
    {
        "titulo": "6. Totalitarismo e autoritarismo: conceitos e debates",
        "conteudo": "<p>O conceito de totalitarismo analisa regimes que pretendem subordinar amplas dimensões da vida social a uma ideologia, um partido e uma liderança. Seu uso exige comparação cuidadosa.</p><p>Entre características recorrentes estão partido dominante ou único, culto à liderança, propaganda, censura, polícia política, mobilização das massas e repressão de opositores.</p><p>Regimes autoritários restringem liberdades e competição política, mas podem buscar desmobilização social e preservar instituições tradicionais com maior autonomia.</p><p>Fascismo italiano, nazismo alemão e stalinismo soviético possuíam semelhanças nos mecanismos de controle, porém bases ideológicas, objetivos econômicos e trajetórias diferentes.</p><p>Fascismos defendiam ultranacionalismo, hierarquia, anticomunismo e violência política. O nazismo acrescentou centralidade extrema ao racismo biológico e ao antissemitismo.</p><p>O stalinismo afirmava construir o socialismo por planejamento e propriedade estatal. Sua ditadura não pode ser definida como variante nacionalista do fascismo sem considerar essas diferenças.</p><p>Historiadores debatem até que ponto os regimes controlaram efetivamente toda a sociedade. A intenção totalizante encontrou limites, acomodações e resistências.</p><div class=\"box-teoria exemplo\"><strong>🧭 Exemplo de prova:</strong><p>Dois regimes podem usar propaganda e partido único sem possuir a mesma ideologia.</p></div><div class=\"box-teoria erro\"><strong>⚠️ Erro clássico:</strong><p>Tratar totalitarismo, fascismo, nazismo, stalinismo e qualquer ditadura como sinônimos perfeitos.</p></div><div class=\"box-teoria dica\"><strong>🎯 Dica de banca:</strong><p>Compare mecanismos de poder e, separadamente, ideologia, propriedade e objetivos.</p></div><div class=\"box-teoria resumo\"><strong>📝 Resumo:</strong><p>Totalitarismo é categoria comparativa, não licença para apagar diferenças históricas.</p></div>"
    },
    {
        "titulo": "7. A ascensão do fascismo italiano",
        "conteudo": "<p>A Itália venceu a Primeira Guerra ao lado da Entente, mas nacionalistas denunciavam uma vitória mutilada por não receber todos os territórios desejados.</p><p>O pós-guerra trouxe inflação, desemprego, ocupações de fábricas e conflitos rurais. O medo do socialismo aproximou proprietários e setores conservadores dos grupos fascistas.</p><p>Benito Mussolini fundou os Fasci di Combattimento em 1919. O movimento combinava nacionalismo radical, culto à ação, anticomunismo e mudanças oportunistas de programa.</p><p>Esquadrões fascistas atacavam organizações de trabalhadores e administrações socialistas com tolerância ou apoio de partes do Estado e das elites.</p><p>Na Marcha sobre Roma de 1922, o rei Vítor Emanuel III recusou decretar estado de sítio e convidou Mussolini a formar governo. A tomada do poder envolveu pressão e decisão institucional, não conquista militar da capital.</p><p>Mussolini inicialmente chefiou uma coalizão. Alterações eleitorais, intimidação e crise após o assassinato de Giacomo Matteotti abriram caminho à ditadura.</p><p>O fascismo não chegou ao poder apenas por voto, golpe ou apoio empresarial: mobilização, coerção, alianças e escolhas da monarquia interagiram.</p><div class=\"box-teoria exemplo\"><strong>🧭 Exemplo de prova:</strong><p>O rei podia bloquear Mussolini, mas escolheu nomeá-lo primeiro-ministro diante da pressão fascista.</p></div><div class=\"box-teoria erro\"><strong>⚠️ Erro clássico:</strong><p>Descrever a Marcha sobre Roma como batalha que derrubou militarmente o governo.</p></div><div class=\"box-teoria dica\"><strong>🎯 Dica de banca:</strong><p>Ascensão fascista = crise social + esquadrismo + apoio conservador + decisão monárquica.</p></div><div class=\"box-teoria resumo\"><strong>📝 Resumo:</strong><p>O fascismo italiano converteu violência de movimento e alianças institucionais em ditadura.</p></div>"
    },
    {
        "titulo": "8. Estado fascista, corporativismo e propaganda",
        "conteudo": "<p>Entre 1925 e 1926, leis fascistíssimas eliminaram oposição legal, restringiram imprensa e concentraram poder no chefe de governo. O Partido Nacional Fascista tornou-se eixo do regime.</p><p>O culto ao Duce apresentava Mussolini como intérprete da nação. Rádio, cinema, escola, arquitetura e cerimônias construíam uma imagem de unidade e dinamismo.</p><p>Organizações juvenis, profissionais e recreativas procuravam enquadrar a sociedade. Mobilização oficial coexistia com adesão oportunista, indiferença privada e limites administrativos.</p><p>O corporativismo organizava patrões e trabalhadores em corporações supervisionadas pelo Estado. Na prática, sindicatos independentes foram eliminados e o regime controlou conflitos trabalhistas.</p><p>A propriedade privada foi preservada. Intervenção estatal e empresas públicas cresceram, especialmente após a crise, sem transformar a Itália em economia socialista.</p><p>Os Pactos de Latrão de 1929 reconheceram o Vaticano e regularam relações com a Igreja. O acordo fortaleceu o regime, embora tensões posteriores permanecessem.</p><p>A política externa buscou prestígio, expansão e império. A aproximação com a Alemanha nazista ocorreu gradualmente e não foi uma aliança automática desde 1922.</p><div class=\"box-teoria exemplo\"><strong>🧭 Exemplo de prova:</strong><p>Uma corporação fascista reunia capital e trabalho sob arbitragem estatal, sem negociação sindical livre.</p></div><div class=\"box-teoria erro\"><strong>⚠️ Erro clássico:</strong><p>Identificar corporativismo fascista com controle dos meios de produção pelos trabalhadores.</p></div><div class=\"box-teoria dica\"><strong>🎯 Dica de banca:</strong><p>Corporativismo substitui conflito autônomo por enquadramento estatal.</p></div><div class=\"box-teoria resumo\"><strong>📝 Resumo:</strong><p>O regime fascista combinou partido, propaganda, repressão, corporativismo e alianças sociais.</p></div>"
    },
    {
        "titulo": "9. República de Weimar, crise e ascensão do nazismo",
        "conteudo": "<p>A República de Weimar nasceu em 1919 com constituição democrática, sufrágio amplo e direitos sociais. Enfrentou desde o início oposição da extrema esquerda, extrema direita e setores ligados ao antigo regime.</p><p>Versalhes, violência política e hiperinflação de 1923 abalaram a legitimidade. A estabilização posterior trouxe relativa prosperidade e intensa produção cultural.</p><p>O Partido Nazista tentou um golpe em 1923 e fracassou. Depois, Hitler combinou propaganda, organização partidária, mobilização eleitoral e violência paramilitar para disputar o poder.</p><p>A crise de 1929 elevou desemprego e enfraqueceu coalizões parlamentares. Nazistas prometeram trabalho, ordem, unidade nacional, anticomunismo e revisão de Versalhes.</p><p>O partido conquistou grande votação, mas nunca obteve sozinho maioria absoluta em eleição nacional livre. Elites conservadoras acreditaram que poderiam controlar Hitler.</p><p>Em janeiro de 1933, o presidente Paul von Hindenburg nomeou Hitler chanceler dentro dos mecanismos constitucionais. A democracia foi destruída rapidamente a partir do governo.</p><p>A ascensão não foi vitória eleitoral simples nem golpe militar clássico. Crise, apoio popular parcial, violência, erros conservadores e decisões presidenciais se combinaram.</p><div class=\"box-teoria exemplo\"><strong>🧭 Exemplo de prova:</strong><p>Um partido antidemocrático utilizou eleições e alianças institucionais para chegar ao governo e eliminar a competição.</p></div><div class=\"box-teoria erro\"><strong>⚠️ Erro clássico:</strong><p>Afirmar que Hitler foi eleito diretamente presidente com maioria absoluta.</p></div><div class=\"box-teoria dica\"><strong>🎯 Dica de banca:</strong><p>1933: Hindenburg nomeia Hitler chanceler; depois ocorre a destruição da democracia.</p></div><div class=\"box-teoria resumo\"><strong>📝 Resumo:</strong><p>A crise de Weimar abriu espaço ao nazismo, mas escolhas políticas concretizaram sua chegada ao poder.</p></div>"
    },
    {
        "titulo": "10. Ditadura nazista, racismo e perseguição",
        "conteudo": "<p>Após o incêndio do Reichstag, um decreto suspendeu direitos civis e permitiu perseguir opositores. A Lei de Plenos Poderes de março de 1933 autorizou o governo a legislar sem o parlamento.</p><p>Partidos e sindicatos foram dissolvidos, administrações coordenadas e adversários presos ou exilados. A Noite das Facas Longas eliminou rivais dentro do movimento e consolidou apoio militar.</p><p>Propaganda dirigida por Joseph Goebbels difundia culto ao Führer, comunidade nacional e anticomunismo. Cultura e educação foram submetidas a censura e enquadramento.</p><p>A ideologia nazista afirmava uma hierarquia racial pseudocientífica. Antissemitismo, eugenia e exclusão de grupos eram elementos centrais, não desvios posteriores.</p><p>As Leis de Nuremberg de 1935 retiraram cidadania dos judeus e proibiram determinadas relações civis. A perseguição foi ampliada por normas, expropriações e violência de Estado.</p><p>Rearmamento e obras reduziram desemprego, enquanto salários, consumo e direitos trabalhistas eram controlados. A recuperação relacionou-se também à preparação militar.</p><p>Resistências existiram em grupos políticos, religiosos, juvenis e individuais, mas enfrentaram repressão intensa. A existência de adesão social não significa apoio uniforme de todos os alemães.</p><div class=\"box-teoria exemplo\"><strong>🧭 Exemplo de prova:</strong><p>Excluir juridicamente um grupo da cidadania transforma preconceito em política de Estado.</p></div><div class=\"box-teoria erro\"><strong>⚠️ Erro clássico:</strong><p>Tratar o racismo nazista como propaganda secundária sem função institucional.</p></div><div class=\"box-teoria dica\"><strong>🎯 Dica de banca:</strong><p>Decreto do Reichstag restringe direitos; Plenos Poderes esvazia o parlamento.</p></div><div class=\"box-teoria resumo\"><strong>📝 Resumo:</strong><p>O nazismo destruiu instituições democráticas e organizou um Estado racial, policial e expansionista.</p></div>"
    },
    {
        "titulo": "11. Stalinismo e a comparação entre regimes",
        "conteudo": "<p>Na União Soviética, Stalin consolidou poder depois da morte de Lenin. O Partido Comunista controlava o Estado, enquanto disputas internas eram progressivamente eliminadas.</p><p>Planos Quinquenais orientaram industrialização pesada. A coletivização reorganizou a agricultura com coerção, resistência e graves custos humanos e econômicos.</p><p>Propaganda, culto a Stalin, censura, polícia política e expurgos estruturaram o regime. Processos públicos apresentavam confissões e condenações como defesa da revolução.</p><p>Fascismo, nazismo e stalinismo mobilizaram propaganda, partido, liderança e repressão. Essas semelhanças sustentam comparações pelo conceito de totalitarismo.</p><p>As diferenças também são essenciais. Nazismo defendia hierarquia racial e propriedade privada subordinada; stalinismo afirmava igualdade de classe, planejamento e propriedade estatal.</p><p>O fascismo italiano conservou monarquia e acordo com a Igreja, enquanto o nazismo reorganizou o Estado em torno da comunidade racial e da expansão territorial.</p><p>A comparação histórica deve explicar sem equiparar moral ou mecanicamente todos os processos. Semelhanças de método não produzem identidade completa de ideologia e estrutura.</p><div class=\"box-teoria exemplo\"><strong>🧭 Exemplo de prova:</strong><p>Partido único aparece em dois regimes, mas pode organizar projetos sociais e econômicos opostos.</p></div><div class=\"box-teoria erro\"><strong>⚠️ Erro clássico:</strong><p>Concluir que semelhanças repressivas tornam idênticas as ideologias nazista e soviética.</p></div><div class=\"box-teoria dica\"><strong>🎯 Dica de banca:</strong><p>Compare em colunas: liderança, partido, propaganda, propriedade, ideologia e inimigo definido.</p></div><div class=\"box-teoria resumo\"><strong>📝 Resumo:</strong><p>O conceito totalitário ilumina mecanismos comuns, mas exige preservar diferenças fundamentais.</p></div>"
    },
    {
        "titulo": "12. Autoritarismos europeus, resistência e síntese",
        "conteudo": "<p>Nem toda ditadura europeia do entreguerras foi fascista ou totalitária. Regimes conservadores autoritários em Portugal, Espanha, Hungria e outras áreas possuíam relações próprias com Igreja, elites e sociedade.</p><p>O salazarismo português valorizava ordem, catolicismo e corporativismo, porém mobilizava massas de modo distinto do nazismo. A Espanha franquista resultou de guerra civil e reuniu forças conservadoras variadas.</p><p>Frentes Populares buscaram unir socialistas, comunistas e republicanos contra o fascismo. Na França, chegaram ao governo por eleições em 1936 e aprovaram reformas sociais.</p><p>Intelectuais, sindicatos, igrejas, grupos juvenis e cidadãos resistiram de formas diferentes. Também houve acomodação, conformismo e colaboração, mostrando uma sociedade mais complexa que a oposição regime versus povo.</p><p>A propaganda totalitária utilizou meios modernos, mas não controlou automaticamente cada pensamento. Recepção dependia de experiência, interesse, medo e contexto.</p><p>A crise econômica favoreceu extremismos ao enfraquecer confiança e ampliar insegurança, mas não determinou um único resultado. Estados Unidos, Reino Unido e países nórdicos preservaram instituições representativas.</p><p>O avanço autoritário deve ser explicado por crise, memória da guerra, anticomunismo, nacionalismo, violência, alianças de elites e escolhas institucionais.</p><div class=\"box-teoria exemplo\"><strong>🧭 Exemplo de prova:</strong><p>Duas sociedades afetadas pelo desemprego podiam escolher respostas políticas diferentes conforme suas instituições e coalizões.</p></div><div class=\"box-teoria erro\"><strong>⚠️ Erro clássico:</strong><p>Transformar a crise de 1929 em causa automática e suficiente do nazifascismo.</p></div><div class=\"box-teoria dica\"><strong>🎯 Dica de banca:</strong><p>Crise abre possibilidades; instituições, movimentos e decisões definem o caminho.</p></div><div class=\"box-teoria checkpoint\"><strong>✅ Checkpoint:</strong><p>Como a depressão enfraqueceu democracias e por que seus efeitos políticos variaram?</p></div><div class=\"box-teoria resumo\"><strong>📝 Resumo:</strong><p>Crise mundial e conflitos do entreguerras favoreceram regimes autoritários, sem tornar sua vitória inevitável.</p></div>"
    }
];
