const estruturasPoliticasEconomicasSociaisEstadoImperialBrasileiroTeoria = [
    {
        "titulo": "🏛️ Página 1 — Estado Imperial e permanências históricas",
        "conteudo": "<div class=\"caixa-destaque\"><h3>🏛️ Estado Imperial Brasileiro: formação, poder e sociedade</h3><p>O Estado Imperial Brasileiro formou-se após a Independência de 1822, mas não representou uma ruptura completa com as estruturas coloniais. A separação política em relação a Portugal preservou muitos elementos do passado: monarquia, escravidão, concentração fundiária, poder das elites agrárias e cidadania restrita.</p><p>A construção do Império envolveu o desafio de manter a unidade territorial, organizar instituições políticas, controlar revoltas regionais e definir os limites da participação social. Ao contrário das repúblicas hispano-americanas fragmentadas, o Brasil manteve a monarquia como forma de governo, com forte centralização do poder.</p><p>Para concursos, a leitura correta evita duas simplificações: dizer que a Independência democratizou a sociedade brasileira ou afirmar que nada mudou. Houve ruptura política com Portugal, mas permanências sociais e econômicas profundas continuaram marcando o novo Estado.</p></div><br><div class=\"caixa-exemplo\"><h3>📌 Exemplo aplicado</h3><p>Uma questão pode pedir a relação entre Independência e formação do Estado Imperial. A resposta forte reconhece ruptura política com Portugal e continuidade de escravidão, latifúndio e elite agrária.</p></div><br><div class=\"erro-classico\"><h3>⚠️ Erro clássico de concurso</h3><p>Achar que a Independência criou imediatamente uma democracia ampla. O Império manteve cidadania censitária e exclusões sociais.</p></div><br><div class=\"dica-concurso\"><h3>🎯 Dica de concurso</h3><p>Compare sempre ruptura política e permanências sociais. Essa é uma das chaves do tema.</p></div><br><div class=\"checkpoint\"><h3>✅ Checkpoint de aprendizagem</h3><ul><li>Independência não significou democratização plena.</li><li>O Império preservou escravidão e latifúndio.</li><li>A unidade territorial foi construída politicamente.</li><li>A elite agrária manteve grande influência.</li></ul></div><br><div class=\"resumo-premium\"><h3>📌 Resumo da página</h3><p>O Estado Imperial combinou ruptura política com Portugal e permanências estruturais da sociedade colonial.</p></div>"
    },
    {
        "titulo": "📜 Página 2 — Constituição de 1824",
        "conteudo": "<div class=\"caixa-destaque\"><h3>📜 Constituição de 1824 e organização do poder</h3><p>A Constituição de 1824 foi outorgada por D. Pedro I após a dissolução da Assembleia Constituinte de 1823. Ela definiu o Brasil como monarquia constitucional, hereditária e representativa, mas concentrou grande poder no imperador, especialmente por meio do Poder Moderador.</p><p>O texto constitucional estabeleceu quatro poderes: Executivo, Legislativo, Judiciário e Moderador. O Poder Moderador permitia ao imperador intervir no funcionamento das instituições, nomear senadores, dissolver a Câmara e escolher ministros. Por isso, a monarquia brasileira tinha aparência constitucional, mas forte centralização imperial.</p><p>A participação política era restrita. O voto era censitário e indireto em muitos níveis, excluindo grande parte da população. Escravizados, mulheres, pobres sem renda suficiente e muitos grupos sociais não participavam efetivamente da vida política institucional.</p></div><br><div class=\"caixa-exemplo\"><h3>📌 Exemplo aplicado</h3><p>Se a prova mencionar Constituição de 1824 e Poder Moderador, a resposta correta deve apontar centralização e ampliação da autoridade imperial.</p></div><br><div class=\"erro-classico\"><h3>⚠️ Erro clássico de concurso</h3><p>Dizer que a Constituição de 1824 implantou sufrágio universal. A participação política era limitada por renda e por exclusões sociais.</p></div><br><div class=\"dica-concurso\"><h3>🎯 Dica de concurso</h3><p>Constituição de 1824 = outorgada, quatro poderes, Poder Moderador e voto censitário.</p></div><br><div class=\"checkpoint\"><h3>✅ Checkpoint de aprendizagem</h3><ul><li>Foi outorgada por D. Pedro I.</li><li>Criou o Poder Moderador.</li><li>Manteve voto censitário.</li><li>Reforçou a centralização política.</li></ul></div><br><div class=\"resumo-premium\"><h3>📌 Resumo da página</h3><p>A Constituição de 1824 estruturou a monarquia imperial com forte autoridade do imperador e participação política restrita.</p></div>"
    },
    {
        "titulo": "👑 Página 3 — Primeiro Reinado",
        "conteudo": "<div class=\"caixa-destaque\"><h3>👑 Primeiro Reinado: centralização e crise política</h3><p>O Primeiro Reinado foi marcado por tensões entre o projeto centralizador de D. Pedro I e setores políticos que defendiam maior autonomia provincial ou maior controle do Legislativo sobre o Executivo. A dissolução da Constituinte e a outorga da Constituição de 1824 alimentaram críticas ao autoritarismo imperial.</p><p>A Confederação do Equador, em 1824, expressou reação ao centralismo monárquico, especialmente em Pernambuco e outras áreas do Nordeste. O movimento defendia projeto republicano e federalista, sendo reprimido pelo governo imperial.</p><p>A crise do Primeiro Reinado também envolveu dificuldades econômicas, desgaste político, impopularidade do imperador, disputas com elites locais e conflitos relacionados à sucessão portuguesa. Esse processo culminou na abdicação de D. Pedro I em 1831.</p></div><br><div class=\"caixa-exemplo\"><h3>📌 Exemplo aplicado</h3><p>Uma alternativa correta sobre o Primeiro Reinado relaciona centralização política, Constituição outorgada, Confederação do Equador e abdicação.</p></div><br><div class=\"erro-classico\"><h3>⚠️ Erro clássico de concurso</h3><p>Achar que o Primeiro Reinado foi período de estabilidade plena. Ele foi marcado por conflitos e desgaste político.</p></div><br><div class=\"dica-concurso\"><h3>🎯 Dica de concurso</h3><p>Associe Primeiro Reinado a D. Pedro I, centralização, Confederação do Equador e abdicação em 1831.</p></div><br><div class=\"checkpoint\"><h3>✅ Checkpoint de aprendizagem</h3><ul><li>D. Pedro I enfrentou oposição política.</li><li>A Constituição de 1824 gerou críticas.</li><li>A Confederação do Equador contestou o centralismo.</li><li>A abdicação ocorreu em 1831.</li></ul></div><br><div class=\"resumo-premium\"><h3>📌 Resumo da página</h3><p>O Primeiro Reinado foi um período de construção institucional e crise da autoridade de D. Pedro I.</p></div>"
    },
    {
        "titulo": "🧭 Página 4 — Período Regencial",
        "conteudo": "<div class=\"caixa-destaque\"><h3>🧭 Regências: descentralização, instabilidade e disputa de projetos</h3><p>Com a abdicação de D. Pedro I, o Brasil entrou no Período Regencial, pois D. Pedro II ainda era menor de idade. Esse período foi marcado por disputas entre centralização e descentralização, reorganização das instituições e intensa instabilidade política.</p><p>O Ato Adicional de 1834 ampliou a autonomia provincial ao criar Assembleias Legislativas Provinciais e modificar a estrutura regencial. No entanto, a descentralização não eliminou tensões. Rebeliões como Cabanagem, Farroupilha, Sabinada e Balaiada revelaram conflitos sociais, regionais e políticos.</p><p>A reação conservadora buscou restaurar a ordem e fortalecer o poder central. O chamado Regresso Conservador expressou medo das elites diante da instabilidade regencial e das mobilizações populares.</p></div><br><div class=\"caixa-exemplo\"><h3>📌 Exemplo aplicado</h3><p>Se uma questão fala em Ato Adicional de 1834, autonomia provincial e rebeliões, o tema central é o Período Regencial.</p></div><br><div class=\"erro-classico\"><h3>⚠️ Erro clássico de concurso</h3><p>Confundir descentralização regencial com democracia social ampla. A autonomia provincial não eliminou exclusões sociais.</p></div><br><div class=\"dica-concurso\"><h3>🎯 Dica de concurso</h3><p>Regência = menoridade de D. Pedro II, Ato Adicional, revoltas e disputa centralização/descentralização.</p></div><br><div class=\"checkpoint\"><h3>✅ Checkpoint de aprendizagem</h3><ul><li>Ocorreu entre 1831 e 1840.</li><li>O Ato Adicional ampliou autonomia provincial.</li><li>Houve muitas revoltas regionais.</li><li>O Regresso Conservador reforçou a centralização.</li></ul></div><br><div class=\"resumo-premium\"><h3>📌 Resumo da página</h3><p>O Período Regencial foi marcado por disputas institucionais e conflitos sociais intensos.</p></div>"
    },
    {
        "titulo": "⚖️ Página 5 — Centralização e unidade territorial",
        "conteudo": "<div class=\"caixa-destaque\"><h3>⚖️ Centralização política e construção da unidade</h3><p>A manutenção da unidade territorial brasileira não foi resultado automático da Independência. Ela foi construída por meio de instituições centralizadas, repressão a rebeliões, negociação com elites provinciais e fortalecimento do aparato estatal.</p><p>A centralização política foi defendida por setores que temiam a fragmentação territorial e a radicalização social. A experiência regencial reforçou a percepção de que o poder central deveria controlar províncias e conter movimentos considerados ameaçadores à ordem imperial.</p><p>Essa centralização conviveu com poderes locais fortes. Senhores de terra, chefes políticos, Guarda Nacional e redes clientelistas continuaram exercendo influência sobre a vida política provincial e municipal.</p></div><br><div class=\"caixa-exemplo\"><h3>📌 Exemplo aplicado</h3><p>A resposta correta em questões sobre unidade territorial deve reconhecer ação política e institucional, não destino natural do Brasil.</p></div><br><div class=\"erro-classico\"><h3>⚠️ Erro clássico de concurso</h3><p>Dizer que o território brasileiro se manteve unido sem conflitos. A unidade foi construída em meio a revoltas e negociações.</p></div><br><div class=\"dica-concurso\"><h3>🎯 Dica de concurso</h3><p>Quando a banca mencionar unidade nacional, pense em centralização, elites provinciais, repressão e negociação.</p></div><br><div class=\"checkpoint\"><h3>✅ Checkpoint de aprendizagem</h3><ul><li>A unidade territorial foi construída.</li><li>O poder central reprimiu rebeliões.</li><li>Elites locais foram importantes.</li><li>Centralização e poder local coexistiram.</li></ul></div><br><div class=\"resumo-premium\"><h3>📌 Resumo da página</h3><p>A unidade do Império resultou de centralização estatal, repressão e pactos com elites regionais.</p></div>"
    },
    {
        "titulo": "☕ Página 6 — Economia imperial e café",
        "conteudo": "<div class=\"caixa-destaque\"><h3>☕ Café, exportação e poder das elites agrárias</h3><p>No século XIX, o café tornou-se o principal produto de exportação do Império, especialmente no Vale do Paraíba e depois no Oeste Paulista. Essa expansão fortaleceu elites agrárias, ampliou a integração ao mercado externo e estimulou ferrovias, crédito, comércio e crescimento urbano em algumas regiões.</p><p>Apesar de mudanças econômicas, a estrutura agrária permaneceu concentrada. O latifúndio e a escravidão continuaram centrais durante grande parte do Império. O enriquecimento cafeeiro deu base social e econômica ao Segundo Reinado, mas também intensificou contradições ligadas ao trabalho escravizado.</p><p>A economia imperial não era exclusivamente cafeeira. Havia agricultura de abastecimento, pecuária, comércio interno, serviços urbanos e atividades regionais variadas. Mesmo assim, o café teve papel decisivo no equilíbrio político e fiscal do Império.</p></div><br><div class=\"caixa-exemplo\"><h3>📌 Exemplo aplicado</h3><p>Se o enunciado relacionar café, escravidão, Vale do Paraíba, Oeste Paulista e ferrovias, a alternativa correta deve apontar a centralidade econômica do café no Segundo Reinado.</p></div><br><div class=\"erro-classico\"><h3>⚠️ Erro clássico de concurso</h3><p>Afirmar que o café eliminou imediatamente a escravidão. A cafeicultura conviveu por décadas com trabalho escravizado.</p></div><br><div class=\"dica-concurso\"><h3>🎯 Dica de concurso</h3><p>Café imperial = exportação, elite agrária, ferrovias, escravidão e depois imigração.</p></div><br><div class=\"checkpoint\"><h3>✅ Checkpoint de aprendizagem</h3><ul><li>O café liderou as exportações.</li><li>A estrutura fundiária permaneceu concentrada.</li><li>A escravidão sustentou parte importante da produção.</li><li>Ferrovias e crédito acompanharam a expansão cafeeira.</li></ul></div><br><div class=\"resumo-premium\"><h3>📌 Resumo da página</h3><p>A economia imperial foi marcada pela força do café, pela exportação e pela permanência de relações sociais desiguais.</p></div>"
    },
    {
        "titulo": "⛓️ Página 7 — Escravidão e sociedade imperial",
        "conteudo": "<div class=\"caixa-destaque\"><h3>⛓️ Escravidão, hierarquias sociais e cidadania restrita</h3><p>A escravidão foi uma das bases da sociedade imperial. Mesmo após a Independência, milhões de africanos e afrodescendentes continuaram submetidos ao trabalho compulsório. O Império construiu instituições políticas modernas em aparência, mas preservou uma ordem social escravista.</p><p>A população livre também era profundamente desigual. Havia elites proprietárias, comerciantes, burocratas, profissionais liberais, militares, trabalhadores livres pobres, libertos, imigrantes, indígenas e muitos grupos excluídos da cidadania política. A renda, a condição jurídica, a cor, o gênero e o acesso à propriedade interferiam nas possibilidades de participação social.</p><p>O fim do tráfico atlântico em 1850, a Lei do Ventre Livre, a Lei dos Sexagenários e a Lei Áurea fizeram parte de um processo gradual e conflituoso. A abolição resultou de pressões de escravizados, libertos, abolicionistas, setores urbanos e mudanças econômicas e políticas.</p></div><br><div class=\"caixa-exemplo\"><h3>📌 Exemplo aplicado</h3><p>Uma questão difícil pode perguntar por que o Império era liberal e escravista ao mesmo tempo. A resposta correta reconhece cidadania restrita e permanência da escravidão.</p></div><br><div class=\"erro-classico\"><h3>⚠️ Erro clássico de concurso</h3><p>Dizer que a Constituição de 1824 tornou todos os habitantes cidadãos iguais. Escravizados estavam excluídos da cidadania política.</p></div><br><div class=\"dica-concurso\"><h3>🎯 Dica de concurso</h3><p>Sempre relacione escravidão a economia, política, direito e hierarquia social.</p></div><br><div class=\"checkpoint\"><h3>✅ Checkpoint de aprendizagem</h3><ul><li>A escravidão permaneceu após 1822.</li><li>A cidadania era restrita.</li><li>A abolição foi gradual e conflituosa.</li><li>Escravizados também foram sujeitos históricos.</li></ul></div><br><div class=\"resumo-premium\"><h3>📌 Resumo da página</h3><p>A sociedade imperial combinou instituições constitucionais com escravidão, desigualdade e exclusão política.</p></div>"
    },
    {
        "titulo": "🗳️ Página 8 — Partidos e parlamentarismo às avessas",
        "conteudo": "<div class=\"caixa-destaque\"><h3>🗳️ Liberais, conservadores e parlamentarismo imperial</h3><p>No Segundo Reinado, a política imperial ficou marcada pela atuação de liberais e conservadores. Embora existissem diferenças, ambos os grupos eram compostos majoritariamente por setores das elites e compartilhavam a defesa da ordem social, da propriedade e, por longo tempo, da escravidão.</p><p>O parlamentarismo implantado no Império é frequentemente chamado de “parlamentarismo às avessas” porque o imperador, por meio do Poder Moderador, tinha papel decisivo na escolha do presidente do Conselho de Ministros. Em vez de o Parlamento determinar plenamente o governo, a Coroa influenciava a formação dos gabinetes.</p><p>Essa lógica ajudou a equilibrar disputas entre facções políticas, mas também reforçou a centralidade do imperador e os limites da representação política.</p></div><br><div class=\"caixa-exemplo\"><h3>📌 Exemplo aplicado</h3><p>Se a banca perguntar por que o parlamentarismo era “às avessas”, a resposta correta aponta a intervenção do imperador na formação dos ministérios.</p></div><br><div class=\"erro-classico\"><h3>⚠️ Erro clássico de concurso</h3><p>Dizer que liberais e conservadores representavam democracia de massas. Eram grupos vinculados às elites políticas e proprietárias.</p></div><br><div class=\"dica-concurso\"><h3>🎯 Dica de concurso</h3><p>Parlamentarismo às avessas = Poder Moderador influenciando a formação do governo.</p></div><br><div class=\"checkpoint\"><h3>✅ Checkpoint de aprendizagem</h3><ul><li>Liberais e conservadores eram grupos de elite.</li><li>O Poder Moderador influenciava gabinetes.</li><li>A representação política era limitada.</li><li>O sistema ajudava a estabilizar o Segundo Reinado.</li></ul></div><br><div class=\"resumo-premium\"><h3>📌 Resumo da página</h3><p>A política imperial combinou partidos de elite, Poder Moderador e representação restrita.</p></div>"
    },
    {
        "titulo": "🛡️ Página 9 — Guarda Nacional, clientelismo e poder local",
        "conteudo": "<div class=\"caixa-destaque\"><h3>🛡️ Poder local, Guarda Nacional e redes de dependência</h3><p>A Guarda Nacional foi criada em 1831 e tornou-se importante instrumento de controle social e político. Ela reforçou a influência de proprietários e chefes locais, que muitas vezes assumiam posições de comando e articulavam redes de dependência nas províncias.</p><p>O poder imperial não existia apenas no Rio de Janeiro. Ele dependia de pactos com elites locais, controle eleitoral, relações clientelistas, distribuição de cargos e capacidade de mobilização regional. Por isso, o Estado imperial combinava centralização institucional com forte presença dos poderes locais.</p><p>Esse tema é importante porque a banca pode apresentar o Estado imperial como totalmente centralizado e sem mediações locais. A leitura correta reconhece o equilíbrio entre centro político e elites provinciais.</p></div><br><div class=\"caixa-exemplo\"><h3>📌 Exemplo aplicado</h3><p>Uma alternativa adequada reconhece que a Guarda Nacional fortaleceu chefes locais e ajudou a manter a ordem social imperial.</p></div><br><div class=\"erro-classico\"><h3>⚠️ Erro clássico de concurso</h3><p>Imaginar que centralização imperial eliminou o poder dos grandes proprietários locais. Na prática, eles continuaram fundamentais.</p></div><br><div class=\"dica-concurso\"><h3>🎯 Dica de concurso</h3><p>Associe Guarda Nacional a ordem, elites locais, clientelismo e controle social.</p></div><br><div class=\"checkpoint\"><h3>✅ Checkpoint de aprendizagem</h3><ul><li>A Guarda Nacional foi criada em 1831.</li><li>Chefes locais tinham influência política.</li><li>Clientelismo marcou a vida imperial.</li><li>Centralização dependia de pactos regionais.</li></ul></div><br><div class=\"resumo-premium\"><h3>📌 Resumo da página</h3><p>O Estado imperial articulou poder central e elites locais para manter a ordem política e social.</p></div>"
    },
    {
        "titulo": "🌍 Página 10 — Política externa e Guerra do Paraguai",
        "conteudo": "<div class=\"caixa-destaque\"><h3>🌍 Política externa, Prata e fortalecimento militar</h3><p>O Império atuou intensamente na região do Prata, área estratégica para comércio, navegação e equilíbrio político sul-americano. Conflitos com Argentina, Uruguai e Paraguai envolveram interesses regionais, fronteiras, navegação e influência diplomática.</p><p>A Guerra do Paraguai teve grande impacto sobre o Brasil. O conflito mobilizou tropas, recursos, escravizados alforriados, voluntários e setores do Exército. Após a guerra, os militares passaram a ter maior protagonismo político e institucional, o que contribuiu para tensões futuras com a monarquia.</p><p>É importante não tratar a guerra como causa única da queda do Império. Ela foi um fator entre outros, ao lado da crise da escravidão, do republicanismo, das questões religiosa e militar e do desgaste da monarquia.</p></div><br><div class=\"caixa-exemplo\"><h3>📌 Exemplo aplicado</h3><p>Se a questão relacionar Guerra do Paraguai e crise imperial, a resposta correta deve apontar fortalecimento do Exército e novas tensões políticas.</p></div><br><div class=\"erro-classico\"><h3>⚠️ Erro clássico de concurso</h3><p>Afirmar que a Guerra do Paraguai, sozinha, derrubou a monarquia. A crise imperial teve causas múltiplas.</p></div><br><div class=\"dica-concurso\"><h3>🎯 Dica de concurso</h3><p>Guerra do Paraguai = impacto militar, fiscal, político e social, mas não explicação única.</p></div><br><div class=\"checkpoint\"><h3>✅ Checkpoint de aprendizagem</h3><ul><li>O Império atuou na região do Prata.</li><li>A Guerra do Paraguai fortaleceu o Exército.</li><li>Militares ganharam protagonismo.</li><li>A queda do Império teve causas múltiplas.</li></ul></div><br><div class=\"resumo-premium\"><h3>📌 Resumo da página</h3><p>A política externa imperial e a Guerra do Paraguai influenciaram o fortalecimento militar e a crise da monarquia.</p></div>"
    },
    {
        "titulo": "⚠️ Página 11 — Crise do Império",
        "conteudo": "<div class=\"caixa-destaque\"><h3>⚠️ Abolicionismo, republicanismo e desgaste da monarquia</h3><p>A crise do Império intensificou-se na segunda metade do século XIX. O sistema escravista entrou em desgaste diante do fim do tráfico, das pressões abolicionistas, das fugas, das ações judiciais, das mobilizações urbanas e das mudanças econômicas.</p><p>O republicanismo cresceu entre setores civis e militares, especialmente a partir de 1870. Ao mesmo tempo, conflitos com a Igreja e com o Exército fragilizaram a autoridade monárquica. Parte das elites agrárias também se afastou do regime, sobretudo após a abolição sem indenização aos proprietários.</p><p>A Proclamação da República, em 1889, não resultou de participação popular ampla. Foi conduzida por setores militares e elites civis, em um contexto de isolamento político da monarquia.</p></div><br><div class=\"caixa-exemplo\"><h3>📌 Exemplo aplicado</h3><p>Uma resposta correta sobre a crise imperial articula abolicionismo, republicanismo, questões militar e religiosa e desgaste das elites monárquicas.</p></div><br><div class=\"erro-classico\"><h3>⚠️ Erro clássico de concurso</h3><p>Dizer que a República nasceu de revolução popular ampla. A participação popular foi limitada no processo de 1889.</p></div><br><div class=\"dica-concurso\"><h3>🎯 Dica de concurso</h3><p>Crise do Império = múltiplos fatores, não causa única.</p></div><br><div class=\"checkpoint\"><h3>✅ Checkpoint de aprendizagem</h3><ul><li>A escravidão entrou em crise.</li><li>O republicanismo cresceu.</li><li>Militares ganharam força política.</li><li>A monarquia ficou isolada em 1889.</li></ul></div><br><div class=\"resumo-premium\"><h3>📌 Resumo da página</h3><p>A crise imperial resultou da combinação entre abolicionismo, republicanismo, tensões institucionais e desgaste das bases sociais da monarquia.</p></div>"
    },
    {
        "titulo": "🎯 Página 12 — Síntese para concursos",
        "conteudo": "<div class=\"caixa-destaque\"><h3>🎯 Como a banca cobra o Estado Imperial</h3><p>Questões sobre o Estado Imperial Brasileiro costumam cobrar a articulação entre política, economia e sociedade. A banca pode perguntar sobre Constituição de 1824, Poder Moderador, centralização, voto censitário, Regência, café, escravidão, partidos, Guarda Nacional e crise final do regime.</p><p>O erro mais comum é escolher alternativas que separam completamente esses planos. A política imperial não pode ser entendida sem a base econômica agrária e escravista; a economia não pode ser entendida sem o poder das elites; e a sociedade não pode ser entendida sem hierarquias jurídicas, raciais, regionais e de gênero.</p><p>A alternativa correta geralmente reconhece permanências e mudanças. O Império criou instituições próprias e manteve a unidade territorial, mas preservou exclusões profundas e entrou em crise quando suas bases sociais e políticas se desgastaram.</p></div><br><div class=\"caixa-exemplo\"><h3>📌 Exemplo aplicado</h3><p>Em prova, desconfie de alternativas que afirmam que o Império foi plenamente democrático, socialmente igualitário ou sem conflitos regionais.</p></div><br><div class=\"erro-classico\"><h3>⚠️ Erro clássico de concurso</h3><p>Escolher alternativa bonita, mas isolada, que fala de Constituição sem mencionar centralização, escravidão ou cidadania restrita.</p></div><br><div class=\"dica-concurso\"><h3>🎯 Dica de concurso</h3><p>Procure respostas que conectem Estado, economia, sociedade e crise política.</p></div><br><div class=\"checkpoint\"><h3>✅ Checkpoint de aprendizagem</h3><ul><li>O tema exige visão integrada.</li><li>Poder Moderador e voto censitário são centrais.</li><li>Café e escravidão sustentaram elites.</li><li>A crise do Império teve múltiplas causas.</li></ul></div><br><div class=\"resumo-premium\"><h3>📌 Resumo da página</h3><p>O Estado Imperial deve ser entendido pela relação entre monarquia centralizada, economia agroexportadora, escravidão, elites locais e cidadania restrita.</p></div>"
    }
];
