const movimentosAnticoloniaisBrasilTeoria = [
    {
        "titulo": "🔥 Página 1 — Crise colonial e conflitos na América portuguesa",
        "conteudo": "<div class=\"caixa-destaque\"><h3>🔥 Anticolonialismo, nativismo e crise do sistema colonial</h3><p>Os movimentos anticoloniais no Brasil não surgiram de forma isolada. Eles resultaram de tensões acumuladas dentro do sistema colonial português: fiscalismo metropolitano, concentração de privilégios, disputas entre grupos locais, restrições comerciais, desigualdades sociais e circulação de novas ideias políticas no mundo atlântico.</p><p>É importante compreender que nem todo conflito colonial foi necessariamente separatista. Muitos movimentos criticavam abusos administrativos ou disputavam poder local, mas ainda não propunham a ruptura com Portugal. Outros, especialmente no fim do século XVIII e início do XIX, passaram a formular projetos mais amplos de autonomia política.</p><p>Para concursos, o aluno deve comparar causas, composição social, objetivos e limites de cada movimento. A banca costuma confundir revoltas nativistas, rebeliões fiscais, disputas entre elites locais e movimentos inspirados por ideias iluministas ou republicanas.</p></div><br><div class=\"caixa-exemplo\"><h3>📌 Exemplo aplicado</h3><p>Se o enunciado falar em impostos, monopólios, poder local e controle metropolitano, o núcleo da questão é a tensão entre interesses coloniais e autoridade portuguesa.</p></div><br><div class=\"erro-classico\"><h3>⚠️ Erro clássico de concurso</h3><p>Achar que todos os movimentos anticoloniais queriam independência nacional nos mesmos termos de 1822.</p></div><br><div class=\"dica-concurso\"><h3>🎯 Dica de concurso</h3><p>Compare sempre: causa, grupo social participante, objetivo político e reação da Coroa.</p></div><br><div class=\"checkpoint\"><h3>✅ Checkpoint de aprendizagem</h3><ul><li>Conflitos coloniais tiveram causas variadas.</li><li>Nem toda revolta foi separatista.</li><li>Fiscalismo e monopólios geraram tensões.</li><li>Ideias liberais ganharam força no fim do século XVIII.</li></ul></div><br><div class=\"resumo-premium\"><h3>📌 Resumo da página</h3><p>Movimentos anticoloniais expressaram tensões contra o controle metropolitano, mas tiveram objetivos e bases sociais diferentes.</p></div>"
    },
    {
        "titulo": "⚖️ Página 2 — Nativismo, separatismo e linguagem de banca",
        "conteudo": "<div class=\"caixa-destaque\"><h3>⚖️ Diferença entre revoltas nativistas e separatistas</h3><p>O termo nativismo costuma ser usado para designar movimentos coloniais que expressavam interesses locais contra medidas da administração portuguesa, mas sem defesa clara de independência. Já o separatismo envolve projeto de ruptura política com a metrópole ou criação de governo autônomo.</p><p>Essa distinção ajuda a compreender por que movimentos como Beckman, Emboabas, Mascates e Vila Rica são geralmente interpretados como nativistas ou contestatórios, enquanto Inconfidência Mineira, Conjuração Baiana e Revolução Pernambucana de 1817 aparecem em outro nível de contestação política.</p><p>A banca pode usar a palavra anticolonial em sentido amplo, incluindo desde conflitos contra abusos coloniais até projetos de separação. Por isso, o candidato deve ler o enunciado e não aplicar rótulos de forma mecânica.</p></div><br><div class=\"caixa-exemplo\"><h3>📌 Exemplo aplicado</h3><p>Uma alternativa correta pode dizer que a Revolta de Beckman contestou monopólios e política local, mas não apresentou projeto nacional de independência.</p></div><br><div class=\"erro-classico\"><h3>⚠️ Erro clássico de concurso</h3><p>Pensar que nativismo significa nacionalismo brasileiro moderno. O Brasil como Estado nacional ainda não existia.</p></div><br><div class=\"dica-concurso\"><h3>🎯 Dica de concurso</h3><p>Quando aparecer “autonomia local”, “monopólio” ou “fiscalismo”, verifique se havia ou não projeto separatista.</p></div><br><div class=\"checkpoint\"><h3>✅ Checkpoint de aprendizagem</h3><ul><li>Nativismo não é igual a independência nacional.</li><li>Separatismo envolve ruptura política.</li><li>Os rótulos dependem do contexto.</li><li>A banca explora comparações entre movimentos.</li></ul></div><br><div class=\"resumo-premium\"><h3>📌 Resumo da página</h3><p>Distinguir nativismo e separatismo é essencial para resolver questões sobre revoltas coloniais.</p></div>"
    },
    {
        "titulo": "🛶 Página 3 — Revolta de Beckman",
        "conteudo": "<div class=\"caixa-destaque\"><h3>🛶 Maranhão, monopólio e trabalho indígena</h3><p>A Revolta de Beckman, ocorrida no Maranhão em 1684, relacionou-se às tensões entre colonos, jesuítas e a Companhia de Comércio do Maranhão. Os colonos criticavam o monopólio comercial, os preços, o abastecimento e a dificuldade de acesso à mão de obra.</p><p>O conflito também envolveu a disputa sobre o trabalho indígena. Os jesuítas defendiam aldeamentos e controle missionário, enquanto colonos buscavam formas de exploração direta dessa mão de obra. A revolta, portanto, não foi movimento popular igualitário, mas reação de setores locais contra entraves econômicos e administrativos.</p><p>A repressão portuguesa mostrou os limites da contestação local. A Coroa podia ajustar mecanismos coloniais, mas não aceitava desafios diretos à autoridade régia.</p></div><br><div class=\"caixa-exemplo\"><h3>📌 Exemplo aplicado</h3><p>Se a prova mencionar Maranhão, Companhia de Comércio, jesuítas e mão de obra indígena, o tema mais provável é a Revolta de Beckman.</p></div><br><div class=\"erro-classico\"><h3>⚠️ Erro clássico de concurso</h3><p>Dizer que Beckman foi uma revolução abolicionista ou democrática. O movimento partiu de interesses de colonos locais.</p></div><br><div class=\"dica-concurso\"><h3>🎯 Dica de concurso</h3><p>Associe Beckman a monopólio comercial, abastecimento, jesuítas e trabalho indígena.</p></div><br><div class=\"checkpoint\"><h3>✅ Checkpoint de aprendizagem</h3><ul><li>Ocorreu no Maranhão em 1684.</li><li>Contestou a Companhia de Comércio.</li><li>Envolveu disputa sobre mão de obra indígena.</li><li>Foi reprimida pela Coroa portuguesa.</li></ul></div><br><div class=\"resumo-premium\"><h3>📌 Resumo da página</h3><p>A Revolta de Beckman expressou tensões locais contra monopólio, jesuítas e administração colonial.</p></div>"
    },
    {
        "titulo": "⚔️ Página 4 — Guerra dos Emboabas",
        "conteudo": "<div class=\"caixa-destaque\"><h3>⚔️ Disputa pelas minas e poder régio</h3><p>A Guerra dos Emboabas, no início do século XVIII, ocorreu em Minas Gerais e envolveu conflitos entre paulistas, que reivindicavam prioridade na descoberta das minas, e grupos chamados emboabas, compostos por portugueses e outros colonos atraídos pelo ouro.</p><p>Mais do que simples rivalidade regional, o conflito revelou a importância econômica das minas e a necessidade de maior intervenção da Coroa. A administração portuguesa procurou controlar a região mineradora, organizar a tributação e reduzir a autonomia dos grupos locais.</p><p>O episódio ajuda a entender como a mineração transformou a organização colonial, deslocando o eixo econômico e ampliando a presença estatal no interior.</p></div><br><div class=\"caixa-exemplo\"><h3>📌 Exemplo aplicado</h3><p>Uma questão que relacione paulistas, emboabas e controle das minas exige reconhecer disputa por riqueza e autoridade na região mineradora.</p></div><br><div class=\"erro-classico\"><h3>⚠️ Erro clássico de concurso</h3><p>Reduzir a Guerra dos Emboabas a conflito entre “brasileiros” e “estrangeiros” no sentido nacional moderno.</p></div><br><div class=\"dica-concurso\"><h3>🎯 Dica de concurso</h3><p>Cuidado com anacronismo: no início do século XVIII não havia nacionalismo brasileiro consolidado.</p></div><br><div class=\"checkpoint\"><h3>✅ Checkpoint de aprendizagem</h3><ul><li>Ocorreu na região mineradora.</li><li>Envolveu paulistas e emboabas.</li><li>A Coroa ampliou controle sobre as minas.</li><li>O ouro aumentou o fiscalismo colonial.</li></ul></div><br><div class=\"resumo-premium\"><h3>📌 Resumo da página</h3><p>A Guerra dos Emboabas expressou disputas pelas minas e fortaleceu a intervenção portuguesa na região.</p></div>"
    },
    {
        "titulo": "🏙️ Página 5 — Guerra dos Mascates",
        "conteudo": "<div class=\"caixa-destaque\"><h3>🏙️ Olinda, Recife e disputas locais</h3><p>A Guerra dos Mascates, em Pernambuco, opôs interesses da elite senhorial de Olinda e comerciantes do Recife. A elevação do Recife à condição de vila afetou o equilíbrio político local e intensificou tensões econômicas e sociais entre proprietários rurais e comerciantes.</p><p>O conflito não deve ser entendido como movimento popular contra Portugal. Ele expressou disputas entre grupos coloniais de poder, em um contexto de mudanças econômicas provocadas pela crise relativa da aristocracia açucareira e pela força crescente dos comerciantes.</p><p>A banca costuma explorar esse movimento para cobrar a diferença entre conflito local de elites e projeto separatista. A leitura correta identifica interesses econômicos, rivalidade urbana e rearranjos de poder.</p></div><br><div class=\"caixa-exemplo\"><h3>📌 Exemplo aplicado</h3><p>Se o item citar Olinda, Recife, comerciantes e senhores de engenho, a resposta deve apontar disputa local de poder em Pernambuco.</p></div><br><div class=\"erro-classico\"><h3>⚠️ Erro clássico de concurso</h3><p>Tratar a Guerra dos Mascates como independência pernambucana. O movimento não tinha esse caráter.</p></div><br><div class=\"dica-concurso\"><h3>🎯 Dica de concurso</h3><p>Associe Mascates a rivalidade entre Olinda senhorial e Recife comercial.</p></div><br><div class=\"checkpoint\"><h3>✅ Checkpoint de aprendizagem</h3><ul><li>Ocorreu em Pernambuco.</li><li>Envolveu Olinda e Recife.</li><li>Expressou disputa entre elites locais.</li><li>Não foi movimento democrático ou nacional.</li></ul></div><br><div class=\"resumo-premium\"><h3>📌 Resumo da página</h3><p>A Guerra dos Mascates revelou tensões entre proprietários rurais e comerciantes no espaço colonial pernambucano.</p></div>"
    },
    {
        "titulo": "⛏️ Página 6 — Revolta de Vila Rica",
        "conteudo": "<div class=\"caixa-destaque\"><h3>⛏️ Fiscalismo minerador e Felipe dos Santos</h3><p>A Revolta de Vila Rica, em 1720, esteve ligada ao descontentamento contra a política fiscal da Coroa na região mineradora, especialmente a criação das Casas de Fundição. A medida buscava controlar melhor a circulação do ouro e garantir a cobrança do quinto.</p><p>Liderada por Felipe dos Santos, a revolta expressou resistência de setores locais às formas de fiscalização metropolitana. No entanto, não apresentou projeto estruturado de independência. A repressão foi severa e reforçou a autoridade portuguesa sobre Minas Gerais.</p><p>O episódio é importante porque antecipa tensões que voltariam a aparecer na Inconfidência Mineira, embora com diferenças ideológicas e políticas significativas.</p></div><br><div class=\"caixa-exemplo\"><h3>📌 Exemplo aplicado</h3><p>Quando o enunciado falar em Casas de Fundição, quinto e Felipe dos Santos, trata-se de fiscalismo minerador em Vila Rica.</p></div><br><div class=\"erro-classico\"><h3>⚠️ Erro clássico de concurso</h3><p>Confundir a Revolta de Vila Rica com a Inconfidência Mineira. Ambas envolvem Minas, mas têm contextos e projetos diferentes.</p></div><br><div class=\"dica-concurso\"><h3>🎯 Dica de concurso</h3><p>Casas de Fundição = controle do ouro e cobrança fiscal.</p></div><br><div class=\"checkpoint\"><h3>✅ Checkpoint de aprendizagem</h3><ul><li>Ocorreu em 1720.</li><li>Relaciona-se ao quinto e às Casas de Fundição.</li><li>Foi reprimida pela Coroa.</li><li>Não foi movimento separatista maduro.</li></ul></div><br><div class=\"resumo-premium\"><h3>📌 Resumo da página</h3><p>Vila Rica expressou resistência ao fiscalismo minerador e reforço do controle metropolitano.</p></div>"
    },
    {
        "titulo": "💎 Página 7 — Inconfidência Mineira",
        "conteudo": "<div class=\"caixa-destaque\"><h3>💎 Elite letrada, derrama e republicanismo limitado</h3><p>A Inconfidência Mineira, de 1789, ocorreu em contexto de crise da mineração, endividamento de elites locais e ameaça de cobrança da derrama. Suas lideranças incluíam membros da elite letrada, proprietários, militares e homens ligados à administração colonial.</p><p>O movimento foi influenciado pelo Iluminismo e pela independência dos Estados Unidos, defendendo ruptura com Portugal e ideias republicanas. Porém, seus limites sociais são importantes: não houve projeto amplo de igualdade social e a escravidão não foi abolida como proposta consensual entre os envolvidos.</p><p>A repressão portuguesa transformou Tiradentes em figura simbólica posteriormente, mas o estudo histórico exige ir além do heroísmo: é preciso compreender interesses sociais, contradições e contexto fiscal.</p></div><br><div class=\"caixa-exemplo\"><h3>📌 Exemplo aplicado</h3><p>Uma questão difícil pode comparar a Inconfidência com a Conjuração Baiana; a primeira teve perfil mais elitizado e limites sociais mais evidentes.</p></div><br><div class=\"erro-classico\"><h3>⚠️ Erro clássico de concurso</h3><p>Afirmar que a Inconfidência defendia democracia social plena e abolição consensual da escravidão.</p></div><br><div class=\"dica-concurso\"><h3>🎯 Dica de concurso</h3><p>Leia a composição social do movimento antes de escolher a alternativa.</p></div><br><div class=\"checkpoint\"><h3>✅ Checkpoint de aprendizagem</h3><ul><li>Contexto de crise da mineração.</li><li>Influência iluminista e republicana.</li><li>Perfil predominantemente elitizado.</li><li>Limites quanto à escravidão e igualdade social.</li></ul></div><br><div class=\"resumo-premium\"><h3>📌 Resumo da página</h3><p>A Inconfidência Mineira foi separatista e republicana, mas socialmente limitada.</p></div>"
    },
    {
        "titulo": "✊ Página 8 — Conjuração Baiana",
        "conteudo": "<div class=\"caixa-destaque\"><h3>✊ Radicalização social e linguagem igualitária</h3><p>A Conjuração Baiana, de 1798, teve maior participação de setores populares urbanos, como alfaiates, soldados, homens livres pobres, negros livres e mestiços. Suas ideias circularam por panfletos e defendiam república, liberdade, igualdade e críticas à ordem colonial.</p><p>Comparada à Inconfidência Mineira, a Conjuração Baiana apresentou maior radicalidade social. A influência da Revolução Francesa foi importante, especialmente na linguagem de direitos e igualdade. A repressão também foi dura e atingiu principalmente participantes populares.</p><p>A banca costuma cobrar esse contraste: Minas aparece como movimento de elite, enquanto Bahia aparece com maior presença popular e propostas sociais mais amplas, embora também inserida nas contradições do período.</p></div><br><div class=\"caixa-exemplo\"><h3>📌 Exemplo aplicado</h3><p>Se a questão mencionar alfaiates, panfletos, soldados e igualdade, pense na Conjuração Baiana.</p></div><br><div class=\"erro-classico\"><h3>⚠️ Erro clássico de concurso</h3><p>Confundir a Conjuração Baiana com movimento exclusivamente de elite mineradora.</p></div><br><div class=\"dica-concurso\"><h3>🎯 Dica de concurso</h3><p>Conjuração Baiana = maior participação popular e linguagem igualitária.</p></div><br><div class=\"checkpoint\"><h3>✅ Checkpoint de aprendizagem</h3><ul><li>Ocorreu em 1798.</li><li>Teve forte presença popular urbana.</li><li>Defendeu república e igualdade.</li><li>Sofreu repressão seletiva e exemplar.</li></ul></div><br><div class=\"resumo-premium\"><h3>📌 Resumo da página</h3><p>A Conjuração Baiana foi um movimento anticolonial de maior radicalidade social e participação popular.</p></div>"
    },
    {
        "titulo": "🌵 Página 9 — Revolução Pernambucana de 1817",
        "conteudo": "<div class=\"caixa-destaque\"><h3>🌵 República, crise econômica e contestação à Corte</h3><p>A Revolução Pernambucana de 1817 ocorreu já no contexto da presença da Corte portuguesa no Brasil. Ela expressou insatisfação com impostos, crise econômica regional, privilégios concedidos ao Rio de Janeiro e influência de ideias liberais e republicanas.</p><p>O movimento proclamou um governo republicano em Pernambuco e teve articulações com outras capitanias do Nordeste. Apesar de sua curta duração, representou um dos projetos políticos mais claros de ruptura com a monarquia portuguesa antes da Independência.</p><p>Seu estudo mostra que a vinda da Corte não eliminou conflitos coloniais; ao contrário, deslocou tensões e reforçou ressentimentos regionais contra a centralização no Rio de Janeiro.</p></div><br><div class=\"caixa-exemplo\"><h3>📌 Exemplo aplicado</h3><p>Se a questão citar 1817, Pernambuco, república e críticas aos privilégios da Corte, a resposta deve reconhecer projeto político separatista e republicano.</p></div><br><div class=\"erro-classico\"><h3>⚠️ Erro clássico de concurso</h3><p>Tratar 1817 como revolta contra a República brasileira, que ainda não existia.</p></div><br><div class=\"dica-concurso\"><h3>🎯 Dica de concurso</h3><p>Contextualize 1817 no período joanino, não no Segundo Reinado.</p></div><br><div class=\"checkpoint\"><h3>✅ Checkpoint de aprendizagem</h3><ul><li>Ocorreu durante o período joanino.</li><li>Teve caráter republicano e separatista.</li><li>Criticou impostos e centralização no Rio.</li><li>Foi reprimida pelas forças monárquicas.</li></ul></div><br><div class=\"resumo-premium\"><h3>📌 Resumo da página</h3><p>A Revolução Pernambucana de 1817 foi importante movimento republicano e anticolonial no período joanino.</p></div>"
    },
    {
        "titulo": "🔍 Página 10 — Comparações entre movimentos",
        "conteudo": "<div class=\"caixa-destaque\"><h3>🔍 Como comparar sem confundir</h3><p>A comparação entre movimentos anticoloniais é uma das formas mais comuns de cobrança. A banca pode aproximar Beckman, Vila Rica, Inconfidência, Conjuração Baiana e Revolução Pernambucana para verificar se o candidato identifica diferenças de contexto, composição social e projeto político.</p><p>Em geral, movimentos do século XVII e início do XVIII tendem a expressar conflitos locais, fiscais ou administrativos, sem projeto nacional. No fim do século XVIII, com a crise do Antigo Regime e a circulação de ideias liberais, surgem propostas mais diretamente separatistas e republicanas.</p><p>Ainda assim, é preciso cuidado: nem todo movimento influenciado pelo liberalismo foi socialmente radical, e nem toda revolta popular defendia os mesmos objetivos. A História exige análise concreta de cada caso.</p></div><br><div class=\"caixa-exemplo\"><h3>📌 Exemplo aplicado</h3><p>Uma boa resposta compara movimentos pela composição social e pelo objetivo, não apenas pela data.</p></div><br><div class=\"erro-classico\"><h3>⚠️ Erro clássico de concurso</h3><p>Escolher alternativas que colocam todos os movimentos como iguais. Cada revolta teve contexto próprio.</p></div><br><div class=\"dica-concurso\"><h3>🎯 Dica de concurso</h3><p>Monte mentalmente uma tabela: local, data, causa, participantes, objetivo e repressão.</p></div><br><div class=\"checkpoint\"><h3>✅ Checkpoint de aprendizagem</h3><ul><li>Beckman: Maranhão e monopólio.</li><li>Vila Rica: fiscalismo minerador.</li><li>Inconfidência: elite e derrama.</li><li>Baiana: participação popular e igualdade.</li></ul></div><br><div class=\"resumo-premium\"><h3>📌 Resumo da página</h3><p>Comparar os movimentos exige observar contexto, composição social, projeto político e limites históricos.</p></div>"
    },
    {
        "titulo": "🚨 Página 11 — Repressão, memória e limites sociais",
        "conteudo": "<div class=\"caixa-destaque\"><h3>🚨 Repressão colonial e construção da memória</h3><p>A Coroa portuguesa reagiu aos movimentos com repressão, punições exemplares, prisões, degredos e execuções em casos específicos. A repressão tinha função política: desencorajar novas contestações e reafirmar a autoridade metropolitana.</p><p>Também é importante estudar a memória desses movimentos. Personagens como Tiradentes foram reinterpretados posteriormente, especialmente na construção de símbolos nacionais. A memória histórica, portanto, não é neutra: ela seleciona heróis, silencia grupos e reorganiza sentidos do passado.</p><p>Os limites sociais dos movimentos devem ser considerados. Alguns expressavam interesses de elites locais; outros contaram com participação popular. Essa diferença é decisiva para evitar leituras idealizadas ou simplistas.</p></div><br><div class=\"caixa-exemplo\"><h3>📌 Exemplo aplicado</h3><p>A banca pode perguntar por que Tiradentes se tornou símbolo nacional depois; a resposta envolve memória política e construção de identidade.</p></div><br><div class=\"erro-classico\"><h3>⚠️ Erro clássico de concurso</h3><p>Confundir memória cívica com análise histórica. Heróis nacionais são construídos historicamente.</p></div><br><div class=\"dica-concurso\"><h3>🎯 Dica de concurso</h3><p>Quando o enunciado falar em memória, símbolo ou herói, pense em usos políticos do passado.</p></div><br><div class=\"checkpoint\"><h3>✅ Checkpoint de aprendizagem</h3><ul><li>A repressão foi instrumento de controle.</li><li>A memória dos movimentos foi construída depois.</li><li>Nem todos os movimentos tinham base popular.</li><li>A análise histórica evita heroização simplista.</li></ul></div><br><div class=\"resumo-premium\"><h3>📌 Resumo da página</h3><p>Repressão e memória são dimensões importantes para entender movimentos anticoloniais.</p></div>"
    },
    {
        "titulo": "🎯 Página 12 — Síntese para concursos",
        "conteudo": "<div class=\"caixa-destaque\"><h3>🎯 Como acertar questões difíceis</h3><p>Para resolver questões sobre movimentos anticoloniais no Brasil, identifique primeiro o período. Movimentos do século XVII e início do XVIII geralmente cobram monopólios, administração local ou fiscalismo. Movimentos do fim do século XVIII e início do XIX tendem a envolver Iluminismo, republicanismo, crise do Antigo Regime e críticas mais diretas à dominação colonial.</p><p>Depois, observe os participantes. Elite mineradora, comerciantes, senhores locais, soldados, alfaiates, homens livres pobres e grupos populares não aparecem nas questões por acaso. A composição social ajuda a entender o alcance e os limites de cada movimento.</p><p>Por fim, desconfie de alternativas absolutas. Expressões como “todos”, “sempre”, “nunca”, “plenamente democrático” ou “sem conflitos” normalmente escondem simplificações. A resposta correta costuma reconhecer contradições.</p></div><br><div class=\"caixa-exemplo\"><h3>📌 Exemplo aplicado</h3><p>Uma alternativa forte sobre o tema reconhece que anticolonialismo não teve uma única forma: variou conforme região, época e grupo social.</p></div><br><div class=\"erro-classico\"><h3>⚠️ Erro clássico de concurso</h3><p>Decorar datas sem entender contexto. Questões difíceis cobram interpretação.</p></div><br><div class=\"dica-concurso\"><h3>🎯 Dica de concurso</h3><p>Procure a tese da alternativa e veja se ela respeita o contexto histórico.</p></div><br><div class=\"checkpoint\"><h3>✅ Checkpoint de aprendizagem</h3><ul><li>Compare causas e participantes.</li><li>Diferencie nativismo e separatismo.</li><li>Evite anacronismos nacionalistas.</li><li>Observe limites sociais e políticos.</li></ul></div><br><div class=\"resumo-premium\"><h3>📌 Resumo da página</h3><p>Movimentos anticoloniais devem ser entendidos por contexto, interesses, participação social, ideias políticas e repressão.</p></div>"
    }
];
