const revoltasMovimentosBrasilImperialTeoria = [
    {
        "titulo": "⚔️ Página 1 — Revoltas imperiais: visão geral",
        "conteudo": "<div class=\"caixa-destaque\"><h3>⚔️ Revoltas e movimentos no Brasil Imperial</h3><p>O Brasil Imperial foi marcado por diversas revoltas e movimentos sociais, políticos e regionais. Esses conflitos revelam que a construção do Estado nacional não foi pacífica nem automática. Houve disputas sobre centralização, autonomia provincial, impostos, cidadania, escravidão, pobreza, poder local e projetos de governo.</p><p>As revoltas do período imperial tiveram composições sociais diferentes. Algumas envolveram elites provinciais; outras tiveram forte participação popular, indígena, negra, livre pobre, escravizada ou sertaneja. Também variaram em seus objetivos: autonomia regional, república, federalismo, contestação social, defesa de interesses locais ou reação a políticas centralizadoras.</p><p>Para concursos, é fundamental comparar causas, participantes, região, período, objetivos e repressão. A banca costuma confundir as revoltas regenciais entre si ou tratar todos os movimentos como separatistas, o que é erro.</p></div><br><div class=\"caixa-exemplo\"><h3>📌 Exemplo aplicado</h3><p>Uma questão pode pedir a característica geral das revoltas imperiais. A resposta correta afirma que elas revelam conflitos sociais e regionais na construção do Estado.</p></div><br><div class=\"erro-classico\"><h3>⚠️ Erro clássico de concurso</h3><p>Achar que todas as revoltas imperiais tinham o mesmo programa político e a mesma base social.</p></div><br><div class=\"dica-concurso\"><h3>🎯 Dica de concurso</h3><p>Monte sempre uma tabela mental: onde ocorreu, quando, quem participou, o que defendia e como terminou.</p></div><br><div class=\"checkpoint\"><h3>✅ Checkpoint de aprendizagem</h3><ul><li>O Império teve muitos conflitos.</li><li>As revoltas tinham bases sociais variadas.</li><li>Nem todas foram separatistas.</li><li>Centralização e autonomia foram temas recorrentes.</li></ul></div><br><div class=\"resumo-premium\"><h3>📌 Resumo da página</h3><p>As revoltas imperiais revelam a disputa pela construção do Estado e os limites da ordem social brasileira.</p></div>"
    },
    {
        "titulo": "🔥 Página 2 — Confederação do Equador",
        "conteudo": "<div class=\"caixa-destaque\"><h3>🔥 Confederação do Equador: república e federalismo</h3><p>A Confederação do Equador ocorreu em 1824, principalmente em Pernambuco, como reação ao centralismo de D. Pedro I e à Constituição outorgada. O movimento defendia ideias republicanas e federalistas, questionando a concentração de poder no imperador.</p><p>O contexto envolve a tradição política pernambucana de contestação, a memória da Revolução de 1817 e a insatisfação com o autoritarismo do Primeiro Reinado. Embora reunisse setores de elite, também contou com adesões mais amplas em diferentes áreas do Nordeste.</p><p>A repressão imperial foi dura e serviu para afirmar a autoridade do governo central. Em concursos, a Confederação do Equador costuma aparecer associada ao Primeiro Reinado, à Constituição de 1824 e ao conflito entre centralização e autonomia provincial.</p></div><br><div class=\"caixa-exemplo\"><h3>📌 Exemplo aplicado</h3><p>Se o enunciado citar Pernambuco, 1824, federalismo e república, o tema é a Confederação do Equador.</p></div><br><div class=\"erro-classico\"><h3>⚠️ Erro clássico de concurso</h3><p>Confundir Confederação do Equador com revolta regencial. Ela ocorreu no Primeiro Reinado, em 1824.</p></div><br><div class=\"dica-concurso\"><h3>🎯 Dica de concurso</h3><p>Confederação do Equador = reação ao centralismo de D. Pedro I e à Constituição de 1824.</p></div><br><div class=\"checkpoint\"><h3>✅ Checkpoint de aprendizagem</h3><ul><li>Ocorreu em 1824.</li><li>Teve força em Pernambuco.</li><li>Defendia república e federalismo.</li><li>Foi reprimida pelo governo imperial.</li></ul></div><br><div class=\"resumo-premium\"><h3>📌 Resumo da página</h3><p>A Confederação do Equador contestou o centralismo do Primeiro Reinado e defendeu projeto republicano-federalista.</p></div>"
    },
    {
        "titulo": "🌊 Página 3 — Cabanagem",
        "conteudo": "<div class=\"caixa-destaque\"><h3>🌊 Cabanagem: participação popular e crise amazônica</h3><p>A Cabanagem ocorreu no Grão-Pará durante o Período Regencial e teve forte participação popular. Envolveu indígenas, mestiços, negros, trabalhadores pobres e setores locais descontentes com a exclusão política e social, além de disputas entre grupos provinciais.</p><p>O movimento foi um dos mais profundos do período regencial porque chegou a tomar o poder provincial. Sua radicalidade social assustou elites e autoridades imperiais. A repressão posterior foi intensa, buscando restaurar a ordem e a autoridade do Estado central.</p><p>A banca costuma destacar a Cabanagem como exemplo de revolta regencial com forte presença popular e tensões sociais profundas na Amazônia.</p></div><br><div class=\"caixa-exemplo\"><h3>📌 Exemplo aplicado</h3><p>Uma alternativa correta sobre a Cabanagem identifica participação popular, região do Grão-Pará e contexto regencial.</p></div><br><div class=\"erro-classico\"><h3>⚠️ Erro clássico de concurso</h3><p>Dizer que a Cabanagem foi movimento exclusivo de grandes proprietários do café paulista.</p></div><br><div class=\"dica-concurso\"><h3>🎯 Dica de concurso</h3><p>Cabanagem = Grão-Pará, Regência, forte participação popular e contestação social.</p></div><br><div class=\"checkpoint\"><h3>✅ Checkpoint de aprendizagem</h3><ul><li>Ocorreu no Grão-Pará.</li><li>Teve forte participação popular.</li><li>Chegou a controlar o governo provincial.</li><li>Foi duramente reprimida.</li></ul></div><br><div class=\"resumo-premium\"><h3>📌 Resumo da página</h3><p>A Cabanagem expressou tensões sociais e políticas profundas na Amazônia regencial.</p></div>"
    },
    {
        "titulo": "🐎 Página 4 — Revolução Farroupilha",
        "conteudo": "<div class=\"caixa-destaque\"><h3>🐎 Farroupilha: autonomia, elites regionais e economia do charque</h3><p>A Revolução Farroupilha, ou Guerra dos Farrapos, ocorreu no Rio Grande do Sul entre 1835 e 1845. O movimento envolveu elites estancieiras, militares e setores regionais insatisfeitos com impostos, concorrência externa e relação com o poder central.</p><p>Os farroupilhas proclamaram a República Rio-Grandense e, depois, houve também a experiência da República Juliana em Santa Catarina. Apesar do discurso republicano e autonomista, o movimento não deve ser confundido com revolução social igualitária. Ele foi marcado pela liderança de setores proprietários.</p><p>O acordo de paz, conhecido como Paz de Ponche Verde, reintegrou a província ao Império e concedeu algumas acomodações políticas e militares. A banca costuma cobrar a longa duração do conflito, sua base regional e a economia do charque.</p></div><br><div class=\"caixa-exemplo\"><h3>📌 Exemplo aplicado</h3><p>Se a questão citar Rio Grande do Sul, charque, república e 1835-1845, a resposta correta é Revolução Farroupilha.</p></div><br><div class=\"erro-classico\"><h3>⚠️ Erro clássico de concurso</h3><p>Afirmar que a Farroupilha foi movimento abolicionista radical e igualitário. A liderança era majoritariamente de elites regionais.</p></div><br><div class=\"dica-concurso\"><h3>🎯 Dica de concurso</h3><p>Farroupilha = Rio Grande do Sul, charque, autonomia provincial, república e longa duração.</p></div><br><div class=\"checkpoint\"><h3>✅ Checkpoint de aprendizagem</h3><ul><li>Ocorreu entre 1835 e 1845.</li><li>Teve liderança de elites regionais.</li><li>Proclamou repúblicas.</li><li>Terminou com acordo de pacificação.</li></ul></div><br><div class=\"resumo-premium\"><h3>📌 Resumo da página</h3><p>A Farroupilha combinou autonomia regional, interesses econômicos do charque e liderança de setores proprietários.</p></div>"
    },
    {
        "titulo": "🏙️ Página 5 — Sabinada",
        "conteudo": "<div class=\"caixa-destaque\"><h3>🏙️ Sabinada: Bahia, república provisória e Regência</h3><p>A Sabinada ocorreu na Bahia, em 1837, durante o Período Regencial. Liderada por setores médios urbanos, militares e profissionais liberais, defendia uma república baiana provisória até a maioridade de D. Pedro II.</p><p>O movimento expressou insatisfação com o governo regencial, críticas à centralização e tensões políticas locais. Sua proposta não era exatamente separar definitivamente a Bahia do Brasil, mas instaurar uma ordem política provisória na província.</p><p>A repressão imperial restaurou o controle sobre Salvador. Para a banca, o ponto-chave é não confundir Sabinada com Cabanagem ou Balaiada: sua base era mais urbana e seu projeto tinha caráter provisório.</p></div><br><div class=\"caixa-exemplo\"><h3>📌 Exemplo aplicado</h3><p>Uma questão que mencione Bahia, 1837, república provisória e Francisco Sabino remete à Sabinada.</p></div><br><div class=\"erro-classico\"><h3>⚠️ Erro clássico de concurso</h3><p>Dizer que a Sabinada ocorreu no Maranhão ou que foi movimento de vaqueiros sertanejos.</p></div><br><div class=\"dica-concurso\"><h3>🎯 Dica de concurso</h3><p>Sabinada = Bahia, Regência, setores urbanos e república provisória.</p></div><br><div class=\"checkpoint\"><h3>✅ Checkpoint de aprendizagem</h3><ul><li>Ocorreu na Bahia.</li><li>Teve caráter urbano.</li><li>Defendia república provisória.</li><li>Foi reprimida pelo governo.</li></ul></div><br><div class=\"resumo-premium\"><h3>📌 Resumo da página</h3><p>A Sabinada foi revolta regencial baiana com projeto republicano provisório e base urbana.</p></div>"
    },
    {
        "titulo": "🧵 Página 6 — Balaiada",
        "conteudo": "<div class=\"caixa-destaque\"><h3>🧵 Balaiada: Maranhão, pobreza e disputa política</h3><p>A Balaiada ocorreu no Maranhão entre 1838 e 1841. O movimento combinou disputas entre facções políticas locais com ampla participação de vaqueiros, artesãos, trabalhadores pobres, sertanejos e grupos marginalizados.</p><p>O nome Balaiada relaciona-se a Manuel Francisco dos Anjos Ferreira, conhecido como Balaio. O movimento também contou com lideranças populares como Raimundo Gomes e Cosme Bento, este associado à mobilização de negros escravizados e quilombolas.</p><p>A repressão comandada por Luís Alves de Lima e Silva contribuiu para sua projeção política posterior. Em concursos, a Balaiada é cobrada como revolta regencial de forte componente popular e social no Maranhão.</p></div><br><div class=\"caixa-exemplo\"><h3>📌 Exemplo aplicado</h3><p>Se o enunciado citar Maranhão, Balaio, Raimundo Gomes, Cosme e participação popular, trata-se da Balaiada.</p></div><br><div class=\"erro-classico\"><h3>⚠️ Erro clássico de concurso</h3><p>Reduzir a Balaiada a simples disputa de elite sem presença popular.</p></div><br><div class=\"dica-concurso\"><h3>🎯 Dica de concurso</h3><p>Balaiada = Maranhão, Regência, pobres livres, escravizados, quilombolas e repressão imperial.</p></div><br><div class=\"checkpoint\"><h3>✅ Checkpoint de aprendizagem</h3><ul><li>Ocorreu no Maranhão.</li><li>Teve participação popular expressiva.</li><li>Misturou conflito social e disputa política local.</li><li>Foi reprimida pelo poder imperial.</li></ul></div><br><div class=\"resumo-premium\"><h3>📌 Resumo da página</h3><p>A Balaiada revelou tensões sociais profundas no Maranhão regencial e mobilização de grupos populares.</p></div>"
    },
    {
        "titulo": "🕌 Página 7 — Revolta dos Malês",
        "conteudo": "<div class=\"caixa-destaque\"><h3>🕌 Revolta dos Malês: escravidão, religião e resistência</h3><p>A Revolta dos Malês ocorreu em Salvador, em 1835, e foi liderada principalmente por africanos muçulmanos escravizados e libertos. O movimento revela a importância das resistências negras urbanas no Brasil Imperial.</p><p>A revolta articulou redes de sociabilidade, práticas religiosas, alfabetização em árabe entre alguns participantes e oposição à escravidão e à opressão social. Embora tenha sido rapidamente reprimida, causou grande impacto nas elites baianas e nas autoridades.</p><p>Para concursos, a Revolta dos Malês não deve ser tratada apenas como revolta religiosa. Ela envolveu religião, etnicidade, escravidão, liberdade e resistência negra urbana.</p></div><br><div class=\"caixa-exemplo\"><h3>📌 Exemplo aplicado</h3><p>Uma questão sobre Salvador, 1835, africanos muçulmanos e resistência escrava aponta para a Revolta dos Malês.</p></div><br><div class=\"erro-classico\"><h3>⚠️ Erro clássico de concurso</h3><p>Reduzir os Malês a conflito sem relação com escravidão. A revolta está ligada à resistência negra no contexto escravista.</p></div><br><div class=\"dica-concurso\"><h3>🎯 Dica de concurso</h3><p>Malês = Bahia, 1835, africanos muçulmanos, escravizados/libertos e resistência urbana.</p></div><br><div class=\"checkpoint\"><h3>✅ Checkpoint de aprendizagem</h3><ul><li>Ocorreu em Salvador.</li><li>Teve liderança africana muçulmana.</li><li>Envolveu escravizados e libertos.</li><li>Foi importante resistência negra urbana.</li></ul></div><br><div class=\"resumo-premium\"><h3>📌 Resumo da página</h3><p>A Revolta dos Malês expressou resistência negra, religiosa e política dentro da sociedade escravista imperial.</p></div>"
    },
    {
        "titulo": "🌴 Página 8 — Revolução Praieira",
        "conteudo": "<div class=\"caixa-destaque\"><h3>🌴 Praieira: liberalismo radical e Pernambuco</h3><p>A Revolução Praieira ocorreu em Pernambuco, em 1848, no contexto do Segundo Reinado. O movimento relacionou-se a disputas entre liberais praieiros e grupos conservadores locais, além de críticas ao domínio político de famílias tradicionais.</p><p>O programa praieiro apresentou reivindicações como voto livre e universal masculino, liberdade de imprensa, federalismo, extinção do Poder Moderador e nacionalização do comércio a retalho. Essas propostas revelam influência do liberalismo radical e do contexto revolucionário de 1848 na Europa.</p><p>Apesar de seu discurso reformista, o movimento tinha limites sociais e não significava democracia plena nos termos atuais. Em concursos, a Praieira é geralmente cobrada como última grande revolta liberal do Império.</p></div><br><div class=\"caixa-exemplo\"><h3>📌 Exemplo aplicado</h3><p>Se a questão mencionar Pernambuco, 1848, Partido da Praia e críticas ao Poder Moderador, o tema é Revolução Praieira.</p></div><br><div class=\"erro-classico\"><h3>⚠️ Erro clássico de concurso</h3><p>Confundir Praieira com Confederação do Equador. Ambas ocorreram em Pernambuco, mas em contextos diferentes.</p></div><br><div class=\"dica-concurso\"><h3>🎯 Dica de concurso</h3><p>Praieira = Pernambuco, 1848, liberalismo radical, crítica ao Poder Moderador e oligarquias locais.</p></div><br><div class=\"checkpoint\"><h3>✅ Checkpoint de aprendizagem</h3><ul><li>Ocorreu em Pernambuco.</li><li>Relaciona-se ao contexto de 1848.</li><li>Criticava oligarquias e centralização.</li><li>Foi reprimida pelo Império.</li></ul></div><br><div class=\"resumo-premium\"><h3>📌 Resumo da página</h3><p>A Praieira foi movimento liberal pernambucano com propostas reformistas e críticas à centralização imperial.</p></div>"
    },
    {
        "titulo": "✊ Página 9 — Resistência escrava e abolicionismo",
        "conteudo": "<div class=\"caixa-destaque\"><h3>✊ Resistências escravas e movimentos abolicionistas</h3><p>Durante todo o Império, escravizados resistiram por fugas, quilombos, negociações, ações judiciais, compra de alforrias, formação de famílias, redes de solidariedade, revoltas e participação em movimentos abolicionistas. Essas ações pressionaram o sistema escravista por baixo.</p><p>O abolicionismo ganhou força na segunda metade do século XIX, reunindo jornalistas, advogados, estudantes, trabalhadores urbanos, libertos, escravizados fugitivos, clubes e sociedades abolicionistas. A abolição não foi simples concessão da monarquia.</p><p>A banca costuma valorizar a agência dos escravizados e libertos. Portanto, alternativas que tratam a população escravizada como passiva ou que explicam a abolição apenas por decisão da princesa Isabel são incompletas.</p></div><br><div class=\"caixa-exemplo\"><h3>📌 Exemplo aplicado</h3><p>Uma resposta correta reconhece que a abolição resultou de pressões sociais múltiplas, incluindo resistência dos próprios escravizados.</p></div><br><div class=\"erro-classico\"><h3>⚠️ Erro clássico de concurso</h3><p>Dizer que os escravizados aguardaram passivamente a Lei Áurea. Isso apaga resistências e ações políticas.</p></div><br><div class=\"dica-concurso\"><h3>🎯 Dica de concurso</h3><p>Abolicionismo = pressão social, resistência escrava, redes urbanas e desgaste da escravidão.</p></div><br><div class=\"checkpoint\"><h3>✅ Checkpoint de aprendizagem</h3><ul><li>A resistência escrava foi constante.</li><li>Quilombos e fugas tinham significado político.</li><li>Abolicionismo envolveu diversos grupos.</li><li>A Lei Áurea foi resultado de pressões acumuladas.</li></ul></div><br><div class=\"resumo-premium\"><h3>📌 Resumo da página</h3><p>As resistências escravas e o abolicionismo foram centrais para a crise final da ordem escravista.</p></div>"
    },
    {
        "titulo": "🗞️ Página 10 — Movimentos urbanos e opinião pública",
        "conteudo": "<div class=\"caixa-destaque\"><h3>🗞️ Imprensa, clubes, associações e mobilização urbana</h3><p>No Império, a vida política não se limitava ao Parlamento. Imprensa, clubes, associações, irmandades, sociedades abolicionistas, espaços religiosos e redes urbanas também foram locais de debate e mobilização.</p><p>Movimentos como a Praieira e o abolicionismo mostram a importância da opinião pública, dos jornais e da circulação de ideias. Mesmo com cidadania restrita, diferentes grupos encontravam formas de pressão política fora dos canais eleitorais formais.</p><p>Esse ponto é importante para evitar a ideia de que apenas deputados, senadores e imperadores faziam política. A história do Império inclui participação social formal e informal.</p></div><br><div class=\"caixa-exemplo\"><h3>📌 Exemplo aplicado</h3><p>Se a prova mencionar jornais, clubes abolicionistas e pressão urbana, a alternativa correta deve reconhecer formas não eleitorais de ação política.</p></div><br><div class=\"erro-classico\"><h3>⚠️ Erro clássico de concurso</h3><p>Pensar que, por haver voto censitário, não existia mobilização política fora das instituições oficiais.</p></div><br><div class=\"dica-concurso\"><h3>🎯 Dica de concurso</h3><p>Observe espaços de sociabilidade: imprensa, clubes, irmandades, associações e ruas.</p></div><br><div class=\"checkpoint\"><h3>✅ Checkpoint de aprendizagem</h3><ul><li>A política imperial ultrapassava o Parlamento.</li><li>A imprensa teve papel importante.</li><li>Clubes e associações mobilizavam pessoas.</li><li>A opinião pública pressionava o Estado.</li></ul></div><br><div class=\"resumo-premium\"><h3>📌 Resumo da página</h3><p>A mobilização urbana e a imprensa ampliaram formas de participação política no Império.</p></div>"
    },
    {
        "titulo": "🔍 Página 11 — Comparando as revoltas",
        "conteudo": "<div class=\"caixa-destaque\"><h3>🔍 Como comparar movimentos imperiais</h3><p>Comparar revoltas imperiais exige atenção a critérios. A Confederação do Equador pertence ao Primeiro Reinado; Cabanagem, Farroupilha, Sabinada, Balaiada e Malês situam-se no contexto regencial; Praieira ocorre no Segundo Reinado. Cada uma tem região, composição social e objetivo próprio.</p><p>Cabanagem e Balaiada tiveram forte participação popular; Farroupilha teve liderança predominante de elites regionais; Sabinada teve base urbana; Malês foi resistência negra urbana; Praieira articulou liberalismo radical e disputa política pernambucana.</p><p>A banca costuma aproximar movimentos por semelhança regional, palavra-chave ou período. O candidato deve evitar respostas automáticas e observar os elementos centrais do enunciado.</p></div><br><div class=\"caixa-exemplo\"><h3>📌 Exemplo aplicado</h3><p>Uma questão que compare Farroupilha e Cabanagem deve reconhecer diferenças de liderança social e objetivos.</p></div><br><div class=\"erro-classico\"><h3>⚠️ Erro clássico de concurso</h3><p>Achar que todas as revoltas regenciais foram idênticas porque ocorreram no mesmo período.</p></div><br><div class=\"dica-concurso\"><h3>🎯 Dica de concurso</h3><p>Compare por período, região, base social, objetivo e desfecho.</p></div><br><div class=\"checkpoint\"><h3>✅ Checkpoint de aprendizagem</h3><ul><li>Os movimentos não foram iguais.</li><li>A base social varia muito.</li><li>O período ajuda a identificar a revolta.</li><li>A região é pista importante, mas não basta.</li></ul></div><br><div class=\"resumo-premium\"><h3>📌 Resumo da página</h3><p>A comparação correta das revoltas imperiais depende de contexto, participantes, projetos e relação com o Estado.</p></div>"
    },
    {
        "titulo": "🎯 Página 12 — Síntese para concursos",
        "conteudo": "<div class=\"caixa-destaque\"><h3>🎯 Como a banca cobra revoltas imperiais</h3><p>Questões sobre revoltas e movimentos no Brasil Imperial costumam cobrar identificação, comparação e interpretação. A banca pode apresentar um enunciado com região, data, participantes e reivindicações, esperando que o candidato reconheça o movimento correto.</p><p>As pegadinhas mais comuns são trocar Cabanagem por Balaiada, confundir Confederação do Equador com Praieira, apresentar Farroupilha como movimento popular igualitário ou tratar os Malês como revolta apenas religiosa.</p><p>A alternativa correta geralmente reconhece complexidade: conflito regional e social, disputa entre centralização e autonomia, participação popular, repressão imperial e limites dos projetos políticos.</p></div><br><div class=\"caixa-exemplo\"><h3>📌 Exemplo aplicado</h3><p>Em prova, se o enunciado trouxer “Pernambuco” sozinho, não responda automaticamente: pode ser 1817, Confederação do Equador ou Praieira.</p></div><br><div class=\"erro-classico\"><h3>⚠️ Erro clássico de concurso</h3><p>Decorar nomes sem relacionar contexto. Isso aumenta erro em questões com distratores fortes.</p></div><br><div class=\"dica-concurso\"><h3>🎯 Dica de concurso</h3><p>Use quatro perguntas: onde, quando, quem participou e o que defendia.</p></div><br><div class=\"checkpoint\"><h3>✅ Checkpoint de aprendizagem</h3><ul><li>Identificação exige pistas completas.</li><li>Pernambuco aparece em vários movimentos.</li><li>Regência concentra muitas revoltas.</li><li>Participação popular é critério importante.</li></ul></div><br><div class=\"resumo-premium\"><h3>📌 Resumo da página</h3><p>Para acertar, compare as revoltas imperiais por contexto, região, base social, objetivo e repressão.</p></div>"
    }
];
