// FAROL DO SABER — Tópico 31 de História
// A Europa da Revolução Industrial e a expansão imperialista dos séculos XIX e XX
// Teoria premium em 12 páginas.

const revolucaoIndustrialExpansaoImperialistaSeculosXIXeXXTeoria = [
    {
        "titulo": "1. Revolução Industrial: conceito, tempo e interpretação",
        "conteudo": "<p>A Revolução Industrial foi um processo de transformação da produção, do trabalho, da energia e das relações sociais iniciado na Grã-Bretanha no século XVIII. O termo revolução indica a profundidade das mudanças, não um acontecimento instantâneo.</p><p>A mecanização elevou a capacidade produtiva, mas seu avanço foi desigual entre setores e regiões. Oficinas, trabalho doméstico, artesanato e agricultura continuaram coexistindo com fábricas durante longo período.</p><p>Uma mudança decisiva foi a passagem progressiva de fontes orgânicas de energia, como força humana, animal, água e madeira, para combustíveis minerais, sobretudo o carvão.</p><p>O processo reuniu inovação técnica, investimento, mercados, transportes, disponibilidade de trabalhadores e novas formas de organização. Nenhum desses fatores, isoladamente, explica o pioneirismo britânico.</p><p>A industrialização alterou ritmos de vida, paisagens urbanas e relações entre proprietários e assalariados. Também ampliou a circulação internacional de mercadorias, capitais e matérias-primas.</p><p>As mudanças não trouxeram benefícios distribuídos de modo igual. Crescimento econômico, exploração do trabalho, mobilização operária e reformas sociais fizeram parte da mesma experiência histórica.</p><p>Em provas, evite uma narrativa automática de progresso. A industrialização aumentou produtividade e inovação, mas produziu conflitos, desigualdades e impactos ambientais.</p><div class=\"box-teoria exemplo\"><strong>🧭 Exemplo de prova:</strong><p>Uma cidade podia reunir fábricas mecanizadas e numerosas oficinas artesanais no mesmo período.</p></div><div class=\"box-teoria erro\"><strong>⚠️ Erro clássico:</strong><p>Definir a Revolução Industrial como simples invenção da máquina a vapor.</p></div><div class=\"box-teoria dica\"><strong>🎯 Dica de banca:</strong><p>Pense em um sistema: energia, tecnologia, capital, trabalho, mercados e transportes.</p></div><div class=\"box-teoria resumo\"><strong>📝 Resumo:</strong><p>A Revolução Industrial foi profunda, gradual, desigual e socialmente conflituosa.</p></div>"
    },
    {
        "titulo": "2. Por que a Grã-Bretanha foi pioneira?",
        "conteudo": "<p>O pioneirismo britânico decorreu da combinação de condições acumuladas, e não de uma suposta superioridade natural. Mudanças agrícolas elevaram a oferta de alimentos e reorganizaram o acesso à terra.</p><p>Os cercamentos consolidaram propriedades e favoreceram a produção comercial, mas também reduziram usos comunitários e pressionaram famílias rurais. Seus efeitos variaram conforme região e período.</p><p>Reservas de carvão mineral relativamente acessíveis abasteceram máquinas e fornos. O ferro forneceu instrumentos, trilhos e equipamentos indispensáveis à expansão produtiva.</p><p>Comércio atlântico, colonização e escravização contribuíram para acumular capitais e ampliar mercados. Essas conexões não explicam tudo, mas não podem ser separadas da industrialização britânica.</p><p>Bancos, crédito, direitos de propriedade e uma elite disposta a investir facilitaram empreendimentos. O Estado protegeu rotas, contratos e interesses comerciais por meios políticos e militares.</p><p>Rios, canais, portos e depois ferrovias reduziram custos de transporte. Um mercado interno relativamente integrado favoreceu a circulação de carvão, alimentos e manufaturas.</p><p>Crescimento populacional ampliou simultaneamente consumidores e trabalhadores. A oferta de mão de obra, porém, não tornou o trabalho fabril uma escolha livre de pressões econômicas.</p><div class=\"box-teoria exemplo\"><strong>🧭 Exemplo de prova:</strong><p>Carvão sem capitais, demanda e transportes não produziria sozinho um sistema industrial.</p></div><div class=\"box-teoria erro\"><strong>⚠️ Erro clássico:</strong><p>Atribuir o pioneirismo a um único invento ou à personalidade inventiva dos britânicos.</p></div><div class=\"box-teoria dica\"><strong>🎯 Dica de banca:</strong><p>Associe agricultura, energia, capital, mercados, império, instituições e transportes.</p></div><div class=\"box-teoria resumo\"><strong>📝 Resumo:</strong><p>A industrialização britânica nasceu da convergência de condições econômicas, sociais, políticas e geográficas.</p></div>"
    },
    {
        "titulo": "3. Primeira Revolução Industrial: têxteis, vapor, carvão e ferro",
        "conteudo": "<p>O setor têxtil do algodão liderou a mecanização. Máquinas de fiar e tecer elevaram a produção e estimularam a concentração de trabalhadores e equipamentos.</p><p>O algodão ligava fábricas britânicas a plantações escravistas e mercados externos. Assim, indústria e economia atlântica formaram circuitos interdependentes.</p><p>A máquina a vapor aperfeiçoada por James Watt permitiu utilizar energia com maior regularidade. Ela não foi criação isolada nem substituiu imediatamente todas as demais fontes.</p><p>O carvão alimentou motores e a siderurgia. Novas técnicas aumentaram a produção de ferro, material empregado em máquinas, pontes, ferramentas e trilhos.</p><p>Canais e estradas melhoradas facilitaram o abastecimento. A ferrovia acelerou o deslocamento, estimulou mineração e siderurgia e integrou mercados regionais.</p><p>O sistema fabril reuniu capital fixo, supervisão e trabalhadores em um mesmo espaço. Essa concentração favoreceu controle do tempo e padronização das tarefas.</p><p>Inovações surgiram por aperfeiçoamentos sucessivos realizados por inventores, artesãos, empresários e trabalhadores. A imagem do gênio solitário oculta esse caráter coletivo.</p><div class=\"box-teoria exemplo\"><strong>🧭 Exemplo de prova:</strong><p>A ferrovia consumia carvão e ferro enquanto ampliava o mercado dessas mesmas atividades.</p></div><div class=\"box-teoria erro\"><strong>⚠️ Erro clássico:</strong><p>Imaginar que a máquina a vapor iniciou e completou sozinha a industrialização.</p></div><div class=\"box-teoria dica\"><strong>🎯 Dica de banca:</strong><p>Têxteis puxam a mecanização; carvão e vapor movem; ferro e ferrovias integram.</p></div><div class=\"box-teoria resumo\"><strong>📝 Resumo:</strong><p>A primeira industrialização articulou algodão, fábrica, energia mineral, metalurgia e transportes.</p></div>"
    },
    {
        "titulo": "4. Sistema fabril, disciplina e divisão do trabalho",
        "conteudo": "<p>Antes da fábrica, mercadores distribuíam matérias-primas a famílias que produziam em casa. Esse sistema doméstico já conectava campo, comércio e manufatura.</p><p>A fábrica concentrou máquinas e trabalhadores sob direção empresarial. O custo dos equipamentos dificultou o controle direto dos produtores sobre os meios de trabalho.</p><p>Relógios, regulamentos, multas e supervisores impuseram horários mais rígidos. A disciplina fabril contrastava com ritmos definidos por tarefa e estação, embora estes não fossem livres de obrigações.</p><p>A divisão do trabalho fragmentou a produção em operações repetidas. Ela podia elevar produtividade, reduzir aprendizagem necessária e ampliar o controle gerencial.</p><p>O salário transformou-se na principal fonte de sobrevivência de muitos trabalhadores urbanos. Sua negociação ocorria em relações marcadas por desigualdade de recursos.</p><p>Empresários buscavam diminuir custos e ampliar produção; trabalhadores defendiam renda, autonomia, segurança e tempo. O conflito social foi estrutural, não simples falha de adaptação individual.</p><p>Fábricas não eliminaram artesãos. Alguns perderam mercados, outros se especializaram, repararam máquinas ou foram incorporados a cadeias industriais.</p><div class=\"box-teoria exemplo\"><strong>🧭 Exemplo de prova:</strong><p>Dividir a fabricação em tarefas simples podia aumentar a produção e reduzir a autonomia do trabalhador.</p></div><div class=\"box-teoria erro\"><strong>⚠️ Erro clássico:</strong><p>Confundir trabalho assalariado com relação automaticamente equilibrada entre as partes.</p></div><div class=\"box-teoria dica\"><strong>🎯 Dica de banca:</strong><p>Sistema fabril = concentração, máquinas, supervisão, disciplina temporal e divisão de tarefas.</p></div><div class=\"box-teoria resumo\"><strong>📝 Resumo:</strong><p>A fábrica reorganizou espaço, tempo, qualificação e poder no processo produtivo.</p></div>"
    },
    {
        "titulo": "5. Urbanização, vida operária e questão social",
        "conteudo": "<p>A industrialização acelerou o crescimento de cidades como Manchester. Migrações internas reuniram trabalhadores perto de fábricas, minas e ferrovias.</p><p>O crescimento urbano frequentemente superou a oferta de moradias, água, esgoto e transporte. Problemas sanitários estimularam debates e políticas públicas ao longo do século XIX.</p><p>Jornadas extensas, instabilidade e ambientes inseguros marcaram parte do trabalho industrial inicial. As condições variavam conforme setor, qualificação, gênero, idade e conjuntura.</p><p>Mulheres e crianças participaram amplamente da produção e contribuíram para a renda familiar. Recebiam, em geral, remunerações menores e estavam sujeitas a relações hierárquicas específicas.</p><p>Famílias operárias criaram redes de vizinhança, associações, cooperativas e espaços de lazer. Não eram vítimas passivas, mas agentes que construíam culturas próprias.</p><p>A expressão questão social reuniu preocupações com pobreza, saúde, moradia, criminalidade e conflito entre capital e trabalho. Reformadores propuseram respostas filantrópicas, legais e políticas.</p><p>Leis fabris limitaram gradualmente certas jornadas e formas de trabalho infantil. Sua aplicação foi desigual e resultou também de pressão organizada dos trabalhadores.</p><div class=\"box-teoria exemplo\"><strong>🧭 Exemplo de prova:</strong><p>Uma lei social podia expressar preocupação das elites e, ao mesmo tempo, responder à mobilização operária.</p></div><div class=\"box-teoria erro\"><strong>⚠️ Erro clássico:</strong><p>Apresentar todos os trabalhadores com experiência idêntica ou totalmente passiva.</p></div><div class=\"box-teoria dica\"><strong>🎯 Dica de banca:</strong><p>Relacione urbanização rápida, infraestrutura insuficiente, questão social e ação coletiva.</p></div><div class=\"box-teoria resumo\"><strong>📝 Resumo:</strong><p>A cidade industrial concentrou oportunidades, precariedades, sociabilidades e disputas por direitos.</p></div>"
    },
    {
        "titulo": "6. Resistências: ludismo, sindicalismo e cartismo",
        "conteudo": "<p>Trabalhadores reagiram às transformações industriais por petições, associações, greves, cooperativas, imprensa e ação política. Suas estratégias mudaram conforme repressão e oportunidades.</p><p>O ludismo atacou máquinas associadas à redução de salários, perda de qualificação e quebra de costumes do ofício. Não foi simples rejeição irracional de toda tecnologia.</p><p>As primeiras trade unions organizaram trabalhadores por ofício ou setor. Negociavam salários, auxílio mútuo e condições, enfrentando períodos de proibição legal.</p><p>O cartismo britânico apresentou a Carta do Povo, que reivindicava reformas políticas como sufrágio masculino mais amplo e voto secreto. Ligou direitos políticos à defesa social dos trabalhadores.</p><p>O socialismo utópico criticou a competição e imaginou comunidades cooperativas. Marx e Engels analisaram o conflito entre burguesia e proletariado como motor da sociedade capitalista.</p><p>Anarquistas criticaram Estado e hierarquias, defendendo formas variadas de associação livre. Socialismos e anarquismos não formaram correntes homogêneas.</p><p>Ao longo do século XIX, sindicatos e partidos operários ampliaram presença. Conquistas vieram por conflito, negociação e legislação, não como resultado espontâneo do crescimento econômico.</p><div class=\"box-teoria exemplo\"><strong>🧭 Exemplo de prova:</strong><p>A destruição de uma máquina podia pressionar um empregador que a utilizava para alterar salários e ofícios.</p></div><div class=\"box-teoria erro\"><strong>⚠️ Erro clássico:</strong><p>Reduzir o ludismo ao medo de qualquer inovação técnica.</p></div><div class=\"box-teoria dica\"><strong>🎯 Dica de banca:</strong><p>Ludismo—controle do trabalho; sindicalismo—organização econômica; cartismo—reforma política.</p></div><div class=\"box-teoria resumo\"><strong>📝 Resumo:</strong><p>O operariado construiu respostas econômicas, políticas e ideológicas à industrialização.</p></div>"
    },
    {
        "titulo": "7. Segunda Revolução Industrial e novos centros",
        "conteudo": "<p>Da segunda metade do século XIX ao início do XX, a industrialização incorporou aço, eletricidade, petróleo, química e novos meios de comunicação. O processo é chamado Segunda Revolução Industrial.</p><p>O aço, mais resistente e progressivamente mais barato, foi aplicado em trilhos, edifícios, navios e máquinas. A indústria química produziu corantes, fertilizantes e medicamentos.</p><p>A eletricidade permitiu iluminação, motores e reorganização das fábricas. O petróleo ganhou importância com motores de combustão e transportes automotores.</p><p>Telégrafo, telefone e cabos submarinos aceleraram informações comerciais e políticas. Distâncias não desapareceram, mas decisões passaram a circular com maior rapidez.</p><p>Alemanha e Estados Unidos tornaram-se potências industriais, enquanto Bélgica, França, Japão e outras áreas avançaram em ritmos próprios. A liderança deixou de ser exclusivamente britânica.</p><p>Pesquisa científica, universidades, laboratórios empresariais e formação técnica aproximaram conhecimento e produção. Empresas passaram a investir de modo sistemático em inovação.</p><p>Produção em massa e administração racional ganharam força no início do século XX. Taylorismo e fordismo aprofundaram divisão de tarefas e padronização, sem eliminar resistência operária.</p><div class=\"box-teoria exemplo\"><strong>🧭 Exemplo de prova:</strong><p>Eletricidade e motores permitiram disposições fabris menos dependentes de um único eixo movido a vapor.</p></div><div class=\"box-teoria erro\"><strong>⚠️ Erro clássico:</strong><p>Tratar a segunda fase como repetição da primeira ou restrita à Inglaterra.</p></div><div class=\"box-teoria dica\"><strong>🎯 Dica de banca:</strong><p>Primeira: carvão, vapor, ferro e têxteis. Segunda: aço, eletricidade, petróleo e química.</p></div><div class=\"box-teoria resumo\"><strong>📝 Resumo:</strong><p>Novas energias, indústrias, comunicações e potências ampliaram a escala do capitalismo industrial.</p></div>"
    },
    {
        "titulo": "8. Capital financeiro, empresas e concentração econômica",
        "conteudo": "<p>Indústrias de aço, ferrovias e química exigiam grandes investimentos. Bancos e mercados de ações passaram a mobilizar capitais em escala superior.</p><p>Sociedades anônimas repartiam propriedade em ações e limitavam responsabilidades dos investidores. Isso facilitava reunir recursos para grandes empreendimentos.</p><p>A aproximação entre bancos e indústrias é associada ao capital financeiro. Instituições de crédito podiam influenciar decisões produtivas e expansão internacional.</p><p>Empresas buscaram controlar concorrência por cartéis, trustes e holdings. Cartéis coordenavam preços ou mercados; trustes reuniam empresas sob direção comum.</p><p>A concentração econômica não eliminou toda concorrência. Grandes grupos disputavam mercados, patentes, matérias-primas e apoio dos Estados.</p><p>A exportação de capitais financiou ferrovias, portos, minas e serviços em diferentes continentes. Esses investimentos podiam gerar infraestrutura e dependência financeira simultaneamente.</p><p>Estados estabeleceram tarifas, contratos, concessões e proteção diplomática. Capital e poder político se relacionavam, mas empresários e governos nem sempre possuíam interesses idênticos.</p><div class=\"box-teoria exemplo\"><strong>🧭 Exemplo de prova:</strong><p>Um banco europeu podia financiar uma ferrovia estrangeira e ampliar sua influência sobre receitas e decisões locais.</p></div><div class=\"box-teoria erro\"><strong>⚠️ Erro clássico:</strong><p>Afirmar que monopólios encerraram definitivamente a competição capitalista.</p></div><div class=\"box-teoria dica\"><strong>🎯 Dica de banca:</strong><p>Capital financeiro liga bancos, grandes empresas, investimentos externos e influência estatal.</p></div><div class=\"box-teoria resumo\"><strong>📝 Resumo:</strong><p>A segunda industrialização intensificou finanças, grandes empresas e internacionalização do capital.</p></div>"
    },
    {
        "titulo": "9. Imperialismo: conceitos, causas e formas de domínio",
        "conteudo": "<p>O novo imperialismo designa a intensificação da expansão de potências industrializadas entre aproximadamente 1870 e 1914. África e Ásia foram alvos centrais, mas o fenômeno alcançou outras regiões.</p><p>Interesses econômicos incluíam matérias-primas, mercados, investimentos e rotas. A importância de cada fator variou, e algumas colônias custaram mais do que renderam diretamente.</p><p>Nacionalismo, prestígio, rivalidades estratégicas e segurança marítima também impulsionaram conquistas. Governos temiam perder posições para potências concorrentes.</p><p>Ideologias racistas, darwinismo social e missão civilizadora procuraram legitimar a dominação. Essas ideias transformavam desigualdade de poder em suposta hierarquia natural.</p><p>O domínio podia assumir forma de colônia, protetorado, concessão, esfera de influência ou controle econômico informal. Soberania local era reduzida em graus diferentes.</p><p>Tecnologias como navio a vapor, telégrafo e armamentos ampliaram capacidades europeias. Conhecimento cartográfico e médico também foi mobilizado pela expansão.</p><p>Os povos submetidos negociaram, adaptaram-se, colaboraram em certas circunstâncias e resistiram de muitas formas. Imperialismo não foi ação unilateral sobre sociedades imóveis.</p><div class=\"box-teoria exemplo\"><strong>🧭 Exemplo de prova:</strong><p>Controlar empréstimos, alfândegas e ferrovias podia limitar um Estado sem anexação formal.</p></div><div class=\"box-teoria erro\"><strong>⚠️ Erro clássico:</strong><p>Explicar todas as conquistas apenas pela busca imediata de mercados consumidores.</p></div><div class=\"box-teoria dica\"><strong>🎯 Dica de banca:</strong><p>Imperialismo combina economia, estratégia, política, tecnologia e ideologia.</p></div><div class=\"box-teoria resumo\"><strong>📝 Resumo:</strong><p>A expansão imperialista foi multicausal e empregou formas diversas de controle.</p></div>"
    },
    {
        "titulo": "10. A partilha da África e as resistências africanas",
        "conteudo": "<p>Até o século XIX, a presença europeia concentrava-se em áreas costeiras africanas, embora existissem relações comerciais antigas. A ocupação territorial acelerou-se nas décadas finais do século.</p><p>A Conferência de Berlim de 1884–1885 estabeleceu regras entre potências, como o princípio da ocupação efetiva. Ela não desenhou sozinha todas as fronteiras nem contou com representação africana.</p><p>Britânicos, franceses, alemães, belgas, portugueses, italianos e espanhóis disputaram territórios. Etiópia e Libéria conservaram independência formal, em condições muito diferentes.</p><p>Fronteiras coloniais reuniram ou dividiram comunidades e redes anteriores. Contudo, conflitos africanos atuais não podem ser explicados mecanicamente apenas por essas linhas.</p><p>Administração direta e governo indireto utilizaram funcionários europeus, autoridades locais e intermediários. O trabalho, a terra e a tributação foram reorganizados para servir a interesses coloniais.</p><p>Sociedades africanas resistiram militarmente, diplomaticamente, culturalmente e no cotidiano. A vitória etíope em Adwa, em 1896, mostrou que a conquista europeia não era inevitável.</p><p>Ferrovias e portos foram construídos sobretudo para circulação de tropas e produtos de exportação. Seus efeitos posteriores não apagam a lógica colonial que orientou os investimentos.</p><div class=\"box-teoria exemplo\"><strong>🧭 Exemplo de prova:</strong><p>Uma ferrovia entre mina e porto podia integrar exportações sem conectar amplamente mercados locais.</p></div><div class=\"box-teoria erro\"><strong>⚠️ Erro clássico:</strong><p>Afirmar que a Conferência de Berlim repartiu o continente em uma única reunião e sem disputas posteriores.</p></div><div class=\"box-teoria dica\"><strong>🎯 Dica de banca:</strong><p>Berlim regulou a competição; ocupação, tratados e guerras concretizaram a partilha.</p></div><div class=\"box-teoria resumo\"><strong>📝 Resumo:</strong><p>A partilha impôs fronteiras e economias coloniais, mas encontrou múltiplas resistências africanas.</p></div>"
    },
    {
        "titulo": "11. Imperialismos na Ásia: Índia, China, Japão e Sudeste Asiático",
        "conteudo": "<p>Na Índia, a Companhia das Índias Orientais ampliou controle britânico antes da administração direta da Coroa. A rebelião de 1857 contribuiu para essa mudança institucional.</p><p>Ferrovias, telégrafos e escolas integraram o domínio britânico, facilitaram exportações e também foram apropriados por movimentos nacionalistas indianos.</p><p>Na China, as Guerras do Ópio resultaram em tratados desiguais, abertura de portos e concessões a potências. O país não foi inteiramente colonizado, mas sofreu forte limitação de soberania.</p><p>Esferas de influência dividiram vantagens comerciais e estratégicas. Rebeliões internas e intervenções externas revelaram tensões entre dinastia, populações e imperialismos.</p><p>O Japão Meiji promoveu centralização, industrialização e reformas militares após 1868. Evitou a colonização formal e tornou-se potência imperialista na Ásia.</p><p>França dominou a Indochina; Países Baixos controlaram as Índias Orientais; britânicos ampliaram posições no sul e sudeste asiático. O Sião preservou independência por diplomacia e reformas.</p><p>Povos asiáticos organizaram resistências, reformas e nacionalismos. O contato com instituições ocidentais não significou aceitação passiva nem simples cópia cultural.</p><div class=\"box-teoria exemplo\"><strong>🧭 Exemplo de prova:</strong><p>Uma ferrovia colonial podia servir ao domínio e depois ajudar nacionalistas a circular pessoas e ideias.</p></div><div class=\"box-teoria erro\"><strong>⚠️ Erro clássico:</strong><p>Tratar toda a Ásia como colônia formal europeia ou o Japão como vítima passiva.</p></div><div class=\"box-teoria dica\"><strong>🎯 Dica de banca:</strong><p>Índia—domínio britânico; China—tratados e esferas; Japão—modernização e imperialismo.</p></div><div class=\"box-teoria resumo\"><strong>📝 Resumo:</strong><p>Na Ásia coexistiram colônias, influência informal, reformas autônomas e resistências.</p></div>"
    },
    {
        "titulo": "12. Ideologias, consequências e síntese histórica",
        "conteudo": "<p>O imperialismo conectou industrialização europeia e reorganização global do poder. Matérias-primas, capitais, transportes e coerção integraram economias em posições desiguais.</p><p>Teorias raciais e darwinismo social aplicaram indevidamente noções biológicas à sociedade. A missão civilizadora apresentou conquista e exploração como tutela moral.</p><p>Exposições, escolas, mapas e literatura popular difundiram imagens hierarquizadas dos povos colonizados. A cultura imperial alcançou o cotidiano das metrópoles.</p><p>Economias coloniais foram direcionadas à exportação, alterando terras, trabalho e produção. Infraestruturas podiam gerar usos locais, mas obedeciam prioritariamente a objetivos de domínio.</p><p>Fronteiras, línguas administrativas e instituições coloniais deixaram heranças duradouras. Seus efeitos foram transformados por sociedades independentes e não determinam um destino inevitável.</p><p>Resistências e nacionalismos reuniram tradições locais, redes religiosas, imprensa, educação e conceitos políticos globais. Os colonizados foram produtores de história, não figurantes.</p><p>Rivalidades imperiais contribuíram para tensões internacionais anteriores à Primeira Guerra Mundial, embora não expliquem isoladamente o conflito.</p><div class=\"box-teoria exemplo\"><strong>🧭 Exemplo de prova:</strong><p>Uma mesma escola colonial podia difundir valores imperiais e formar críticos do colonialismo.</p></div><div class=\"box-teoria erro\"><strong>⚠️ Erro clássico:</strong><p>Confundir desenvolvimento técnico com benefício social igual ou ausência de dominação.</p></div><div class=\"box-teoria dica\"><strong>🎯 Dica de banca:</strong><p>Analise industrialização e imperialismo por conexões, desigualdades, agência e resistência.</p></div><div class=\"box-teoria checkpoint\"><strong>✅ Checkpoint:</strong><p>Como energia, fábrica, capital e poder imperial reorganizaram o mundo contemporâneo?</p></div><div class=\"box-teoria resumo\"><strong>📝 Resumo:</strong><p>Industrialização e imperialismo ampliaram capacidades e conexões, mas também dominação, desigualdades e resistências.</p></div>"
    }
];
