// ==========================================================
// FAROL DO SABER — TRANSPETRO / TAIFEIRO — BANCO 2026
// Legislação Marítima e Ambiental — 2.9 Obrigações de trabalho e previdência social — REVISÃO MÉDIA V111
// 35 questões • sem imagens • conteúdo preservado; distratores recalibrados ao padrão Cesgranrio
// Base: CTM/Decreto 10.671/2021; Lei 8.213/1991; Decreto 3.048/1999;
// EC 103/2019; STF ADI 6309 (resultado de junho/2026).
// Taifeiro 2018 Q23 e Taifeiro 2023 Q15: calibragem histórica, sem reprodução.
// ==========================================================
(() => {
    "use strict";

    const loteObrigacoesTrabalhoPrevidenciaTAA2026 =
[
    {
        "id": "TAA-2026-LMA-2.9-001",
        "disciplina": "Conhecimentos Específicos",
        "eixo": "Legislação Marítima e Ambiental",
        "topicoEdital": "2.9 Obrigações de trabalho e previdência social",
        "assunto": "Acordo de emprego — exame prévio e orientação",
        "tipoOrigem": "inedita_farol",
        "origemInterna": "Inédita Farol 2026 — elaborada com base em fontes oficiais vigentes e calibrada ao padrão Fundação Cesgranrio. Taifeiro 2018 Q23 e Taifeiro 2023 Q15 foram usadas apenas como referência histórica de incidência e NÃO foram reproduzidas.",
        "comentario": "A CTM protege a liberdade e a compreensão do consentimento contratual. O marítimo deve poder examinar o acordo e obter orientação antes de assiná-lo.",
        "explicacaoCorreta": "A CTM protege a liberdade e a compreensão do consentimento contratual. O marítimo deve poder examinar o acordo e obter orientação antes de assiná-lo.",
        "revisaoAssunto": "Acordo de emprego marítimo não é mera formalidade. A Norma A2.1 exige oportunidade de leitura e orientação prévias, além de assinatura livre e compreensão suficiente dos direitos e responsabilidades.",
        "memorizar2026": "Antes de assinar: examinar + receber orientação + compreender.",
        "dicaMacete": "Se a alternativa transforma a assinatura em renúncia ao direito de compreender o contrato, desconfie.",
        "pegadinha": "A banca pode confundir 'contrato padronizado' com dispensa de leitura e esclarecimento.",
        "fonte": "Decreto nº 10.671/2021 — Convenção sobre Trabalho Marítimo (CTM 2006), Norma A2.1, item 1, alínea b.",
        "atualizacao2026": "Base oficial vigente conferida no texto promulgado da CTM 2006.",
        "enunciado": "Antes da assinatura do acordo de emprego marítimo, a empresa informa ao tripulante que não haverá tempo para leitura detalhada nem possibilidade de buscar orientação, porque o modelo contratual é padronizado. À luz da CTM, essa prática é",
        "alternativas": [
            "regular, porque a assinatura do trabalhador presume conhecimento integral do conteúdo contratual.",
            "admitida quando o armador afirma que o modelo contratual é idêntico para toda a tripulação.",
            "aceitável se o documento ficar disponível a bordo após o embarque.",
            "incompatível: o marítimo deve examinar o acordo e poder obter orientação antes da assinatura.",
            "a restrição é aceitável quando o contrato não contém cláusula de remuneração variável."
        ],
        "correta": 3,
        "analiseAlternativas": [
            "Incorreta. A assinatura não elimina o direito de exame prévio e de orientação.",
            "Incorreta. A padronização do contrato não afasta a garantia individual de compreensão.",
            "Incorreta. A possibilidade de examinar o acordo existe antes da assinatura.",
            "Correta. A CTM protege a liberdade e a compreensão do consentimento contratual. O marítimo deve poder examinar o acordo e obter orientação antes de assiná-lo.",
            "Incorreta. A garantia não depende do tipo de remuneração."
        ]
    },
    {
        "id": "TAA-2026-LMA-2.9-002",
        "disciplina": "Conhecimentos Específicos",
        "eixo": "Legislação Marítima e Ambiental",
        "topicoEdital": "2.9 Obrigações de trabalho e previdência social",
        "assunto": "Acordo de emprego — vias assinadas",
        "tipoOrigem": "inedita_farol",
        "origemInterna": "Inédita Farol 2026 — elaborada com base em fontes oficiais vigentes e calibrada ao padrão Fundação Cesgranrio. Taifeiro 2018 Q23 e Taifeiro 2023 Q15 foram usadas apenas como referência histórica de incidência e NÃO foram reproduzidas.",
        "comentario": "A CTM prevê que armador e gente do mar tenham ambos um original assinado do acordo de emprego.",
        "explicacaoCorreta": "A CTM prevê que armador e gente do mar tenham ambos um original assinado do acordo de emprego.",
        "revisaoAssunto": "O contrato de emprego marítimo deve ser documentado de modo que as duas partes possam comprovar as condições ajustadas.",
        "memorizar2026": "Contrato marítimo: um original assinado para cada parte.",
        "dicaMacete": "Diferencie 'acesso à informação a bordo' de 'ter o próprio original assinado'.",
        "pegadinha": "Uma cópia informal ou foto não substitui a exigência expressa da Norma A2.1.",
        "fonte": "Decreto nº 10.671/2021 — CTM 2006, Norma A2.1, item 1, alínea c.",
        "atualizacao2026": "Regra contratual vigente no texto promulgado da CTM.",
        "enunciado": "Quanto à formalização do acordo de emprego marítimo, a CTM exige, entre outras garantias,",
        "alternativas": [
            "o armador e o marítimo conservarem, cada qual, um original assinado do acordo de emprego marítimo celebrado.",
            "o armador conservar o original e entregar ao trabalhador um extrato com as principais condições.",
            "o trabalhador conservar o original, ficando à empresa um registro eletrônico do vínculo.",
            "o comandante guardar os dois originais no cofre do navio até o término do embarque.",
            "a empresa fornecer cópia do acordo ao trabalhador quando houver fiscalização em porto."
        ],
        "correta": 0,
        "analiseAlternativas": [
            "Correta. A CTM prevê que armador e gente do mar tenham ambos um original assinado do acordo de emprego.",
            "Incorreta. A norma exige original assinado para ambas as partes.",
            "Incorreta. A exigência alcança armador e gente do mar.",
            "Incorreta. A via do marítimo deve estar sob sua disponibilidade, não retida como regra.",
            "Incorreta. A obrigação não surge apenas durante fiscalização."
        ]
    },
    {
        "id": "TAA-2026-LMA-2.9-003",
        "disciplina": "Conhecimentos Específicos",
        "eixo": "Legislação Marítima e Ambiental",
        "topicoEdital": "2.9 Obrigações de trabalho e previdência social",
        "assunto": "Condições de emprego — acesso a bordo",
        "tipoOrigem": "inedita_farol",
        "origemInterna": "Inédita Farol 2026 — elaborada com base em fontes oficiais vigentes e calibrada ao padrão Fundação Cesgranrio. Taifeiro 2018 Q23 e Taifeiro 2023 Q15 foram usadas apenas como referência histórica de incidência e NÃO foram reproduzidas.",
        "comentario": "A informação sobre condições de emprego deve estar facilmente acessível a bordo, inclusive para fiscalização.",
        "explicacaoCorreta": "A informação sobre condições de emprego deve estar facilmente acessível a bordo, inclusive para fiscalização.",
        "revisaoAssunto": "A CTM trata transparência contratual como requisito de bordo, não apenas administrativo em terra.",
        "memorizar2026": "Condições de emprego: informação precisa e acessível a bordo.",
        "dicaMacete": "Quando a alternativa manda toda a prova do vínculo para terra, procure a exigência de acesso a bordo.",
        "pegadinha": "A banca pode trocar disponibilidade documental por mero conhecimento verbal.",
        "fonte": "Decreto nº 10.671/2021 — CTM 2006, Norma A2.1, item 1, alínea d.",
        "atualizacao2026": "Base oficial vigente conferida no Decreto nº 10.671/2021.",
        "enunciado": "Uma companhia mantém os acordos de emprego completos apenas em sua sede administrativa, deixando a bordo somente um resumo das condições contratuais. Considerando a CTM, essa organização",
        "alternativas": [
            "é compatível, porque basta que o comandante possa consultar as condições de emprego quando algum tripulante solicitar informação.",
            "é compatível se a companhia mantiver o acordo integralmente disponível em terra e informar por mensagem os pontos principais à tripulação.",
            "é incompatível quando a embarcação estiver em porto estrangeiro sujeito a inspeção do Estado do Porto.",
            "é incompatível porque cada tripulante deveria portar permanentemente o original físico do contrato durante o serviço.",
            "contraria a CTM, que exige acesso fácil a bordo às condições de emprego e à cópia do acordo, inclusive para permitir verificação de seus termos."
        ],
        "correta": 4,
        "analiseAlternativas": [
            "Incorreta. O acesso deve ser fácil aos interessados, não centralizado dessa forma.",
            "Incorreta. A CTM exige acesso a bordo às condições relevantes e à cópia do acordo.",
            "Incorreta. A exigência não nasce somente nessa situação.",
            "Incorreta. A CTM não exige que o original permaneça fisicamente com o marítimo em todo momento.",
            "Correta. A informação sobre condições de emprego deve estar facilmente acessível a bordo, inclusive para fiscalização."
        ]
    },
    {
        "id": "TAA-2026-LMA-2.9-004",
        "disciplina": "Conhecimentos Específicos",
        "eixo": "Legislação Marítima e Ambiental",
        "topicoEdital": "2.9 Obrigações de trabalho e previdência social",
        "assunto": "Remuneração — periodicidade",
        "tipoOrigem": "inedita_farol",
        "origemInterna": "Inédita Farol 2026 — elaborada com base em fontes oficiais vigentes e calibrada ao padrão Fundação Cesgranrio. Taifeiro 2018 Q23 e Taifeiro 2023 Q15 foram usadas apenas como referência histórica de incidência e NÃO foram reproduzidas.",
        "comentario": "A remuneração deve ser periódica e integral; o intervalo de pagamento não pode exceder um mês.",
        "explicacaoCorreta": "A remuneração deve ser periódica e integral; o intervalo de pagamento não pode exceder um mês.",
        "revisaoAssunto": "A Norma A2.2 estabelece uma proteção objetiva contra longos períodos sem pagamento.",
        "memorizar2026": "Salário da gente do mar: intervalo de pagamento ≤ 1 mês.",
        "dicaMacete": "Se aparecer pagamento bimestral como regra, está além do limite da CTM.",
        "pegadinha": "A expressão 'salário consolidado' não muda o prazo máximo de pagamento.",
        "fonte": "Decreto nº 10.671/2021 — CTM 2006, Regra 2.2 e Norma A2.2, item 1.",
        "atualizacao2026": "Regra vigente conforme o texto promulgado da CTM.",
        "enunciado": "Uma companhia pretende pagar a remuneração devida aos marítimos em intervalos regulares de 45 dias. De acordo com a CTM, essa prática é",
        "alternativas": [
            "compatível, porque a CTM disciplina a integralidade do pagamento, mas não fixa intervalo máximo entre pagamentos.",
            "compatível se houver adiantamento parcial no mês intermediário, ainda que não corresponda à remuneração devida.",
            "incompatível, pois a remuneração devida deve ser paga em intervalos que não excedam um mês.",
            "irregular quando o contrato tiver prazo inferior a seis meses, hipótese em que o pagamento deve ser mensal.",
            "permitida para marítimos que recebam salário consolidado."
        ],
        "correta": 2,
        "analiseAlternativas": [
            "Incorreta. A CTM fixa também periodicidade máxima.",
            "Incorreta. A obrigação é de pagamento da remuneração devida em intervalo não superior a um mês.",
            "Correta. A remuneração deve ser periódica e integral; o intervalo de pagamento não pode exceder um mês.",
            "Incorreta. O limite de intervalo não depende da duração do contrato.",
            "Incorreta. Salário consolidado não afasta a periodicidade máxima."
        ]
    },
    {
        "id": "TAA-2026-LMA-2.9-005",
        "disciplina": "Conhecimentos Específicos",
        "eixo": "Legislação Marítima e Ambiental",
        "topicoEdital": "2.9 Obrigações de trabalho e previdência social",
        "assunto": "Horas de descanso — conceito",
        "tipoOrigem": "inedita_farol",
        "origemInterna": "Inédita Farol 2026 — elaborada com base em fontes oficiais vigentes e calibrada ao padrão Fundação Cesgranrio. Taifeiro 2018 Q23 e Taifeiro 2023 Q15 foram usadas apenas como referência histórica de incidência e NÃO foram reproduzidas.",
        "comentario": "A CTM diferencia tempo de descanso de pausas curtas. Essa distinção impede maquiar o registro de repouso.",
        "explicacaoCorreta": "A CTM diferencia tempo de descanso de pausas curtas. Essa distinção impede maquiar o registro de repouso.",
        "revisaoAssunto": "Horas de trabalho são o tempo em que se exige trabalho para o navio; descanso é o tempo fora dessas horas, sem incluir pausas curtas.",
        "memorizar2026": "Pausa curta ≠ hora de descanso.",
        "dicaMacete": "Cuidado com alternativas que tentem converter qualquer intervalo em repouso regulamentar.",
        "pegadinha": "O local da pausa, por si só, não muda a definição.",
        "fonte": "Decreto nº 10.671/2021 — CTM 2006, Norma A2.3, item 1.",
        "atualizacao2026": "Definições vigentes no texto promulgado da CTM.",
        "enunciado": "Durante uma jornada, o tripulante recebe várias pausas curtas entre tarefas. Para fins do cálculo das horas mínimas de descanso da CTM, essas pausas curtas podem ser computadas como horas de descanso?",
        "alternativas": [
            "Sim, desde que a pausa tenha ocorrido fora do posto de trabalho.",
            "Sim, quando o tripulante puder sentar-se durante a pausa.",
            "Sim, se a pausa for registrada pelo superior no livro de serviço.",
            "Não. A CTM exclui as pausas curtas do conceito de horas de descanso.",
            "Não, porque a CTM considera descanso os períodos contínuos que alcancem oito horas."
        ],
        "correta": 3,
        "analiseAlternativas": [
            "Incorreta. A CTM exclui pausas curtas do conceito de descanso.",
            "Incorreta. A posição corporal não define hora de descanso.",
            "Incorreta. Registro não transforma pausa curta em descanso para fins da definição.",
            "Correta. A CTM diferencia tempo de descanso de pausas curtas. Essa distinção impede maquiar o registro de repouso.",
            "Incorreta. A CTM não define descanso por um mínimo genérico de oito horas."
        ]
    },
    {
        "id": "TAA-2026-LMA-2.9-006",
        "disciplina": "Conhecimentos Específicos",
        "eixo": "Legislação Marítima e Ambiental",
        "topicoEdital": "2.9 Obrigações de trabalho e previdência social",
        "assunto": "Limite máximo de horas de trabalho",
        "tipoOrigem": "inedita_farol",
        "origemInterna": "Inédita Farol 2026 — elaborada com base em fontes oficiais vigentes e calibrada ao padrão Fundação Cesgranrio. Taifeiro 2018 Q23 e Taifeiro 2023 Q15 foram usadas apenas como referência histórica de incidência e NÃO foram reproduzidas.",
        "comentario": "Pelo critério de trabalho máximo, a CTM estabelece 14 horas em 24 e 72 em sete dias.",
        "explicacaoCorreta": "Pelo critério de trabalho máximo, a CTM estabelece 14 horas em 24 e 72 em sete dias.",
        "revisaoAssunto": "A prova pode misturar os dois pares numéricos da CTM: 14/72 para trabalho máximo e 10/77 para descanso mínimo.",
        "memorizar2026": "Trabalho máximo = 14/24 + 72/7.",
        "dicaMacete": "Memorize os pares sem cruzá-los: 14–72 trabalha; 10–77 descansa.",
        "pegadinha": "O distrator clássico troca 72 por 77.",
        "fonte": "Decreto nº 10.671/2021 — CTM 2006, Norma A2.3, item 5, alínea a.",
        "atualizacao2026": "Limites oficiais vigentes no texto promulgado da CTM.",
        "enunciado": "Se a organização do serviço a bordo adotar o critério de limite máximo de horas de trabalho previsto na CTM, quais são os limites aplicáveis?",
        "alternativas": [
            "No máximo 12 horas em 24 horas e 60 horas em sete dias.",
            "No máximo 16 horas em 24 horas e 72 horas em sete dias.",
            "No máximo 14 horas em 24 horas e 84 horas em sete dias.",
            "No máximo 14 horas em 24 horas e 72 horas em sete dias.",
            "No máximo 10 horas em 24 horas e 77 horas em sete dias."
        ],
        "correta": 3,
        "analiseAlternativas": [
            "Incorreta. Esses não são os limites máximos definidos na Norma A2.3.",
            "Incorreta. O limite diário excede 14 horas.",
            "Incorreta. O limite semanal excede 72 horas.",
            "Correta. Pelo critério de trabalho máximo, a CTM estabelece 14 horas em 24 e 72 em sete dias.",
            "Incorreta. 10 e 77 correspondem ao critério de descanso mínimo, não trabalho máximo."
        ]
    },
    {
        "id": "TAA-2026-LMA-2.9-007",
        "disciplina": "Conhecimentos Específicos",
        "eixo": "Legislação Marítima e Ambiental",
        "topicoEdital": "2.9 Obrigações de trabalho e previdência social",
        "assunto": "Limite mínimo de horas de descanso",
        "tipoOrigem": "inedita_farol",
        "origemInterna": "Inédita Farol 2026 — elaborada com base em fontes oficiais vigentes e calibrada ao padrão Fundação Cesgranrio. Taifeiro 2018 Q23 e Taifeiro 2023 Q15 foram usadas apenas como referência histórica de incidência e NÃO foram reproduzidas.",
        "comentario": "Descanso mínimo: 10 horas em 24 e 77 horas em sete dias.",
        "explicacaoCorreta": "Descanso mínimo: 10 horas em 24 e 77 horas em sete dias.",
        "revisaoAssunto": "Os pares 14/72 e 10/77 são cobrança provável porque têm números próximos e funções opostas.",
        "memorizar2026": "Descanso mínimo = 10/24 + 77/7.",
        "dicaMacete": "Associe 77 ao descanso semanal.",
        "pegadinha": "Não confunda 72 horas de trabalho máximo com 77 horas de descanso mínimo.",
        "fonte": "Decreto nº 10.671/2021 — CTM 2006, Norma A2.3, item 5, alínea b.",
        "atualizacao2026": "Limites oficiais vigentes no texto promulgado da CTM.",
        "enunciado": "Se a organização do serviço a bordo adotar o critério de horas mínimas de descanso previsto na CTM, qual combinação está correta?",
        "alternativas": [
            "8 horas em 24 horas e 56 horas em sete dias.",
            "10 horas em 24 horas e 72 horas em sete dias.",
            "12 horas em 24 horas e 77 horas em sete dias.",
            "14 horas em 24 horas e 72 horas em sete dias.",
            "10 horas em 24 horas e 77 horas em sete dias."
        ],
        "correta": 4,
        "analiseAlternativas": [
            "Incorreta. A CTM estabelece mínimos superiores.",
            "Incorreta. 72 integra o limite de trabalho máximo, não o mínimo semanal de descanso.",
            "Incorreta. O mínimo diário indicado na norma é 10 horas.",
            "Incorreta. Esse par pertence ao limite máximo de trabalho.",
            "Correta. Descanso mínimo: 10 horas em 24 e 77 horas em sete dias."
        ]
    },
    {
        "id": "TAA-2026-LMA-2.9-008",
        "disciplina": "Conhecimentos Específicos",
        "eixo": "Legislação Marítima e Ambiental",
        "topicoEdital": "2.9 Obrigações de trabalho e previdência social",
        "assunto": "Fracionamento do descanso",
        "tipoOrigem": "inedita_farol",
        "origemInterna": "Inédita Farol 2026 — elaborada com base em fontes oficiais vigentes e calibrada ao padrão Fundação Cesgranrio. Taifeiro 2018 Q23 e Taifeiro 2023 Q15 foram usadas apenas como referência histórica de incidência e NÃO foram reproduzidas.",
        "comentario": "A CTM protege também a qualidade do descanso, limitando seu fracionamento.",
        "explicacaoCorreta": "A CTM protege também a qualidade do descanso, limitando seu fracionamento.",
        "revisaoAssunto": "O descanso pode ser dividido em no máximo dois períodos; um deles deve ter pelo menos seis horas ininterruptas, e o intervalo entre períodos consecutivos não pode ultrapassar 14 horas.",
        "memorizar2026": "Máximo 2 períodos; um ≥ 6h; intervalo entre descansos ≤ 14h.",
        "dicaMacete": "Somar dez horas não basta: examine como o descanso foi dividido.",
        "pegadinha": "A banca pode dar o total correto e esconder um fracionamento proibido.",
        "fonte": "Decreto nº 10.671/2021 — CTM 2006, Norma A2.3, item 6.",
        "atualizacao2026": "Regra de fracionamento vigente na CTM.",
        "enunciado": "Em um período de 24 horas, a escala concede ao marítimo dez horas de descanso divididas em três períodos distintos. Considerando a regra geral da CTM, essa distribuição",
        "alternativas": [
            "atende à CTM, porque o total de dez horas é suficiente, independentemente do número de períodos em que o descanso foi dividido.",
            "não atende à CTM, porque o descanso foi dividido em três períodos, quando a regra geral admite no máximo dois períodos em 24 horas.",
            "atende à CTM desde que os três períodos ocorram dentro das mesmas vinte e quatro horas e somem exatamente dez horas.",
            "não atende se um dos períodos tiver duração inferior a duas horas, admitindo-se a divisão em três períodos.",
            "não atende porque o descanso mínimo diário deveria ser de doze horas contínuas, sem qualquer possibilidade de fracionamento."
        ],
        "correta": 1,
        "analiseAlternativas": [
            "Incorreta. A divisão também possui limites.",
            "Correta. A CTM protege também a qualidade do descanso, limitando seu fracionamento.",
            "Incorreta. Ainda há excesso de fracionamento.",
            "Incorreta. A regra geral admite no máximo dois períodos.",
            "Incorreta. O mínimo e a regra de fracionamento estão incorretos."
        ]
    },
    {
        "id": "TAA-2026-LMA-2.9-009",
        "disciplina": "Conhecimentos Específicos",
        "eixo": "Legislação Marítima e Ambiental",
        "topicoEdital": "2.9 Obrigações de trabalho e previdência social",
        "assunto": "Treinamentos e fadiga",
        "tipoOrigem": "inedita_farol",
        "origemInterna": "Inédita Farol 2026 — elaborada com base em fontes oficiais vigentes e calibrada ao padrão Fundação Cesgranrio. Taifeiro 2018 Q23 e Taifeiro 2023 Q15 foram usadas apenas como referência histórica de incidência e NÃO foram reproduzidas.",
        "comentario": "Exercícios obrigatórios continuam necessários, mas devem ser planejados de modo a reduzir interferência no descanso e fadiga.",
        "explicacaoCorreta": "Exercícios obrigatórios continuam necessários, mas devem ser planejados de modo a reduzir interferência no descanso e fadiga.",
        "revisaoAssunto": "A CTM trata fadiga como risco de segurança. Drill realista não significa drill mal planejado.",
        "memorizar2026": "Treinamento: minimizar interferência no descanso e não produzir fadiga.",
        "dicaMacete": "Diferencie exercício programado de emergência real.",
        "pegadinha": "A exceção ampla de emergência do comandante não transforma todo treinamento em emergência.",
        "fonte": "Decreto nº 10.671/2021 — CTM 2006, Norma A2.3, item 7.",
        "atualizacao2026": "Regra vigente na CTM 2006.",
        "enunciado": "Ao programar exercícios obrigatórios de emergência, a administração do navio deve compatibilizá-los com as regras de trabalho e descanso. Segundo a CTM, esses exercícios devem",
        "alternativas": [
            "minimizar a interferência com os períodos de descanso e não produzir fadiga.",
            "ser programados durante os períodos de descanso para reproduzir condições operacionais mais exigentes.",
            "ser dispensados quando houver qualquer possibilidade de interromper o repouso.",
            "ser dirigidos aos tripulantes que não estejam escalados para serviço no período subsequente.",
            "ter prioridade absoluta sobre qualquer limite de fadiga, ainda que não exista emergência real."
        ],
        "correta": 0,
        "analiseAlternativas": [
            "Correta. Exercícios obrigatórios continuam necessários, mas devem ser planejados de modo a reduzir interferência no descanso e fadiga.",
            "Incorreta. A CTM busca minimizar a interferência com o descanso.",
            "Incorreta. A norma não proíbe exercícios; orienta sua condução.",
            "Incorreta. Essa condição não é a regra da CTM.",
            "Incorreta. Treinamento não autoriza ignorar o princípio de prevenção da fadiga."
        ]
    },
    {
        "id": "TAA-2026-LMA-2.9-010",
        "disciplina": "Conhecimentos Específicos",
        "eixo": "Legislação Marítima e Ambiental",
        "topicoEdital": "2.9 Obrigações de trabalho e previdência social",
        "assunto": "Disponibilidade e descanso compensatório",
        "tipoOrigem": "inedita_farol",
        "origemInterna": "Inédita Farol 2026 — elaborada com base em fontes oficiais vigentes e calibrada ao padrão Fundação Cesgranrio. Taifeiro 2018 Q23 e Taifeiro 2023 Q15 foram usadas apenas como referência histórica de incidência e NÃO foram reproduzidas.",
        "comentario": "A disponibilidade não permite que interrupções do repouso sejam ignoradas.",
        "explicacaoCorreta": "A disponibilidade não permite que interrupções do repouso sejam ignoradas.",
        "revisaoAssunto": "Quando o período normal de descanso é interrompido por chamadas ao trabalho, a Norma A2.3 assegura descanso compensatório adequado.",
        "memorizar2026": "Descanso interrompido por chamada → compensação adequada.",
        "dicaMacete": "O foco é recuperar repouso, não apenas pagar horas.",
        "pegadinha": "A banca pode oferecer dinheiro como substituto automático do descanso.",
        "fonte": "Decreto nº 10.671/2021 — CTM 2006, Norma A2.3, item 8.",
        "atualizacao2026": "Regra vigente no texto promulgado da CTM.",
        "enunciado": "Um marítimo permanece de sobreaviso e tem seu período normal de descanso interrompido por chamadas efetivas ao trabalho. Pela CTM, após essa interrupção ele",
        "alternativas": [
            "perde o período interrompido, pois disponibilidade é incompatível com qualquer compensação.",
            "tem direito a período adequado de descanso compensatório.",
            "deve receber compensação financeira pela chamada, sem reposição específica do período interrompido.",
            "pode compensar o período de descanso no próximo desembarque, desde que a escala seja registrada.",
            "tem direito a descanso compensatório quando a chamada ultrapassa seis horas de duração."
        ],
        "correta": 1,
        "analiseAlternativas": [
            "Incorreta. A CTM prevê expressamente descanso compensatório.",
            "Correta. A disponibilidade não permite que interrupções do repouso sejam ignoradas.",
            "Incorreta. A norma trata de descanso compensatório, não apenas pagamento.",
            "Incorreta. A CTM não limita a compensação a esse momento.",
            "Incorreta. A norma não condiciona o direito a esse patamar."
        ]
    },
    {
        "id": "TAA-2026-LMA-2.9-011",
        "disciplina": "Conhecimentos Específicos",
        "eixo": "Legislação Marítima e Ambiental",
        "topicoEdital": "2.9 Obrigações de trabalho e previdência social",
        "assunto": "Quadro da escala de trabalho a bordo",
        "tipoOrigem": "inedita_farol",
        "origemInterna": "Inédita Farol 2026 — elaborada com base em fontes oficiais vigentes e calibrada ao padrão Fundação Cesgranrio. Taifeiro 2018 Q23 e Taifeiro 2023 Q15 foram usadas apenas como referência histórica de incidência e NÃO foram reproduzidas.",
        "comentario": "O quadro deve permitir visualizar a organização do serviço e os limites aplicáveis de trabalho ou descanso.",
        "explicacaoCorreta": "O quadro deve permitir visualizar a organização do serviço e os limites aplicáveis de trabalho ou descanso.",
        "revisaoAssunto": "A CTM exige que o quadro esteja em local de fácil acesso e traga escala no mar/porto e os limites legais ou coletivos pertinentes.",
        "memorizar2026": "Quadro da escala = serviço a bordo/porto + limites de trabalho/descanso.",
        "dicaMacete": "Se a alternativa fala só em nomes, CIR ou férias, ela não descreve a finalidade da escala.",
        "pegadinha": "A banca pode confundir documentos de tripulação com controle de fadiga.",
        "fonte": "Decreto nº 10.671/2021 — CTM 2006, Norma A2.3, item 10.",
        "atualizacao2026": "Conteúdo mínimo vigente na CTM.",
        "enunciado": "O quadro com a organização do trabalho que deve ficar disponível a bordo, conforme a CTM, deve apresentar",
        "alternativas": [
            "a escala de serviço a bordo e no porto, acompanhada do limite máximo de trabalho ou do mínimo de descanso aplicável à organização adotada.",
            "os nomes dos tripulantes e os postos designados, ficando os limites de jornada no acordo de emprego.",
            "os horários de serviço durante a navegação, enquanto as rotinas de porto constam de quadro separado.",
            "o total mensal de horas extras de cada tripulante, substituindo o registro diário de trabalho e descanso exigido pela convenção.",
            "o horário de início de cada quarto e a duração prevista, sendo o descanso apurado pelo registro diário."
        ],
        "correta": 0,
        "analiseAlternativas": [
            "Correta. O quadro deve permitir visualizar a organização do serviço e os limites aplicáveis de trabalho ou descanso.",
            "Incorreta. A escala deve trazer também os limites aplicáveis.",
            "Incorreta. A escala deve contemplar bordo e porto.",
            "Incorreta. Quadro e registro diário são instrumentos diferentes.",
            "Incorreta. A norma exige informação mais completa."
        ]
    },
    {
        "id": "TAA-2026-LMA-2.9-012",
        "disciplina": "Conhecimentos Específicos",
        "eixo": "Legislação Marítima e Ambiental",
        "topicoEdital": "2.9 Obrigações de trabalho e previdência social",
        "assunto": "Registro diário de trabalho e descanso",
        "tipoOrigem": "inedita_farol",
        "origemInterna": "Inédita Farol 2026 — elaborada com base em fontes oficiais vigentes e calibrada ao padrão Fundação Cesgranrio. Taifeiro 2018 Q23 e Taifeiro 2023 Q15 foram usadas apenas como referência histórica de incidência e NÃO foram reproduzidas.",
        "comentario": "O controle de jornada deve ser verificável também pelo próprio trabalhador.",
        "explicacaoCorreta": "O controle de jornada deve ser verificável também pelo próprio trabalhador.",
        "revisaoAssunto": "A Norma A2.3 exige manutenção de registro diário e entrega de cópia ao marítimo, rubricada pelas partes indicadas.",
        "memorizar2026": "Registro diário: marítimo recebe sua cópia rubricada.",
        "dicaMacete": "Não confunda quadro coletivo da escala com registro individual.",
        "pegadinha": "Digitalização não elimina a transparência exigida pela CTM.",
        "fonte": "Decreto nº 10.671/2021 — CTM 2006, Norma A2.3, item 12.",
        "atualizacao2026": "Regra vigente no texto promulgado da CTM.",
        "enunciado": "A empresa mantém os registros diários de trabalho e descanso, mas informa ao marítimo que ele não receberá cópia de seu próprio registro. À luz da CTM, essa conduta é",
        "alternativas": [
            "correta, porque os registros integram a documentação de controle do armador e ficam disponíveis para inspeção.",
            "correta se o quadro geral da escala estiver exposto em local visível.",
            "incorreta quando houver fiscalização trabalhista, ocasião em que o marítimo deve receber a documentação.",
            "correta quando o controle é eletrônico e fica armazenado por mais de um ano.",
            "incorreta, pois o marítimo deve receber cópia rubricada do próprio registro."
        ],
        "correta": 4,
        "analiseAlternativas": [
            "Incorreta. A CTM garante cópia ao marítimo.",
            "Incorreta. Quadro e registro individual são exigências distintas.",
            "Incorreta. A cópia é direito do marítimo, não obrigação condicionada à fiscalização.",
            "Incorreta. O meio eletrônico não elimina a obrigação de fornecer a cópia prevista.",
            "Correta. O controle de jornada deve ser verificável também pelo próprio trabalhador."
        ]
    },
    {
        "id": "TAA-2026-LMA-2.9-013",
        "disciplina": "Conhecimentos Específicos",
        "eixo": "Legislação Marítima e Ambiental",
        "topicoEdital": "2.9 Obrigações de trabalho e previdência social",
        "assunto": "Emergência — suspensão da escala pelo comandante",
        "tipoOrigem": "inedita_farol",
        "origemInterna": "Inédita Farol 2026 — elaborada com base em fontes oficiais vigentes e calibrada ao padrão Fundação Cesgranrio. Taifeiro 2018 Q23 e Taifeiro 2023 Q15 foram usadas apenas como referência histórica de incidência e NÃO foram reproduzidas.",
        "comentario": "Segurança imediata prevalece na emergência, mas a exceção não é permanente e gera dever de recompor o descanso.",
        "explicacaoCorreta": "Segurança imediata prevalece na emergência, mas a exceção não é permanente e gera dever de recompor o descanso.",
        "revisaoAssunto": "A Norma A2.3 equilibra resposta a emergência e controle de fadiga: trabalho necessário agora, descanso adequado depois.",
        "memorizar2026": "Emergência real: comandante pode suspender a escala; normalizou → descanso adequado.",
        "dicaMacete": "A exceção termina quando a situação normal é restabelecida.",
        "pegadinha": "Não transforme a autorização emergencial em carta branca para escalas cronicamente excessivas.",
        "fonte": "Decreto nº 10.671/2021 — CTM 2006, Norma A2.3, item 14.",
        "atualizacao2026": "Regra emergencial vigente na CTM.",
        "enunciado": "Surge uma emergência que exige mobilização imediata de tripulantes durante o período normal de descanso. A CTM admite que o comandante",
        "alternativas": [
            "exija o trabalho necessário à emergência e, depois, assegure descanso adequado aos envolvidos.",
            "mantenha rigidamente a escala, mesmo que isso impeça resposta à emergência.",
            "suspenda definitivamente os limites de descanso pelo restante da viagem.",
            "mobilize prioritariamente os oficiais, preservando o descanso dos demais tripulantes durante a emergência.",
            "compense a interrupção por pagamento adicional, registrando a alteração excepcional da escala."
        ],
        "correta": 0,
        "analiseAlternativas": [
            "Correta. Segurança imediata prevalece na emergência, mas a exceção não é permanente e gera dever de recompor o descanso.",
            "Incorreta. A CTM preserva o poder do comandante em emergência.",
            "Incorreta. A exceção dura até o restabelecimento da situação normal.",
            "Incorreta. A norma não cria essa exclusão geral.",
            "Incorreta. A CTM exige descanso adequado quando viável após a normalização."
        ]
    },
    {
        "id": "TAA-2026-LMA-2.9-014",
        "disciplina": "Conhecimentos Específicos",
        "eixo": "Legislação Marítima e Ambiental",
        "topicoEdital": "2.9 Obrigações de trabalho e previdência social",
        "assunto": "Férias anuais remuneradas",
        "tipoOrigem": "inedita_farol",
        "origemInterna": "Inédita Farol 2026 — elaborada com base em fontes oficiais vigentes e calibrada ao padrão Fundação Cesgranrio. Taifeiro 2018 Q23 e Taifeiro 2023 Q15 foram usadas apenas como referência histórica de incidência e NÃO foram reproduzidas.",
        "comentario": "A CTM adota como base mínima 2,5 dias civis por mês de emprego, sujeita ao regime nacional/coletivo aplicável.",
        "explicacaoCorreta": "A CTM adota como base mínima 2,5 dias civis por mês de emprego, sujeita ao regime nacional/coletivo aplicável.",
        "revisaoAssunto": "A cobrança tende a misturar dias úteis, dias civis, semanas e meses.",
        "memorizar2026": "Férias CTM: mínimo 2,5 dias civis por mês.",
        "dicaMacete": "2,5 por mês — não por semana e não necessariamente dias úteis.",
        "pegadinha": "Falta justificada não deve ser consumida como férias anuais.",
        "fonte": "Decreto nº 10.671/2021 — CTM 2006, Norma A2.4, item 2.",
        "atualizacao2026": "Regra mínima vigente no texto promulgado da CTM.",
        "enunciado": "Considerando o padrão mínimo da CTM para férias anuais remuneradas, assinale a alternativa correta.",
        "alternativas": [
            "1 dia civil por mês de emprego, incluindo faltas justificadas no total das férias.",
            "2 dias úteis por mês, descontando do período todas as licenças médicas.",
            "30 dias fixos a cada três meses de emprego, independentemente da legislação ou acordo aplicável.",
            "2,5 dias úteis por semana de emprego.",
            "no mínimo 2,5 dias civis por mês de emprego; faltas justificadas não integram as férias anuais."
        ],
        "correta": 4,
        "analiseAlternativas": [
            "Incorreta. O mínimo da CTM é 2,5 dias civis e faltas justificadas não integram as férias.",
            "Incorreta. A norma fala em 2,5 dias civis e não traz essa regra geral.",
            "Incorreta. Esse não é o método mínimo previsto na CTM.",
            "Incorreta. A unidade é mês de emprego e dias civis.",
            "Correta. A CTM adota como base mínima 2,5 dias civis por mês de emprego, sujeita ao regime nacional/coletivo aplicável."
        ]
    },
    {
        "id": "TAA-2026-LMA-2.9-015",
        "disciplina": "Conhecimentos Específicos",
        "eixo": "Legislação Marítima e Ambiental",
        "topicoEdital": "2.9 Obrigações de trabalho e previdência social",
        "assunto": "Repatriação — hipóteses",
        "tipoOrigem": "inedita_farol",
        "origemInterna": "Inédita Farol 2026 — elaborada com base em fontes oficiais vigentes e calibrada ao padrão Fundação Cesgranrio. Taifeiro 2018 Q23 e Taifeiro 2023 Q15 foram usadas apenas como referência histórica de incidência e NÃO foram reproduzidas.",
        "comentario": "A expiração do contrato enquanto o marítimo está no estrangeiro é hipótese expressa de repatriação.",
        "explicacaoCorreta": "A expiração do contrato enquanto o marítimo está no estrangeiro é hipótese expressa de repatriação.",
        "revisaoAssunto": "A CTM também contempla término pelo armador, término justificado pelo marítimo e incapacidade de continuar desempenhando as tarefas em certas circunstâncias.",
        "memorizar2026": "Contrato expirou no exterior → repatriação é hipótese protegida.",
        "dicaMacete": "Repatriação não é prêmio por acidente; é proteção contratual e humana mais ampla.",
        "pegadinha": "A banca pode inverter a lógica e exigir tempo mínimo de contrato inexistente.",
        "fonte": "Decreto nº 10.671/2021 — CTM 2006, Norma A2.5.1, item 1.",
        "atualizacao2026": "Regra vigente no texto promulgado da CTM.",
        "enunciado": "O acordo de emprego de um marítimo expira enquanto ele se encontra em porto estrangeiro, longe do local para o qual tem direito de retornar. Essa situação",
        "alternativas": [
            "não gera repatriação porque o término do contrato ocorreu regularmente.",
            "gera repatriação quando o término do contrato estiver associado a incapacidade que impeça a continuidade do serviço.",
            "assegura hospedagem no porto de desembarque, ficando o transporte de retorno a cargo do trabalhador.",
            "integra as hipóteses em que deve ser assegurado o direito à repatriação.",
            "depende de o contrato ter duração mínima de doze meses."
        ],
        "correta": 3,
        "analiseAlternativas": [
            "Incorreta. O término do contrato no exterior é hipótese expressa.",
            "Incorreta. A incapacidade é outra hipótese; não é a única.",
            "Incorreta. A repatriação é, em regra, livre de despesas nas condições da CTM.",
            "Correta. A expiração do contrato enquanto o marítimo está no estrangeiro é hipótese expressa de repatriação.",
            "Incorreta. A norma não cria esse requisito para a hipótese descrita."
        ]
    },
    {
        "id": "TAA-2026-LMA-2.9-016",
        "disciplina": "Conhecimentos Específicos",
        "eixo": "Legislação Marítima e Ambiental",
        "topicoEdital": "2.9 Obrigações de trabalho e previdência social",
        "assunto": "Repatriação — custos e descontos",
        "tipoOrigem": "inedita_farol",
        "origemInterna": "Inédita Farol 2026 — elaborada com base em fontes oficiais vigentes e calibrada ao padrão Fundação Cesgranrio. Taifeiro 2018 Q23 e Taifeiro 2023 Q15 foram usadas apenas como referência histórica de incidência e NÃO foram reproduzidas.",
        "comentario": "A proteção contra antecipação e descontos evita transferir rotineiramente ao marítimo o custo da repatriação.",
        "explicacaoCorreta": "A proteção contra antecipação e descontos evita transferir rotineiramente ao marítimo o custo da repatriação.",
        "revisaoAssunto": "A Norma A2.5.1 admite ressalva ligada a sério descumprimento de obrigações contratuais, conforme legislação, medidas ou acordos aplicáveis.",
        "memorizar2026": "Repatriação: custo não é antecipado pelo marítimo como regra.",
        "dicaMacete": "Desconto salarial para repatriação não é regra automática.",
        "pegadinha": "A exceção por sério descumprimento não autoriza cobrança genérica prevista unilateralmente.",
        "fonte": "Decreto nº 10.671/2021 — CTM 2006, Norma A2.5.1, item 3.",
        "atualizacao2026": "Regra vigente no texto promulgado da CTM.",
        "enunciado": "Quanto aos custos da repatriação a que o marítimo faz jus nos termos da CTM, assinale a alternativa correta.",
        "alternativas": [
            "o armador pode exigir depósito prévio integral se o marítimo assinar o acordo de emprego antes de embarcar e reconhecer a dívida futura.",
            "o armador pode descontar os custos do salário final quando o contrato terminar no exterior, independentemente de apuração de falta grave.",
            "o armador não pode, como regra, exigir pagamento antecipado nem descontar do salário do marítimo os custos da repatriação a que ele tenha direito.",
            "o marítimo deve antecipar metade do custo e a companhia suportar a outra metade, salvo se a repatriação ocorrer por motivo de saúde.",
            "o custo pode ser transferido ao marítimo quando a passagem escolhida superar o valor da rota de retorno inicialmente prevista."
        ],
        "correta": 2,
        "analiseAlternativas": [
            "Incorreta. A regra geral veda adiantamento dessa natureza.",
            "Incorreta. A CTM não autoriza desconto geral dessa forma.",
            "Correta. A proteção contra antecipação e descontos evita transferir rotineiramente ao marítimo o custo da repatriação.",
            "Incorreta. Não é o modelo da CTM.",
            "Incorreta. A variação de custo não cria essa autorização."
        ]
    },
    {
        "id": "TAA-2026-LMA-2.9-017",
        "disciplina": "Conhecimentos Específicos",
        "eixo": "Legislação Marítima e Ambiental",
        "topicoEdital": "2.9 Obrigações de trabalho e previdência social",
        "assunto": "Acidente do trabalho — conceito legal",
        "tipoOrigem": "inedita_farol",
        "origemInterna": "Inédita Farol 2026 — elaborada com base em fontes oficiais vigentes e calibrada ao padrão Fundação Cesgranrio. Taifeiro 2018 Q23 e Taifeiro 2023 Q15 foram usadas apenas como referência histórica de incidência e NÃO foram reproduzidas.",
        "comentario": "O art. 19 abrange lesão corporal ou perturbação funcional que cause morte ou perda/redução permanente ou temporária da capacidade.",
        "explicacaoCorreta": "O art. 19 abrange lesão corporal ou perturbação funcional que cause morte ou perda/redução permanente ou temporária da capacidade.",
        "revisaoAssunto": "A palavra 'temporária' é uma pegadinha importante: não é necessário que a incapacidade seja definitiva.",
        "memorizar2026": "Acidente do trabalho pode gerar redução temporária ou permanente.",
        "dicaMacete": "Procure três elementos: trabalho + dano/perturbação + repercussão sobre vida/capacidade.",
        "pegadinha": "Não confunda acidente previdenciário com 'fato da navegação' da legislação marítima.",
        "fonte": "Lei nº 8.213/1991, art. 19.",
        "atualizacao2026": "Texto legal vigente consultado na versão consolidada do Planalto.",
        "enunciado": "Durante uma faina, um Taifeiro sofre lesão corporal diretamente relacionada ao trabalho e fica temporariamente incapaz de exercer suas atividades. Para a Lei nº 8.213/1991, o evento caracteriza",
        "alternativas": [
            "doença profissional decorrente das condições em que a faina foi executada.",
            "evento sem enquadramento como acidente do trabalho, porque a lei exigiria incapacidade permanente ou morte para reconhecer a natureza acidentária.",
            "acidente pessoal sem relação ocupacional.",
            "acidente do trabalho, pois houve lesão decorrente do exercício do trabalho a serviço da empresa com redução temporária da capacidade.",
            "fato da navegação sujeito ao regime marítimo, sem enquadramento como acidente do trabalho."
        ],
        "correta": 3,
        "analiseAlternativas": [
            "Incorreta. Lesão súbita decorrente da faina não é automaticamente doença profissional.",
            "Incorreta. A lei inclui redução temporária da capacidade.",
            "Incorreta. O enunciado estabelece nexo com o trabalho.",
            "Correta. O art. 19 abrange lesão corporal ou perturbação funcional que cause morte ou perda/redução permanente ou temporária da capacidade.",
            "Incorreta. Um evento pode ter repercussões em esferas diferentes; o conceito previdenciário está presente."
        ]
    },
    {
        "id": "TAA-2026-LMA-2.9-018",
        "disciplina": "Conhecimentos Específicos",
        "eixo": "Legislação Marítima e Ambiental",
        "topicoEdital": "2.9 Obrigações de trabalho e previdência social",
        "assunto": "Dever empresarial — proteção e informação de riscos",
        "tipoOrigem": "inedita_farol",
        "origemInterna": "Inédita Farol 2026 — questão revisada para cobrança realista no padrão Fundação Cesgranrio, com base em fonte oficial vigente.",
        "comentario": "A Lei nº 8.213/1991 impõe à empresa responsabilidade pela adoção e uso das medidas de proteção e pelo fornecimento de informações detalhadas sobre riscos.",
        "explicacaoCorreta": "A Lei nº 8.213/1991 impõe à empresa responsabilidade pela adoção e uso das medidas de proteção e pelo fornecimento de informações detalhadas sobre riscos.",
        "revisaoAssunto": "Esta questão funde dois deveres que antes estavam artificialmente separados no banco.",
        "memorizar2026": "Proteção + informação são deveres empresariais complementares.",
        "dicaMacete": "Não aceite alternativa em que EPI vira transferência integral de responsabilidade.",
        "pegadinha": "‘Trabalhador experiente’ não significa trabalhador dispensado de informação.",
        "fonte": "Lei nº 8.213/1991, art. 19, §§ 1º a 3º.",
        "atualizacao2026": "Texto legal vigente consultado na versão consolidada do Planalto.",
        "enunciado": "Uma empresa afirma que, depois de fornecer EPI ao trabalhador, deixa de ter responsabilidade por medidas coletivas de proteção e por informar detalhadamente os riscos da operação. Essa afirmação é",
        "alternativas": [
            "incorreta: a empresa continua responsável por medidas coletivas e individuais de proteção e por informar de forma pormenorizada os riscos da operação.",
            "correta, porque o fornecimento de EPI adequado transfere ao empregado a responsabilidade pelas demais medidas preventivas e pelo reconhecimento dos riscos inerentes à tarefa.",
            "correta se o trabalhador já tiver executado a mesma tarefa anteriormente e possuir experiência suficiente para reconhecer os perigos sem orientação.",
            "incorreta porque a obrigação de informar riscos se limita à identificação dos produtos e equipamentos empregados na tarefa.",
            "incorreta porque as medidas coletivas substituem as medidas individuais quando ambas se destinam ao mesmo risco."
        ],
        "correta": 0,
        "analiseAlternativas": [
            "Correta. A Lei nº 8.213/1991 impõe à empresa responsabilidade pela adoção e uso das medidas de proteção e pelo fornecimento de informações detalhadas sobre riscos.",
            "Incorreta. EPI não elimina os deveres empresariais.",
            "Incorreta. Experiência não elimina o dever de informar.",
            "Incorreta. Esses dados não substituem informação de risco.",
            "Incorreta. A lei menciona proteção coletiva e individual."
        ]
    },
    {
        "id": "TAA-2026-LMA-2.9-020",
        "disciplina": "Conhecimentos Específicos",
        "eixo": "Legislação Marítima e Ambiental",
        "topicoEdital": "2.9 Obrigações de trabalho e previdência social",
        "assunto": "Doença profissional x doença do trabalho",
        "tipoOrigem": "inedita_farol",
        "origemInterna": "Inédita Farol 2026 — questão revisada para cobrança realista no padrão Fundação Cesgranrio, com base em fonte oficial vigente.",
        "comentario": "A lei diferencia a doença vinculada à própria atividade profissional daquela relacionada às condições especiais do trabalho.",
        "explicacaoCorreta": "A lei diferencia a doença vinculada à própria atividade profissional daquela relacionada às condições especiais do trabalho.",
        "revisaoAssunto": "Profissional = produzida/desencadeada pelo exercício peculiar à atividade; do trabalho = adquirida/desencadeada pelas condições especiais em que o trabalho é realizado.",
        "memorizar2026": "Profissão → doença profissional; condições → doença do trabalho.",
        "dicaMacete": "Não trate as duas expressões como sinônimos perfeitos.",
        "pegadinha": "A diferença conceitual pode aparecer em alternativas quase idênticas.",
        "fonte": "Lei nº 8.213/1991, art. 20, I e II.",
        "atualizacao2026": "",
        "enunciado": "Considere: I — enfermidade produzida ou desencadeada pelo exercício peculiar a determinada atividade; II — enfermidade adquirida ou desencadeada em função de condições especiais em que o trabalho é realizado. Nos termos da Lei nº 8.213/1991, I e II correspondem, respectivamente, a",
        "alternativas": [
            "doença do trabalho e doença profissional.",
            "acidente típico e doença profissional.",
            "doença profissional e doença do trabalho.",
            "doença comum e acidente de trajeto.",
            "doença endêmica e concausa."
        ],
        "correta": 2,
        "analiseAlternativas": [
            "Incorreta. Os conceitos estão invertidos.",
            "Incorreta. O primeiro caso é doença profissional.",
            "Correta. A lei diferencia a doença vinculada à própria atividade profissional daquela relacionada às condições especiais do trabalho.",
            "Incorreta. Não correspondem às descrições.",
            "Incorreta. São institutos diferentes."
        ]
    },
    {
        "id": "TAA-2026-LMA-2.9-021",
        "disciplina": "Conhecimentos Específicos",
        "eixo": "Legislação Marítima e Ambiental",
        "topicoEdital": "2.9 Obrigações de trabalho e previdência social",
        "assunto": "Doença endêmica e doença não listada — exceções",
        "tipoOrigem": "inedita_farol",
        "origemInterna": "Inédita Farol 2026 — questão revisada para cobrança realista no padrão Fundação Cesgranrio, com base em fonte oficial vigente.",
        "comentario": "A Lei nº 8.213/1991 traz exclusões e também exceções; a banca pode cobrar justamente o detalhe que impede respostas absolutas.",
        "explicacaoCorreta": "A Lei nº 8.213/1991 traz exclusões e também exceções; a banca pode cobrar justamente o detalhe que impede respostas absolutas.",
        "revisaoAssunto": "Endemia pode ser reconhecida se a exposição decorrer do trabalho. Doença não listada pode ser reconhecida excepcionalmente quando houver relação direta com condições especiais do trabalho.",
        "memorizar2026": "Regra geral tem exceção quando o nexo ocupacional é demonstrado.",
        "dicaMacete": "Palavras como 'nunca' e 'qualquer' costumam esconder a exceção legal.",
        "pegadinha": "Estar empregado quando a doença surge não prova, sozinho, o nexo.",
        "fonte": "Lei nº 8.213/1991, art. 20, § 1º, d, e § 2º.",
        "atualizacao2026": "",
        "enunciado": "A Lei nº 8.213/1991 estabelece exclusões no conceito de doença do trabalho, mas admite situações excepcionais. Qual alternativa apresenta uma dessas hipóteses que pode receber enquadramento ocupacional quando demonstrado o nexo exigido pela lei?",
        "alternativas": [
            "qualquer doença degenerativa surgida durante o vínculo, ainda que não haja relação demonstrável com o trabalho ou com as condições especiais da atividade.",
            "doença inerente ao grupo etário do empregado, mesmo sem exposição ocupacional diferenciada ou agravamento ligado às condições de trabalho.",
            "a endemia decorrente de exposição determinada pelo trabalho ou a doença não listada quando houver relação direta com as condições especiais da atividade.",
            "qualquer enfermidade não listada, desde que o empregado pertença a categoria aquaviária e possua tempo de embarque registrado em CIR.",
            "doença endêmica comum à região, mesmo quando o trabalho não criou nem aumentou a exposição e não houve contato determinado pela atividade."
        ],
        "correta": 2,
        "analiseAlternativas": [
            "Incorreta. A simultaneidade temporal não basta.",
            "Incorreta. A lei a exclui em regra.",
            "Correta. A Lei nº 8.213/1991 traz exclusões e também exceções; a banca pode cobrar justamente o detalhe que impede respostas absolutas.",
            "Incorreta. Categoria e CIR não substituem nexo ocupacional.",
            "Incorreta. A exceção depende da exposição determinada pelo trabalho."
        ]
    },
    {
        "id": "TAA-2026-LMA-2.9-023",
        "disciplina": "Conhecimentos Específicos",
        "eixo": "Legislação Marítima e Ambiental",
        "topicoEdital": "2.9 Obrigações de trabalho e previdência social",
        "assunto": "Concausa",
        "tipoOrigem": "inedita_farol",
        "origemInterna": "Inédita Farol 2026 — elaborada com base em fontes oficiais vigentes e calibrada ao padrão Fundação Cesgranrio. Taifeiro 2018 Q23 e Taifeiro 2023 Q15 foram usadas apenas como referência histórica de incidência e NÃO foram reproduzidas.",
        "comentario": "A legislação admite concausa: o trabalho pode contribuir diretamente sem ser a causa exclusiva.",
        "explicacaoCorreta": "A legislação admite concausa: o trabalho pode contribuir diretamente sem ser a causa exclusiva.",
        "revisaoAssunto": "Essa é uma distinção clássica de prova entre causalidade exclusiva e contribuição relevante.",
        "memorizar2026": "Trabalho não precisa ser a única causa.",
        "dicaMacete": "Se a alternativa exigir causa exclusiva, está mais restritiva que a lei.",
        "pegadinha": "Concausa não significa qualquer coincidência; precisa haver contribuição direta prevista em lei.",
        "fonte": "Lei nº 8.213/1991, art. 21, I.",
        "atualizacao2026": "Regra vigente consultada no Planalto.",
        "enunciado": "Um trabalhador já possuía condição anterior, mas a atividade exercida contribuiu diretamente para o agravamento e para a incapacidade resultante. À luz da Lei nº 8.213/1991, o evento",
        "alternativas": [
            "não pode ser acidente do trabalho porque a atividade profissional precisa ser a causa única e exclusiva da incapacidade para existir nexo acidentário.",
            "pode ser equiparado a acidente do trabalho, pois a contribuição do trabalho para a incapacidade pode caracterizar concausa mesmo sem ser causa única.",
            "só pode ser reconhecido se a causa ligada ao trabalho tiver contribuído com mais da metade da incapacidade apurada pela perícia.",
            "não pode ser acidente quando existe doença ou condição anterior que também tenha contribuído para o resultado incapacitante.",
            "seria equiparado se o fator não ocupacional surgisse depois do evento relacionado ao serviço, sem condição anterior relevante."
        ],
        "correta": 1,
        "analiseAlternativas": [
            "Incorreta. A lei admite concausa.",
            "Correta. A legislação admite concausa: o trabalho pode contribuir diretamente sem ser a causa exclusiva.",
            "Incorreta. A lei não estabelece esse percentual.",
            "Incorreta. A concausa admite contribuição de fatores diversos.",
            "Incorreta. Essa limitação não corresponde à regra legal."
        ]
    },
    {
        "id": "TAA-2026-LMA-2.9-024",
        "disciplina": "Conhecimentos Específicos",
        "eixo": "Legislação Marítima e Ambiental",
        "topicoEdital": "2.9 Obrigações de trabalho e previdência social",
        "assunto": "Acidente equiparado — atos de terceiros e colegas",
        "tipoOrigem": "inedita_farol",
        "origemInterna": "Inédita Farol 2026 — questão revisada para cobrança realista no padrão Fundação Cesgranrio, com base em fonte oficial vigente.",
        "comentario": "A Lei nº 8.213/1991 lista diversas situações equiparadas no local e horário de trabalho.",
        "explicacaoCorreta": "A Lei nº 8.213/1991 lista diversas situações equiparadas no local e horário de trabalho.",
        "revisaoAssunto": "Unir as hipóteses em uma questão de assertivas é mais próximo da banca do que fazer um flashcard para cada inciso.",
        "memorizar2026": "Equiparação não se limita a culpa direta do empregador.",
        "dicaMacete": "Leia quem praticou o ato e em que contexto ocorreu.",
        "pegadinha": "A existência de terceiro não elimina automaticamente o nexo legal.",
        "fonte": "Lei nº 8.213/1991, art. 21, II.",
        "atualizacao2026": "",
        "enunciado": "No local e no horário de trabalho ocorrem três eventos: I — lesão causada por sabotagem praticada por terceiro; II — lesão decorrente de imprudência de um colega de trabalho; III — agressão praticada por pessoa privada do uso da razão. Considerando as hipóteses equiparadas da Lei nº 8.213/1991, assinale a alternativa correta.",
        "alternativas": [
            "o evento I pode ser equiparado, enquanto atos de colegas ou de pessoas privadas de discernimento exigem enquadramento diverso.",
            "os três eventos podem ser equiparados a acidente do trabalho, porque a lei contempla diferentes atos de terceiros e colegas no local e horário de trabalho.",
            "o evento II pode ser equiparado porque o agente causador mantém vínculo com o ambiente de trabalho da vítima.",
            "os eventos I e III não se equiparam a acidente do trabalho porque foram praticados por terceiros sem vínculo empregatício com a vítima ou com a empresa.",
            "nenhum dos três pode ser equiparado se não houver defeito em máquina, ferramenta ou instalação pertencente à empregadora."
        ],
        "correta": 1,
        "analiseAlternativas": [
            "Incorreta. A lei contempla outras hipóteses.",
            "Correta. A Lei nº 8.213/1991 lista diversas situações equiparadas no local e horário de trabalho.",
            "Incorreta. Não exige isso.",
            "Incorreta. A lei prevê atos de terceiros em hipóteses específicas.",
            "Incorreta. Defeito de equipamento não é requisito geral."
        ]
    },
    {
        "id": "TAA-2026-LMA-2.9-026",
        "disciplina": "Conhecimentos Específicos",
        "eixo": "Legislação Marítima e Ambiental",
        "topicoEdital": "2.9 Obrigações de trabalho e previdência social",
        "assunto": "Contaminação acidental",
        "tipoOrigem": "inedita_farol",
        "origemInterna": "Inédita Farol 2026 — elaborada com base em fontes oficiais vigentes e calibrada ao padrão Fundação Cesgranrio. Taifeiro 2018 Q23 e Taifeiro 2023 Q15 foram usadas apenas como referência histórica de incidência e NÃO foram reproduzidas.",
        "comentario": "A legislação equipara a doença proveniente de contaminação acidental do empregado no exercício da atividade.",
        "explicacaoCorreta": "A legislação equipara a doença proveniente de contaminação acidental do empregado no exercício da atividade.",
        "revisaoAssunto": "O enunciado pode envolver produto de limpeza, agente biológico ou outra substância, desde que presentes os elementos legais.",
        "memorizar2026": "Contaminação acidental no exercício da atividade = hipótese legal.",
        "dicaMacete": "Não misture classificação de carga perigosa com conceito previdenciário de acidente.",
        "pegadinha": "A recuperação posterior não apaga o evento acidentário.",
        "fonte": "Lei nº 8.213/1991, art. 21, III.",
        "atualizacao2026": "Regra vigente consultada no Planalto.",
        "enunciado": "Um Taifeiro sofre contaminação acidental durante a manipulação de substância empregada no serviço. Para a Lei nº 8.213/1991, a doença proveniente dessa contaminação",
        "alternativas": [
            "é doença comum quando a contaminação não produz lesão traumática imediata.",
            "só tem natureza ocupacional se atingir simultaneamente três ou mais trabalhadores.",
            "é equiparada a acidente do trabalho, quando ocorre no exercício da atividade.",
            "é considerada acidente quando a substância estiver enquadrada como carga perigosa no transporte marítimo.",
            "não pode ser acidente se a vítima receber tratamento e se recuperar totalmente."
        ],
        "correta": 2,
        "analiseAlternativas": [
            "Incorreta. A lei prevê expressamente contaminação acidental.",
            "Incorreta. Não existe esse requisito numérico.",
            "Correta. A legislação equipara a doença proveniente de contaminação acidental do empregado no exercício da atividade.",
            "Incorreta. O enquadramento previdenciário não depende dessa classificação marítima específica.",
            "Incorreta. Recuperação não elimina a natureza do evento."
        ]
    },
    {
        "id": "TAA-2026-LMA-2.9-027",
        "disciplina": "Conhecimentos Específicos",
        "eixo": "Legislação Marítima e Ambiental",
        "topicoEdital": "2.9 Obrigações de trabalho e previdência social",
        "assunto": "Acidente fora do local e horário",
        "tipoOrigem": "inedita_farol",
        "origemInterna": "Inédita Farol 2026 — elaborada com base em fontes oficiais vigentes e calibrada ao padrão Fundação Cesgranrio. Taifeiro 2018 Q23 e Taifeiro 2023 Q15 foram usadas apenas como referência histórica de incidência e NÃO foram reproduzidas.",
        "comentario": "A lei rompe a ideia simplista de que acidente do trabalho só ocorre dentro do estabelecimento.",
        "explicacaoCorreta": "A lei rompe a ideia simplista de que acidente do trabalho só ocorre dentro do estabelecimento.",
        "revisaoAssunto": "Também há hipóteses de serviço espontâneo para evitar prejuízo/proporcionar proveito e viagem a serviço da empresa.",
        "memorizar2026": "Ordem da empresa fora do local/horário pode manter o nexo acidentário.",
        "dicaMacete": "Pergunte se o trabalhador estava agindo sob autoridade ou interesse direto da empresa.",
        "pegadinha": "Local e horário são importantes, mas não são critérios absolutos.",
        "fonte": "Lei nº 8.213/1991, art. 21, IV, alínea a.",
        "atualizacao2026": "Regra vigente consultada no Planalto.",
        "enunciado": "Fora do estabelecimento e do horário habitual, um empregado sofre acidente enquanto executa ordem expressa da empresa. Para fins previdenciários, esse evento",
        "alternativas": [
            "não pode ter natureza acidentária porque ocorreu fora da embarcação.",
            "pode ser acidente do trabalho por ter ocorrido na execução de ordem da empresa.",
            "só pode ser reconhecido se o deslocamento ocorrer em veículo da empresa.",
            "é acidente comum porque o contrato de trabalho não produz efeitos fora da jornada normal.",
            "depende de o serviço durar mais de duas horas."
        ],
        "correta": 1,
        "analiseAlternativas": [
            "Incorreta. A lei prevê hipóteses fora do local de trabalho.",
            "Correta. A lei rompe a ideia simplista de que acidente do trabalho só ocorre dentro do estabelecimento.",
            "Incorreta. A hipótese da alínea a não contém essa limitação.",
            "Incorreta. A lei cria equiparação específica.",
            "Incorreta. Não há esse requisito temporal."
        ]
    },
    {
        "id": "TAA-2026-LMA-2.9-028",
        "disciplina": "Conhecimentos Específicos",
        "eixo": "Legislação Marítima e Ambiental",
        "topicoEdital": "2.9 Obrigações de trabalho e previdência social",
        "assunto": "Comunicação de Acidente do Trabalho — CAT",
        "tipoOrigem": "inedita_farol",
        "origemInterna": "Inédita Farol 2026 — elaborada com base em fontes oficiais vigentes e calibrada ao padrão Fundação Cesgranrio. Taifeiro 2018 Q23 e Taifeiro 2023 Q15 foram usadas apenas como referência histórica de incidência e NÃO foram reproduzidas.",
        "comentario": "A CAT não deve ficar condicionada ao tempo de afastamento nem à vontade da vítima.",
        "explicacaoCorreta": "A CAT não deve ficar condicionada ao tempo de afastamento nem à vontade da vítima.",
        "revisaoAssunto": "Na falta de comunicação pela empresa, podem formalizá-la o próprio acidentado, dependentes, sindicato competente, médico assistente ou autoridade pública; isso não elimina a responsabilidade da empresa pelo descumprimento.",
        "memorizar2026": "CAT pela empresa: até o 1º dia útil seguinte; morte: imediato.",
        "dicaMacete": "Não espere saber quantos dias haverá de afastamento para lembrar do prazo legal.",
        "pegadinha": "A banca pode misturar prazo da CAT com regras de benefício por incapacidade.",
        "fonte": "Lei nº 8.213/1991, art. 22 e §§ 1º a 3º.",
        "atualizacao2026": "Prazo legal vigente consultado no Planalto.",
        "enunciado": "A empresa toma conhecimento de acidente do trabalho ocorrido com um empregado. De acordo com a Lei nº 8.213/1991, qual é o prazo geral para emissão da CAT e qual providência adicional existe em caso de morte?",
        "alternativas": [
            "até o fim do mês em que ocorreu o acidente e, em caso de morte, no prazo de vinte e quatro horas após o registro do óbito.",
            "até o primeiro dia útil seguinte ao da ocorrência e, havendo morte, a comunicação deve ser feita de imediato à autoridade competente.",
            "em até cinco dias úteis após o afastamento e, se houver morte, até o primeiro dia útil seguinte ao evento.",
            "a comunicação é exigida após a confirmação de incapacidade que gere afastamento previdenciário.",
            "o prazo pode ser definido em procedimento interno da empresa, desde que o trabalhador receba cópia do registro e seja informado formalmente sobre o evento."
        ],
        "correta": 1,
        "analiseAlternativas": [
            "Incorreta. Os prazos não são esses.",
            "Correta. A CAT não deve ficar condicionada ao tempo de afastamento nem à vontade da vítima.",
            "Incorreta. A comunicação deve ocorrer antes.",
            "Incorreta. A obrigação não depende desse filtro.",
            "Incorreta. Norma interna não substitui o prazo legal."
        ]
    },
    {
        "id": "TAA-2026-LMA-2.9-029",
        "disciplina": "Conhecimentos Específicos",
        "eixo": "Legislação Marítima e Ambiental",
        "topicoEdital": "2.9 Obrigações de trabalho e previdência social",
        "assunto": "Acidente do trabalho — descanso/refeição a bordo",
        "tipoOrigem": "inedita_farol",
        "origemInterna": "Inédita Farol 2026 — tema calibrado pela Taifeiro 2023 Q15, sem reprodução do caso original.",
        "comentario": "A Lei nº 8.213/1991 considera o empregado em exercício do trabalho durante refeição, descanso ou satisfação de necessidades fisiológicas no local de trabalho ou durante este.",
        "explicacaoCorreta": "A Lei nº 8.213/1991 considera o empregado em exercício do trabalho durante refeição, descanso ou satisfação de necessidades fisiológicas no local de trabalho ou durante este.",
        "revisaoAssunto": "É uma forma de cobrança comprovada pela Cesgranrio em Taifeiro 2023, mas o caso aqui é novo e não reproduz a prova anterior.",
        "memorizar2026": "Descanso/refeição no local de trabalho não significa automaticamente 'fora do trabalho'.",
        "dicaMacete": "Embarcado, cuidado com a conclusão automática de que intervalo rompe o nexo.",
        "pegadinha": "A questão histórica usou banheiro/alojamento; aqui usamos outro cenário para treinar a regra, não memorizar a resposta antiga.",
        "fonte": "Lei nº 8.213/1991, art. 21, § 1º; calibragem: Transpetro/Cesgranrio Taifeiro 2023, Q15.",
        "atualizacao2026": "Regra do art. 21, § 1º, da Lei nº 8.213/1991 conferida para o Banco 2026.",
        "enunciado": "Durante período de descanso a bordo, no próprio local de trabalho, um Taifeiro sofre acidente ao se deslocar para satisfazer necessidade fisiológica. Considerando a Lei nº 8.213/1991, o fato",
        "alternativas": [
            "não caracteriza acidente do trabalho porque o intervalo para refeição ou descanso suspende o exercício das atividades laborais.",
            "pode ser reconhecido se o Taifeiro estiver cumprindo ordem direta relacionada à atividade no momento do evento.",
            "não pode ser acidente porque o refeitório não corresponde ao posto habitual de trabalho do Taifeiro e fica fora do setor onde exerce suas tarefas.",
            "pode ser reconhecido quando a lesão produzir incapacidade permanente para o trabalho habitual.",
            "pode caracterizar acidente do trabalho, pois refeição e descanso no local de trabalho não retiram, por si sós, o empregado do exercício do trabalho."
        ],
        "correta": 4,
        "analiseAlternativas": [
            "Incorreta. A lei prevê regra expressa em sentido contrário.",
            "Incorreta. Essa condição não é exigida pela regra sobre refeição/descanso.",
            "Incorreta. A regra se refere ao local de trabalho, não apenas ao posto habitual.",
            "Incorreta. A redução pode ser temporária ou permanente.",
            "Correta. A Lei nº 8.213/1991 considera o empregado em exercício do trabalho durante refeição, descanso ou satisfação de necessidades fisiológicas no local de trabalho ou durante este."
        ]
    },
    {
        "id": "TAA-2026-LMA-2.9-030",
        "disciplina": "Conhecimentos Específicos",
        "eixo": "Legislação Marítima e Ambiental",
        "topicoEdital": "2.9 Obrigações de trabalho e previdência social",
        "assunto": "Aposentadoria especial — categoria profissional",
        "tipoOrigem": "inedita_farol",
        "origemInterna": "Inédita Farol 2026 — elaborada com base em fontes oficiais vigentes e calibrada ao padrão Fundação Cesgranrio. Taifeiro 2018 Q23 e Taifeiro 2023 Q15 foram usadas apenas como referência histórica de incidência e NÃO foram reproduzidas.",
        "comentario": "A aposentadoria especial é ligada à exposição nociva, não a um rótulo profissional genérico.",
        "explicacaoCorreta": "A aposentadoria especial é ligada à exposição nociva, não a um rótulo profissional genérico.",
        "revisaoAssunto": "O Decreto nº 3.048/1999 exige comprovação de efetiva exposição aos agentes químicos, físicos, biológicos ou associação prejudicial, nas condições regulamentares.",
        "memorizar2026": "Aquaviário ≠ aposentadoria especial automática.",
        "dicaMacete": "Pergunte sempre: qual agente, qual exposição, qual prova?",
        "pegadinha": "A banca pode explorar a antiga lógica de enquadramento por categoria para induzir erro.",
        "fonte": "Lei nº 8.213/1991, arts. 57 e 58; Decreto nº 3.048/1999, arts. 64 e 68.",
        "atualizacao2026": "Em 2026 permanece necessária a comprovação da efetiva exposição; a ADI 6309 não criou benefício automático por categoria.",
        "enunciado": "Um marítimo sustenta que o simples fato de pertencer à categoria de Taifeiro garante aposentadoria especial, independentemente de comprovação das condições de exposição. Essa afirmação é",
        "alternativas": [
            "incorreta: a categoria não basta; é preciso comprovar efetiva exposição nociva e os demais requisitos.",
            "correta, pois a inscrição como aquaviário substitui qualquer comprovação ambiental.",
            "correta para o aquaviário que mantenha CIR válida e tempo de embarque regularmente registrado.",
            "incorreta porque a EC nº 103/2019 substituiu a aposentadoria especial por outra modalidade de benefício.",
            "correta para empregado de empresa de navegação que exerça atividade embarcada de forma habitual."
        ],
        "correta": 0,
        "analiseAlternativas": [
            "Correta. A aposentadoria especial é ligada à exposição nociva, não a um rótulo profissional genérico.",
            "Incorreta. A categoria, por si só, não substitui prova de exposição.",
            "Incorreta. Validade da CIR não cria direito automático à aposentadoria especial.",
            "Incorreta. O benefício não foi extinto.",
            "Incorreta. A efetiva exposição é elemento central."
        ]
    },
    {
        "id": "TAA-2026-LMA-2.9-031",
        "disciplina": "Conhecimentos Específicos",
        "eixo": "Legislação Marítima e Ambiental",
        "topicoEdital": "2.9 Obrigações de trabalho e previdência social",
        "assunto": "Aposentadoria especial — tempos de exposição",
        "tipoOrigem": "inedita_farol",
        "origemInterna": "Inédita Farol 2026 — questão revisada para cobrança realista no padrão Fundação Cesgranrio, com base em fonte oficial vigente.",
        "comentario": "A categoria do trabalhador não define, por si, um único tempo; o enquadramento depende da exposição e da hipótese legal.",
        "explicacaoCorreta": "A categoria do trabalhador não define, por si, um único tempo; o enquadramento depende da exposição e da hipótese legal.",
        "revisaoAssunto": "Para a prova, memorize 15/20/25, mas não trate isso como direito automático do aquaviário.",
        "memorizar2026": "Especial: 15, 20 ou 25 anos conforme o caso.",
        "dicaMacete": "Número correto sem prova de exposição ainda não resolve o direito.",
        "pegadinha": "A Reforma alterou regras, mas não extinguiu o benefício.",
        "fonte": "Lei nº 8.213/1991, art. 57; INSS — Aposentadoria Especial.",
        "atualizacao2026": "A página oficial do INSS em 2026 mantém referência a 15, 20 ou 25 anos conforme o agente/atividade.",
        "enunciado": "Um candidato afirma que toda aposentadoria especial exige exatamente 25 anos de exposição, qualquer que seja o agente ou a hipótese regulamentar. Essa afirmação é",
        "alternativas": [
            "correta, porque todo enquadramento especial exige exatamente vinte e cinco anos de exposição, qualquer que seja o agente nocivo considerado.",
            "correta, porque a EC nº 103/2019 fixou vinte anos como referência geral de exposição, com diferenciação na forma de cálculo.",
            "incorreta: a Lei nº 8.213/1991 prevê, conforme a hipótese de exposição, períodos de 15, 20 ou 25 anos de trabalho em condições especiais.",
            "incorreta porque os tempos legais são dez, vinte e trinta anos, definidos conforme o enquadramento profissional do segurado.",
            "incorreta porque a aposentadoria especial foi extinta pela Reforma da Previdência e substituída integralmente por aposentadoria programada."
        ],
        "correta": 2,
        "analiseAlternativas": [
            "Incorreta. A lei prevê também 15 e 20 anos em hipóteses específicas.",
            "Incorreta. Não houve essa unificação.",
            "Correta. A categoria do trabalhador não define, por si, um único tempo; o enquadramento depende da exposição e da hipótese legal.",
            "Incorreta. A sequência e o critério estão errados.",
            "Incorreta. O benefício permanece."
        ]
    },
    {
        "id": "TAA-2026-LMA-2.9-032",
        "disciplina": "Conhecimentos Específicos",
        "eixo": "Legislação Marítima e Ambiental",
        "topicoEdital": "2.9 Obrigações de trabalho e previdência social",
        "assunto": "Comprovação da exposição — documento e laudo",
        "tipoOrigem": "inedita_farol",
        "origemInterna": "Inédita Farol 2026 — elaborada com base em fontes oficiais vigentes e calibrada ao padrão Fundação Cesgranrio. Taifeiro 2018 Q23 e Taifeiro 2023 Q15 foram usadas apenas como referência histórica de incidência e NÃO foram reproduzidas.",
        "comentario": "A comprovação previdenciária não se confunde com habilitação marítima ou aptidão médica.",
        "explicacaoCorreta": "A comprovação previdenciária não se confunde com habilitação marítima ou aptidão médica.",
        "revisaoAssunto": "A Lei nº 8.213/1991 e o Regulamento vinculam a prova de exposição a documento baseado em laudo técnico das condições ambientais.",
        "memorizar2026": "Exposição especial exige prova técnica, não apenas cargo ou CIR.",
        "dicaMacete": "CIR prova carreira marítima; documento previdenciário prova condições de exposição.",
        "pegadinha": "A banca pode trocar documento de habilitação por documento ambiental.",
        "fonte": "Lei nº 8.213/1991, art. 58, § 1º; Decreto nº 3.048/1999, art. 68, § 3º.",
        "atualizacao2026": "Regra de comprovação vigente consultada nas versões consolidadas do Planalto.",
        "enunciado": "Para comprovar a efetiva exposição a agentes nocivos para fins de aposentadoria especial, a documentação previdenciária deve estar apoiada em",
        "alternativas": [
            "a CIR e o Rol de Equipagem, associados ao registro de tempo embarcado e à descrição detalhada da função, comprovam a exposição nociva nas atividades exercidas habitualmente a bordo.",
            "uma declaração pessoal do trabalhador, confirmando exposição habitual, basta quando o agente nocivo é conhecido no ambiente de bordo.",
            "qualquer atestado médico assistencial que mencione desconforto relacionado ao serviço substitui o laudo técnico das condições ambientais.",
            "laudo técnico das condições ambientais, elaborado por médico do trabalho ou engenheiro de segurança, servindo de base à comprovação previdenciária.",
            "o contrato de trabalho que descreva atividade embarcada comprova exposição nociva quando identifica o agente existente no setor."
        ],
        "correta": 3,
        "analiseAlternativas": [
            "Incorreta. Documentos marítimos não substituem prova previdenciária da exposição.",
            "Incorreta. A legislação exige documentação técnica.",
            "Incorreta. Atestado assistencial não equivale ao documento técnico exigido.",
            "Correta. A comprovação previdenciária não se confunde com habilitação marítima ou aptidão médica.",
            "Incorreta. Atividade embarcada por si só não comprova exposição."
        ]
    },
    {
        "id": "TAA-2026-LMA-2.9-033",
        "disciplina": "Conhecimentos Específicos",
        "eixo": "Legislação Marítima e Ambiental",
        "topicoEdital": "2.9 Obrigações de trabalho e previdência social",
        "assunto": "Perfil profissiográfico — dever empresarial",
        "tipoOrigem": "inedita_farol",
        "origemInterna": "Inédita Farol 2026 — elaborada com base em fontes oficiais vigentes e calibrada ao padrão Fundação Cesgranrio. Taifeiro 2018 Q23 e Taifeiro 2023 Q15 foram usadas apenas como referência histórica de incidência e NÃO foram reproduzidas.",
        "comentario": "O perfil profissiográfico acompanha as atividades e condições laborais relevantes e é responsabilidade documental da empresa.",
        "explicacaoCorreta": "O perfil profissiográfico acompanha as atividades e condições laborais relevantes e é responsabilidade documental da empresa.",
        "revisaoAssunto": "Para prova, diferencie documentos marítimos de habilitação/embarque e documentos previdenciários de exposição.",
        "memorizar2026": "Perfil profissiográfico: empresa elabora, atualiza e fornece cópia na rescisão.",
        "dicaMacete": "Não aceite CIR como substituto automático do documento previdenciário.",
        "pegadinha": "Documentos podem coexistir porque provam fatos diferentes.",
        "fonte": "Lei nº 8.213/1991, art. 58, § 4º.",
        "atualizacao2026": "Regra vigente consultada no Planalto.",
        "enunciado": "Quanto ao perfil profissiográfico relativo às atividades e condições de trabalho do empregado, a Lei nº 8.213/1991 atribui à empresa o dever de",
        "alternativas": [
            "elaborá-lo quando o empregado completar o período de exposição previsto para a aposentadoria especial.",
            "o substitua pela CIR quando se tratar de aquaviário.",
            "o mantenha sigiloso, sem fornecer cópia ao trabalhador na rescisão.",
            "emiti-lo mediante solicitação do trabalhador ou determinação da autoridade previdenciária.",
            "manter o perfil atualizado e fornecer cópia autêntica ao trabalhador na rescisão."
        ],
        "correta": 4,
        "analiseAlternativas": [
            "Incorreta. O dever documental não nasce apenas no momento da aposentadoria.",
            "Incorreta. CIR e documento previdenciário têm finalidades diferentes.",
            "Incorreta. A lei prevê fornecimento de cópia autêntica.",
            "Incorreta. A obrigação existe independentemente de processo judicial.",
            "Correta. O perfil profissiográfico acompanha as atividades e condições laborais relevantes e é responsabilidade documental da empresa."
        ]
    },
    {
        "id": "TAA-2026-LMA-2.9-034",
        "disciplina": "Conhecimentos Específicos",
        "eixo": "Legislação Marítima e Ambiental",
        "topicoEdital": "2.9 Obrigações de trabalho e previdência social",
        "assunto": "Exposição efetiva — eliminação e neutralização",
        "tipoOrigem": "inedita_farol",
        "origemInterna": "Inédita Farol 2026 — elaborada com base em fontes oficiais vigentes e calibrada ao padrão Fundação Cesgranrio. Taifeiro 2018 Q23 e Taifeiro 2023 Q15 foram usadas apenas como referência histórica de incidência e NÃO foram reproduzidas.",
        "comentario": "O Regulamento define efetiva exposição considerando se a nocividade permanece após as medidas de controle.",
        "explicacaoCorreta": "O Regulamento define efetiva exposição considerando se a nocividade permanece após as medidas de controle.",
        "revisaoAssunto": "Eliminação impossibilita a exposição; neutralização reduz intensidade, concentração ou dose ao limite aplicável.",
        "memorizar2026": "Especial exige nocividade efetiva, não mera presença nominal do agente.",
        "dicaMacete": "Pergunte se o risco foi realmente eliminado ou neutralizado.",
        "pegadinha": "Não confunda existência do agente no ambiente com exposição previdenciariamente caracterizada.",
        "fonte": "Decreto nº 3.048/1999, art. 64, §§ 1º e 1º-A.",
        "atualizacao2026": "Critérios regulamentares vigentes consultados no Planalto.",
        "enunciado": "Em determinado ambiente de trabalho, as medidas de controle eliminam efetivamente a exposição do trabalhador ao agente prejudicial. Para a caracterização da efetiva exposição, essa eliminação",
        "alternativas": [
            "é irrelevante, porque basta a existência nominal do agente no setor.",
            "afasta a efetiva exposição enquanto a nocividade estiver realmente eliminada.",
            "garante aposentadoria especial justamente porque houve investimento em controle de risco.",
            "só produz efeito se o empregado deixar de usar EPI.",
            "enquadra o período como atividade especial de quinze anos, em razão do risco originalmente existente."
        ],
        "correta": 1,
        "analiseAlternativas": [
            "Incorreta. A caracterização considera a efetiva exposição e as medidas de controle.",
            "Correta. O Regulamento define efetiva exposição considerando se a nocividade permanece após as medidas de controle.",
            "Incorreta. O benefício está ligado à nocividade não eliminada/neutralizada.",
            "Incorreta. A regra não depende dessa inversão.",
            "Incorreta. Não há essa consequência automática."
        ]
    },
    {
        "id": "TAA-2026-LMA-2.9-035",
        "disciplina": "Conhecimentos Específicos",
        "eixo": "Legislação Marítima e Ambiental",
        "topicoEdital": "2.9 Obrigações de trabalho e previdência social",
        "assunto": "ADI 6309 — idade, conversão e cálculo",
        "tipoOrigem": "inedita_farol",
        "origemInterna": "Inédita Farol 2026 — questão revisada para cobrança realista no padrão Fundação Cesgranrio, com base em fonte oficial vigente.",
        "comentario": "O julgamento teve resultados diferentes para pontos diferentes: invalidou a idade mínima, mas não derrubou toda a disciplina da Reforma.",
        "explicacaoCorreta": "O julgamento teve resultados diferentes para pontos diferentes: invalidou a idade mínima, mas não derrubou toda a disciplina da Reforma.",
        "revisaoAssunto": "A antiga versão tinha três questões separadas sobre o mesmo julgamento; agora uma questão de assertivas exige domínio integrado.",
        "memorizar2026": "ADI 6309: idade cai; conversão pós-EC103 continua vedada; cálculo novo permanece.",
        "dicaMacete": "Não transforme uma inconstitucionalidade parcial em anulação total da Reforma.",
        "pegadinha": "A palavra 'integralmente' é uma pegadinha importante.",
        "fonte": "STF — ADI 6309; Ministério da Previdência Social — julgamento da ADI 6309, publicação oficial de 26/06/2026.",
        "atualizacao2026": "Conferido em fonte oficial em agosto de 2026: idade mínima invalidada; vedação de conversão do tempo especial posterior à EC 103/2019 e novos critérios de cálculo mantidos.",
        "enunciado": "Considere as afirmações sobre o resultado do julgamento da ADI 6309 divulgado em 2026: I — a idade mínima para aposentadoria especial do RGPS, nas hipóteses questionadas, foi declarada inconstitucional; II — foi mantida a vedação à conversão em tempo comum do período especial posterior à EC nº 103/2019; III — foram mantidos os novos critérios de cálculo do benefício introduzidos pela Reforma da Previdência. Está correto o que se afirma em",
        "alternativas": [
            "I, II e III.",
            "I.",
            "II.",
            "I e II.",
            "II e III."
        ],
        "correta": 0,
        "analiseAlternativas": [
            "Correta. O julgamento teve resultados diferentes para pontos diferentes: invalidou a idade mínima, mas não derrubou toda a disciplina da Reforma.",
            "Incorreta. II e III também foram mantidos.",
            "Incorreta. I e III também estão corretos.",
            "Incorreta. O cálculo também foi mantido.",
            "Incorreta. A idade mínima foi invalidada."
        ]
    },
    {
        "id": "TAA-2026-LMA-2.9-038",
        "disciplina": "Conhecimentos Específicos",
        "eixo": "Legislação Marítima e Ambiental",
        "topicoEdital": "2.9 Obrigações de trabalho e previdência social",
        "assunto": "Aposentadoria especial — permanência em atividade nociva",
        "tipoOrigem": "inedita_farol",
        "origemInterna": "Inédita Farol 2026 — elaborada com base em fontes oficiais vigentes e calibrada ao padrão Fundação Cesgranrio. Taifeiro 2018 Q23 e Taifeiro 2023 Q15 foram usadas apenas como referência histórica de incidência e NÃO foram reproduzidas.",
        "comentario": "A lógica protetiva da aposentadoria especial é afastar o segurado da exposição nociva que fundamentou o benefício.",
        "explicacaoCorreta": "A lógica protetiva da aposentadoria especial é afastar o segurado da exposição nociva que fundamentou o benefício.",
        "revisaoAssunto": "O art. 57, § 8º, da Lei nº 8.213/1991 remete ao regime aplicável à continuidade em atividade nociva; o Regulamento disciplina a cessação do pagamento após notificação.",
        "memorizar2026": "Aposentadoria especial não combina com permanência na mesma exposição nociva.",
        "dicaMacete": "Não misture consequência previdenciária com cancelamento de documento marítimo.",
        "pegadinha": "A banca pode usar CIR, categoria ou vínculo empregatício como distração.",
        "fonte": "Lei nº 8.213/1991, art. 57, § 8º; Decreto nº 3.048/1999, art. 69, parágrafo único.",
        "atualizacao2026": "Regra previdenciária vigente consultada no Planalto.",
        "enunciado": "Um segurado obtém aposentadoria especial e permanece exercendo atividade que o expõe aos mesmos agentes nocivos que fundamentaram o benefício. À luz da disciplina previdenciária aplicável,",
        "alternativas": [
            "o benefício deve ser acumulado normalmente com a mesma exposição nociva, sem qualquer consequência.",
            "a aposentadoria especial passa a receber tratamento equivalente ao auxílio-acidente enquanto persistir a exposição.",
            "o segurado perde definitivamente toda qualidade de segurado no RGPS.",
            "a empresa deve cancelar a CIR do trabalhador.",
            "a manutenção do pagamento é incompatível com a permanência ou o retorno à atividade nociva."
        ],
        "correta": 4,
        "analiseAlternativas": [
            "Incorreta. A legislação prevê consequência para permanência/retorno à atividade nociva.",
            "Incorreta. Não existe essa conversão automática.",
            "Incorreta. A consequência não é essa.",
            "Incorreta. CIR é matéria marítima e não é cancelada automaticamente por essa situação previdenciária.",
            "Correta. A lógica protetiva da aposentadoria especial é afastar o segurado da exposição nociva que fundamentou o benefício."
        ]
    },
    {
        "id": "TAA-2026-LMA-2.9-039",
        "disciplina": "Conhecimentos Específicos",
        "eixo": "Legislação Marítima e Ambiental",
        "topicoEdital": "2.9 Obrigações de trabalho e previdência social",
        "assunto": "Aposentadoria especial — carência",
        "tipoOrigem": "inedita_farol",
        "origemInterna": "Inédita Farol 2026 — questão revisada para cobrança realista no padrão Fundação Cesgranrio, com base em fonte oficial vigente.",
        "comentario": "A questão transforma o número de 180 contribuições em aplicação prática.",
        "explicacaoCorreta": "A questão transforma o número de 180 contribuições em aplicação prática.",
        "revisaoAssunto": "Tempo especial e carência não são a mesma coisa; o candidato deve conferir ambos.",
        "memorizar2026": "Carência: 180 contribuições.",
        "dicaMacete": "Não some 'anos expostos' e 'número de contribuições' como se fossem um único requisito.",
        "pegadinha": "CIR prova situação marítima, não carência do RGPS.",
        "fonte": "INSS — Aposentadoria Especial; Lei nº 8.213/1991.",
        "atualizacao2026": "Carência de 180 contribuições mantida na orientação oficial do INSS para aposentadoria especial em 2026.",
        "enunciado": "Um segurado comprova o período de exposição exigido para sua hipótese de aposentadoria especial, mas possui apenas 170 contribuições mensais computadas para carência. Nessa situação,",
        "alternativas": [
            "a carência está cumprida, porque o tempo especial elimina qualquer número mínimo de contribuições.",
            "a carência exigida nessa modalidade é de 120 contribuições mensais.",
            "o requisito de carência não foi cumprido, pois são necessárias 180 contribuições mensais.",
            "a carência só existe para aposentadoria comum.",
            "a CIR válida substitui as contribuições faltantes."
        ],
        "correta": 2,
        "analiseAlternativas": [
            "Incorreta. Tempo de exposição e carência são requisitos distintos.",
            "Incorreta. O número indicado é 180.",
            "Correta. A questão transforma o número de 180 contribuições em aplicação prática.",
            "Incorreta. A aposentadoria especial também possui carência.",
            "Incorreta. Documento marítimo não substitui requisito previdenciário."
        ]
    },
    {
        "id": "TAA-2026-LMA-2.9-040",
        "disciplina": "Conhecimentos Específicos",
        "eixo": "Legislação Marítima e Ambiental",
        "topicoEdital": "2.9 Obrigações de trabalho e previdência social",
        "assunto": "Caso integrador — Taifeiro e aposentadoria especial",
        "tipoOrigem": "inedita_farol",
        "origemInterna": "Inédita Farol 2026 — elaborada com base em fontes oficiais vigentes e calibrada ao padrão Fundação Cesgranrio. Taifeiro 2018 Q23 e Taifeiro 2023 Q15 foram usadas apenas como referência histórica de incidência e NÃO foram reproduzidas.",
        "comentario": "O caso integra carreira marítima e previdência: documentos e conceitos de um sistema não substituem automaticamente os do outro.",
        "explicacaoCorreta": "O caso integra carreira marítima e previdência: documentos e conceitos de um sistema não substituem automaticamente os do outro.",
        "revisaoAssunto": "A aposentadoria especial depende da exposição nociva efetiva e comprovada. Em 2026, a idade mínima da EC 103 foi invalidada pelo STF, mas os demais requisitos não desapareceram.",
        "memorizar2026": "Mesmo cargo ≠ mesmo enquadramento previdenciário automático.",
        "dicaMacete": "Separe 'tempo embarcado' de 'tempo especial comprovado'.",
        "pegadinha": "A banca pode usar a familiaridade com CIR e tempo de embarque para esconder a exigência de prova ambiental.",
        "fonte": "Lei nº 8.213/1991, arts. 57 e 58; Decreto nº 3.048/1999, arts. 64 e 68; STF, ADI 6309.",
        "atualizacao2026": "Atualizado para o resultado da ADI 6309 divulgado oficialmente em junho de 2026.",
        "enunciado": "Dois Taifeiros têm a mesma categoria e igual tempo de embarque. O primeiro possui documentação técnica que comprova efetiva exposição a agente nocivo; no segundo, as medidas de controle eliminaram a nocividade. Para fins de aposentadoria especial, o fato de ambos terem o mesmo cargo e tempo embarcado",
        "alternativas": [
            "os dois possuem o mesmo enquadramento previdenciário porque exercem a mesma categoria marítima e têm igual tempo de embarque.",
            "nenhum pode obter aposentadoria especial após a EC nº 103/2019.",
            "o trabalhador sem exposição comprovada tem preferência por possuir o mesmo tempo de embarque.",
            "não basta: o direito depende da efetiva exposição comprovada e dos demais requisitos de cada segurado.",
            "a CIR do primeiro trabalhador é suficiente para provar o agente nocivo, tornando desnecessário documento técnico."
        ],
        "correta": 3,
        "analiseAlternativas": [
            "Incorreta. A categoria não substitui a análise da exposição.",
            "Incorreta. O benefício continua existindo.",
            "Incorreta. Tempo de embarque, sozinho, não prova nocividade.",
            "Correta. O caso integra carreira marítima e previdência: documentos e conceitos de um sistema não substituem automaticamente os do outro.",
            "Incorreta. CIR não substitui a documentação previdenciária de exposição."
        ]
    }
];

    const atual = Array.isArray(window.questoesTaifeiroBanco2026)
        ? window.questoesTaifeiroBanco2026
        : [];
    const idsExistentes = new Set(atual.map(q => q && q.id).filter(Boolean));
    const novas = loteObrigacoesTrabalhoPrevidenciaTAA2026.filter(q => !idsExistentes.has(q.id));
    window.questoesTaifeiroBanco2026 = atual.concat(novas);
})();
