// ==========================================================
// FAROL DO SABER — TRANSPETRO / TAIFEIRO — BANCO 2026
// Legislação Marítima e Ambiental — 2.1 Fluxo de carreira
// 35 questões • sem imagens • gabarito A-E equilibrado
// Base normativa atual: NORMAM-101/DPC + LESTA/RLESTA + PREPOM 2026
// NORMAM-101/DPC vigente: Portaria DPC/DGN/MB nº 205, de 22/07/2026
// As microaulas (revisaoAssunto) trazem a referência normativa específica.
// Não reutiliza questões de Taifeiro 2018/2023.
// ==========================================================
(() => {
    "use strict";

    const loteFluxoCarreiraTAA2026 =
[
    {
        "id": "TAA-2026-LMA-2.1-001",
        "disciplina": "Conhecimentos Específicos",
        "eixo": "Legislação Marítima e Ambiental",
        "topicoEdital": "2.1 Fluxo de carreira",
        "assunto": "Conceito de aquaviário",
        "tipoOrigem": "inedita_farol",
        "origemInterna": "Inédita Farol 2026",
        "enunciado": "Segundo a legislação brasileira de segurança do tráfego aquaviário, considera-se aquaviário",
        "alternativas": [
            "todo aquele com habilitação certificada pela Autoridade Marítima para operar embarcações em caráter profissional.",
            "qualquer pessoa que trabalhe em área portuária, ainda que nunca exerça atividade embarcada.",
            "o proprietário de embarcação mercante que a explore economicamente, mesmo sem habilitação profissional.",
            "todo tripulante ou passageiro que permaneça embarcado por período superior a vinte e quatro horas.",
            "somente o profissional pertencente aos grupos de Marítimos e Fluviários e inscrito como oficial."
        ],
        "correta": 0,
        "comentario": "A LESTA define aquaviário pela habilitação certificada pela Autoridade Marítima para operar embarcações profissionalmente.",
        "explicacaoCorreta": "A LESTA define aquaviário pela habilitação certificada pela Autoridade Marítima para operar embarcações profissionalmente.",
        "revisaoAssunto": "A definição legal é funcional: o elemento central é a habilitação certificada pela Autoridade Marítima para operar embarcações em caráter profissional. Ela não se confunde com proprietário, passageiro ou trabalhador portuário. Fonte: LESTA — Lei nº 9.537/1997, Capítulo I, art. 2º, II.",
        "memorizar2026": "Aquaviário = habilitação da Autoridade Marítima + operação profissional de embarcação.",
        "dicaMacete": "Se aparecer “caráter profissional”, lembre da definição legal de aquaviário.",
        "pegadinha": "A banca pode trocar aquaviário por amador, proprietário ou profissional portuário.",
        "analiseAlternativas": [
            "Correta. Reproduz o núcleo da definição do art. 2º, II, da LESTA.",
            "Incorreta. Trabalhador portuário não se torna aquaviário apenas pelo local onde trabalha.",
            "Incorreta. Propriedade da embarcação não substitui habilitação profissional.",
            "Incorreta. Permanência a bordo não define a condição de aquaviário.",
            "Incorreta. A categoria aquaviário não se limita a oficiais dos grupos Marítimos e Fluviários."
        ],
        "fonte": "LESTA — Lei nº 9.537/1997, Capítulo I, art. 2º, II.",
        "atualizacao2026": "Referência conferida para o Banco 2026. A NORMAM-101/DPC vigente consta na página oficial da DPC vinculada à Portaria DPC/DGN/MB nº 205, de 22/07/2026."
    },
    {
        "id": "TAA-2026-LMA-2.1-002",
        "disciplina": "Conhecimentos Específicos",
        "eixo": "Legislação Marítima e Ambiental",
        "topicoEdital": "2.1 Fluxo de carreira",
        "assunto": "Ingresso e inscrição na carreira",
        "tipoOrigem": "inedita_farol",
        "origemInterna": "Inédita Farol 2026",
        "enunciado": "Um candidato deseja localizar, na NORMAM-101/DPC, as regras gerais sobre ingresso e inscrição de aquaviários. Segundo orientação oficial da DPC, esses assuntos são tratados, respectivamente,",
        "alternativas": [
            "no Capítulo 2, Seções III e IV.",
            "no Capítulo 1, Seções I e II.",
            "no Capítulo 3, Seções I e II.",
            "exclusivamente no Anexo 2-D.",
            "somente no PREPOM, sem previsão na NORMAM-101/DPC."
        ],
        "correta": 1,
        "comentario": "A DPC informa que o ingresso e a inscrição de aquaviários são disciplinados no Capítulo 1, Seções I e II, respectivamente, da NORMAM-101/DPC.",
        "explicacaoCorreta": "A DPC informa que o ingresso e a inscrição de aquaviários são disciplinados no Capítulo 1, Seções I e II, respectivamente, da NORMAM-101/DPC.",
        "revisaoAssunto": "O fluxo profissional começa pelo ingresso e pela inscrição. A própria DPC orienta que o candidato consulte o Capítulo 1 da NORMAM-101/DPC: Seção I para ingresso e Seção II para inscrição. Fonte: NORMAM-101/DPC, Capítulo 1, Seções I e II; DPC — Perguntas Frequentes, “Como faço para me tornar aquaviário?”.",
        "memorizar2026": "Ingresso → Cap. 1, Seção I; inscrição → Cap. 1, Seção II.",
        "dicaMacete": "Memorize a ordem lógica: primeiro ingresso, depois inscrição.",
        "pegadinha": "O Anexo 2-A é importantíssimo para categorias e certificações, mas não substitui as seções gerais de ingresso e inscrição.",
        "analiseAlternativas": [
            "Incorreta. O Capítulo 2 concentra outros procedimentos de carreira.",
            "Correta. É a localização indicada pela própria DPC.",
            "Incorreta. O Capítulo 3 não é a referência geral indicada para ingresso e inscrição.",
            "Incorreta. O Anexo 2-D está associado à Licença de Categoria/Capacidade Superior.",
            "Incorreta. O PREPOM complementa a formação, mas ingresso e inscrição têm disciplina na NORMAM-101."
        ],
        "fonte": "NORMAM-101/DPC, Capítulo 1, Seções I e II; DPC — Perguntas Frequentes, “Como faço para me tornar aquaviário?”.",
        "atualizacao2026": "Referência conferida para o Banco 2026. A NORMAM-101/DPC vigente consta na página oficial da DPC vinculada à Portaria DPC/DGN/MB nº 205, de 22/07/2026."
    },
    {
        "id": "TAA-2026-LMA-2.1-003",
        "disciplina": "Conhecimentos Específicos",
        "eixo": "Legislação Marítima e Ambiental",
        "topicoEdital": "2.1 Fluxo de carreira",
        "assunto": "Grupos de aquaviários — Marítimos",
        "tipoOrigem": "inedita_farol",
        "origemInterna": "Inédita Farol 2026",
        "enunciado": "Nos termos do Regulamento da Lei de Segurança do Tráfego Aquaviário, pertencem ao 1º Grupo — Marítimos os tripulantes que operam embarcações classificadas, entre outras possibilidades, para",
        "alternativas": [
            "atividades exclusivamente subaquáticas executadas por mergulhadores profissionais.",
            "serviço de praticagem, como aquaviários não tripulantes.",
            "navegação em mar aberto, apoio marítimo, apoio portuário e determinadas navegações interiores em áreas marítimas abrigadas.",
            "somente navegação interior em rios e lagos, sem atuação em áreas marítimas.",
            "manobras de navios exclusivamente em diques, estaleiros e carreiras."
        ],
        "correta": 2,
        "comentario": "O RLESTA enquadra como Marítimos os tripulantes que operam embarcações de mar aberto, apoio marítimo, apoio portuário e também certas navegações interiores em áreas marítimas abrigadas.",
        "explicacaoCorreta": "O RLESTA enquadra como Marítimos os tripulantes que operam embarcações de mar aberto, apoio marítimo, apoio portuário e também certas navegações interiores em áreas marítimas abrigadas.",
        "revisaoAssunto": "Os grupos não são definidos apenas pelo nome da categoria; o tipo de atividade e de navegação é relevante. O 1º Grupo é o dos Marítimos. Fonte: RLESTA — Decreto nº 2.596/1998, Capítulo I, art. 1º, I.",
        "memorizar2026": "1º Grupo = Marítimos.",
        "dicaMacete": "Mar aberto e apoio marítimo apontam fortemente para o 1º Grupo.",
        "pegadinha": "A banca pode usar funções reais de outros grupos como Práticos, Mergulhadores ou Agentes de Manobra.",
        "analiseAlternativas": [
            "Incorreta. Atividades subaquáticas caracterizam o grupo de Mergulhadores.",
            "Incorreta. Práticos constituem grupo próprio e são aquaviários não tripulantes.",
            "Correta. É a descrição do 1º Grupo — Marítimos no RLESTA.",
            "Incorreta. Essa descrição se aproxima do grupo de Fluviários.",
            "Incorreta. Manobra e docagem em diques, estaleiros e carreiras correspondem ao 6º Grupo."
        ],
        "fonte": "RLESTA — Decreto nº 2.596/1998, Capítulo I, art. 1º, I.",
        "atualizacao2026": "Referência conferida para o Banco 2026. A NORMAM-101/DPC vigente consta na página oficial da DPC vinculada à Portaria DPC/DGN/MB nº 205, de 22/07/2026."
    },
    {
        "id": "TAA-2026-LMA-2.1-004",
        "disciplina": "Conhecimentos Específicos",
        "eixo": "Legislação Marítima e Ambiental",
        "topicoEdital": "2.1 Fluxo de carreira",
        "assunto": "Grupos de aquaviários — Fluviários",
        "tipoOrigem": "inedita_farol",
        "origemInterna": "Inédita Farol 2026",
        "enunciado": "Um tripulante exerce profissionalmente suas funções em embarcações classificadas para navegação interior em lagos e rios e para apoio portuário fluvial. Pelo RLESTA, ele integra o grupo dos",
        "alternativas": [
            "Pescadores.",
            "Marítimos.",
            "Práticos.",
            "Fluviários.",
            "Agentes de Manobra e Docagem."
        ],
        "correta": 3,
        "comentario": "O 2º Grupo — Fluviários reúne tripulantes que operam embarcações de navegação interior nos lagos e rios e de apoio portuário fluvial.",
        "explicacaoCorreta": "O 2º Grupo — Fluviários reúne tripulantes que operam embarcações de navegação interior nos lagos e rios e de apoio portuário fluvial.",
        "revisaoAssunto": "Na prova, associe Fluviários às hidrovias interiores, especialmente rios e lagos. A natureza da navegação diferencia esse grupo dos Marítimos. Fonte: RLESTA — Decreto nº 2.596/1998, Capítulo I, art. 1º, II.",
        "memorizar2026": "2º Grupo = Fluviários = rios, lagos e apoio portuário fluvial.",
        "dicaMacete": "“Fluvial” no enunciado é uma pista, mas confira a atividade descrita.",
        "pegadinha": "Marítimos também podem atuar em áreas abrigadas; a banca pode explorar essa fronteira.",
        "analiseAlternativas": [
            "Incorreta. Pescadores exercem atividades a bordo de embarcações de pesca.",
            "Incorreta. O caso descrito é de navegação interior fluvial.",
            "Incorreta. Prático presta serviço de praticagem e não é o tripulante descrito.",
            "Correta. Corresponde ao 2º Grupo — Fluviários.",
            "Incorreta. Agentes de Manobra e Docagem têm atividade específica em diques, estaleiros e carreiras."
        ],
        "fonte": "RLESTA — Decreto nº 2.596/1998, Capítulo I, art. 1º, II.",
        "atualizacao2026": "Referência conferida para o Banco 2026. A NORMAM-101/DPC vigente consta na página oficial da DPC vinculada à Portaria DPC/DGN/MB nº 205, de 22/07/2026."
    },
    {
        "id": "TAA-2026-LMA-2.1-005",
        "disciplina": "Conhecimentos Específicos",
        "eixo": "Legislação Marítima e Ambiental",
        "topicoEdital": "2.1 Fluxo de carreira",
        "assunto": "Grupos de aquaviários — distinções",
        "tipoOrigem": "inedita_farol",
        "origemInterna": "Inédita Farol 2026",
        "enunciado": "Assinale a associação correta entre grupo de aquaviários e atividade prevista no RLESTA.",
        "alternativas": [
            "Mergulhadores — prestação exclusiva de serviço de praticagem em zonas de praticagem.",
            "Pescadores — manobra de navios em diques, estaleiros e carreiras.",
            "Fluviários — execução de atividades subaquáticas eventuais a bordo.",
            "Marítimos — exercício exclusivo de pesca profissional.",
            "Agentes de Manobra e Docagem — manobra de navios em diques, estaleiros e carreiras."
        ],
        "correta": 4,
        "comentario": "O 6º Grupo é constituído pelos Agentes de Manobra e Docagem, aquaviários não tripulantes que manobram navios em diques, estaleiros e carreiras.",
        "explicacaoCorreta": "O 6º Grupo é constituído pelos Agentes de Manobra e Docagem, aquaviários não tripulantes que manobram navios em diques, estaleiros e carreiras.",
        "revisaoAssunto": "O RLESTA organiza os aquaviários em grupos segundo a natureza da atividade. Saber distinguir os grupos ajuda a compreender que os fluxos de carreira não são intercambiáveis automaticamente. Fonte: RLESTA — Decreto nº 2.596/1998, Capítulo I, art. 1º, I a VI.",
        "memorizar2026": "6º Grupo = Agentes de Manobra e Docagem.",
        "dicaMacete": "Diques + estaleiros + carreiras → Agentes de Manobra e Docagem.",
        "pegadinha": "A questão mistura descrições verdadeiras, mas deslocadas para o grupo errado.",
        "analiseAlternativas": [
            "Incorreta. Praticagem pertence ao grupo dos Práticos.",
            "Incorreta. Essa atividade é dos Agentes de Manobra e Docagem.",
            "Incorreta. Atividades subaquáticas caracterizam Mergulhadores.",
            "Incorreta. Pesca profissional caracteriza Pescadores, não Marítimos em geral.",
            "Correta. É a descrição normativa do 6º Grupo."
        ],
        "fonte": "RLESTA — Decreto nº 2.596/1998, Capítulo I, art. 1º, I a VI.",
        "atualizacao2026": "Referência conferida para o Banco 2026. A NORMAM-101/DPC vigente consta na página oficial da DPC vinculada à Portaria DPC/DGN/MB nº 205, de 22/07/2026."
    },
    {
        "id": "TAA-2026-LMA-2.1-006",
        "disciplina": "Conhecimentos Específicos",
        "eixo": "Legislação Marítima e Ambiental",
        "topicoEdital": "2.1 Fluxo de carreira",
        "assunto": "Taifeiro — Seção de Câmara",
        "tipoOrigem": "inedita_farol",
        "origemInterna": "Inédita Farol 2026",
        "enunciado": "No fluxo de formação previsto para o CAAQ-CTS, a categoria de Taifeiro (TAA) pertence à",
        "alternativas": [
            "Seção de Câmara.",
            "Seção de Convés.",
            "Seção de Máquinas.",
            "Seção de Saúde.",
            "Seção de Praticagem."
        ],
        "correta": 0,
        "comentario": "O Taifeiro (TAA), assim como o Cozinheiro (CZA), é categoria da Seção de Câmara.",
        "explicacaoCorreta": "O Taifeiro (TAA), assim como o Cozinheiro (CZA), é categoria da Seção de Câmara.",
        "revisaoAssunto": "A identificação da seção é relevante para compreender o enquadramento profissional. No CAAQ-CTS, CZA e TAA pertencem à Câmara; ENF e ASA pertencem à Saúde. Fonte: PREPOM-Aquaviários/2026 — Curso de Adaptação para Aquaviários Cozinheiro, Taifeiro, Enfermeiro e Auxiliar de Saúde (CAAQ-CTS); documentos oficiais de seleção 2026 da Marinha.",
        "memorizar2026": "TAA = Câmara; CZA = Câmara.",
        "dicaMacete": "Câmara lembra hotelaria, alimentação, arrumação e apoio de habitabilidade a bordo.",
        "pegadinha": "A banca pode trocar Taifeiro por Auxiliar de Saúde, que pertence à Seção de Saúde.",
        "analiseAlternativas": [
            "Correta. TAA integra a Seção de Câmara.",
            "Incorreta. Convés reúne categorias próprias de navegação e manobra.",
            "Incorreta. Máquinas reúne categorias ligadas à operação e manutenção dos sistemas de máquinas.",
            "Incorreta. Saúde inclui ENF e ASA no contexto do CAAQ-CTS.",
            "Incorreta. Praticagem é atividade de grupo próprio, não seção do TAA."
        ],
        "fonte": "PREPOM-Aquaviários/2026 — Curso de Adaptação para Aquaviários Cozinheiro, Taifeiro, Enfermeiro e Auxiliar de Saúde (CAAQ-CTS); documentos oficiais de seleção 2026 da Marinha.",
        "atualizacao2026": "Referência conferida para o Banco 2026. A NORMAM-101/DPC vigente consta na página oficial da DPC vinculada à Portaria DPC/DGN/MB nº 205, de 22/07/2026."
    },
    {
        "id": "TAA-2026-LMA-2.1-007",
        "disciplina": "Conhecimentos Específicos",
        "eixo": "Legislação Marítima e Ambiental",
        "topicoEdital": "2.1 Fluxo de carreira",
        "assunto": "CAAQ-CTS — enquadramento",
        "tipoOrigem": "inedita_farol",
        "origemInterna": "Inédita Farol 2026",
        "enunciado": "O Curso de Adaptação para Aquaviários CAAQ-CTS habilita, conforme a opção e os requisitos aplicáveis, profissionais para as categorias de",
        "alternativas": [
            "Marinheiro de Convés, Marinheiro de Máquinas, Taifeiro e Prático.",
            "Cozinheiro, Taifeiro, Enfermeiro e Auxiliar de Saúde.",
            "Taifeiro, Eletricista, Condutor de Máquinas e Auxiliar de Saúde.",
            "Cozinheiro, Moço de Convés, Moço de Máquinas e Enfermeiro.",
            "Taifeiro, Prático, Mergulhador e Agente de Manobra."
        ],
        "correta": 1,
        "comentario": "O CAAQ-CTS é o curso de adaptação destinado às categorias Cozinheiro, Taifeiro, Enfermeiro e Auxiliar de Saúde.",
        "explicacaoCorreta": "O CAAQ-CTS é o curso de adaptação destinado às categorias Cozinheiro, Taifeiro, Enfermeiro e Auxiliar de Saúde.",
        "revisaoAssunto": "O curso agrupa duas categorias da Seção de Câmara (CZA e TAA) e duas da Seção de Saúde (ENF e ASA). A opção efetiva depende do enquadramento e dos requisitos do processo seletivo. Fonte: PREPOM-Aquaviários/2026 — CAAQ-CTS; editais oficiais da Marinha para o CAAQ-CTS em 2026.",
        "memorizar2026": "CAAQ-CTS = CZA + TAA + ENF + ASA.",
        "dicaMacete": "Memorize “CTS” como o conjunto tradicional Câmara/Saúde do curso.",
        "pegadinha": "A banca pode incluir cargos Transpetro que existem no edital, mas não pertencem ao CAAQ-CTS.",
        "analiseAlternativas": [
            "Incorreta. Marinheiro e Prático têm vias formativas próprias.",
            "Correta. É o conjunto de categorias abrangido pelo CAAQ-CTS.",
            "Incorreta. Eletricista e Condutor de Máquinas não integram esse curso.",
            "Incorreta. Moço de Convés e Moço de Máquinas têm cursos específicos.",
            "Incorreta. Prático, Mergulhador e Agente de Manobra pertencem a outros fluxos profissionais."
        ],
        "fonte": "PREPOM-Aquaviários/2026 — CAAQ-CTS; editais oficiais da Marinha para o CAAQ-CTS em 2026.",
        "atualizacao2026": "Referência conferida para o Banco 2026. A NORMAM-101/DPC vigente consta na página oficial da DPC vinculada à Portaria DPC/DGN/MB nº 205, de 22/07/2026."
    },
    {
        "id": "TAA-2026-LMA-2.1-008",
        "disciplina": "Conhecimentos Específicos",
        "eixo": "Legislação Marítima e Ambiental",
        "topicoEdital": "2.1 Fluxo de carreira",
        "assunto": "Taifeiro — ausência de ascensão de categoria",
        "tipoOrigem": "inedita_farol",
        "origemInterna": "Inédita Farol 2026",
        "enunciado": "Em edital oficial da Marinha de 2026 para o CAAQ-CTS, ao tratar de Cozinheiro, Taifeiro, Enfermeiro e Auxiliar de Saúde, é informado que esses profissionais",
        "alternativas": [
            "ascendem automaticamente para categoria superior após dois anos de embarque.",
            "somente podem exercer suas funções no 2º Grupo — Fluviários.",
            "não possuem ascensão de categoria, mecanismo previsto para outras seções.",
            "passam obrigatoriamente à Seção de Convés depois do primeiro embarque.",
            "dependem de Licença de Categoria Superior permanente para continuar na profissão."
        ],
        "correta": 2,
        "comentario": "Documentos oficiais de seleção do CAAQ-CTS em 2026 registram expressamente que CZA, TAA, ENF e ASA não têm ascensão de categoria, prevista para outras seções.",
        "explicacaoCorreta": "Documentos oficiais de seleção do CAAQ-CTS em 2026 registram expressamente que CZA, TAA, ENF e ASA não têm ascensão de categoria, prevista para outras seções.",
        "revisaoAssunto": "Esse ponto é decisivo para Taifeiro: o edital do concurso cobra “fluxo de carreira dos aquaviários” de forma geral, mas o próprio TAA não segue uma cadeia de ascensões de categoria como ocorre em outras seções. Fonte: Edital CAAQ-CTS T02/2026 — Capitania dos Portos de Sergipe, item 1.4; PREPOM-Aquaviários/2026.",
        "memorizar2026": "TAA: categoria da Câmara sem ascensão de categoria no fluxo do CAAQ-CTS.",
        "dicaMacete": "Não aplique ao Taifeiro automaticamente as escadas de promoção de Convés ou Máquinas.",
        "pegadinha": "A prova pode cobrar a regra geral de ascensão e, em outra questão, a exceção prática de TAA/CZA/ENF/ASA.",
        "analiseAlternativas": [
            "Incorreta. Não existe ascensão automática por dois anos para essas categorias.",
            "Incorreta. O CAAQ-CTS pode habilitar no 1º Grupo — Marítimos ou 2º Grupo — Fluviários, conforme o caso.",
            "Correta. É a ressalva expressa no edital oficial do CAAQ-CTS em 2026.",
            "Incorreta. Não há migração obrigatória para Convés.",
            "Incorreta. LCS é temporária e excepcional, não mecanismo permanente de continuidade profissional."
        ],
        "fonte": "Edital CAAQ-CTS T02/2026 — Capitania dos Portos de Sergipe, item 1.4; PREPOM-Aquaviários/2026.",
        "atualizacao2026": "Referência conferida para o Banco 2026. A NORMAM-101/DPC vigente consta na página oficial da DPC vinculada à Portaria DPC/DGN/MB nº 205, de 22/07/2026."
    },
    {
        "id": "TAA-2026-LMA-2.1-009",
        "disciplina": "Conhecimentos Específicos",
        "eixo": "Legislação Marítima e Ambiental",
        "topicoEdital": "2.1 Fluxo de carreira",
        "assunto": "Ascensão de categoria — requisitos gerais",
        "tipoOrigem": "inedita_farol",
        "origemInterna": "Inédita Farol 2026",
        "enunciado": "Para os aquaviários pertencentes a fluxos que admitem ascensão de categoria, essa ascensão pode decorrer de",
        "alternativas": [
            "mera antiguidade cadastral, independentemente de qualificação.",
            "indicação da empresa, sem comprovação de requisito profissional.",
            "aprovação em exame médico, isoladamente.",
            "conclusão de estágio, curso e/ou tempo de embarque, conforme os requisitos aplicáveis.",
            "alteração de endereço para outra jurisdição marítima."
        ],
        "correta": 3,
        "comentario": "A orientação oficial da Marinha estabelece que a ascensão de categoria pode ocorrer por conclusão de estágio, curso e/ou tempo de embarque.",
        "explicacaoCorreta": "A orientação oficial da Marinha estabelece que a ascensão de categoria pode ocorrer por conclusão de estágio, curso e/ou tempo de embarque.",
        "revisaoAssunto": "Não existe um requisito único para todas as categorias. O Quadro Geral de Certificações indica as condições aplicáveis a cada fluxo, e a ascensão pode combinar estágio, curso e tempo de embarque. Fonte: NORMAM-101/DPC — itens 1.26, 1.27 e 1.28 e Anexo 2-A; DPC/CPBA — serviço “Ascensão de Categoria”.",
        "memorizar2026": "Ascensão: estágio e/ou curso e/ou tempo de embarque, conforme a categoria.",
        "dicaMacete": "Desconfie de alternativas que transformem um único requisito em regra universal.",
        "pegadinha": "Mudança de jurisdição é procedimento administrativo distinto da ascensão.",
        "analiseAlternativas": [
            "Incorreta. Antiguidade isolada não substitui requisitos profissionais.",
            "Incorreta. Indicação empresarial não elimina as exigências normativas.",
            "Incorreta. Aptidão de saúde pode ser requisito documental, mas não define sozinha a ascensão.",
            "Correta. É a fórmula utilizada pela Marinha.",
            "Incorreta. Alteração de jurisdição não é ascensão."
        ],
        "fonte": "NORMAM-101/DPC — itens 1.26, 1.27 e 1.28 e Anexo 2-A; DPC/CPBA — serviço “Ascensão de Categoria”.",
        "atualizacao2026": "Referência conferida para o Banco 2026. A NORMAM-101/DPC vigente consta na página oficial da DPC vinculada à Portaria DPC/DGN/MB nº 205, de 22/07/2026."
    },
    {
        "id": "TAA-2026-LMA-2.1-010",
        "disciplina": "Conhecimentos Específicos",
        "eixo": "Legislação Marítima e Ambiental",
        "topicoEdital": "2.1 Fluxo de carreira",
        "assunto": "Ascensão — registros decorrentes",
        "tipoOrigem": "inedita_farol",
        "origemInterna": "Inédita Farol 2026",
        "enunciado": "Uma ascensão de categoria regularmente deferida exige, segundo a orientação da DPC,",
        "alternativas": [
            "apenas anotação interna da empresa de navegação.",
            "somente emissão de novo documento de identidade civil.",
            "registro apenas no Rol de Equipagem da embarcação em que o aquaviário está servindo.",
            "substituição automática da CIR por passaporte marítimo estrangeiro.",
            "registro na CIR, atualização no SISAQUA e, se for o caso, emissão de outra certificação."
        ],
        "correta": 4,
        "comentario": "A ascensão repercute nos registros oficiais da carreira: deve constar na CIR, ser atualizada no SISAQUA e pode exigir nova certificação.",
        "explicacaoCorreta": "A ascensão repercute nos registros oficiais da carreira: deve constar na CIR, ser atualizada no SISAQUA e pode exigir nova certificação.",
        "revisaoAssunto": "A carreira do aquaviário é controlada pela Autoridade Marítima. Por isso, a promoção não se resume a um ato da empresa; ela precisa refletir nos registros oficiais. Fonte: NORMAM-101/DPC — disciplina de ascensão; DPC — Documentação e Certificação de Pessoal Aquaviário, pergunta sobre ascensão de categoria.",
        "memorizar2026": "Ascensão deferida → CIR + SISAQUA + certificação, quando cabível.",
        "dicaMacete": "Procure na alternativa os registros oficiais da Autoridade Marítima.",
        "pegadinha": "O Rol de Equipagem registra o embarque, mas não substitui os atos de carreira.",
        "analiseAlternativas": [
            "Incorreta. A empresa não efetiva isoladamente a ascensão.",
            "Incorreta. Documento civil não substitui registro profissional marítimo.",
            "Incorreta. O Rol não é suficiente para formalizar ascensão.",
            "Incorreta. Não existe substituição por passaporte marítimo estrangeiro.",
            "Correta. Esses são os registros e providências indicados pela DPC."
        ],
        "fonte": "NORMAM-101/DPC — disciplina de ascensão; DPC — Documentação e Certificação de Pessoal Aquaviário, pergunta sobre ascensão de categoria.",
        "atualizacao2026": "Referência conferida para o Banco 2026. A NORMAM-101/DPC vigente consta na página oficial da DPC vinculada à Portaria DPC/DGN/MB nº 205, de 22/07/2026."
    },
    {
        "id": "TAA-2026-LMA-2.1-011",
        "disciplina": "Conhecimentos Específicos",
        "eixo": "Legislação Marítima e Ambiental",
        "topicoEdital": "2.1 Fluxo de carreira",
        "assunto": "Iniciativa para requerer ascensão",
        "tipoOrigem": "inedita_farol",
        "origemInterna": "Inédita Farol 2026",
        "enunciado": "Um aquaviário já cumpriu os requisitos exigidos para determinada ascensão de categoria. A iniciativa para requerê-la cabe",
        "alternativas": [
            "ao próprio aquaviário, perante sua Organização Militar de jurisdição.",
            "exclusivamente ao comandante da embarcação em que ele estiver embarcado.",
            "à empresa de navegação, mesmo sem manifestação do interessado.",
            "ao sindicato profissional da categoria.",
            "à Agência Nacional de Transportes Aquaviários."
        ],
        "correta": 0,
        "comentario": "Cabe ao aquaviário a iniciativa de requerer a ascensão para a qual possua os requisitos, perante sua OM de jurisdição.",
        "explicacaoCorreta": "Cabe ao aquaviário a iniciativa de requerer a ascensão para a qual possua os requisitos, perante sua OM de jurisdição.",
        "revisaoAssunto": "A empresa pode fornecer documentos e, em situações previstas, recomendações, mas o procedimento de ascensão é requerido pelo interessado à sua jurisdição. Fonte: NORMAM-101/DPC — Anexo 2-A e procedimento de ascensão; DPC — Documentação e Certificação de Pessoal Aquaviário.",
        "memorizar2026": "Quem requer a ascensão = aquaviário interessado.",
        "dicaMacete": "Requerimento profissional à CP/DL/AG de jurisdição.",
        "pegadinha": "Não confunda ascensão com LCS: na LCS, a solicitação parte da empresa em circunstância excepcional.",
        "analiseAlternativas": [
            "Correta. A iniciativa é do aquaviário interessado.",
            "Incorreta. O comandante não substitui o requerente como regra do procedimento.",
            "Incorreta. A empresa auxilia documentalmente, mas não é a titular do requerimento de ascensão.",
            "Incorreta. Sindicato não processa a ascensão perante a Autoridade Marítima.",
            "Incorreta. A ANTAQ não administra a carreira e habilitação do aquaviário."
        ],
        "fonte": "NORMAM-101/DPC — Anexo 2-A e procedimento de ascensão; DPC — Documentação e Certificação de Pessoal Aquaviário.",
        "atualizacao2026": "Referência conferida para o Banco 2026. A NORMAM-101/DPC vigente consta na página oficial da DPC vinculada à Portaria DPC/DGN/MB nº 205, de 22/07/2026."
    },
    {
        "id": "TAA-2026-LMA-2.1-012",
        "disciplina": "Conhecimentos Específicos",
        "eixo": "Legislação Marítima e Ambiental",
        "topicoEdital": "2.1 Fluxo de carreira",
        "assunto": "Ordem de Serviço na ascensão",
        "tipoOrigem": "inedita_farol",
        "origemInterna": "Inédita Farol 2026",
        "enunciado": "Após a análise dos requisitos e o deferimento da ascensão, o ato deve ser respaldado por",
        "alternativas": [
            "certidão expedida pelo Tribunal Marítimo.",
            "Ordem de Serviço da CP/DL/AG onde a ascensão foi requerida.",
            "resolução da ANTAQ.",
            "ata da empresa de navegação.",
            "autorização do Ministério do Trabalho."
        ],
        "correta": 1,
        "comentario": "A DPC estabelece que a ascensão de categoria deverá ser respaldada por Ordem de Serviço da CP/DL/AG onde foi requerida.",
        "explicacaoCorreta": "A DPC estabelece que a ascensão de categoria deverá ser respaldada por Ordem de Serviço da CP/DL/AG onde foi requerida.",
        "revisaoAssunto": "A Ordem de Serviço é o suporte administrativo da Autoridade Marítima para formalização da ascensão, depois da conferência dos requisitos. Fonte: NORMAM-101/DPC — procedimento de ascensão; DPC — Documentação e Certificação de Pessoal Aquaviário.",
        "memorizar2026": "Ascensão formalizada → Ordem de Serviço da CP/DL/AG.",
        "dicaMacete": "Associe carreira do aquaviário à Autoridade Marítima, não a órgãos econômicos ou trabalhistas.",
        "pegadinha": "A empresa pode emitir comprovantes, mas não substitui o ato administrativo da CP/DL/AG.",
        "analiseAlternativas": [
            "Incorreta. Tribunal Marítimo não formaliza ascensão profissional.",
            "Correta. É o ato indicado pela DPC.",
            "Incorreta. A ANTAQ não expede a Ordem de Serviço de ascensão.",
            "Incorreta. Ata empresarial não formaliza a alteração de categoria.",
            "Incorreta. A competência é da Autoridade Marítima."
        ],
        "fonte": "NORMAM-101/DPC — procedimento de ascensão; DPC — Documentação e Certificação de Pessoal Aquaviário.",
        "atualizacao2026": "Referência conferida para o Banco 2026. A NORMAM-101/DPC vigente consta na página oficial da DPC vinculada à Portaria DPC/DGN/MB nº 205, de 22/07/2026."
    },
    {
        "id": "TAA-2026-LMA-2.1-013",
        "disciplina": "Conhecimentos Específicos",
        "eixo": "Legislação Marítima e Ambiental",
        "topicoEdital": "2.1 Fluxo de carreira",
        "assunto": "Quadro Geral de Certificações — Anexo 2-A",
        "tipoOrigem": "inedita_farol",
        "origemInterna": "Inédita Farol 2026",
        "enunciado": "Para verificar os requisitos de acesso às diversas categorias, bem como limitações e observações pertinentes à carreira, a principal referência indicada pela DPC é",
        "alternativas": [
            "o Anexo 1-G da NORMAM-101/DPC.",
            "o Anexo 1-S da NORMAM-101/DPC.",
            "o Quadro Geral de Certificações — Anexo 2-A da NORMAM-101/DPC.",
            "o Anexo 2-D da NORMAM-101/DPC.",
            "o Rol de Equipagem da última embarcação."
        ],
        "correta": 2,
        "comentario": "O Anexo 2-A reúne o Quadro Geral de Certificações e é a referência para os requisitos de acesso às categorias, limitações e observações.",
        "explicacaoCorreta": "O Anexo 2-A reúne o Quadro Geral de Certificações e é a referência para os requisitos de acesso às categorias, limitações e observações.",
        "revisaoAssunto": "Para estudar fluxo de carreira, o Anexo 2-A é central. Os demais anexos citados têm funções documentais específicas: 1-G para tempo em navio estrangeiro, 1-S para atestado de embarque e 2-D para LCS. Fonte: NORMAM-101/DPC, Anexo 2-A — Quadro Geral de Certificações; DPC — Perguntas Frequentes.",
        "memorizar2026": "Anexo 2-A = mapa dos requisitos/certificações da carreira.",
        "dicaMacete": "2-A é o “quadro de carreira”.",
        "pegadinha": "A banca pode trocar anexos porque todos aparecem em procedimentos de aquaviários.",
        "analiseAlternativas": [
            "Incorreta. O Anexo 1-G é utilizado em comprovação de embarque em navio de bandeira estrangeira.",
            "Incorreta. O Anexo 1-S é o Atestado de Embarque de Aquaviários.",
            "Correta. É a referência geral de requisitos de categorias e certificações.",
            "Incorreta. O Anexo 2-D é o modelo ligado à LCS.",
            "Incorreta. Rol de Equipagem é documento de embarcação, não substitui o Anexo 2-A."
        ],
        "fonte": "NORMAM-101/DPC, Anexo 2-A — Quadro Geral de Certificações; DPC — Perguntas Frequentes.",
        "atualizacao2026": "Referência conferida para o Banco 2026. A NORMAM-101/DPC vigente consta na página oficial da DPC vinculada à Portaria DPC/DGN/MB nº 205, de 22/07/2026."
    },
    {
        "id": "TAA-2026-LMA-2.1-014",
        "disciplina": "Conhecimentos Específicos",
        "eixo": "Legislação Marítima e Ambiental",
        "topicoEdital": "2.1 Fluxo de carreira",
        "assunto": "Cômputo qualitativo do tempo de embarque",
        "tipoOrigem": "inedita_farol",
        "origemInterna": "Inédita Farol 2026",
        "enunciado": "Na análise do tempo de embarque para ascensão, os registros da CIR são examinados qualitativamente para verificar",
        "alternativas": [
            "apenas se o aquaviário permaneceu embarcado por mais de 30 dias consecutivos.",
            "somente o nome comercial da empresa empregadora.",
            "se a embarcação navegou exclusivamente em águas internacionais.",
            "a compatibilidade dos registros de embarque da CIR com o CTS da embarcação e com a categoria/função necessária à ascensão pretendida.",
            "exclusivamente a soma bruta dos dias, sem considerar a função exercida."
        ],
        "correta": 3,
        "comentario": "A Marinha não considera apenas a quantidade de dias. Também verifica se o embarque ocorreu na categoria e função compatíveis com a ascensão pretendida, comparando registros da CIR e CTS.",
        "explicacaoCorreta": "A Marinha não considera apenas a quantidade de dias. Também verifica se o embarque ocorreu na categoria e função compatíveis com a ascensão pretendida, comparando registros da CIR e CTS.",
        "revisaoAssunto": "O tempo de embarque é quantitativo e qualitativo. Um período pode existir na CIR e ainda assim não servir para determinada ascensão se a função/categoria exercida não atender ao requisito. Fonte: NORMAM-101/DPC, itens 1.26 a 1.28; CPBA — Ascensão de Categoria, análise qualitativa dos registros da CIR e compatibilidade com o CTS.",
        "memorizar2026": "Tempo válido para ascensão = dias + categoria/função compatíveis.",
        "dicaMacete": "Cesgranrio gosta da oposição “somar dias” × “verificar função”.",
        "pegadinha": "A simples presença a bordo não garante que todo o tempo seja aproveitável para qualquer ascensão.",
        "analiseAlternativas": [
            "Incorreta. Não há regra geral de 30 dias consecutivos para validar o período.",
            "Incorreta. O empregador é dado documental, mas não é o núcleo da análise qualitativa.",
            "Incorreta. O critério não é navegação internacional exclusiva.",
            "Correta. É a análise descrita pela Marinha.",
            "Incorreta. A função exercida é relevante e pode impedir o cômputo do período."
        ],
        "fonte": "NORMAM-101/DPC, itens 1.26 a 1.28; CPBA — Ascensão de Categoria, análise qualitativa dos registros da CIR e compatibilidade com o CTS.",
        "atualizacao2026": "Referência conferida para o Banco 2026. A NORMAM-101/DPC vigente consta na página oficial da DPC vinculada à Portaria DPC/DGN/MB nº 205, de 22/07/2026."
    },
    {
        "id": "TAA-2026-LMA-2.1-015",
        "disciplina": "Conhecimentos Específicos",
        "eixo": "Legislação Marítima e Ambiental",
        "topicoEdital": "2.1 Fluxo de carreira",
        "assunto": "Tempo em função inferior",
        "tipoOrigem": "inedita_farol",
        "origemInterna": "Inédita Farol 2026",
        "enunciado": "Um aquaviário pretende utilizar, para ascensão, período em que esteve embarcado exercendo cargo ou função inferior à categoria ou qualificação exigida para a ascensão pretendida. Segundo a orientação da Marinha, esse período",
        "alternativas": [
            "é computado em dobro, por representar experiência adicional.",
            "é computado se a empresa autorizar expressamente.",
            "é sempre computado pela simples existência da anotação na CIR.",
            "é convertido automaticamente em tempo equivalente da categoria superior.",
            "não deve ser computado para a ascensão quando não comprovar o exercício na categoria e função necessárias."
        ],
        "correta": 4,
        "comentario": "A análise qualitativa busca evitar justamente o cômputo de tempo em cargo ou função inferior à categoria/qualificação necessária para a ascensão.",
        "explicacaoCorreta": "A análise qualitativa busca evitar justamente o cômputo de tempo em cargo ou função inferior à categoria/qualificação necessária para a ascensão.",
        "revisaoAssunto": "Para fins de carreira, não basta “ter estado embarcado”. O tempo precisa corresponder ao tipo de experiência previsto para a categoria pretendida. Fonte: NORMAM-101/DPC, itens 1.26 a 1.28; CPBA — Ascensão de Categoria, análise qualitativa do tempo.",
        "memorizar2026": "Função inferior incompatível ≠ tempo válido para ascensão pretendida.",
        "dicaMacete": "Pergunte sempre “em qual categoria e função esse embarque ocorreu?”.",
        "pegadinha": "A CIR é prova relevante, mas seu registro é analisado em conjunto com os requisitos da ascensão.",
        "analiseAlternativas": [
            "Incorreta. Não existe cômputo em dobro por função inferior.",
            "Incorreta. A empresa não pode afastar requisito normativo por autorização própria.",
            "Incorreta. A anotação é analisada qualitativamente.",
            "Incorreta. Não há conversão automática para categoria superior.",
            "Correta. O tempo precisa comprovar a experiência profissional exigida."
        ],
        "fonte": "NORMAM-101/DPC, itens 1.26 a 1.28; CPBA — Ascensão de Categoria, análise qualitativa do tempo.",
        "atualizacao2026": "Referência conferida para o Banco 2026. A NORMAM-101/DPC vigente consta na página oficial da DPC vinculada à Portaria DPC/DGN/MB nº 205, de 22/07/2026."
    },
    {
        "id": "TAA-2026-LMA-2.1-016",
        "disciplina": "Conhecimentos Específicos",
        "eixo": "Legislação Marítima e Ambiental",
        "topicoEdital": "2.1 Fluxo de carreira",
        "assunto": "Atestado de Embarque — Anexo 1-S",
        "tipoOrigem": "inedita_farol",
        "origemInterna": "Inédita Farol 2026",
        "enunciado": "Para comprovar o tempo de embarque em procedimentos como ascensão de categoria, a NORMAM-101/DPC prevê a apresentação do",
        "alternativas": [
            "Atestado de Embarque de Aquaviários, conforme modelo do Anexo 1-S.",
            "modelo de LCS do Anexo 2-D.",
            "certificado de praticagem previsto para o 5º Grupo.",
            "Anexo 1-G em todos os casos, inclusive embarques nacionais.",
            "Certificado de Segurança da Navegação da embarcação como documento único."
        ],
        "correta": 0,
        "comentario": "O Anexo 1-S é o modelo de Atestado de Embarque de Aquaviários utilizado na comprovação do tempo, em conjunto com os registros da CIR.",
        "explicacaoCorreta": "O Anexo 1-S é o modelo de Atestado de Embarque de Aquaviários utilizado na comprovação do tempo, em conjunto com os registros da CIR.",
        "revisaoAssunto": "O cômputo para ascensão exige coerência documental. O Anexo 1-S é preenchido pela empresa com base em seus registros e confrontado com as folhas de embarque da CIR. Fonte: NORMAM-101/DPC, item 1.26.1 e Anexo 1-S; CPBA/CIAGA — comprovação e contagem do tempo de embarque.",
        "memorizar2026": "Anexo 1-S = Atestado de Embarque.",
        "dicaMacete": "“S” de serviço/sea service ajuda a lembrar o documento de embarque.",
        "pegadinha": "O Anexo 1-G aparece especificamente quando há tempo em navio de bandeira estrangeira.",
        "analiseAlternativas": [
            "Correta. É o documento indicado pela norma para comprovação do tempo de embarque.",
            "Incorreta. O Anexo 2-D é vinculado à Licença de Categoria/Capacidade Superior.",
            "Incorreta. Certificação de Prático não substitui o atestado de embarque.",
            "Incorreta. O Anexo 1-G é utilizado quando aplicável a embarques em navios de bandeira estrangeira.",
            "Incorreta. CTS/CSN da embarcação não substitui a documentação do tempo individual do aquaviário."
        ],
        "fonte": "NORMAM-101/DPC, item 1.26.1 e Anexo 1-S; CPBA/CIAGA — comprovação e contagem do tempo de embarque.",
        "atualizacao2026": "Referência conferida para o Banco 2026. A NORMAM-101/DPC vigente consta na página oficial da DPC vinculada à Portaria DPC/DGN/MB nº 205, de 22/07/2026."
    },
    {
        "id": "TAA-2026-LMA-2.1-017",
        "disciplina": "Conhecimentos Específicos",
        "eixo": "Legislação Marítima e Ambiental",
        "topicoEdital": "2.1 Fluxo de carreira",
        "assunto": "Preenchimento do Anexo 1-S",
        "tipoOrigem": "inedita_farol",
        "origemInterna": "Inédita Farol 2026",
        "enunciado": "Ao preencher o Anexo 1-S para comprovação do tempo de embarque de um aquaviário, a empresa de navegação deve basear-se",
        "alternativas": [
            "na declaração verbal do comandante, independentemente de seus registros.",
            "exclusivamente em seus registros de tempo de embarque do sistema de controle interno e no rol das embarcações.",
            "apenas nas anotações manuscritas apresentadas pelo próprio aquaviário.",
            "em estimativa do período médio trabalhado por empregados da mesma categoria.",
            "somente nos recolhimentos previdenciários, dispensados os registros marítimos."
        ],
        "correta": 1,
        "comentario": "A NORMAM determina que a empresa preencha o Anexo 1-S com base exclusivamente em seus registros de controle interno e no rol das embarcações.",
        "explicacaoCorreta": "A NORMAM determina que a empresa preencha o Anexo 1-S com base exclusivamente em seus registros de controle interno e no rol das embarcações.",
        "revisaoAssunto": "Esse procedimento cria uma trilha documental que será comparada com a CIR pela Autoridade Marítima. A lógica é impedir que o tempo seja comprovado apenas por declarações não verificáveis. Fonte: NORMAM-101/DPC, item 1.26.1, alíneas “a” a “e”; CIAGA — Comprovação e Contagem do Tempo de Embarque.",
        "memorizar2026": "Empresa: controle interno + rol → Anexo 1-S.",
        "dicaMacete": "Pense em duas fontes empresariais: sistema interno e rol.",
        "pegadinha": "Contribuição previdenciária pode ter outras finalidades, mas não substitui a comprovação marítima prevista para ascensão.",
        "analiseAlternativas": [
            "Incorreta. A norma exige registros objetivos da empresa.",
            "Correta. É a base documental expressamente indicada.",
            "Incorreta. O aquaviário apresenta documentos, mas não substitui os registros empresariais.",
            "Incorreta. Estimativa não comprova tempo individual.",
            "Incorreta. Registros previdenciários não são o documento substitutivo previsto no procedimento."
        ],
        "fonte": "NORMAM-101/DPC, item 1.26.1, alíneas “a” a “e”; CIAGA — Comprovação e Contagem do Tempo de Embarque.",
        "atualizacao2026": "Referência conferida para o Banco 2026. A NORMAM-101/DPC vigente consta na página oficial da DPC vinculada à Portaria DPC/DGN/MB nº 205, de 22/07/2026."
    },
    {
        "id": "TAA-2026-LMA-2.1-018",
        "disciplina": "Conhecimentos Específicos",
        "eixo": "Legislação Marítima e Ambiental",
        "topicoEdital": "2.1 Fluxo de carreira",
        "assunto": "Divergência CIR × Anexo 1-S",
        "tipoOrigem": "inedita_farol",
        "origemInterna": "Inédita Farol 2026",
        "enunciado": "Durante a conferência do tempo de embarque, a Autoridade Marítima identifica períodos e categorias que aparecem no Anexo 1-S, mas não coincidem com as folhas de registro de embarque da CIR. Esses períodos",
        "alternativas": [
            "devem ser aceitos pela metade.",
            "são aceitos se superiores a seis meses.",
            "não são considerados para o cômputo do tempo de embarque.",
            "são convertidos em tempo de estágio.",
            "devem ser homologados automaticamente pelo armador."
        ],
        "correta": 2,
        "comentario": "No confronto documental, períodos/categorias não coincidentes entre os registros não são considerados para o cômputo.",
        "explicacaoCorreta": "No confronto documental, períodos/categorias não coincidentes entre os registros não são considerados para o cômputo.",
        "revisaoAssunto": "A Cesgranrio pode transformar uma regra documental simples em caso prático. O importante é lembrar que a comprovação exige consistência entre CIR e Anexo 1-S. Fonte: NORMAM-101/DPC, item 1.26.1, alíneas “c” a “e”; CIAGA — Comprovação e Contagem do Tempo de Embarque.",
        "memorizar2026": "CIR e 1-S precisam coincidir.",
        "dicaMacete": "Divergiu período/categoria? Desconfie do cômputo.",
        "pegadinha": "A empresa não tem poder de homologar unilateralmente divergência perante a Autoridade Marítima.",
        "analiseAlternativas": [
            "Incorreta. A norma não cria cômputo pela metade.",
            "Incorreta. A duração não sana divergência documental.",
            "Correta. Períodos/categorias não coincidentes não são computados.",
            "Incorreta. Divergência não se converte automaticamente em estágio.",
            "Incorreta. A análise cabe aos representantes da Autoridade Marítima."
        ],
        "fonte": "NORMAM-101/DPC, item 1.26.1, alíneas “c” a “e”; CIAGA — Comprovação e Contagem do Tempo de Embarque.",
        "atualizacao2026": "Referência conferida para o Banco 2026. A NORMAM-101/DPC vigente consta na página oficial da DPC vinculada à Portaria DPC/DGN/MB nº 205, de 22/07/2026."
    },
    {
        "id": "TAA-2026-LMA-2.1-019",
        "disciplina": "Conhecimentos Específicos",
        "eixo": "Legislação Marítima e Ambiental",
        "topicoEdital": "2.1 Fluxo de carreira",
        "assunto": "Embarques em mais de uma empresa",
        "tipoOrigem": "inedita_farol",
        "origemInterna": "Inédita Farol 2026",
        "enunciado": "Um aquaviário trabalhou, em períodos distintos, para três empresas de navegação e pretende comprovar esses embarques para fins de carreira. No procedimento do Anexo 1-S, ele deverá",
        "alternativas": [
            "escolher apenas a empresa do maior período e desprezar as demais.",
            "pedir que a empresa atual certifique também os embarques realizados nas antigas empregadoras.",
            "apresentar somente a CIR, pois o Anexo 1-S é dispensado quando há mais de uma empresa.",
            "solicitar o Anexo 1-S às empresas correspondentes aos períodos de embarque que pretende comprovar, conforme o procedimento aplicável.",
            "solicitar à ANTAQ um único mapa consolidado de todos os vínculos."
        ],
        "correta": 3,
        "comentario": "O procedimento de cômputo prevê que o aquaviário obtenha o Anexo 1-S das empresas nas quais realizou os períodos que serão comprovados, para confronto com a CIR.",
        "explicacaoCorreta": "O procedimento de cômputo prevê que o aquaviário obtenha o Anexo 1-S das empresas nas quais realizou os períodos que serão comprovados, para confronto com a CIR.",
        "revisaoAssunto": "Cada empresa certifica os períodos existentes em seus próprios registros. Uma empresa atual não pode simplesmente declarar, em nome das anteriores, tempos que não constem de seu controle. Fonte: NORMAM-101/DPC, item 1.26.1; CIAGA — Comprovação e Contagem do Tempo de Embarque.",
        "memorizar2026": "Mais de uma empresa → documentação correspondente a cada vínculo/período.",
        "dicaMacete": "Quem tem o registro é quem certifica o período.",
        "pegadinha": "A exceção para empresa encerrada possui tratamento extraordinário próprio; não autoriza a empresa atual a assumir todos os registros.",
        "analiseAlternativas": [
            "Incorreta. Períodos válidos de outras empresas podem ser relevantes e não devem ser descartados por essa razão.",
            "Incorreta. A empresa atual deve basear-se nos próprios registros.",
            "Incorreta. A existência de várias empresas não dispensa automaticamente o Anexo 1-S.",
            "Correta. Cada período deve ser documentalmente comprovado conforme a origem dos registros.",
            "Incorreta. A ANTAQ não emite esse mapa de carreira individual."
        ],
        "fonte": "NORMAM-101/DPC, item 1.26.1; CIAGA — Comprovação e Contagem do Tempo de Embarque.",
        "atualizacao2026": "Referência conferida para o Banco 2026. A NORMAM-101/DPC vigente consta na página oficial da DPC vinculada à Portaria DPC/DGN/MB nº 205, de 22/07/2026."
    },
    {
        "id": "TAA-2026-LMA-2.1-020",
        "disciplina": "Conhecimentos Específicos",
        "eixo": "Legislação Marítima e Ambiental",
        "topicoEdital": "2.1 Fluxo de carreira",
        "assunto": "Embarque em navio de bandeira estrangeira",
        "tipoOrigem": "inedita_farol",
        "origemInterna": "Inédita Farol 2026",
        "enunciado": "Quando aplicável, o documento específico indicado pela NORMAM-101/DPC para comprovação de tempo de embarque em navio de bandeira estrangeira é o",
        "alternativas": [
            "Anexo 2-A.",
            "Anexo 2-D.",
            "Rol Portuário.",
            "Certificado de Segurança da Navegação.",
            "Anexo 1-G."
        ],
        "correta": 4,
        "comentario": "Para tempo de embarque em navios de bandeira estrangeira, a documentação do serviço de ascensão remete ao Anexo 1-G da NORMAM-101/DPC, quando aplicável.",
        "explicacaoCorreta": "Para tempo de embarque em navios de bandeira estrangeira, a documentação do serviço de ascensão remete ao Anexo 1-G da NORMAM-101/DPC, quando aplicável.",
        "revisaoAssunto": "Não confunda os anexos: 1-S é o Atestado de Embarque usado no cômputo ordinário; 1-G aparece para tempo em navio estrangeiro; 2-A é o Quadro Geral de Certificações; 2-D é LCS. Fonte: NORMAM-101/DPC, Anexo 1-G; CPBA — Ascensão de Categoria, documentação necessária.",
        "memorizar2026": "Navio estrangeiro → lembre do Anexo 1-G.",
        "dicaMacete": "Faça um mapa dos anexos: 1-G estrangeiro; 1-S embarque; 2-A carreira; 2-D LCS.",
        "pegadinha": "A Cesgranrio pode cobrar o número do anexo dentro de uma situação prática.",
        "analiseAlternativas": [
            "Incorreta. Anexo 2-A é o Quadro Geral de Certificações.",
            "Incorreta. Anexo 2-D é o modelo de LCS.",
            "Incorreta. Rol Portuário tem outra finalidade.",
            "Incorreta. CSN não é o documento individual indicado para comprovar esse tempo.",
            "Correta. É o anexo indicado para embarque em navio de bandeira estrangeira, quando aplicável."
        ],
        "fonte": "NORMAM-101/DPC, Anexo 1-G; CPBA — Ascensão de Categoria, documentação necessária.",
        "atualizacao2026": "Referência conferida para o Banco 2026. A NORMAM-101/DPC vigente consta na página oficial da DPC vinculada à Portaria DPC/DGN/MB nº 205, de 22/07/2026."
    },
    {
        "id": "TAA-2026-LMA-2.1-021",
        "disciplina": "Conhecimentos Específicos",
        "eixo": "Legislação Marítima e Ambiental",
        "topicoEdital": "2.1 Fluxo de carreira",
        "assunto": "Transferência de categoria — caráter excepcional",
        "tipoOrigem": "inedita_farol",
        "origemInterna": "Inédita Farol 2026",
        "enunciado": "A transferência de categoria entre Seções e/ou Grupos diferentes, segundo a NORMAM-101/DPC,",
        "alternativas": [
            "é excepcional e pode ser concedida pelo Capitão dos Portos, mediante requerimento e análise dos requisitos.",
            "é automática quando duas categorias possuem o mesmo nível de equivalência.",
            "é obrigatória sempre que o aquaviário muda de empresa de navegação.",
            "independe de avaliação de competência profissional.",
            "é decidida exclusivamente pelo empregador do aquaviário."
        ],
        "correta": 0,
        "comentario": "A transferência entre grupos/seções não é uma promoção automática; tem caráter excepcional e depende de avaliação e decisão do Capitão dos Portos.",
        "explicacaoCorreta": "A transferência entre grupos/seções não é uma promoção automática; tem caráter excepcional e depende de avaliação e decisão do Capitão dos Portos.",
        "revisaoAssunto": "Ascensão e transferência não são sinônimos. A transferência muda grupo e/ou seção e exige análise de equivalência profissional e dos requisitos da categoria pretendida. Fonte: NORMAM-101/DPC, Capítulo 2, art. 2.4; DPC/CPBA — Transferência de Categoria entre Seções e/ou Grupos Diferentes.",
        "memorizar2026": "Transferência entre grupos/seções = excepcional.",
        "dicaMacete": "Mesmo nível não significa transferência automática.",
        "pegadinha": "A banca pode chamar transferência de “ascensão lateral”; juridicamente os procedimentos são distintos.",
        "analiseAlternativas": [
            "Correta. Resume o caráter excepcional do procedimento.",
            "Incorreta. Nível de equivalência não prova competência equivalente entre grupos.",
            "Incorreta. Troca de empresa não produz transferência de categoria.",
            "Incorreta. A avaliação de competência é elemento central.",
            "Incorreta. O empregador não substitui a decisão da Autoridade Marítima."
        ],
        "fonte": "NORMAM-101/DPC, Capítulo 2, art. 2.4; DPC/CPBA — Transferência de Categoria entre Seções e/ou Grupos Diferentes.",
        "atualizacao2026": "Referência conferida para o Banco 2026. A NORMAM-101/DPC vigente consta na página oficial da DPC vinculada à Portaria DPC/DGN/MB nº 205, de 22/07/2026."
    },
    {
        "id": "TAA-2026-LMA-2.1-022",
        "disciplina": "Conhecimentos Específicos",
        "eixo": "Legislação Marítima e Ambiental",
        "topicoEdital": "2.1 Fluxo de carreira",
        "assunto": "Transferência de categoria — critérios",
        "tipoOrigem": "inedita_farol",
        "origemInterna": "Inédita Farol 2026",
        "enunciado": "Na análise de transferência de categoria entre grupos e/ou seções, a DPC destaca, entre os critérios,",
        "alternativas": [
            "apenas o tempo total de contribuição previdenciária do interessado.",
            "os requisitos de habilitação para o grupo pretendido, os requisitos de ingresso na categoria pretendida e a justificativa de necessidade do mercado de trabalho.",
            "somente a existência de vaga na empresa atual.",
            "apenas a identidade de nível de equivalência entre as duas categorias.",
            "exclusivamente o tempo de embarque na última embarcação."
        ],
        "correta": 1,
        "comentario": "A transferência exige análise mais ampla que a simples comparação de níveis: habilitação para o grupo, ingresso na categoria e necessidade do mercado integram a avaliação.",
        "explicacaoCorreta": "A transferência exige análise mais ampla que a simples comparação de níveis: habilitação para o grupo, ingresso na categoria e necessidade do mercado integram a avaliação.",
        "revisaoAssunto": "O procedimento é excepcional justamente porque pode deslocar o aquaviário entre estruturas profissionais diferentes. A Autoridade Marítima avalia formação, requisitos e necessidade. Fonte: NORMAM-101/DPC, Capítulo 2, art. 2.4; DPC — Documentação e Certificação de Pessoal Aquaviário.",
        "memorizar2026": "Transferência: grupo + categoria + mercado.",
        "dicaMacete": "Memorize três filtros: habilitação, ingresso e necessidade.",
        "pegadinha": "“Mesmo nível” sozinho não basta.",
        "analiseAlternativas": [
            "Incorreta. Previdência não é o critério central de transferência de categoria.",
            "Correta. São os três pontos destacados pela DPC.",
            "Incorreta. Vaga empresarial isolada não basta.",
            "Incorreta. Equivalência numérica não significa competência equivalente.",
            "Incorreta. Tempo de embarque pode integrar a análise, mas não é o único critério indicado."
        ],
        "fonte": "NORMAM-101/DPC, Capítulo 2, art. 2.4; DPC — Documentação e Certificação de Pessoal Aquaviário.",
        "atualizacao2026": "Referência conferida para o Banco 2026. A NORMAM-101/DPC vigente consta na página oficial da DPC vinculada à Portaria DPC/DGN/MB nº 205, de 22/07/2026."
    },
    {
        "id": "TAA-2026-LMA-2.1-023",
        "disciplina": "Conhecimentos Específicos",
        "eixo": "Legislação Marítima e Ambiental",
        "topicoEdital": "2.1 Fluxo de carreira",
        "assunto": "Nível de equivalência e competência",
        "tipoOrigem": "inedita_farol",
        "origemInterna": "Inédita Farol 2026",
        "enunciado": "Dois aquaviários de grupos diferentes possuem categorias classificadas no mesmo nível de equivalência. A partir desse dado, é correto concluir que",
        "alternativas": [
            "eles possuem automaticamente as mesmas regras STCW e capacidades.",
            "um pode transferir-se para a categoria do outro sem requerimento.",
            "o mesmo nível, por si só, não basta para estabelecer equivalência de competência entre grupos diferentes.",
            "a Autoridade Marítima deve conceder transferência automática.",
            "a diferença de qualificação entre grupos deixa de ter relevância."
        ],
        "correta": 2,
        "comentario": "A DPC adverte expressamente que o nível de equivalência não basta para comparar competência entre aquaviários de grupos diferentes.",
        "explicacaoCorreta": "A DPC adverte expressamente que o nível de equivalência não basta para comparar competência entre aquaviários de grupos diferentes.",
        "revisaoAssunto": "O número do nível é uma referência de enquadramento, não uma declaração de identidade profissional. Grupos diferentes podem exigir qualificações, cursos e capacidades significativamente distintos. Fonte: NORMAM-101/DPC, Capítulo 2, art. 2.4; DPC — Perguntas Frequentes sobre transferência de categoria.",
        "memorizar2026": "Mesmo nível ≠ mesma competência.",
        "dicaMacete": "Se a questão trocar “equivalência de nível” por “equivalência de competência”, desconfie.",
        "pegadinha": "Esse é um excelente distrator porque a palavra “equivalência” induz a pensar em identidade completa.",
        "analiseAlternativas": [
            "Incorreta. Regras e capacidades dependem da habilitação específica.",
            "Incorreta. Transferência exige procedimento e análise.",
            "Correta. É a ressalva expressa da DPC.",
            "Incorreta. Não há automatismo por igualdade de nível.",
            "Incorreta. Diferenças de qualificação continuam relevantes."
        ],
        "fonte": "NORMAM-101/DPC, Capítulo 2, art. 2.4; DPC — Perguntas Frequentes sobre transferência de categoria.",
        "atualizacao2026": "Referência conferida para o Banco 2026. A NORMAM-101/DPC vigente consta na página oficial da DPC vinculada à Portaria DPC/DGN/MB nº 205, de 22/07/2026."
    },
    {
        "id": "TAA-2026-LMA-2.1-024",
        "disciplina": "Conhecimentos Específicos",
        "eixo": "Legislação Marítima e Ambiental",
        "topicoEdital": "2.1 Fluxo de carreira",
        "assunto": "Complementação para transferência",
        "tipoOrigem": "inedita_farol",
        "origemInterna": "Inédita Farol 2026",
        "enunciado": "Na transferência de categoria entre grupos/seções, se a formação anterior não for suficiente para a nova categoria pretendida, a Autoridade Marítima poderá exigir complementação por meio de",
        "alternativas": [
            "apenas novo exame médico, dispensada formação profissional.",
            "somente declaração da empresa atestando experiência.",
            "exclusivamente pagamento de taxa adicional.",
            "aulas, treinamentos, embarques e/ou provas escritas ou práticas, conforme a necessidade de nivelamento profissional.",
            "conversão automática do tempo de serviço em certificado de competência."
        ],
        "correta": 3,
        "comentario": "A DPC prevê que a formação possa ser complementada com aulas, treinamento, embarque e/ou provas escritas ou práticas para alcançar os requisitos mínimos da categoria pretendida.",
        "explicacaoCorreta": "A DPC prevê que a formação possa ser complementada com aulas, treinamento, embarque e/ou provas escritas ou práticas para alcançar os requisitos mínimos da categoria pretendida.",
        "revisaoAssunto": "A análise compara o conteúdo da formação anterior com o currículo vigente da categoria pretendida. Havendo lacunas, pode haver complementação, em vez de simples equivalência burocrática. Fonte: NORMAM-101/DPC, Capítulo 2, art. 2.4; CPBA — Transferência de Categoria entre Seções e/ou Grupos Diferentes.",
        "memorizar2026": "Transferência pode exigir nivelamento profissional.",
        "dicaMacete": "Formação diferente → pode haver aulas, treino, embarque ou prova.",
        "pegadinha": "Experiência empresarial não substitui automaticamente o currículo profissional exigido.",
        "analiseAlternativas": [
            "Incorreta. Exame de saúde não substitui formação profissional.",
            "Incorreta. Declaração empresarial isolada não supre lacunas curriculares.",
            "Incorreta. Taxa não substitui avaliação de competência.",
            "Correta. São formas de complementação mencionadas pela Marinha.",
            "Incorreta. Tempo de serviço não se converte automaticamente em certificado."
        ],
        "fonte": "NORMAM-101/DPC, Capítulo 2, art. 2.4; CPBA — Transferência de Categoria entre Seções e/ou Grupos Diferentes.",
        "atualizacao2026": "Referência conferida para o Banco 2026. A NORMAM-101/DPC vigente consta na página oficial da DPC vinculada à Portaria DPC/DGN/MB nº 205, de 22/07/2026."
    },
    {
        "id": "TAA-2026-LMA-2.1-025",
        "disciplina": "Conhecimentos Específicos",
        "eixo": "Legislação Marítima e Ambiental",
        "topicoEdital": "2.1 Fluxo de carreira",
        "assunto": "Transferência de categoria x transferência de jurisdição",
        "tipoOrigem": "inedita_farol",
        "origemInterna": "Inédita Farol 2026",
        "enunciado": "Um aquaviário muda sua residência e passa a exercer a atividade em localidade sob responsabilidade de outra Organização Militar, mantendo a mesma categoria profissional. O procedimento correspondente é",
        "alternativas": [
            "ascensão de categoria.",
            "Licença de Categoria Superior.",
            "transferência de categoria entre seções.",
            "nova inscrição como aquaviário.",
            "transferência de jurisdição."
        ],
        "correta": 4,
        "comentario": "A mudança da OM responsável pelo cadastro em razão do local de residência/atividade é transferência de jurisdição, não alteração de categoria.",
        "explicacaoCorreta": "A mudança da OM responsável pelo cadastro em razão do local de residência/atividade é transferência de jurisdição, não alteração de categoria.",
        "revisaoAssunto": "A transferência de jurisdição muda a OM responsável pelos principais lançamentos da carreira na CIR e no SISAQUA. A categoria profissional pode permanecer exatamente a mesma. Fonte: NORMAM-101/DPC, item/art. 1.30; DPC — Documentação e Certificação de Pessoal Aquaviário.",
        "memorizar2026": "Mudou a OM responsável, não a profissão → transferência de jurisdição.",
        "dicaMacete": "Pergunte: mudou a categoria ou apenas a jurisdição administrativa?",
        "pegadinha": "“Transferência” aparece em dois procedimentos diferentes; a banca pode explorar essa semelhança de nomes.",
        "analiseAlternativas": [
            "Incorreta. Não há elevação para categoria superior.",
            "Incorreta. LCS autoriza temporariamente função superior em embarcação específica.",
            "Incorreta. A seção profissional foi mantida.",
            "Incorreta. O aquaviário já está inscrito.",
            "Correta. É a situação típica de transferência de jurisdição."
        ],
        "fonte": "NORMAM-101/DPC, item/art. 1.30; DPC — Documentação e Certificação de Pessoal Aquaviário.",
        "atualizacao2026": "Referência conferida para o Banco 2026. A NORMAM-101/DPC vigente consta na página oficial da DPC vinculada à Portaria DPC/DGN/MB nº 205, de 22/07/2026."
    },
    {
        "id": "TAA-2026-LMA-2.1-026",
        "disciplina": "Conhecimentos Específicos",
        "eixo": "Legislação Marítima e Ambiental",
        "topicoEdital": "2.1 Fluxo de carreira",
        "assunto": "Licença de Categoria/Capacidade Superior — conceito",
        "tipoOrigem": "inedita_farol",
        "origemInterna": "Inédita Farol 2026",
        "enunciado": "A Licença de Categoria/Capacidade Superior (LCS) é",
        "alternativas": [
            "autorização temporária para o aquaviário exercer, em embarcação específica, funções pertinentes a categoria/capacidade superior à de seu enquadramento.",
            "promoção definitiva para a categoria imediatamente superior.",
            "documento que substitui permanentemente a CIR.",
            "autorização genérica para servir em qualquer embarcação de qualquer arqueação.",
            "modalidade de transferência de jurisdição entre Capitanias."
        ],
        "correta": 0,
        "comentario": "A LCS autoriza temporariamente o exercício de funções superiores em uma embarcação específica; ela não altera definitivamente a categoria do aquaviário.",
        "explicacaoCorreta": "A LCS autoriza temporariamente o exercício de funções superiores em uma embarcação específica; ela não altera definitivamente a categoria do aquaviário.",
        "revisaoAssunto": "A diferença fundamental é temporal e funcional: LCS é excepcional e limitada; ascensão é alteração formal da categoria quando os requisitos são cumpridos. Fonte: NORMAM-101/DPC, Capítulo 2, art. 2.3 e Anexo 2-D; DPC — Perguntas Frequentes sobre LCS.",
        "memorizar2026": "LCS ≠ promoção definitiva.",
        "dicaMacete": "“Licença” lembra autorização temporária, não ascensão.",
        "pegadinha": "A alternativa pode parecer promoção porque permite exercer função superior, mas o enquadramento real permanece distinto.",
        "analiseAlternativas": [
            "Correta. Resume a natureza jurídica da LCS.",
            "Incorreta. A licença não promove definitivamente o aquaviário.",
            "Incorreta. A CIR continua sendo documento profissional.",
            "Incorreta. A LCS está vinculada a embarcação específica.",
            "Incorreta. Jurisdição é procedimento administrativo diferente."
        ],
        "fonte": "NORMAM-101/DPC, Capítulo 2, art. 2.3 e Anexo 2-D; DPC — Perguntas Frequentes sobre LCS.",
        "atualizacao2026": "Referência conferida para o Banco 2026. A NORMAM-101/DPC vigente consta na página oficial da DPC vinculada à Portaria DPC/DGN/MB nº 205, de 22/07/2026."
    },
    {
        "id": "TAA-2026-LMA-2.1-027",
        "disciplina": "Conhecimentos Específicos",
        "eixo": "Legislação Marítima e Ambiental",
        "topicoEdital": "2.1 Fluxo de carreira",
        "assunto": "LCS — prazo e embarcação específica",
        "tipoOrigem": "inedita_farol",
        "origemInterna": "Inédita Farol 2026",
        "enunciado": "Quanto à duração e ao alcance da Licença de Categoria/Capacidade Superior, a NORMAM-101/DPC estabelece que ela",
        "alternativas": [
            "é válida por prazo indeterminado enquanto persistir o vínculo empregatício.",
            "é concedida para embarcação específica e por período determinado que não pode exceder seis meses.",
            "é válida por doze meses para qualquer embarcação da mesma empresa.",
            "pode ser usada em qualquer embarcação nacional durante três anos.",
            "não possui limite temporal quando autorizada pelo armador."
        ],
        "correta": 1,
        "comentario": "A LCS é individualizada para embarcação específica e tem prazo determinado, limitado a seis meses.",
        "explicacaoCorreta": "A LCS é individualizada para embarcação específica e tem prazo determinado, limitado a seis meses.",
        "revisaoAssunto": "O próprio modelo de LCS contém dados como nome e arqueação bruta da embarcação, reforçando que a autorização não é genérica para a frota inteira. Fonte: NORMAM-101/DPC, Capítulo 2, art. 2.3 e Anexo 2-D; DPC — Documentação e Certificação de Pessoal Aquaviário.",
        "memorizar2026": "LCS = embarcação específica + máximo 6 meses.",
        "dicaMacete": "Se aparecer “qualquer navio da empresa”, está errado.",
        "pegadinha": "O caráter temporário diferencia a LCS da ascensão formal.",
        "analiseAlternativas": [
            "Incorreta. Não é licença por prazo indeterminado.",
            "Correta. Esses são os limites informados pela DPC.",
            "Incorreta. Não há autorização genérica anual para a frota.",
            "Incorreta. A LCS não é habilitação ampla de três anos.",
            "Incorreta. O armador não afasta o limite normativo."
        ],
        "fonte": "NORMAM-101/DPC, Capítulo 2, art. 2.3 e Anexo 2-D; DPC — Documentação e Certificação de Pessoal Aquaviário.",
        "atualizacao2026": "Referência conferida para o Banco 2026. A NORMAM-101/DPC vigente consta na página oficial da DPC vinculada à Portaria DPC/DGN/MB nº 205, de 22/07/2026."
    },
    {
        "id": "TAA-2026-LMA-2.1-028",
        "disciplina": "Conhecimentos Específicos",
        "eixo": "Legislação Marítima e Ambiental",
        "topicoEdital": "2.1 Fluxo de carreira",
        "assunto": "LCS — excepcionalidade e iniciativa",
        "tipoOrigem": "inedita_farol",
        "origemInterna": "Inédita Farol 2026",
        "enunciado": "Uma empresa pretende obter LCS para um aquaviário. De acordo com a orientação da DPC, a licença deve ser concedida",
        "alternativas": [
            "sempre que a empresa alegar redução de custos operacionais.",
            "automaticamente quando o aquaviário possuir mais de cinco anos de CIR.",
            "em circunstâncias excepcionais, depois de esgotados os recursos para substituição do tripulante, mediante solicitação da empresa.",
            "apenas após ascensão definitiva do aquaviário.",
            "pelo sindicato, sem participação da Autoridade Marítima."
        ],
        "correta": 2,
        "comentario": "A LCS só deve ser concedida em situação excepcional e após esgotados os recursos para substituir o tripulante, mediante solicitação formal da empresa.",
        "explicacaoCorreta": "A LCS só deve ser concedida em situação excepcional e após esgotados os recursos para substituir o tripulante, mediante solicitação formal da empresa.",
        "revisaoAssunto": "Esse desenho evita que a licença seja usada como atalho permanente para suprir tripulação em categoria superior. Trata-se de solução excepcional, controlada pela Autoridade Marítima. Fonte: NORMAM-101/DPC, Capítulo 2, art. 2.3; DPC — Perguntas Frequentes sobre LCS.",
        "memorizar2026": "LCS = exceção + falta de substituto + pedido da empresa.",
        "dicaMacete": "Compare com ascensão: ascensão é requerida pelo aquaviário; LCS nasce de necessidade excepcional da empresa.",
        "pegadinha": "Experiência longa não transforma a licença em direito automático.",
        "analiseAlternativas": [
            "Incorreta. Economia operacional não é fundamento automático da licença.",
            "Incorreta. Tempo de CIR não gera LCS automática.",
            "Correta. É a condição de excepcionalidade destacada pela DPC.",
            "Incorreta. Se já houve ascensão definitiva, a lógica da LCS para aquela superioridade muda completamente.",
            "Incorreta. A licença é concedida pela Autoridade Marítima competente."
        ],
        "fonte": "NORMAM-101/DPC, Capítulo 2, art. 2.3; DPC — Perguntas Frequentes sobre LCS.",
        "atualizacao2026": "Referência conferida para o Banco 2026. A NORMAM-101/DPC vigente consta na página oficial da DPC vinculada à Portaria DPC/DGN/MB nº 205, de 22/07/2026."
    },
    {
        "id": "TAA-2026-LMA-2.1-029",
        "disciplina": "Conhecimentos Específicos",
        "eixo": "Legislação Marítima e Ambiental",
        "topicoEdital": "2.1 Fluxo de carreira",
        "assunto": "Ascensão x LCS",
        "tipoOrigem": "inedita_farol",
        "origemInterna": "Inédita Farol 2026",
        "enunciado": "Um aquaviário recebe autorização por quatro meses para exercer capacidade superior à de seu enquadramento em uma embarcação determinada. Ao término, essa autorização, por si só,",
        "alternativas": [
            "transforma automaticamente o período em ascensão definitiva.",
            "dispensa qualquer requisito futuro do Anexo 2-A.",
            "transfere o aquaviário para outro grupo profissional.",
            "não equivale a ascensão definitiva de categoria, pois caracteriza LCS temporária.",
            "altera permanentemente a categoria impressa na CIR."
        ],
        "correta": 3,
        "comentario": "Exercer temporariamente função superior por LCS não é o mesmo que ascender de categoria. A ascensão exige o cumprimento do fluxo e dos requisitos próprios.",
        "explicacaoCorreta": "Exercer temporariamente função superior por LCS não é o mesmo que ascender de categoria. A ascensão exige o cumprimento do fluxo e dos requisitos próprios.",
        "revisaoAssunto": "A banca pode explorar o efeito prático semelhante — “exercer função superior” — para confundir institutos distintos. O ponto decisivo é que a LCS é temporária e vinculada à embarcação. Fonte: NORMAM-101/DPC, Capítulo 2, arts. 2.3 e 2.4; Anexo 2-A e Anexo 2-D; DPC — Perguntas Frequentes.",
        "memorizar2026": "LCS temporária ≠ ascensão definitiva.",
        "dicaMacete": "Pergunte se houve mudança permanente da categoria ou apenas autorização temporária.",
        "pegadinha": "Exercer uma função superior não significa, sozinho, possuir a categoria superior.",
        "analiseAlternativas": [
            "Incorreta. A licença não se converte automaticamente em ascensão.",
            "Incorreta. Requisitos do Anexo 2-A continuam aplicáveis à ascensão.",
            "Incorreta. LCS não produz transferência automática de grupo.",
            "Correta. A situação descrita é típica de LCS.",
            "Incorreta. O enquadramento não se torna definitivamente superior pela licença."
        ],
        "fonte": "NORMAM-101/DPC, Capítulo 2, arts. 2.3 e 2.4; Anexo 2-A e Anexo 2-D; DPC — Perguntas Frequentes.",
        "atualizacao2026": "Referência conferida para o Banco 2026. A NORMAM-101/DPC vigente consta na página oficial da DPC vinculada à Portaria DPC/DGN/MB nº 205, de 22/07/2026."
    },
    {
        "id": "TAA-2026-LMA-2.1-030",
        "disciplina": "Conhecimentos Específicos",
        "eixo": "Legislação Marítima e Ambiental",
        "topicoEdital": "2.1 Fluxo de carreira",
        "assunto": "Anexo 2-D — LCS",
        "tipoOrigem": "inedita_farol",
        "origemInterna": "Inédita Farol 2026",
        "enunciado": "O modelo documental indicado pela DPC para concessão da Licença de Categoria/Capacidade Superior é o",
        "alternativas": [
            "Anexo 1-G.",
            "Anexo 1-S.",
            "Anexo 2-A.",
            "Anexo 1-L.",
            "Anexo 2-D."
        ],
        "correta": 4,
        "comentario": "O Anexo 2-D da NORMAM-101/DPC é o modelo utilizado para a Licença de Categoria/Capacidade Superior.",
        "explicacaoCorreta": "O Anexo 2-D da NORMAM-101/DPC é o modelo utilizado para a Licença de Categoria/Capacidade Superior.",
        "revisaoAssunto": "Os anexos têm funções diferentes. Para prova, a associação mais importante neste ponto é: Anexo 2-D = LCS. Fonte: NORMAM-101/DPC, Capítulo 2, art. 2.3 e Anexo 2-D; DPC — Perguntas Frequentes.",
        "memorizar2026": "2-D = Licença de Categoria/Capacidade Superior.",
        "dicaMacete": "Guarde o trio: 1-S embarque; 2-A carreira; 2-D LCS.",
        "pegadinha": "O número do anexo é um detalhe típico para a banca colocar em alternativas parecidas.",
        "analiseAlternativas": [
            "Incorreta. 1-G está ligado a embarque em navio estrangeiro.",
            "Incorreta. 1-S é o Atestado de Embarque.",
            "Incorreta. 2-A é o Quadro Geral de Certificações.",
            "Incorreta. 1-L é utilizado em outros procedimentos documentais, não é o modelo da LCS.",
            "Correta. O modelo da LCS é o Anexo 2-D."
        ],
        "fonte": "NORMAM-101/DPC, Capítulo 2, art. 2.3 e Anexo 2-D; DPC — Perguntas Frequentes.",
        "atualizacao2026": "Referência conferida para o Banco 2026. A NORMAM-101/DPC vigente consta na página oficial da DPC vinculada à Portaria DPC/DGN/MB nº 205, de 22/07/2026."
    },
    {
        "id": "TAA-2026-LMA-2.1-031",
        "disciplina": "Conhecimentos Específicos",
        "eixo": "Legislação Marítima e Ambiental",
        "topicoEdital": "2.1 Fluxo de carreira",
        "assunto": "Fluxo administrativo da ascensão",
        "tipoOrigem": "inedita_farol",
        "origemInterna": "Inédita Farol 2026",
        "enunciado": "Considere as etapas: I — o aquaviário cumpre os requisitos da categoria pretendida; II — apresenta requerimento à OM de jurisdição; III — a Autoridade Marítima confere a documentação e os requisitos; IV — a ascensão é respaldada por Ordem de Serviço e refletida nos registros de carreira. A sequência está",
        "alternativas": [
            "correta e compatível com o procedimento de ascensão.",
            "incorreta, porque o pedido deve partir exclusivamente da empresa.",
            "incorreta, porque a Ordem de Serviço deve preceder o cumprimento dos requisitos.",
            "incorreta, porque a ascensão não produz atualização em registros oficiais.",
            "incorreta, porque a análise cabe exclusivamente à ANTAQ."
        ],
        "correta": 0,
        "comentario": "O fluxo descrito sintetiza corretamente o procedimento: requisitos → requerimento → conferência → formalização e atualização dos registros.",
        "explicacaoCorreta": "O fluxo descrito sintetiza corretamente o procedimento: requisitos → requerimento → conferência → formalização e atualização dos registros.",
        "revisaoAssunto": "Em questões sequenciais, a Cesgranrio pode deslocar uma etapa. O requerimento não cria o direito sem requisitos, e a Ordem de Serviço não vem antes da análise. Fonte: NORMAM-101/DPC — procedimento de ascensão, itens 1.26 a 1.28 e Anexo 2-A; DPC/CPBA — Ascensão de Categoria.",
        "memorizar2026": "Ascensão: cumprir → requerer → comprovar → formalizar.",
        "dicaMacete": "Organize mentalmente o processo em ordem cronológica.",
        "pegadinha": "Trocar a iniciativa do aquaviário pela empresa é uma armadilha frequente quando a questão também menciona LCS.",
        "analiseAlternativas": [
            "Correta. A sequência reproduz a lógica do procedimento.",
            "Incorreta. Na ascensão, a iniciativa é do aquaviário.",
            "Incorreta. A Ordem de Serviço decorre da análise, não a antecede.",
            "Incorreta. CIR/SISAQUA são atualizados.",
            "Incorreta. A ANTAQ não processa a carreira profissional do aquaviário."
        ],
        "fonte": "NORMAM-101/DPC — procedimento de ascensão, itens 1.26 a 1.28 e Anexo 2-A; DPC/CPBA — Ascensão de Categoria.",
        "atualizacao2026": "Referência conferida para o Banco 2026. A NORMAM-101/DPC vigente consta na página oficial da DPC vinculada à Portaria DPC/DGN/MB nº 205, de 22/07/2026."
    },
    {
        "id": "TAA-2026-LMA-2.1-032",
        "disciplina": "Conhecimentos Específicos",
        "eixo": "Legislação Marítima e Ambiental",
        "topicoEdital": "2.1 Fluxo de carreira",
        "assunto": "Curso e ascensão — ausência de automatismo",
        "tipoOrigem": "inedita_farol",
        "origemInterna": "Inédita Farol 2026",
        "enunciado": "Um aquaviário concluiu um curso do Ensino Profissional Marítimo relacionado à sua área e afirma que, por esse fato isolado, a Autoridade Marítima é obrigada a promovê-lo imediatamente. Essa afirmação é",
        "alternativas": [
            "correta, porque todo curso do EPM produz ascensão automática.",
            "incorreta, porque a ascensão depende dos requisitos específicos da categoria pretendida previstos no Quadro Geral de Certificações, podendo envolver curso, estágio e/ou tempo de embarque.",
            "correta apenas quando o aquaviário está desempregado.",
            "correta se houver autorização verbal do comandante.",
            "incorreta somente porque toda ascensão exige dez anos de embarque."
        ],
        "correta": 1,
        "comentario": "A conclusão de curso pode ser um dos requisitos, mas não transforma toda ascensão em ato automático. É necessário verificar o Anexo 2-A e as exigências da categoria concreta.",
        "explicacaoCorreta": "A conclusão de curso pode ser um dos requisitos, mas não transforma toda ascensão em ato automático. É necessário verificar o Anexo 2-A e as exigências da categoria concreta.",
        "revisaoAssunto": "O erro clássico é converter “curso pode gerar requisito de ascensão” em “qualquer curso gera promoção”. As condições variam conforme a categoria e o fluxo profissional. Fonte: NORMAM-101/DPC, itens 1.26 a 1.28 e Anexo 2-A; DPC — Ascensão de Categoria.",
        "memorizar2026": "Curso pode ser requisito; não é sinônimo universal de ascensão automática.",
        "dicaMacete": "Antes de responder, pergunte: “o Anexo 2-A exige mais alguma coisa?”.",
        "pegadinha": "A alternativa errada costuma usar palavras como “automaticamente”, “sempre” ou um tempo fixo inexistente para todas as categorias.",
        "analiseAlternativas": [
            "Incorreta. Cursos não produzem ascensão automática em todos os fluxos.",
            "Correta. Os requisitos são específicos da categoria pretendida.",
            "Incorreta. Situação de emprego não cria essa regra.",
            "Incorreta. Comandante não substitui o procedimento administrativo.",
            "Incorreta. Não existe exigência universal de dez anos."
        ],
        "fonte": "NORMAM-101/DPC, itens 1.26 a 1.28 e Anexo 2-A; DPC — Ascensão de Categoria.",
        "atualizacao2026": "Referência conferida para o Banco 2026. A NORMAM-101/DPC vigente consta na página oficial da DPC vinculada à Portaria DPC/DGN/MB nº 205, de 22/07/2026."
    },
    {
        "id": "TAA-2026-LMA-2.1-033",
        "disciplina": "Conhecimentos Específicos",
        "eixo": "Legislação Marítima e Ambiental",
        "topicoEdital": "2.1 Fluxo de carreira",
        "assunto": "Taifeiro — enquadramento no fluxo",
        "tipoOrigem": "inedita_farol",
        "origemInterna": "Inédita Farol 2026",
        "enunciado": "Em relação especificamente ao Taifeiro (TAA), assinale a afirmação correta.",
        "alternativas": [
            "Integra a Seção de Máquinas e pode ascender a Condutor de Máquinas pelo simples tempo de embarque.",
            "Integra a Seção de Saúde e sua categoria imediatamente superior é Enfermeiro.",
            "Integra a Seção de Câmara e os documentos oficiais do CAAQ-CTS informam que essa categoria não possui ascensão de categoria, prevista para outras seções.",
            "Integra a Seção de Convés e ascende automaticamente a Marinheiro de Convés.",
            "É categoria do grupo dos Práticos e depende de Zona de Praticagem."
        ],
        "correta": 2,
        "comentario": "O TAA pertence à Seção de Câmara. No CAAQ-CTS, a Marinha informa que os profissionais CZA/TAA/ENF/ASA não têm ascensão de categoria como ocorre em outros fluxos.",
        "explicacaoCorreta": "O TAA pertence à Seção de Câmara. No CAAQ-CTS, a Marinha informa que os profissionais CZA/TAA/ENF/ASA não têm ascensão de categoria como ocorre em outros fluxos.",
        "revisaoAssunto": "Essa é provavelmente a principal particularidade para o candidato a Taifeiro: estudar o fluxo geral dos aquaviários sem presumir que sua própria categoria tenha uma escada de ascensão. Fonte: PREPOM-Aquaviários/2026 — CAAQ-CTS; Edital CAAQ-CTS T02/2026, item 1.4, Capitania dos Portos de Sergipe.",
        "memorizar2026": "TAA = Câmara; sem ascensão de categoria no CAAQ-CTS.",
        "dicaMacete": "Taifeiro não vira categoria de Convés ou Máquinas por mera antiguidade.",
        "pegadinha": "A banca pode aproveitar a familiaridade com carreiras de Convés/Máquinas para induzir uma promoção inexistente do TAA.",
        "analiseAlternativas": [
            "Incorreta. TAA não pertence à Seção de Máquinas.",
            "Incorreta. TAA é Câmara; ENF é Saúde.",
            "Correta. É o enquadramento oficial e a ressalva do CAAQ-CTS.",
            "Incorreta. Não há ascensão automática para Marinheiro de Convés.",
            "Incorreta. Práticos constituem outro grupo profissional."
        ],
        "fonte": "PREPOM-Aquaviários/2026 — CAAQ-CTS; Edital CAAQ-CTS T02/2026, item 1.4, Capitania dos Portos de Sergipe.",
        "atualizacao2026": "Referência conferida para o Banco 2026. A NORMAM-101/DPC vigente consta na página oficial da DPC vinculada à Portaria DPC/DGN/MB nº 205, de 22/07/2026."
    },
    {
        "id": "TAA-2026-LMA-2.1-034",
        "disciplina": "Conhecimentos Específicos",
        "eixo": "Legislação Marítima e Ambiental",
        "topicoEdital": "2.1 Fluxo de carreira",
        "assunto": "Fluxos distintos dentro da carreira aquaviária",
        "tipoOrigem": "inedita_farol",
        "origemInterna": "Inédita Farol 2026",
        "enunciado": "Ao estudar “fluxo de carreira dos aquaviários” para o cargo de Taifeiro, é juridicamente adequado compreender que",
        "alternativas": [
            "todas as categorias aquaviárias possuem exatamente a mesma sequência de níveis e promoções.",
            "o nível de equivalência torna os grupos profissionais intercambiáveis.",
            "a carreira depende apenas do empregador e não da Autoridade Marítima.",
            "existem diferentes grupos, seções e categorias, com requisitos próprios; além disso, algumas categorias como TAA não possuem ascensão de categoria no fluxo do CAAQ-CTS.",
            "a única forma de evolução profissional de qualquer aquaviário é a LCS."
        ],
        "correta": 3,
        "comentario": "A estrutura aquaviária é plural: grupos e seções têm requisitos próprios. A ascensão existe em diversos fluxos, mas não deve ser generalizada ao TAA, cuja documentação do CAAQ-CTS afasta a ascensão de categoria.",
        "explicacaoCorreta": "A estrutura aquaviária é plural: grupos e seções têm requisitos próprios. A ascensão existe em diversos fluxos, mas não deve ser generalizada ao TAA, cuja documentação do CAAQ-CTS afasta a ascensão de categoria.",
        "revisaoAssunto": "Esse raciocínio protege contra duas generalizações erradas: tratar todos os aquaviários como uma carreira única e presumir que mesmo nível signifique mesma competência. Fonte: RLESTA — Decreto nº 2.596/1998, Capítulo I, art. 1º; NORMAM-101/DPC, Capítulos 1 e 2, Anexo 2-A; PREPOM-Aquaviários/2026 — CAAQ-CTS.",
        "memorizar2026": "Carreira aquaviária não é uma escada única para todos os grupos e seções.",
        "dicaMacete": "Primeiro identifique grupo, seção e categoria; depois aplique o fluxo correspondente.",
        "pegadinha": "A palavra “aquaviário” é ampla e inclui profissionais com formações e trajetórias muito diferentes.",
        "analiseAlternativas": [
            "Incorreta. Há múltiplos grupos, seções e requisitos.",
            "Incorreta. Nível de equivalência não iguala competências entre grupos.",
            "Incorreta. A carreira é regulada pela Autoridade Marítima.",
            "Correta. Resume a estrutura normativa e a particularidade do TAA.",
            "Incorreta. LCS é autorização excepcional, não única forma de evolução profissional."
        ],
        "fonte": "RLESTA — Decreto nº 2.596/1998, Capítulo I, art. 1º; NORMAM-101/DPC, Capítulos 1 e 2, Anexo 2-A; PREPOM-Aquaviários/2026 — CAAQ-CTS.",
        "atualizacao2026": "Referência conferida para o Banco 2026. A NORMAM-101/DPC vigente consta na página oficial da DPC vinculada à Portaria DPC/DGN/MB nº 205, de 22/07/2026."
    },
    {
        "id": "TAA-2026-LMA-2.1-035",
        "disciplina": "Conhecimentos Específicos",
        "eixo": "Legislação Marítima e Ambiental",
        "topicoEdital": "2.1 Fluxo de carreira",
        "assunto": "Integradora — ascensão, transferência e LCS",
        "tipoOrigem": "inedita_farol",
        "origemInterna": "Inédita Farol 2026",
        "enunciado": "Considere três situações: I — um aquaviário de fluxo que admite promoção cumpriu os requisitos do Anexo 2-A e requer categoria superior à sua OM de jurisdição; II — outro pretende mudar de grupo profissional, embora as categorias tenham o mesmo nível de equivalência; III — a empresa necessita excepcionalmente que um aquaviário exerça capacidade superior em uma embarcação específica por quatro meses. As situações I, II e III correspondem, respectivamente, a",
        "alternativas": [
            "transferência de jurisdição, ascensão automática e nova inscrição.",
            "LCS, transferência de jurisdição e ascensão.",
            "ascensão, LCS e transferência de categoria.",
            "nova inscrição, ascensão e transferência de jurisdição.",
            "ascensão de categoria, transferência de categoria sujeita a avaliação de competência e Licença de Categoria/Capacidade Superior."
        ],
        "correta": 4,
        "comentario": "A situação I descreve ascensão; a II, transferência entre grupos/seções, que não é automática por equivalência de nível; e a III, LCS temporária e específica.",
        "explicacaoCorreta": "A situação I descreve ascensão; a II, transferência entre grupos/seções, que não é automática por equivalência de nível; e a III, LCS temporária e específica.",
        "revisaoAssunto": "Esta questão reúne as três distinções mais importantes do tópico. Ascensão é promoção dentro do fluxo aplicável; transferência muda grupo/seção e exige avaliação; LCS é autorização temporária para função superior em embarcação específica. Fonte: NORMAM-101/DPC, Anexo 2-A; Capítulo 2, arts. 2.3 e 2.4; DPC — Documentação e Certificação de Pessoal Aquaviário.",
        "memorizar2026": "Ascensão ≠ transferência ≠ LCS.",
        "dicaMacete": "Resolva cada situação separadamente e só depois compare as alternativas.",
        "pegadinha": "Todas envolvem “mudança” na vida profissional, mas produzem efeitos jurídicos distintos.",
        "analiseAlternativas": [
            "Incorreta. As três classificações estão deslocadas.",
            "Incorreta. I não é LCS e II não é simples jurisdição.",
            "Incorreta. II é transferência; III é LCS.",
            "Incorreta. I não é nova inscrição e III não é jurisdição.",
            "Correta. As três situações correspondem aos três institutos descritos."
        ],
        "fonte": "NORMAM-101/DPC, Anexo 2-A; Capítulo 2, arts. 2.3 e 2.4; DPC — Documentação e Certificação de Pessoal Aquaviário.",
        "atualizacao2026": "Referência conferida para o Banco 2026. A NORMAM-101/DPC vigente consta na página oficial da DPC vinculada à Portaria DPC/DGN/MB nº 205, de 22/07/2026."
    }
];

    const atual = Array.isArray(window.questoesTaifeiroBanco2026)
        ? window.questoesTaifeiroBanco2026
        : [];
    const idsExistentes = new Set(atual.map(q => q && q.id).filter(Boolean));
    const novas = loteFluxoCarreiraTAA2026.filter(q => !idsExistentes.has(q.id));
    window.questoesTaifeiroBanco2026 = atual.concat(novas);
})();
