const constituicaoGestaoLegislacaoEducacionalAbaetetubaTeoria = [
  {
    "titulo": "📚 Página 1 — Didática, ensino e aprendizagem",
    "conteudo": "<div class=\"apostila-container\">\n<p>A Didática estuda e orienta o processo de ensino, articulando finalidades educacionais, conhecimentos, métodos, recursos, relações pedagógicas e avaliação. Ela não corresponde a uma coleção de técnicas neutras: toda escolha didática expressa uma concepção de sociedade, de conhecimento, de estudante e de formação humana.</p>\n<p>Ensinar pressupõe intencionalidade. O professor seleciona objetivos, organiza conteúdos, propõe situações de aprendizagem e acompanha os resultados. Essa organização precisa considerar os conhecimentos prévios dos estudantes, as características da turma, o contexto sociocultural e as aprendizagens definidas no currículo.</p>\n<p>O estudante não é mero receptor de informações. A aprendizagem envolve participação, elaboração de sentidos, interação, investigação, memória, linguagem e aplicação do conhecimento. Exposição oral pode integrar o trabalho docente, mas precisa ser combinada com perguntas, problemas, análise de fontes, produção e feedback.</p>\n<p>Método é o caminho organizado para alcançar objetivos educacionais. Uma metodologia adequada não é escolhida por moda, mas por coerência com o conteúdo, a etapa de ensino, as condições da escola e as necessidades dos estudantes. Estratégias diferentes podem ser usadas dentro de uma mesma sequência didática.</p>\n<p>Recursos didáticos incluem textos, imagens, mapas, objetos, tecnologias, jogos, documentos e ambientes da comunidade. O recurso não garante aprendizagem por si próprio; seu valor depende da mediação, da acessibilidade, da problematização e da relação com os objetivos da aula.</p>\n<p>A prática pedagógica exige reflexão contínua. Planejar, observar, avaliar e replanejar formam um ciclo. Quando a turma não aprende como esperado, a resposta docente deve envolver análise das condições de ensino, novas intervenções e apoio, evitando responsabilizar o estudante de forma isolada.</p>\n<div class=\"farol-quadro farol-memorize\"><strong>🧠 Memorize</strong>Didática articula objetivos, conteúdos, métodos, recursos e avaliação em um ciclo de reflexão e replanejamento.</div>\n</div>"
  },
  {
    "titulo": "🗂️ Página 2 — Planejamento educacional e projeto político-pedagógico",
    "conteudo": "<div class=\"apostila-container\">\n<p>Planejamento educacional é um processo de previsão, decisão, execução, acompanhamento e revisão. Ele organiza ações em diferentes níveis: políticas públicas, sistema de ensino, escola, área de conhecimento, período letivo, unidade didática e aula. Esses níveis precisam dialogar para evitar planos desconectados da realidade.</p>\n<p>O plano de aula traduz objetivos curriculares em situações concretas de ensino. Deve apresentar coerência entre objetivos, conteúdos, procedimentos, recursos, tempo e avaliação. Um objetivo formulado como desenvolvimento de análise histórica, por exemplo, não pode ser avaliado apenas pela repetição de datas.</p>\n<p>O projeto político-pedagógico, ou PPP, expressa a identidade da escola, suas finalidades, princípios, diagnóstico, prioridades e formas de ação. É político porque envolve escolhas coletivas sobre educação e sociedade; é pedagógico porque organiza o trabalho de ensino e aprendizagem.</p>\n<p>A elaboração do PPP deve ser participativa, envolvendo profissionais, estudantes, famílias e comunidade de acordo com suas atribuições. Participação não significa ausência de coordenação: a gestão precisa garantir espaços de escuta, registro, decisão, execução e prestação de contas.</p>\n<p>Um PPP efetivo não é documento produzido apenas para cumprir exigência administrativa. Ele orienta currículo, formação, avaliação, convivência, inclusão, uso de recursos e relação com a comunidade. Suas metas precisam ser acompanhadas por indicadores e ações possíveis.</p>\n<p>Planejamento é flexível, mas não improvisado. Mudanças podem ser necessárias diante de resultados, eventos ou necessidades da turma. Replanejar significa preservar as finalidades e ajustar caminhos com base em evidências, e não abandonar objetivos sem análise.</p>\n<div class=\"farol-quadro farol-memorize\"><strong>🧠 Memorize</strong>Planejamento é processo; o PPP é coletivo, político, pedagógico e orientador da ação escolar.</div>\n</div>"
  },
  {
    "titulo": "🏛️ Página 3 — Sistemas de ensino, regime de colaboração e gestão democrática",
    "conteudo": "<div class=\"apostila-container\">\n<p>A educação brasileira é organizada em regime federativo. União, Estados, Distrito Federal e Municípios possuem responsabilidades próprias e atuam em colaboração. A Constituição e a LDB estruturam competências, prioridades e mecanismos de cooperação para garantir o direito à educação.</p>\n<p>Sistema de ensino envolve órgãos normativos, instituições educacionais, redes, regras, acompanhamento e políticas. Não se reduz ao conjunto de escolas: inclui responsabilidades de autorização, avaliação, supervisão, financiamento, formação e organização curricular.</p>\n<p>A União exerce funções normativas, redistributivas e supletivas e organiza o sistema federal. Estados e Distrito Federal atuam prioritariamente no ensino fundamental e médio, enquanto Municípios atuam prioritariamente na educação infantil e no ensino fundamental, sem impedir cooperação entre os entes.</p>\n<p>A gestão democrática é princípio do ensino público. Sua concretização pode envolver conselhos, participação na elaboração do PPP, transparência, diálogo, eleição ou seleção de dirigentes conforme a norma do sistema e acompanhamento social das decisões.</p>\n<p>Autonomia escolar não significa independência absoluta. A escola toma decisões pedagógicas e administrativas dentro da legislação, das políticas do sistema e dos recursos disponíveis. Autonomia responsável exige participação, planejamento, avaliação e compromisso com o direito de aprendizagem.</p>\n<p>O regime de colaboração busca enfrentar desigualdades de capacidade entre redes e territórios. Cooperação técnica e financeira, definição de padrões de qualidade, compartilhamento de informações e articulação de políticas são instrumentos para que o endereço do estudante não determine a qualidade de seu atendimento.</p>\n<div class=\"farol-quadro farol-memorize\"><strong>🧠 Memorize</strong>Sistemas de ensino combinam competências federativas, gestão democrática, autonomia responsável e colaboração.</div>\n</div>"
  },
  {
    "titulo": "📊 Página 4 — Avaliação, recuperação e progressão escolar",
    "conteudo": "<div class=\"apostila-container\">\n<p>Avaliação da aprendizagem é parte do processo pedagógico e produz informações para estudantes, professores, famílias e escola. Ela deve verificar o que foi aprendido, identificar dificuldades, orientar intervenções e apoiar decisões, em vez de funcionar apenas como classificação ao final do período.</p>\n<p>A avaliação diagnóstica identifica conhecimentos prévios e necessidades antes ou no início de uma sequência. A formativa acompanha o percurso e oferece devolutivas. A somativa sintetiza resultados ao final de uma etapa. Essas funções podem coexistir, desde que o professor saiba qual decisão pretende apoiar.</p>\n<p>Instrumentos variados permitem observar diferentes aprendizagens: questões objetivas, produções escritas, projetos, apresentações, debates, portfólios e análise de documentos. A escolha precisa corresponder ao objetivo; avaliar argumentação histórica exige evidências diferentes das usadas para verificar reconhecimento de um conceito.</p>\n<p>Critérios devem ser claros e comunicados. Feedback de qualidade informa o que foi alcançado, o que precisa melhorar e qual ação pode ser realizada. Apenas indicar nota ou erro oferece pouca orientação para a aprendizagem.</p>\n<p>A recuperação deve ocorrer de forma contínua e articulada ao ensino. Repetir a mesma explicação e a mesma prova pode reproduzir a dificuldade. Recuperar implica diversificar mediações, oferecer tempo, acompanhar avanços e registrar intervenções.</p>\n<p>Progressão escolar não deve ser confundida com promoção automática. Sistemas de progressão precisam assegurar acompanhamento, aprendizagem e apoio. A decisão sobre avanço considera normas do sistema e resultados educacionais, evitando tanto reprovação meramente punitiva quanto avanço sem garantia de aprendizagem.</p>\n<div class=\"farol-quadro farol-memorize\"><strong>🧠 Memorize</strong>Avaliar é produzir evidências para intervir; recuperação contínua e progressão exigem garantia de aprendizagem.</div>\n</div>"
  },
  {
    "titulo": "🧭 Página 5 — Currículo e Base Nacional Comum Curricular",
    "conteudo": "<div class=\"apostila-container\">\n<p>Currículo é uma seleção cultural e pedagógica de conhecimentos, experiências, valores e práticas. Ele não é apenas uma grade de disciplinas: define o que se considera importante ensinar, como os tempos e espaços são organizados e quais sujeitos e perspectivas ganham visibilidade.</p>\n<p>O currículo possui dimensões prescrita, praticada e avaliada. Documentos oficiais orientam aprendizagens; professores e escolas interpretam essas orientações nas situações concretas; avaliações influenciam prioridades. Compreender essas dimensões evita tratar currículo como texto que se executa mecanicamente.</p>\n<p>A Base Nacional Comum Curricular é documento normativo que define aprendizagens essenciais da Educação Básica. Ela apresenta competências gerais, competências específicas e habilidades, buscando garantir direitos de aprendizagem e orientar currículos, materiais, formação e avaliação.</p>\n<p>A BNCC não substitui o currículo da rede nem o PPP da escola. Currículos incorporam a base comum e acrescentam características regionais e locais, escolhas metodológicas, organização temporal e experiências próprias. A parte comum e a contextualização territorial devem ser integradas.</p>\n<p>Competência envolve mobilizar conhecimentos, habilidades, atitudes e valores para responder a demandas complexas. Por isso, trabalhar competências não significa abandonar conteúdos; conhecimentos são necessários para analisar problemas, argumentar, decidir e agir.</p>\n<p>No ensino de História, currículo e BNCC precisam favorecer pensamento histórico, análise de fontes, compreensão de temporalidades, reconhecimento de sujeitos diversos e relações entre escalas local, regional, nacional e mundial. A seleção de conteúdos deve evitar silenciamentos e simplificações.</p>\n<div class=\"farol-quadro farol-memorize\"><strong>🧠 Memorize</strong>A BNCC define aprendizagens essenciais, mas currículos e PPP contextualizam e organizam a prática.</div>\n</div>"
  },
  {
    "titulo": "🇧🇷 Página 6 — Constituição: princípios fundamentais e objetivos da República",
    "conteudo": "<div class=\"apostila-container\">\n<p>Os artigos 1º a 4º da Constituição apresentam fundamentos, separação de Poderes, objetivos da República e princípios das relações internacionais. Esses dispositivos formam a base para interpretar direitos, políticas públicas e deveres estatais, inclusive na educação.</p>\n<p>Entre os fundamentos da República estão soberania, cidadania, dignidade da pessoa humana, valores sociais do trabalho e da livre iniciativa e pluralismo político. Na escola, esses fundamentos orientam práticas de respeito, participação e formação para a cidadania.</p>\n<p>A Constituição afirma que todo poder emana do povo, exercido por representantes eleitos ou diretamente nos termos constitucionais. A gestão democrática e a participação da comunidade escolar dialogam com essa concepção, embora dependam das normas educacionais e dos sistemas de ensino.</p>\n<p>Os Poderes da União são Legislativo, Executivo e Judiciário, independentes e harmônicos entre si. A separação de Poderes impede a concentração absoluta de autoridade e estabelece controles institucionais, sem eliminar cooperação entre funções estatais.</p>\n<p>Os objetivos fundamentais incluem construir sociedade livre, justa e solidária; garantir o desenvolvimento; erradicar pobreza e marginalização e reduzir desigualdades; e promover o bem de todos sem preconceitos ou discriminações. Políticas educacionais podem ser analisadas à luz desses objetivos.</p>\n<p>Nas relações internacionais, a Constituição indica princípios como independência nacional, prevalência dos direitos humanos, autodeterminação dos povos, não intervenção, igualdade entre Estados, defesa da paz, solução pacífica de conflitos e cooperação entre os povos.</p>\n<div class=\"farol-quadro farol-memorize\"><strong>🧠 Memorize</strong>Fundamentos e objetivos da República orientam cidadania, dignidade, pluralismo e redução de desigualdades.</div>\n</div>"
  },
  {
    "titulo": "⚖️ Página 7 — Direitos e garantias fundamentais: artigos 5º a 17",
    "conteudo": "<div class=\"apostila-container\">\n<p>Os artigos 5º a 17 abrangem direitos individuais e coletivos, direitos sociais, nacionalidade, direitos políticos e partidos políticos. O edital inclui esse conjunto, por isso a preparação deve compreender princípios e aplicações, evitando decorar frases sem entender sua função.</p>\n<p>O artigo 5º assegura igualdade perante a lei e protege vida, liberdade, igualdade, segurança e propriedade. Também reúne garantias como legalidade, liberdade de consciência, expressão com vedação do anonimato, inviolabilidade da intimidade, direito de reunião, associação e devido processo.</p>\n<p>Direitos fundamentais não são instrumentos para eliminar direitos de outras pessoas. Em situações de conflito, aplica-se interpretação constitucional, proporcionalidade e proteção da dignidade. No ambiente escolar, liberdade de expressão convive com deveres de respeito, proteção e enfrentamento à discriminação.</p>\n<p>Os direitos sociais incluem educação, saúde, alimentação, trabalho, moradia, transporte, lazer, segurança, previdência, proteção à maternidade e infância e assistência aos desamparados. Sua efetivação depende de políticas públicas, financiamento e controle social.</p>\n<p>Direitos políticos permitem participação na escolha de representantes e na vida pública, conforme regras de alistamento, voto, elegibilidade e perda ou suspensão. A cidadania escolar não substitui esses direitos, mas prepara estudantes para participação crítica e responsável.</p>\n<p>Partidos políticos possuem autonomia dentro da ordem constitucional e são essenciais à representação democrática. Pluralismo não significa ausência de regras; atuação partidária deve respeitar soberania nacional, regime democrático, pluripartidarismo e direitos fundamentais.</p>\n<div class=\"farol-quadro farol-memorize\"><strong>🧠 Memorize</strong>Direitos fundamentais abrangem liberdades, direitos sociais, participação política e pluralismo democrático.</div>\n</div>"
  },
  {
    "titulo": "🎓 Página 8 — Direito à educação: artigos 205 a 214",
    "conteudo": "<div class=\"apostila-container\">\n<p>O artigo 205 define a educação como direito de todos e dever do Estado e da família, promovida com colaboração da sociedade. Suas finalidades são pleno desenvolvimento da pessoa, preparo para o exercício da cidadania e qualificação para o trabalho.</p>\n<p>O artigo 206 apresenta princípios do ensino, entre eles igualdade de condições para acesso e permanência, liberdade de aprender e ensinar, pluralismo, gratuidade do ensino público, valorização dos profissionais, gestão democrática, padrão de qualidade e garantia do direito à educação e aprendizagem ao longo da vida.</p>\n<p>O dever estatal inclui educação básica obrigatória e gratuita dos quatro aos dezessete anos, atendimento educacional especializado às pessoas com deficiência preferencialmente na rede regular, educação infantil, acesso aos níveis mais elevados segundo a capacidade, oferta noturna e programas suplementares.</p>\n<p>O acesso ao ensino obrigatório e gratuito é direito público subjetivo. Isso permite exigir do poder público a oferta correspondente. A autoridade competente pode ser responsabilizada quando deixa de oferecer ou oferece irregularmente o ensino obrigatório.</p>\n<p>A organização federativa da educação ocorre em regime de colaboração. A União exerce função redistributiva e supletiva; Municípios atuam prioritariamente na educação infantil e no ensino fundamental; Estados e Distrito Federal, no ensino fundamental e médio.</p>\n<p>Os artigos 212 a 214 tratam de financiamento e planejamento. A Constituição vincula percentuais mínimos de receitas de impostos à manutenção e desenvolvimento do ensino e determina plano nacional de educação de duração decenal, com objetivos articulados para o desenvolvimento educacional.</p>\n<div class=\"farol-quadro farol-memorize\"><strong>🧠 Memorize</strong>Educação é direito de todos, com princípios, deveres estatais, colaboração, financiamento e planejamento.</div>\n</div>"
  },
  {
    "titulo": "📜 Página 9 — LDB e ECA na organização do trabalho escolar",
    "conteudo": "<div class=\"apostila-container\">\n<p>A LDB estabelece diretrizes e bases da educação nacional. Ela reconhece processos formativos em diferentes espaços e disciplina a educação escolar, que deve vincular-se ao mundo do trabalho e à prática social. Seus princípios orientam acesso, permanência, liberdade, pluralismo, qualidade, diversidade e gestão.</p>\n<p>A proposta pedagógica é responsabilidade institucional e referência para o trabalho coletivo. Estabelecimentos de ensino elaboram e executam sua proposta, administram recursos, asseguram cumprimento do calendário, acompanham o plano docente e articulam-se com famílias e comunidade.</p>\n<p>Docentes participam da elaboração da proposta pedagógica, elaboram e cumprem plano de trabalho, zelam pela aprendizagem, estabelecem estratégias de recuperação, cumprem dias e horas e colaboram com articulação entre escola, famílias e comunidade.</p>\n<p>O Estatuto da Criança e do Adolescente adota a proteção integral e reconhece crianças e adolescentes como sujeitos de direitos com prioridade. Na educação, assegura igualdade de acesso e permanência, respeito, possibilidade de contestar critérios avaliativos e participação em entidades estudantis.</p>\n<p>A escola integra a rede de proteção. Situações de violência, violações de direitos, faltas reiteradas ou evasão exigem registro, intervenção pedagógica, comunicação com responsáveis e acionamento dos órgãos competentes conforme a legislação.</p>\n<p>LDB e ECA devem ser lidos de forma articulada: uma organiza o sistema e o trabalho educacional; o outro reforça proteção, participação e prioridade. A ação escolar precisa combinar ensino de qualidade, cuidado, prevenção e respeito ao devido processo.</p>\n<div class=\"farol-quadro farol-memorize\"><strong>🧠 Memorize</strong>LDB organiza o trabalho educacional; ECA assegura proteção integral, participação e prioridade.</div>\n</div>"
  },
  {
    "titulo": "♿ Página 10 — PNE indicado no edital e educação inclusiva",
    "conteudo": "<div class=\"apostila-container\">\n<p>O edital de Abaetetuba cita expressamente a Lei nº 13.005/2014, que aprovou um Plano Nacional de Educação com diretrizes, metas e estratégias. Para esta preparação, o módulo segue esse recorte normativo indicado pelo edital, sem substituir automaticamente a referência por legislação posterior.</p>\n<p>Entre as diretrizes da Lei nº 13.005/2014 estão erradicação do analfabetismo, universalização do atendimento, superação das desigualdades, melhoria da qualidade, formação para o trabalho e cidadania, gestão democrática, valorização dos profissionais, respeito aos direitos humanos e sustentabilidade.</p>\n<p>Metas educacionais exigem monitoramento, cooperação federativa e participação social. Plano não é lista de intenções: deve orientar políticas, orçamento, responsabilidades e avaliação. Em questão de concurso, é importante distinguir diretriz, meta, estratégia e mecanismo de acompanhamento.</p>\n<p>Educação inclusiva garante acesso, participação, aprendizagem e pertencimento. Matrícula em turma comum é ponto de partida, mas barreiras arquitetônicas, comunicacionais, pedagógicas, tecnológicas e atitudinais precisam ser identificadas e removidas.</p>\n<p>O atendimento educacional especializado organiza recursos e serviços de acessibilidade para complementar ou suplementar a formação do estudante, sem substituir a escolarização comum. Planejamento colaborativo, acessibilidade e avaliação adequada devem preservar objetivos de aprendizagem e dignidade.</p>\n<p>Inclusão não significa reduzir expectativas de aprendizagem. Significa oferecer meios, adaptações razoáveis, recursos e apoios para que cada estudante participe e demonstre conhecimentos. A escola inclusiva beneficia toda a comunidade ao ampliar formas de ensinar, comunicar e conviver.</p>\n<div class=\"farol-quadro farol-memorize\"><strong>🧠 Memorize</strong>Didática articula objetivos, conteúdos, métodos, recursos e avaliação em um ciclo de reflexão e replanejamento.</div>\n</div>"
  }
];
