const conviviosConfrontosEuropaMedievalAbaetetubaTeoria = [
  {
    "titulo": "🏰 Página 1 — Idade Média: periodização, fontes e pluralidade",
    "conteudo": "<div class=\"apostila-container\">\n<p>A expressão Idade Média foi criada por estudiosos europeus de períodos posteriores para designar, de forma geral, os séculos situados entre a Antiguidade e a Modernidade. Datas como 476, associada à deposição do último imperador romano do Ocidente, e 1453, ligada à tomada de Constantinopla pelos otomanos, são marcos convencionais, não fronteiras que transformaram todas as sociedades de maneira imediata.</p>\n<p>O período medieval durou aproximadamente mil anos e reuniu experiências muito diferentes. Reinos latino-cristãos, Império Bizantino, sociedades islâmicas, comunidades judaicas, povos eslavos, nórdicos e diversas populações locais estabeleceram relações de guerra, negociação, migração, comércio e intercâmbio cultural.</p>\n<p>A antiga imagem de uma época de estagnação e ignorância resulta de leituras produzidas em contextos específicos. A Europa medieval conheceu desigualdades, violências, epidemias e perseguições, mas também transformações agrícolas, crescimento urbano, circulação de saberes, produção artística, formação de universidades e renovação das instituições políticas.</p>\n<p>As fontes medievais incluem crônicas, leis, cartas, registros fiscais, documentos eclesiásticos, narrativas de viagem, obras literárias, edifícios, moedas, imagens, objetos e vestígios arqueológicos. Como grande parte dos textos foi produzida por grupos letrados, é necessário confrontar diferentes tipos de evidência para estudar camponeses, mulheres, minorias religiosas e outros sujeitos menos registrados.</p>\n<p>As divisões em Alta, Plena e Baixa Idade Média ajudam a organizar processos, mas não devem ser utilizadas como modelos rígidos. Mudanças demográficas, econômicas, políticas e religiosas ocorreram em ritmos distintos no Mediterrâneo, na Europa ocidental, no norte europeu e nas regiões orientais.</p>\n<p>O eixo dos convívios e confrontos propõe observar as fronteiras como espaços de contato. Guerras e perseguições coexistiram com traduções, alianças, empréstimos linguísticos, técnicas compartilhadas, circulação de mercadorias e experiências de coexistência que variaram conforme o tempo e o lugar.</p>\n<div class=\"farol-quadro farol-memorize\"><strong>🧠 Memorize</strong>A periodização medieval é uma ferramenta de análise: marcos cronológicos não transformam todas as sociedades ao mesmo tempo.</div>\n</div>"
  },
  {
    "titulo": "Página 2 — Reinos pós-romanos, ruralização e formação feudal",
    "conteudo": "<div class=\"apostila-container\">\n<p>A desagregação do poder imperial romano no Ocidente não significou o desaparecimento imediato de suas instituições e práticas. Reinos formados por francos, visigodos, ostrogodos, lombardos e outros grupos combinaram tradições militares próprias com direito romano, cristianismo, administração territorial e colaboração de elites locais.</p>\n<p>O termo povos germânicos reúne comunidades diversas, que não possuíam uma identidade política única. Migrações, recrutamento militar, acordos com Roma e conflitos nas fronteiras ocorreram durante séculos, tornando inadequada a ideia de uma invasão uniforme que teria destruído repentinamente o mundo romano.</p>\n<p>Entre os séculos V e X, várias regiões do Ocidente experimentaram redução de redes administrativas, insegurança e maior concentração da vida econômica no campo. Isso não eliminou cidades nem trocas comerciais, mas alterou sua escala, suas funções e suas conexões com os poderes locais.</p>\n<p>A formação das relações feudais foi gradual e desigual. Senhores controlavam terras, direitos e recursos; camponeses possuíam diferentes condições jurídicas; e laços de dependência política articulavam proteção, serviço e autoridade. Não existiu um único modelo feudal aplicado de forma idêntica a toda a Europa.</p>\n<p>Vassalagem e servidão não são sinônimos. A vassalagem vinculava principalmente membros das elites por compromissos de fidelidade e concessões de benefícios, enquanto a servidão dizia respeito a obrigações camponesas, acesso à terra e submissão a poderes senhoriais.</p>\n<p>O Império Carolíngio, especialmente sob Carlos Magno, buscou integrar territórios por meio de conquistas, alianças aristocráticas, cristianização e administração regional. Sua fragmentação posterior favoreceu novas configurações de poder, sem apagar a importância de instituições e referências políticas carolíngias.</p>\n<div class=\"farol-quadro farol-memorize\"><strong>🧠 Memorize</strong>A formação feudal foi gradual, regionalmente diversa e construída pela combinação de tradições romanas, locais e pós-romanas.</div>\n</div>"
  },
  {
    "titulo": "Página 3 — Império Bizantino: continuidade romana e cristianismo oriental",
    "conteudo": "<div class=\"apostila-container\">\n<p>O Império Bizantino é o nome utilizado por historiadores para o Império Romano do Oriente, cuja capital era Constantinopla. Seus habitantes se identificavam como romanos, e o Estado preservou instituições imperiais enquanto incorporava transformações linguísticas, religiosas e culturais ao longo de muitos séculos.</p>\n<p>A posição de Constantinopla entre o Mediterrâneo e o mar Negro favoreceu comércio, diplomacia e defesa. A cidade conectava rotas europeias e asiáticas, reunindo mercadores, embaixadores, artesãos e peregrinos de diferentes origens.</p>\n<p>No governo de Justiniano, no século VI, campanhas militares buscaram recuperar áreas do antigo Ocidente romano. A compilação conhecida como Corpus Juris Civilis organizou tradições jurídicas e exerceu influência posterior, embora as conquistas territoriais tenham sido caras e parcialmente revertidas.</p>\n<p>A vida religiosa bizantina articulava imperador, clero, mosteiros e comunidades locais. A controvérsia iconoclasta, entre os séculos VIII e IX, envolveu disputas sobre o uso de imagens sagradas e também interesses políticos, sociais e territoriais.</p>\n<p>As diferenças entre as Igrejas de Roma e Constantinopla foram construídas gradualmente. O cisma de 1054 tornou-se marco simbólico da separação entre catolicismo romano e cristianismo ortodoxo, mas contatos, negociações e conflitos continuaram depois dessa data.</p>\n<p>Bizâncio desempenhou papel central na circulação de textos antigos, técnicas, arte religiosa e tradições políticas. Suas relações com eslavos, árabes, latinos e povos das estepes envolveram conversões, casamentos, guerras e intercâmbios que influenciaram diversas regiões.</p>\n<div class=\"farol-quadro farol-memorize\"><strong>🧠 Memorize</strong>Bizâncio foi o Império Romano do Oriente; seus habitantes se reconheciam como romanos.</div>\n</div>"
  },
  {
    "titulo": "☪️ Página 4 — Formação das sociedades islâmicas e redes de conhecimento",
    "conteudo": "<div class=\"apostila-container\">\n<p>O islamismo surgiu no século VII na península Arábica, associado à pregação de Maomé e à formação de uma comunidade de fiéis, a umma. A Hégira, migração de Meca para Medina em 622, tornou-se marco do calendário islâmico e da organização política da nova comunidade.</p>\n<p>Após a morte de Maomé, disputas sobre liderança contribuíram para divisões políticas e religiosas. Califados como o Omíada e o Abássida expandiram territórios, mas o mundo islâmico nunca foi uma unidade política permanente nem culturalmente homogênea.</p>\n<p>Cidades como Damasco, Bagdá, Cairo, Córdoba e outras tornaram-se centros de comércio, administração e produção intelectual. Árabe, persa, berbere, turco e diversas línguas locais conviveram em sociedades marcadas por diferenças regionais.</p>\n<p>Estudiosos em territórios islâmicos traduziram, comentaram e ampliaram obras gregas, persas e indianas. Matemática, medicina, astronomia, filosofia, geografia e técnicas agrícolas circularam por redes que alcançavam o Mediterrâneo, a Ásia e a África.</p>\n<p>Cristãos e judeus receberam, em muitos contextos, estatutos específicos como comunidades protegidas mediante obrigações fiscais e jurídicas. Essas condições variaram conforme governantes e períodos, podendo combinar tolerância limitada, desigualdade legal, cooperação e episódios de perseguição.</p>\n<p>As relações entre sociedades islâmicas e cristãs não se resumiram às guerras. Comércio, diplomacia, tradução de textos, circulação de moedas, empréstimos linguísticos e transmissão de técnicas demonstram que as fronteiras também funcionavam como zonas de interação.</p>\n<div class=\"farol-quadro farol-memorize\"><strong>🧠 Memorize</strong>O mundo islâmico medieval foi plural e conectado por redes políticas, urbanas, comerciais e intelectuais.</div>\n</div>"
  },
  {
    "titulo": "⛪ Página 5 — Cristandade latina, Igreja, mosteiros e disputas de poder",
    "conteudo": "<div class=\"apostila-container\">\n<p>Na Europa ocidental, o cristianismo latino tornou-se referência importante para calendários, rituais, legitimidade política, educação e assistência. Entretanto, a Igreja medieval não era uma instituição uniforme: bispos, papado, mosteiros, paróquias, ordens religiosas e poderes locais podiam cooperar ou entrar em conflito.</p>\n<p>Os mosteiros tiveram funções religiosas, econômicas e culturais. Monges e monjas organizaram comunidades, administraram terras, preservaram manuscritos, ofereceram hospitalidade e participaram de redes políticas. A experiência monástica variou conforme regras, ordens e regiões.</p>\n<p>Movimentos de reforma buscaram controlar práticas do clero e ampliar a autonomia eclesiástica diante de senhores laicos. A chamada Questão das Investiduras colocou papas e imperadores em disputa sobre a nomeação de autoridades religiosas e a relação entre poderes espiritual e temporal.</p>\n<p>A vida religiosa popular incluía peregrinações, festas, cultos de santos, relíquias, confrarias e devoções locais. Essas práticas não eram separadas da vida social, pois organizavam calendários de trabalho, solidariedade comunitária e identidades urbanas ou rurais.</p>\n<p>As autoridades eclesiásticas classificaram determinadas crenças como heresias e criaram mecanismos de investigação e repressão. A Inquisição medieval não funcionou de forma idêntica em todos os lugares, devendo ser estudada em seus contextos jurídicos e políticos específicos.</p>\n<p>As relações entre Igreja e sociedade produziram cooperação, conflitos e negociações. Reis utilizaram símbolos cristãos para legitimar governos, enquanto comunidades, ordens e clérigos também limitaram, contestaram ou reformularam o poder político.</p>\n<div class=\"farol-quadro farol-memorize\"><strong>🧠 Memorize</strong>A Igreja medieval reunia instituições e grupos diversos, atravessados por cooperação, reforma e disputa de poder.</div>\n</div>"
  },
  {
    "titulo": "Página 6 — Trabalho, senhorios, camponeses e transformações econômicas",
    "conteudo": "<div class=\"apostila-container\">\n<p>A maior parte da população medieval vivia no campo e dependia da agricultura. Senhorios reuniam terras de exploração direta, parcelas camponesas, bosques, pastagens, moinhos e direitos de cobrança, mas sua organização variava bastante entre regiões.</p>\n<p>Camponeses livres, servos, arrendatários e trabalhadores sazonais possuíam condições distintas. A servidão restringia mobilidade e impunha obrigações, porém não equivalia à escravidão antiga: servos mantinham família, instrumentos, costumes comunitários e diferentes formas de acesso à terra.</p>\n<p>As relações senhoriais envolviam corveias, rendas, taxas e serviços. Ao mesmo tempo, aldeias podiam negociar costumes, administrar áreas comuns e resistir a exigências consideradas abusivas, revelando que os camponeses também eram agentes históricos.</p>\n<p>Entre os séculos XI e XIII, crescimento populacional, expansão de áreas cultivadas e difusão de técnicas contribuíram para elevar a produção em várias regiões. Arado pesado, rotação de culturas e melhor uso da força animal tiveram importância desigual conforme clima e solo.</p>\n<p>O aumento das trocas fortaleceu feiras, rotas e centros urbanos. Mercadores conectaram o Mediterrâneo, o mar do Norte, o Báltico e áreas interiores, articulando produtos orientais, metais, tecidos, cereais, sal e outros bens.</p>\n<p>As corporações de ofício regulavam aprendizado, produção e comercialização em muitas cidades. Elas protegiam interesses de mestres e trabalhadores qualificados, mas também estabeleciam hierarquias e barreiras de acesso, especialmente para estrangeiros, mulheres e grupos marginalizados.</p>\n<div class=\"farol-quadro farol-memorize\"><strong>🧠 Memorize</strong>Servidão e escravidão são relações diferentes; a condição camponesa medieval também variava conforme a região.</div>\n</div>"
  },
  {
    "titulo": "Página 7 — Comunidades judaicas, minorias e convivência desigual",
    "conteudo": "<div class=\"apostila-container\">\n<p>Comunidades judaicas viveram em diferentes regiões da Europa medieval, mantendo tradições religiosas, redes familiares e formas próprias de organização. Suas experiências variaram conforme cidade, reino, proteção política e relações com vizinhos cristãos ou muçulmanos.</p>\n<p>Judeus atuaram em múltiplas atividades, como artesanato, medicina, comércio, tradução, administração e produção intelectual. A associação automática de toda a população judaica ao empréstimo de dinheiro apaga sua diversidade e resulta de restrições profissionais e estereótipos históricos.</p>\n<p>Em determinados momentos, governantes concederam proteção e privilégios às comunidades judaicas, buscando competências profissionais e receitas fiscais. Essa proteção podia ser instável e transformar-se em exploração, expulsão ou violência quando mudavam os interesses políticos.</p>\n<p>Acusações religiosas, boatos e discursos antijudaicos estimularam perseguições, sobretudo em períodos de crise. Durante as Cruzadas e a Peste Negra, comunidades foram atacadas, apesar de não haver fundamento para culpabilizá-las por epidemias ou problemas sociais.</p>\n<p>Na Península Ibérica, cristãos, judeus e muçulmanos compartilharam espaços urbanos, conhecimentos e práticas culturais, mas a convivência não significava igualdade constante. Cooperação cotidiana coexistiu com fronteiras jurídicas, disputas políticas, conversões forçadas e perseguições.</p>\n<p>Para estudar minorias, o historiador deve analisar documentos produzidos por autoridades e também buscar registros internos, inscrições, objetos, manuscritos e vestígios arqueológicos. Essa comparação ajuda a evitar que a voz dos perseguidores seja tratada como descrição neutra dos grupos perseguidos.</p>\n<div class=\"farol-quadro farol-memorize\"><strong>🧠 Memorize</strong>Convivência não significa igualdade: intercâmbios culturais podiam coexistir com discriminação e perseguição.</div>\n</div>"
  },
  {
    "titulo": "Página 8 — Cruzadas, Península Ibérica e fronteiras mediterrânicas",
    "conteudo": "<div class=\"apostila-container\">\n<p>As Cruzadas iniciadas no final do século XI reuniram motivações religiosas, políticas, econômicas e sociais. Papas, nobres, cavaleiros, cidades mercantis, peregrinos e populações locais participaram com interesses diferentes, tornando insuficiente explicá-las por uma única causa.</p>\n<p>A Primeira Cruzada conquistou Jerusalém e estabeleceu Estados latinos no Oriente. Essas formações dependeram de fortalezas, alianças, comércio e imigração, convivendo com populações cristãs orientais, muçulmanas e judaicas.</p>\n<p>A Quarta Cruzada desviou-se de seu objetivo anunciado e saqueou Constantinopla em 1204. O episódio demonstra que conflitos entre cristãos latinos e bizantinos também marcaram o período e enfraqueceram o Império Romano do Oriente.</p>\n<p>Na Península Ibérica, a chamada Reconquista foi um processo longo, com avanços, recuos, alianças e guerras entre poderes cristãos e muçulmanos. O termo pode sugerir unidade inexistente, pois os reinos envolvidos disputavam territórios e cooperavam conforme interesses políticos.</p>\n<p>Fronteiras mediterrânicas permitiram circulação de produtos, técnicas e conhecimentos. Comerciantes italianos, muçulmanos, judeus, bizantinos e outros agentes criaram redes que atravessavam divisões religiosas mesmo durante períodos de guerra.</p>\n<p>A expansão cristã na Península Ibérica terminou politicamente com a conquista de Granada em 1492, mas foi acompanhada por pressões de conversão e expulsões. Esse processo mostra que a construção de Estados também podia envolver homogeneização religiosa e violência.</p>\n<div class=\"farol-quadro farol-memorize\"><strong>🧠 Memorize</strong>Cruzadas e Reconquista envolveram religião, política, economia e alianças variáveis.</div>\n</div>"
  },
  {
    "titulo": "Página 9 — Cidades, universidades, artes e circulação cultural",
    "conteudo": "<div class=\"apostila-container\">\n<p>O crescimento urbano medieval ocorreu em ritmos variados e não representou simples renascimento de cidades antigas. Centros episcopais, portos, fortalezas, mercados e núcleos artesanais ampliaram funções políticas e econômicas a partir de diferentes trajetórias.</p>\n<p>Comunas e cartas de franquia registraram negociações entre habitantes urbanos e senhores. Algumas cidades conquistaram autonomia fiscal ou jurídica, mas continuaram marcadas por desigualdades entre elites mercantis, artesãos, trabalhadores pobres, estrangeiros e mulheres.</p>\n<p>As universidades surgiram como corporações de mestres e estudantes. Bolonha destacou-se nos estudos jurídicos, Paris em teologia e outras instituições desenvolveram currículos, graus e privilégios, mantendo relações complexas com Igreja, cidades e governantes.</p>\n<p>A escolástica procurou organizar argumentos por meio de leitura, debate e conciliação de autoridades. Traduções de obras gregas, árabes e judaicas alimentaram discussões em filosofia, medicina e ciência, demonstrando que a produção intelectual dependia de redes interculturais.</p>\n<p>A arquitetura românica e a gótica apresentam diferenças regionais e cronológicas. Catedrais, igrejas e edifícios urbanos mobilizavam recursos, técnicas e trabalho coletivo, expressando devoção, competição política e identidade comunitária.</p>\n<p>Literaturas em línguas vernáculas, canções, narrativas de cavalaria e produções visuais ampliaram formas de expressão além do latim erudito. Cultura cortesã, cultura popular e cultura clerical mantiveram contatos e tensões, sem constituir universos isolados.</p>\n<div class=\"farol-quadro farol-memorize\"><strong>🧠 Memorize</strong>Universidades e cidades cresceram por negociações, redes comerciais e circulação intercultural de saberes.</div>\n</div>"
  },
  {
    "titulo": "🌧️ Página 10 — Crises, conflitos e mudanças no final da Idade Média",
    "conteudo": "<div class=\"apostila-container\">\n<p>A partir do século XIV, mudanças climáticas, crises de abastecimento, guerras e epidemias afetaram diversas regiões europeias. A Grande Fome e outras dificuldades revelaram a vulnerabilidade de populações dependentes de colheitas e redes comerciais instáveis.</p>\n<p>A Peste Negra provocou enorme mortalidade, mas seus efeitos não foram idênticos em todos os lugares. A redução populacional alterou relações de trabalho, preços, rendas e mobilidade, ao mesmo tempo em que estimulou medo, religiosidade, perseguições e novas políticas públicas.</p>\n<p>Revoltas camponesas e urbanas, como a Jacquerie francesa e o levante inglês de 1381, expressaram tensões sobre impostos, trabalho e autoridade. Embora muitas tenham sido reprimidas, demonstraram capacidade de organização e disputa por direitos.</p>\n<p>A Guerra dos Cem Anos envolveu dinastias, territórios, fiscalidade e formação de exércitos. O conflito contribuiu para mudanças militares e políticas, mas a consolidação dos reinos não ocorreu de forma linear nem eliminou poderes regionais.</p>\n<p>O final da Idade Média apresentou transformações no comércio, na monarquia, na cultura escrita e na religiosidade. Esses processos prepararam mudanças posteriores, mas não devem ser descritos como simples passagem inevitável do feudalismo para o capitalismo.</p>\n<p>No ensino de História, a Europa medieval deve ser tratada como espaço plural e conectado. Comparar fontes cristãs, judaicas, islâmicas e bizantinas permite compreender tanto os confrontos quanto os convívios, evitando estereótipos de atraso, isolamento ou conflito religioso permanente.</p>\n<div class=\"farol-quadro farol-memorize\"><strong>🧠 Memorize</strong>As crises do século XIV produziram mudanças diversas, não uma transição automática e igual em toda a Europa.</div>\n</div>"
  }
];
