const legadosAntiguidadeClassicaAbaetetubaTeoria = [
  {
    "titulo": "🏛️ Página 1 — Antiguidade Clássica e o problema dos legados",
    "conteudo": "<div class=\"apostila-container\">\n<p>A expressão Antiguidade Clássica costuma designar, sobretudo, experiências históricas ligadas às sociedades gregas e romanas. Trata-se de uma classificação criada por estudiosos posteriores, e não de um nome usado de maneira uniforme por todos os povos da época.</p>\n<p>O adjetivo clássico foi associado à ideia de modelo, excelência e permanência. Essa valorização influenciou a educação, as artes e a política europeias, mas também pode produzir uma leitura limitada quando transforma Grécia e Roma em origem única do mundo ocidental.</p>\n<p>Gregos e romanos viveram em contato permanente com egípcios, fenícios, persas, povos africanos, comunidades do Oriente Próximo e diversas populações europeias. Comércio, guerras, migrações e intercâmbios culturais fizeram do Mediterrâneo um espaço de conexões.</p>\n<p>Legado histórico não significa cópia direta. Ideias, instituições, palavras, obras e técnicas foram selecionadas, reinterpretadas e adaptadas em épocas diferentes. Democracia, república, cidadania e direito, por exemplo, ganharam sentidos novos ao longo do tempo.</p>\n<p>As fontes sobre a Antiguidade incluem textos, inscrições, moedas, edifícios, cerâmicas, esculturas, objetos cotidianos e vestígios funerários. Como grande parte da documentação escrita foi produzida por grupos letrados e dominantes, a arqueologia ajuda a ampliar a análise social.</p>\n<p>Estudar os legados clássicos exige reconhecer contribuições e limites. As sociedades antigas produziram filosofia, literatura, instituições e conhecimentos duradouros, mas também conviveram com escravidão, guerras de conquista, desigualdades de gênero e cidadanias restritas.</p>\n<div class=\"farol-quadro farol-memorize\"><strong>🧠 Memorize</strong>Legado histórico é permanência reinterpretada: conceitos antigos mudam de sentido em novos contextos.</div>\n</div>"
  },
  {
    "titulo": "🏺 Página 2 — O mundo grego, as pólis e a cidadania",
    "conteudo": "<div class=\"apostila-container\">\n<p>O mundo grego antigo não formava um Estado unificado. Era composto por pólis, comunidades políticas autônomas com instituições, leis, territórios e cultos próprios. Atenas, Esparta, Corinto e Tebas apresentaram trajetórias diferentes.</p>\n<p>A pólis articulava espaço urbano, campos, santuários e relações de pertencimento. A vida política ocorria em assembleias, conselhos, magistraturas e tribunais, embora a participação variasse conforme o regime e a condição social.</p>\n<p>Em Atenas, reformas atribuídas a Sólon e Clístenes contribuíram para reorganizar conflitos e ampliar a participação dos cidadãos. No século V a.C., a democracia ateniense utilizou assembleia, sorteio de cargos e votação direta em várias decisões.</p>\n<p>A cidadania ateniense era restrita a homens livres reconhecidos como membros da comunidade cívica. Mulheres, estrangeiros residentes e pessoas escravizadas estavam excluídos da participação política formal, apesar de integrarem a vida econômica, religiosa e social.</p>\n<p>Esparta organizou-se em torno de uma elite de cidadãos guerreiros, sustentada pelo trabalho dos hilotas e por comunidades submetidas. Suas instituições combinavam reis, conselho de anciãos, magistrados e assembleia, não podendo ser reduzidas a uma simples monarquia militar.</p>\n<p>As experiências gregas mostram que cidadania e exclusão caminharam juntas. Por isso, usar Atenas como referência para a democracia moderna requer comparação histórica, evitando projetar direitos atuais sobre uma sociedade antiga.</p>\n<div class=\"farol-quadro farol-memorize\"><strong>🧠 Memorize</strong>Legado histórico é permanência reinterpretada: conceitos antigos mudam de sentido em novos contextos.</div>\n</div>"
  },
  {
    "titulo": "⚔️ Página 3 — Conflitos, expansão e mundo helenístico",
    "conteudo": "<div class=\"apostila-container\">\n<p>As Guerras Médicas colocaram várias pólis gregas em confronto com o Império Persa no início do século V a.C. A resistência comum fortaleceu identidades helênicas, mas não eliminou rivalidades entre as cidades.</p>\n<p>A Guerra do Peloponeso opôs principalmente Atenas e Esparta, acompanhadas por suas alianças. O conflito prolongado enfraqueceu diversas pólis e revelou tensões entre impérios marítimos, autonomia política e interesses regionais.</p>\n<p>No século IV a.C., a Macedônia ampliou seu controle sobre o mundo grego. Filipe II organizou forças militares e alianças, enquanto Alexandre conquistou territórios que alcançaram o Egito, a Pérsia e partes da Ásia Central e da Índia.</p>\n<p>As conquistas de Alexandre favoreceram a formação de reinos helenísticos. Neles, línguas, cultos, conhecimentos e estilos artísticos gregos interagiram com tradições egípcias, persas e orientais, produzindo combinações culturais variadas.</p>\n<p>Alexandria, no Egito, tornou-se importante centro intelectual e comercial. Sua biblioteca e seu museu simbolizam a circulação de textos e estudiosos, mas o conhecimento helenístico dependia de redes mais amplas entre cidades, cortes e comunidades.</p>\n<p>A expansão grega anterior, com fundação de colônias pelo Mediterrâneo e pelo mar Negro, também criou redes econômicas e culturais. Essas comunidades mantinham vínculos religiosos e linguísticos, sem formar um império político único.</p>\n<div class=\"farol-quadro farol-memorize\"><strong>🧠 Memorize</strong>Legado histórico é permanência reinterpretada: conceitos antigos mudam de sentido em novos contextos.</div>\n</div>"
  },
  {
    "titulo": "🎭 Página 4 — Religião, filosofia, teatro, arte e conhecimento",
    "conteudo": "<div class=\"apostila-container\">\n<p>A religião grega era politeísta e integrada à vida cívica. Festivais, sacrifícios, oráculos e cultos domésticos articulavam comunidade, família e política. Os mitos ofereciam narrativas sobre deuses, heróis, origem e ordem social.</p>\n<p>A filosofia grega reuniu correntes diversas. Sócrates, Platão e Aristóteles são referências importantes, mas o pensamento antigo também incluiu sofistas, cínicos, estoicos, epicuristas e outras escolas que discutiram ética, conhecimento, natureza e política.</p>\n<p>O teatro ateniense estava ligado a festivais religiosos e à vida pública. Tragédias e comédias abordavam conflitos familiares, guerra, poder, justiça e comportamento cívico, permitindo que a comunidade refletisse sobre tensões coletivas.</p>\n<p>Historiadores como Heródoto e Tucídides procuraram explicar guerras e ações humanas por meio de investigação, comparação de relatos e análise política. Suas obras não seguem os métodos atuais, mas contribuíram para formas críticas de narrar o passado.</p>\n<p>Matemática, medicina, astronomia e geografia desenvolveram-se por intercâmbios entre diferentes povos. Autores gregos sistematizaram conhecimentos, mas não os criaram isoladamente, pois dialogaram com tradições egípcias, mesopotâmicas e outras.</p>\n<p>A arte grega valorizou proporção, movimento e representação do corpo em vários períodos, sem possuir um estilo único. Templos, cerâmicas e esculturas cumpriam funções religiosas, políticas e funerárias, além de expressarem escolhas estéticas.</p>\n<div class=\"farol-quadro farol-memorize\"><strong>🧠 Memorize</strong>Legado histórico é permanência reinterpretada: conceitos antigos mudam de sentido em novos contextos.</div>\n</div>"
  },
  {
    "titulo": "🏛️ Página 5 — Roma, República e conflitos sociais",
    "conteudo": "<div class=\"apostila-container\">\n<p>A história romana foi construída por tradições literárias, arqueologia e inscrições. Narrativas sobre Rômulo e Remo pertencem ao campo mítico e ajudaram a explicar a origem e a identidade de Roma, não constituindo relato factual completo.</p>\n<p>Durante a República, o poder era distribuído entre magistraturas, Senado e assembleias. Cônsules exerciam funções executivas e militares, enquanto outros cargos tratavam de justiça, finanças, administração urbana e fiscalização.</p>\n<p>A República romana não era uma democracia igualitária. Famílias aristocráticas controlavam grande parte das decisões, e as relações de patronato e clientela influenciavam eleições, proteção jurídica e acesso a recursos.</p>\n<p>Conflitos entre patrícios e plebeus levaram à criação de instituições como o tribunato da plebe e à conquista de direitos. A Lei das Doze Tábuas tornou públicas normas importantes, embora não tenha eliminado desigualdades sociais.</p>\n<p>A expansão romana pela península Itálica e pelo Mediterrâneo combinou guerras, tratados, concessões graduais de cidadania e integração de elites locais. Esse processo produziu alianças, resistências e diferentes condições jurídicas.</p>\n<p>As Guerras Púnicas contra Cartago ampliaram o domínio romano no Mediterrâneo ocidental. A expansão trouxe riquezas, territórios e pessoas escravizadas, mas também agravou disputas fundiárias, tensões sociais e conflitos políticos.</p>\n<div class=\"farol-quadro farol-memorize\"><strong>🧠 Memorize</strong>Legado histórico é permanência reinterpretada: conceitos antigos mudam de sentido em novos contextos.</div>\n</div>"
  },
  {
    "titulo": "🦅 Página 6 — Do Principado ao Império mediterrânico",
    "conteudo": "<div class=\"apostila-container\">\n<p>As guerras civis do final da República envolveram generais, exércitos, facções aristocráticas e demandas sociais. A ascensão de Otávio, chamado Augusto, inaugurou o Principado, regime que preservava formas republicanas enquanto concentrava poderes.</p>\n<p>A chamada Pax Romana designa um período de relativa estabilidade em extensas áreas do Império. A expressão não significa ausência de guerras, rebeliões ou violência, pois fronteiras e províncias continuaram marcadas por conflitos.</p>\n<p>O governo imperial dependia de exército, impostos, cidades, estradas, portos e administrações provinciais. Elites locais colaboravam com Roma e recebiam vantagens, enquanto comunidades negociavam, resistiam ou adaptavam práticas imperiais.</p>\n<p>Romanização deve ser entendida como processo desigual de interação, e não como simples imposição cultural. Línguas, cultos, leis, hábitos urbanos e costumes locais combinaram-se de formas distintas nas províncias.</p>\n<p>A escravidão era central na economia e na sociedade romanas. Pessoas escravizadas atuavam na agricultura, nas minas, nas casas, nas oficinas e em funções administrativas, podendo existir situações diversas de violência, especialização e possibilidade de alforria.</p>\n<p>Em 212 d.C., a Constituição Antoniniana ampliou a cidadania romana à maior parte dos homens livres do Império. A medida fortaleceu uma identidade jurídica comum, mas não eliminou diferenças econômicas, regionais e políticas.</p>\n<div class=\"farol-quadro farol-memorize\"><strong>🧠 Memorize</strong>Legado histórico é permanência reinterpretada: conceitos antigos mudam de sentido em novos contextos.</div>\n</div>"
  },
  {
    "titulo": "⚖️ Página 7 — Direito, língua, cidades e técnicas",
    "conteudo": "<div class=\"apostila-container\">\n<p>O direito romano formou conceitos sobre propriedade, contratos, família, obrigações e procedimentos judiciais. Sua influência posterior ocorreu por preservação, estudo e reelaboração, especialmente em instituições medievais e modernas.</p>\n<p>O latim difundiu-se por administração, exército, comércio e vida urbana. Nas províncias ocidentais, suas transformações contribuíram para o surgimento das línguas românicas, como português, espanhol, francês, italiano e romeno.</p>\n<p>Estradas romanas facilitavam deslocamento militar, cobrança de impostos, circulação de mercadorias e comunicação. Elas não foram construídas apenas para promover comércio, pois integravam uma estratégia de governo e controle territorial.</p>\n<p>Aquedutos, pontes, termas, anfiteatros e sistemas de drenagem revelam conhecimentos de engenharia e organização do trabalho. Essas obras dependiam de impostos, mão de obra e decisões políticas, além de atenderem de maneira desigual às populações.</p>\n<p>As cidades romanas funcionavam como centros administrativos, econômicos e simbólicos. Fóruns, templos, basílicas e monumentos expressavam hierarquias, cultos e a presença do poder imperial.</p>\n<p>Palavras como república, Senado, cidadão e constituição foram retomadas em épocas posteriores. A permanência vocabular não garante identidade de significado, pois cada sociedade reinterpretou esses conceitos segundo seus próprios conflitos.</p>\n<div class=\"farol-quadro farol-memorize\"><strong>🧠 Memorize</strong>Legado histórico é permanência reinterpretada: conceitos antigos mudam de sentido em novos contextos.</div>\n</div>"
  },
  {
    "titulo": "✝️ Página 8 — Religiões, cristianismo e Antiguidade Tardia",
    "conteudo": "<div class=\"apostila-container\">\n<p>O Império Romano abrigava numerosos cultos. Deuses locais, tradições familiares, religiões de mistério e culto imperial coexistiam, embora autoridades pudessem reprimir práticas consideradas ameaçadoras à ordem política.</p>\n<p>O cristianismo nasceu no contexto judaico da Palestina e se expandiu por redes urbanas do Império. Comunidades cristãs apresentaram diversidade de interpretações, lideranças e práticas antes de uma organização institucional mais ampla.</p>\n<p>As perseguições aos cristãos ocorreram em momentos e regiões diferentes, não de forma contínua durante toda a história imperial. Elas estiveram ligadas a contextos políticos, exigências de culto e busca de unidade.</p>\n<p>No século IV, medidas associadas a Constantino permitiram maior liberdade de culto e favoreceram a Igreja. Mais tarde, o cristianismo niceno recebeu condição oficial, transformando relações entre religião e poder imperial.</p>\n<p>A Antiguidade Tardia foi período de mudanças políticas, econômicas, religiosas e culturais. Em vez de simples decadência, estudos atuais destacam continuidades, reorganizações regionais e formação de novas estruturas.</p>\n<p>O ano de 476 é usado como marco convencional para o fim do Império Romano do Ocidente. O Império Romano do Oriente continuou por séculos, e instituições romanas permaneceram em reinos, cidades, leis e práticas cristãs.</p>\n<div class=\"farol-quadro farol-memorize\"><strong>🧠 Memorize</strong>Legado histórico é permanência reinterpretada: conceitos antigos mudam de sentido em novos contextos.</div>\n</div>"
  },
  {
    "titulo": "🏛️ Página 9 — Releituras modernas do mundo clássico",
    "conteudo": "<div class=\"apostila-container\">\n<p>Durante o Renascimento, estudiosos e artistas buscaram manuscritos, formas arquitetônicas e temas greco-romanos. Essa retomada não recuperou uma Antiguidade intacta, mas produziu novas interpretações segundo valores e interesses dos séculos XV e XVI.</p>\n<p>Pensadores políticos modernos utilizaram exemplos de Atenas e Roma para discutir república, virtude cívica, tirania e participação. Essas referências foram seletivas e adaptadas a sociedades muito diferentes das antigas.</p>\n<p>O neoclassicismo valorizou colunas, frontões, equilíbrio e temas históricos. Edifícios públicos e monumentos adotaram essa linguagem para associar Estados modernos a autoridade, racionalidade e prestígio.</p>\n<p>Movimentos democráticos recorreram à experiência ateniense, enquanto projetos republicanos valorizaram Roma. Entretanto, cidadania universal, direitos humanos, representação eleitoral e igualdade jurídica resultaram de processos modernos, não de simples herança antiga.</p>\n<p>A Antiguidade também foi apropriada por nacionalismos, imperialismos e teorias raciais. A ideia de uma civilização clássica pura ignorou contatos mediterrânicos e foi usada para criar hierarquias entre povos.</p>\n<p>Museus, escavações e coleções contribuíram para o conhecimento arqueológico, mas também levantam debates sobre retirada de objetos, domínio colonial, tráfico de antiguidades e direito das comunidades de origem ao patrimônio.</p>\n<div class=\"farol-quadro farol-memorize\"><strong>🧠 Memorize</strong>Legado histórico é permanência reinterpretada: conceitos antigos mudam de sentido em novos contextos.</div>\n</div>"
  },
  {
    "titulo": "🎓 Página 10 — Ensino crítico dos legados clássicos",
    "conteudo": "<div class=\"apostila-container\">\n<p>No ensino de História, a Antiguidade Clássica deve ser apresentada como campo de experiências diversas, e não como coleção de heróis, batalhas e obras monumentais. A análise precisa incluir trabalhadores, mulheres, estrangeiros, escravizados e povos provinciais.</p>\n<p>Textos antigos devem ser contextualizados. Um discurso político, uma peça teatral ou uma lei expressa linguagem, público e interesses específicos. Compará-los com inscrições, imagens e vestígios materiais reduz a dependência da visão das elites letradas.</p>\n<p>Comparações entre democracia ateniense e democracia atual podem ser produtivas quando evidenciam diferenças de escala, cidadania, representação, direitos e participação. A comparação se torna anacrônica quando apaga essas diferenças.</p>\n<p>O estudo dos legados deve mostrar mediações históricas. Direito romano, filosofia grega e arquitetura clássica chegaram ao presente por traduções, escolas, religiões, universidades, movimentos artísticos e disputas políticas.</p>\n<p>Atividades com mapas ajudam a compreender o Mediterrâneo como rede de circulação. Linhas do tempo e estudos de caso também permitem distinguir períodos gregos, República romana, Império e Antiguidade Tardia.</p>\n<p>Uma abordagem crítica reconhece contribuições sem idealização. O objetivo é compreender como sociedades antigas produziram instituições e culturas marcantes, quais exclusões sustentaram essas experiências e por que elas continuam sendo reinterpretadas.</p>\n<div class=\"farol-quadro farol-memorize\"><strong>🧠 Memorize</strong>Legado histórico é permanência reinterpretada: conceitos antigos mudam de sentido em novos contextos.</div>\n</div>"
  }
];
